"""CFN All-SEC List 2024"""

{
  "sec": {
    "Awards": {
      "PlayerOfTheYear": {"name":"Nick Emmanwori","position":"S","school":"South Carolina"},
      "OffensivePlayerOfTheYear": {"name":"Dylan Sampson","position":"RB","school":"Tennessee"},
      "DefensivePlayerOfTheYear": {"name":"Nick Emmanwori","position":"S","school":"South Carolina"},
      "SpecialistOfTheYear": {"name":"Brett Thorson","position":"P","school":"Georgia"},
      "NewcomerOfTheYear": {"name":"Ryan Williams","position":"WR","school":"Alabama"},
      "CoachOfTheYear": {"name":"Shane Beamer","position":"Coach","school":"South Carolina"},
      "ImpactFreshmanOfTheYear": {"name":"Ryan Williams","position":"WR","school":"Alabama"}
    },
    "PositionAwards": {
      "QuarterbackOfTheYear": {"name":"Jaxson Dart","position":"QB","school":"Ole Miss"},
      "RunningBackOfTheYear": {"name":"Dylan Sampson","position":"RB","school":"Tennessee"},
      "WideReceiverOfTheYear": {"name":"Tre Harris","position":"WR","school":"Ole Miss"},
      "TightEndOfTheYear": {"name":"Gunnar Helm","position":"TE","school":"Texas"},
      "OffensiveTackleOfTheYear": {"name":"Kelvin Banks Jr.","position":"OT","school":"Texas"},
      "OffensiveGuardOfTheYear": {"name":"Dylan Fairchild","position":"OG","school":"Georgia"},
      "CenterOfTheYear": {"name":"Jake Slaughter","position":"C","school":"Florida"},
      "OffensiveLinemanOfTheYear": {"name":"Kelvin Banks Jr.","position":"OT","school":"Texas"},
      "OffensiveLineOfTheYear": {"name":"Missouri Tigers","position":"OL Unit","school":"Missouri"},
      "OffensiveNewcomerOfTheYear": {"name":"Ryan Williams","position":"WR","school":"Alabama"},
      "EdgeDefenderOfTheYear": {"name":"James Pearce Jr.","position":"EDGE","school":"Tennessee"},
      "InteriorDefenderOfTheYear": {"name":"T.J. Sanders","position":"DT","school":"South Carolina"},
      "LinebackerOfTheYear": {"name":"Chris Paul Jr.","position":"LB","school":"Ole Miss"},
      "CornerbackOfTheYear": {"name":"Jahdae Barron","position":"CB","school":"Texas"},
      "SafetyOfTheYear": {"name":"Nick Emmanwori","position":"S","school":"South Carolina"},
      "DefensiveLineOfTheYear": {"name":"South Carolina Gamecocks","position":"DL Unit","school":"South Carolina"},
      "SecondaryOfTheYear": {"name":"Texas Longhorns","position":"Secondary Unit","school":"Texas"},
      "DefensiveNewcomerOfTheYear": {"name":"Dylan Stewart","position":"EDGE","school":"South Carolina"},
      "DefensiveTransferOfTheYear": {"name":"Princely Umanmielen","position":"EDGE","school":"Ole Miss"},
      "KickerOfTheYear": {"name":"Peyton Woodring","position":"PK","school":"Georgia"},
      "PunterOfTheYear": {"name":"Brett Thorson","position":"P","school":"Georgia"},
      "KickReturnerOfTheYear": {"name":"Barion Brown","position":"KR","school":"Kentucky"},
      "PuntReturnerOfTheYear": {"name":"Martel Hight","position":"PR","school":"Vanderbilt"},
      "SpecialTeamerOfTheYear": {"name":"King Mack","position":"ST","school":"Alabama"},
      "KickoffSpecialistOfTheYear": {"name":"Caden Davis","position":"KOS","school":"Ole Miss"}
    },
    "FirstTeam": {
      "Offense": [
        {"position":"QB","name":"Jaxson Dart","school":"Ole Miss"},
        {"position":"RB","name":"Dylan Sampson","school":"Tennessee"},
        {"position":"RB","name":"Jarquez Hunter","school":"Auburn"},
        {"position":"WR","name":"Andrew Armstrong","school":"Arkansas"},
        {"position":"WR","name":"Tre Harris","school":"Ole Miss"},
        {"position":"WR","name":"KeAndre Lambert-Smith","school":"Auburn"},
        {"position":"TE","name":"Gunnar Helm","school":"Texas"},
        {"position":"FLEX","name":"Ryan Williams","school":"Alabama"},
        {"position":"OT","name":"Kelvin Banks Jr.","school":"Texas"},
        {"position":"OG","name":"Dylan Fairchild","school":"Georgia"},
        {"position":"OC","name":"Jake Slaughter","school":"Florida"},
        {"position":"OG","name":"Ar’maj Reed-Adams","school":"Texas AM"},
        {"position":"OT","name":"Armand Mambou","school":"Missouri"}
      ],
      "Defense": [
        {"position":"EDGE","name":"James Pearce Jr.","school":"Tennessee"},
        {"position":"DT","name":"T.J. Sanders","school":"South Carolina"},
        {"position":"DT","name":"JJ Pegues","school":"Ole Miss"},
        {"position":"EDGE","name":"Dylan Stewart","school":"South Carolina"},
        {"position":"LB","name":"Chris Paul Jr.","school":"Ole Miss"},
        {"position":"LB","name":"Jihaad Campbell","school":"Alabama"},
        {"position":"LB","name":"Whit Weeks","school":"LSU"},
        {"position":"CB","name":"Jahdae Barron","school":"Texas"},
        {"position":"CB","name":"Trey Amos","school":"Ole Miss"},
        {"position":"CB","name":"Brian Mayes","school":"Texas AM"},
        {"position":"SS","name":"Nick Emmanwori","school":"South Carolina"},
        {"position":"FS","name":"Michael Taaffe","school":"Texas"},
        {"position":"S","name":"Andrew Mukuba","school":"Texas"},
        {"position":"FLEX","name":"Jermod McCoy","school":"Tennessee"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Peyton Woodring","school":"Georgia"},
        {"position":"KOS","name":"Caden Davis","school":"Ole Miss"},
        {"position":"P","name":"Brett Thorson","school":"Georgia"},
        {"position":"KR","name":"Barion Brown","school":"Kentucky"},
        {"position":"PR","name":"Martel Hight","school":"Vanderbilt"}
      ]
    },
    "SecondTeam": {
      "Offense": [
        {"position":"QB","name":"Diego Pavia","school":"Vanderbilt"},
        {"position":"RB","name":"Raheim Sanders","school":"South Carolina"},
        {"position":"RB","name":"Ja’Quinden Jackson","school":"Arkansas"},
        {"position":"WR","name":"Matthew Golden","school":"Texas"},
        {"position":"WR","name":"Kyren Lacy","school":"LSU"},
        {"position":"WR","name":"Kevin Coleman","school":"Mississippi State"},
        {"position":"TE","name":"Eli Stowers","school":"Vanderbilt"},
        {"position":"FLEX","name":"Theo Wease Jr.","school":"Missouri"},
        {"position":"OT","name":"Marcus Bryant","school":"Missouri"},
        {"position":"OG","name":"Cam’Ron Johnson","school":"Missouri"},
        {"position":"OC","name":"Jared Wilson","school":"Florida"},
        {"position":"OG","name":"Cayden Green","school":"Missouri"},
        {"position":"OT","name":"Micah Pettus","school":"Ole Miss"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Princely Umanmielen","school":"Ole Miss"},
        {"position":"DT","name":"Walter Nolen","school":"Ole Miss"},
        {"position":"DT","name":"Caleb Banks","school":"Florida"},
        {"position":"EDGE","name":"Bradyn Swinson","school":"LSU"},
        {"position":"LB","name":"Jalon Walker","school":"Georgia"},
        {"position":"LB","name":"Danny Stutsman","school":"Oklahoma"},
        {"position":"LB","name":"Anthony Hill Jr.","school":"Texas"},
        {"position":"CB","name":"Judge Collier","school":"South Carolina"},
        {"position":"CB","name":"Will Lee III","school":"Texas AM"},
        {"position":"CB","name":"Jalen Kilgore","school":"South Carolina"},
        {"position":"SS","name":"John Saunders Jr.","school":"Ole Miss"},
        {"position":"FS","name":"Dan Jackson","school":"Georgia"},
        {"position":"S","name":"Malachi Moore","school":"Alabama"},
        {"position":"FLEX","name":"Jadon Canady","school":"Ole Miss"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Brock Taylor","school":"Vanderbilt"},
        {"position":"KOS","name":"Aeron Burrell","school":"LSU"},
        {"position":"P","name":"Kai Kroeger","school":"South Carolina"},
        {"position":"KR","name":"Junior Sherrill","school":"Vanderbilt"},
        {"position":"PR","name":"Silas Bolden","school":"Texas"},
        {"position":"ST","name":"Colin Bryant","school":"South Carolina"}
      ]
    },
    "ThirdTeam": {
      "Offense": [
        {"position":"QB","name":"Taylen Green","school":"Arkansas"},
        {"position":"RB","name":"Le’Veon Moss","school":"Texas AM"},
        {"position":"RB","name":"Henry Parrish Jr.","school":"Ole Miss"},
        {"position":"WR","name":"Cayden Lee","school":"Ole Miss"},
        {"position":"WR","name":"Elijhah Badger","school":"Florida"},
        {"position":"WR","name":"Aaron Anderson","school":"LSU"},
        {"position":"TE","name":"Mason Taylor","school":"LSU"},
        {"position":"FLEX","name":"Caden Durham","school":"LSU"},
        {"position":"OT","name":"Dillon Wade","school":"Auburn"},
        {"position":"OG","name":"Hayden Conner","school":"Texas"},
        {"position":"OC","name":"Jake Majors","school":"Texas"},
        {"position":"OG","name":"Torricelli Simpkins III","school":"South Carolina"},
        {"position":"OT","name":"Kadyn Proctor","school":"Alabama"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Kyle Kennard","school":"South Carolina"},
        {"position":"DT","name":"Omarr Norman-Lott","school":"Tennessee"},
        {"position":"DT","name":"Tonka Hemingway","school":"South Carolina"},
        {"position":"EDGE","name":"Suntarine Perkins","school":"Ole Miss"},
        {"position":"LB","name":"C.J. Allen","school":"Georgia"},
        {"position":"LB","name":"Deontae Lawson","school":"Alabama"},
        {"position":"LB","name":"Xavian Sorey Jr.","school":"Arkansas"},
        {"position":"CB","name":"Ashton Stamps","school":"LSU"},
        {"position":"CB","name":"Domani Jackson","school":"Alabama"},
        {"position":"CB","name":"Malik Muhammad","school":"Texas"},
        {"position":"SS","name":"Bray Hubbard","school":"Alabama"},
        {"position":"FS","name":"Billy Bowman Jr.","school":"Oklahoma"},
        {"position":"S","name":"Marcus Ratcliffe","school":"Texas AM"},
        {"position":"FLEX","name":"Daylen Everette","school":"Georgia"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Randy Bond","school":"Texas AM"},
        {"position":"KOS","name":"Jared Zirkel","school":"Texas AM"},
        {"position":"P","name":"Jeremy Crawshaw","school":"Florida"},
        {"position":"KR","name":"Zavion Thomas","school":"LSU"},
        {"position":"PR","name":"Boo Carter","school":"Tennessee"},
        {"position":"ST","name":"Lewis Carter","school":"Oklahoma"}
      ]
    },
    "HonorableMention": [
      {"position":"QB","name":"Carson Beck","school":"Georgia"},
      {"position":"QB","name":"Nico Iamaleava","school":"Tennessee"},
      {"position":"QB","name":"Garrett Nussmeier","school":"LSU"},
      {"position":"RB","name":"Jam Miller","school":"Alabama"},
      {"position":"RB","name":"Marcus Carroll","school":"Missouri"},
      {"position":"RB","name":"Davon Booth","school":"Mississippi State"},
      {"position":"RB","name":"Amari Daniels","school":"Texas AM"},
      {"position":"RB","name":"Quintrevion Wisner","school":"Texas"},
      {"position":"RB","name":"Nate Noel","school":"Missouri"},
      {"position":"WR","name":"Luther Burden III","school":"Missouri"},
      {"position":"WR","name":"Dont’e Thornton Jr.","school":"Tennessee"},
      {"position":"WR","name":"Cam Coleman","school":"Auburn"},
      {"position":"WR","name":"Dominic Lovett","school":"Georgia"},
      {"position":"WR","name":"Isaiah Bond","school":"Texas"},
      {"position":"WR","name":"Antwane Wells Jr.","school":"Ole Miss"},
      {"position":"WR","name":"Jordan Watkins","school":"Ole Miss"},
      {"position":"WR","name":"Chimere Dike","school":"Florida"},
      {"position":"WR","name":"Germie Bernard","school":"Alabama"},
      {"position":"TE","name":"Caden Prieskorn","school":"Ole Miss"},
      {"position":"TE","name":"Lawson Luckie","school":"Georgia"},
      {"position":"TE","name":"Joshua Simon","school":"South Carolina"},
      {"position":"FLEX","name":"Jaydon Blue","school":"Texas"},
      {"position":"FLEX","name":"Seydou Traore","school":"Mississippi State"},
      {"position":"FLEX","name":"Luke Hasz","school":"Arkansas"},
      {"position":"OT","name":"Dametrious Crownover","school":"Texas AM"},
      {"position":"OT","name":"Monroe Freeling","school":"Georgia"},
      {"position":"OT","name":"Cameron Williams","school":"Texas"},
      {"position":"OG","name":"Tyler Booker","school":"Alabama"},
      {"position":"OG","name":"Andrej Karic","school":"Tennessee"},
      {"position":"OG","name":"Tate Ratledge","school":"Georgia"},
      {"position":"OC","name":"Cooper Mays","school":"Tennessee"},
      {"position":"OC","name":"Connor Tollison","school":"Missouri"},
      {"position":"OC","name":"Delfin Xavier Castillo","school":"Vanderbilt"},
      {"position":"OG","name":"Miles Frazier","school":"LSU"},
      {"position":"OG","name":"Jeremiah Wright","school":"Auburn"},
      {"position":"OG","name":"DJ Campbell","school":"Texas"},
      {"position":"OT","name":"Fernando Carmona","school":"Arkansas"},
      {"position":"OT","name":"Will Campbell","school":"LSU"},
      {"position":"OT","name":"Brandon Crenshaw‑Dickson","school":"Florida"},
      {"position":"EDGE","name":"Johnny Walker Jr.","school":"Missouri"},
      {"position":"EDGE","name":"LT Overton","school":"Alabama"},
      {"position":"EDGE","name":"Keldric Faulk","school":"Auburn"},
      {"position":"DT","name":"Cam’Ron Jackson","school":"Florida"},
      {"position":"DT","name":"Gracen Halton","school":"Oklahoma"},
      {"position":"DT","name":"Alfred Collins","school":"Texas"},
      {"position":"DT","name":"Shemar Turner","school":"Texas AM"},
      {"position":"DT","name":"Eric Gregory","school":"Arkansas"},
      {"position":"DT","name":"Deone Walker","school":"Kentucky"},
      {"position":"EDGE","name":"Colin Simmons","school":"Texas"},
      {"position":"EDGE","name":"Barryn Sorrell","school":"Texas"},
      {"position":"EDGE","name":"Landon Jackson","school":"Arkansas"},
      {"position":"LB","name":"Demetrius Knight Jr.","school":"South Carolina"},
      {"position":"LB","name":"Bryan Longwell","school":"Vanderbilt"},
      {"position":"LB","name":"Smael Mondon","school":"Georgia"},
      {"position":"LB","name":"Kip Lewis","school":"Oklahoma"},
      {"position":"LB","name":"Dorian Mausi","school":"Auburn"},
      {"position":"LB","name":"Corey Flagg","school":"Missouri"},
      {"position":"LB","name":"Bam Martin-Scott","school":"South Carolina"},
      {"position":"LB","name":"Stone Blanton","school":"Mississippi State"},
      {"position":"LB","name":"Greg Penn III","school":"LSU"},
      {"position":"CB","name":"O’Donnell Fortune","school":"South Carolina"},
      {"position":"CB","name":"Martel Hight","school":"Vanderbilt"},
      {"position":"CB","name":"Zy Alexander","school":"LSU"},
      {"position":"CB","name":"Boo Carter","school":"Tennessee"},
      {"position":"CB","name":"Doneiko Slaughter","school":"Arkansas"},
      {"position":"CB","name":"Kayin Lee","school":"Auburn"},
      {"position":"CB","name":"Jonquis Hardaway","school":"Kentucky"},
      {"position":"CB","name":"Dreyden Norwood","school":"Missouri"},
      {"position":"CB","name":"Jay Crawford","school":"Auburn"},
      {"position":"SS","name":"Major Burns","school":"LSU"},
      {"position":"SS","name":"Isaac Smith","school":"Mississippi State"},
      {"position":"SS","name":"Randon Fontenette","school":"Vanderbilt"},
      {"position":"FS","name":"TJ Metcalf","school":"Arkansas"},
      {"position":"FS","name":"Jordan Castell","school":"Florida"},
      {"position":"FS","name":"Sage Ryan","school":"LSU"},
      {"position":"S","name":"Malaki Starks","school":"Georgia"},
      {"position":"S","name":"Zion Childress","school":"Kentucky"},
      {"position":"S","name":"Daylan Carnell","school":"Missouri"},
      {"position":"FLEX","name":"Sai’vion Jones","school":"LSU"},
      {"position":"FLEX","name":"Trikweze Bridges","school":"Florida"},
      {"position":"FLEX","name":"Keon Sabb","school":"Alabama"},
      {"position":"PK","name":"Trey Smack","school":"Florida"},
      {"position":"PK","name":"Alex Raynor","school":"Kentucky"},
      {"position":"KOS","name":"Josh Turbyville","school":"Tennessee"},
      {"position":"P","name":"James Burnip","school":"Alabama"},
      {"position":"KR","name":"Jeremiah Cobb","school":"Auburn"},
      {"position":"PR","name":"Chimere Dike","school":"Florida"},
      {"position":"ST","name":"Jailen Ruth","school":"Vanderbilt"}
    ]
  }
}
