"""CFN All-Big Ten List"""

{
  "bigTen": {
    "Awards": {
      "PlayerOfTheYear": {"name":"Derrick Harmon","position":"DT","school":"Oregon"},
      "OffensivePlayerOfTheYear": {"name":"Kaleb Johnson","position":"RB","school":"Iowa"},
      "DefensivePlayerOfTheYear": {"name":"Derrick Harmon","position":"DT","school":"Oregon"},
      "SpecialistOfTheYear": {"name":"Dominic Zvada","position":"PK","school":"Michigan"},
      "NewcomerOfTheYear": {"name":"Jeremiah Smith","position":"WR-X","school":"Ohio State"},
      "CoachOfTheYear": {"name":"Curt Cignetti","position":"Coach","school":"Indiana"},
      "ImpactFreshmanOfTheYear": {"name":"Jeremiah Smith","position":"WR-X","school":"Ohio State"}
    },
    "PositionAwards": {
      "QuarterbackOfTheYear": {"name":"Kurtis Rourke","position":"QB","school":"Indiana"},
      "RunningBackOfTheYear": {"name":"Kaleb Johnson","position":"RB","school":"Iowa"},
      "WideReceiverOfTheYear": {"name":"Tai Felton","position":"WR-X","school":"Maryland"},
      "TightEndOfTheYear": {"name":"Tyler Warren","position":"TE","school":"Penn State"},
      "OffensiveTackleOfTheYear": {"name":"Hollin Pierce","position":"LT","school":"Rutgers"},
      "OffensiveGuardOfTheYear": {"name":"Nishad Strother","position":"LG","school":"Oregon"},
      "CenterOfTheYear": {"name":"Mike Katic","position":"C","school":"Indiana"},
      "OffensiveLinemanOfTheYear": {"name":"Hollin Pierce","position":"LT","school":"Rutgers"},
      "OffensiveLineOfTheYear": {"name":"Oregon Ducks","position":"OL Unit","school":"Oregon"},
      "OffensiveNewcomerOfTheYear": {"name":"Jeremiah Smith","position":"WR-X","school":"Ohio State"},
      "OffensiveTransferOfTheYear": {"name":"Kurtis Rourke","position":"QB","school":"Indiana"},
      "EdgeDefenderOfTheYear": {"name":"Mikail Kamara","position":"STUD","school":"Indiana"},
      "InteriorDefenderOfTheYear": {"name":"Derrick Harmon","position":"DT","school":"Oregon"},
      "LinebackerOfTheYear": {"name":"Jay Higgins","position":"MLB","school":"Iowa"},
      "CornerbackOfTheYear": {"name":"Xavier Scott","position":"NB","school":"Illinois"},
      "SafetyOfTheYear": {"name":"Tysheem Johnson","position":"SS","school":"Oregon"},
      "DefensiveLineOfTheYear": {"name":"Indiana Hoosiers","position":"DL Unit","school":"Indiana"},
      "DefensiveNewcomerOfTheYear": {"name":"Illinois Fighting Illini","position":"DL Unit","school":"Illinois"},
      "DefensiveTransferOfTheYear": {"name":"Mikail Kamara","position":"STUD","school":"Indiana"},
      "KickerOfTheYear": {"name":"Dominic Zvada","position":"PK","school":"Michigan"},
      "PunterOfTheYear": {"name":"Rhys Dakin","position":"PT","school":"Iowa"},
      "KickReturnerOfTheYear": {"name":"Kaden Wetjen","position":"KR","school":"Iowa"},
      "PuntReturnerOfTheYear": {"name":"Kaden Wetjen","position":"PR","school":"Iowa"},
      "SpecialTeamerOfTheYear": {"name":"Bryson Bonds","position":"ST","school":"Indiana"},
      "KickoffSpecialistOfTheYear": {"name":"Dragan Kesich","position":"KO","school":"Minnesota"}
    },
    "FirstTeam": {
      "Offense": [
        {"position":"QB","name":"Kurtis Rourke","school":"Indiana"},
        {"position":"RB","name":"Kaleb Johnson","school":"Iowa"},
        {"position":"RB","name":"Jordan James","school":"Oregon"},
        {"position":"WR","name":"Tai Felton","school":"Maryland"},
        {"position":"WR-X","name":"Jeremiah Smith","school":"Ohio State"},
        {"position":"WR-Z","name":"Pat Bryant","school":"Illinois"},
        {"position":"TE","name":"Tyler Warren","school":"Penn State"},
        {"position":"WR-X","name":"Tez Johnson","school":"Oregon"},
        {"position":"LT","name":"Hollin Pierce","school":"Rutgers"},
        {"position":"LG","name":"Nishad Strother","school":"Oregon"},
        {"position":"C","name":"Mike Katic","school":"Indiana"},
        {"position":"RG","name":"Emmanuel Pregnon","school":"USC"},
        {"position":"LT","name":"Josh Conerly Jr.","school":"Oregon"}
      ],
      "Defense": [
        {"position":"STUD","name":"Mikail Kamara","school":"Indiana"},
        {"position":"DT","name":"Derrick Harmon","school":"Oregon"},
        {"position":"DT","name":"Mason Graham","school":"Michigan"},
        {"position":"RDE","name":"Abdul Carter","school":"Penn State"},
        {"position":"MLB","name":"Carson Schwesinger","school":"UCLA"},
        {"position":"LB","name":"Jailin Walker","school":"Indiana"},
        {"position":"MLB","name":"Jay Higgins","school":"Iowa"},
        {"position":"NB","name":"Xavier Scott","school":"Illinois"},
        {"position":"LCB","name":"Torrie Cox Jr.","school":"Illinois"},
        {"position":"LCB","name":"D’Angelo Ponds","school":"Indiana"},
        {"position":"FS","name":"Tysheem Johnson","school":"Oregon"},
        {"position":"FS","name":"Jaylen Reed","school":"Penn State"},
        {"position":"SS","name":"Lathan Ransom","school":"Ohio State"},
        {"position":"WLB","name":"Aiden Fisher","school":"Indiana"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Dominic Zvada","school":"Michigan"},
        {"position":"KO","name":"Dragan Kesich","school":"Minnesota"},
        {"position":"PT","name":"Rhys Dakin","school":"Iowa"},
        {"position":"KR","name":"Kaden Wetjen","school":"Iowa"},
        {"position":"PR","name":"Kaden Wetjen","school":"Iowa"},
        {"position":"ST","name":"Bryson Bonds","school":"Indiana"}
      ]
    },
    "SecondTeam": {
      "Offense": [
        {"position":"QB","name":"Dillon Gabriel","school":"Oregon"},
        {"position":"RB","name":"Kyle Monangai","school":"Rutgers"},
        {"position":"RB","name":"Kalel Mullings","school":"Michigan"},
        {"position":"WR-X","name":"Elijah Sarratt","school":"Indiana"},
        {"position":"WR-X","name":"Denzel Boston","school":"Washington"},
        {"position":"WR-Z","name":"Emeka Egbuka","school":"Ohio State"},
        {"position":"TE","name":"Colston Loveland","school":"Michigan"},
        {"position":"WR-Z","name":"Harrison Wallace III","school":"Penn State"},
        {"position":"LT","name":"Aireontae Ersery","school":"Minnesota"},
        {"position":"LG","name":"Olaivavega Ioane","school":"Penn State"},
        {"position":"C","name":"Logan Jones","school":"Iowa"},
        {"position":"RG","name":"Connor Colby","school":"Iowa"},
        {"position":"RT","name":"Gennings Dunker","school":"Iowa"}
      ],
      "Defense": [
        {"position":"LOLB","name":"Gabe Jacas","school":"Illinois"},
        {"position":"DT","name":"James Carpenter","school":"Indiana"},
        {"position":"DT","name":"Kenneth Grant","school":"Michigan"},
        {"position":"DE","name":"Jack Sawyer","school":"Ohio State"},
        {"position":"MLB","name":"Kydran Jenkins","school":"Purdue"},
        {"position":"MLB","name":"Daniel Djabome","school":"Rutgers"},
        {"position":"MLB","name":"Carson Bruener","school":"Washington"},
        {"position":"LCB","name":"Malcolm Hartzog","school":"Nebraska"},
        {"position":"RCB","name":"Ethan Robinson","school":"Minnesota"},
        {"position":"RCB","name":"Charles Brantley","school":"Michigan State"},
        {"position":"SS","name":"Nikai Martinez","school":"Michigan State"},
        {"position":"FS","name":"Koi Perich","school":"Minnesota"},
        {"position":"SS","name":"Dillon Thieneman","school":"Purdue"},
        {"position":"FS","name":"Caleb Downs","school":"Ohio State"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Drew Stevens","school":"Iowa"},
        {"position":"KO","name":"Atticus Sappington","school":"Oregon"},
        {"position":"PT","name":"Eddie Czaplicki","school":"USC"},
        {"position":"KR","name":"Joseph Himon II","school":"Northwestern"},
        {"position":"PR","name":"Tez Johnson","school":"Oregon"},
        {"position":"ST","name":"Isaiah Jones","school":"Indiana"}
      ]
    },
    "ThirdTeam": {
      "Offense": [
        {"position":"QB","name":"Drew Allar","school":"Penn State"},
        {"position":"RB","name":"Jonah Coleman","school":"Washington"},
        {"position":"RB","name":"Woody Marks","school":"USC"},
        {"position":"WR-X","name":"Nick Marsh","school":"Michigan State"},
        {"position":"WR-Z","name":"Daniel Jackson","school":"Minnesota"},
        {"position":"WR-X","name":"Dymere Miller","school":"Rutgers"},
        {"position":"TE","name":"Terrance Ferguson","school":"Oregon"},
        {"position":"WR-X","name":"Kaden Prather","school":"Maryland"},
        {"position":"OT","name":"Marcus Mbow","school":"Purdue"},
        {"position":"LG","name":"Josh Thompson","school":"Northwestern"},
        {"position":"C","name":"Jonah Monheim","school":"USC"},
        {"position":"RG","name":"Tyler Cooper","school":"Minnesota"},
        {"position":"RT","name":"Caleb Tiernan","school":"Northwestern"}
      ],
      "Defense": [
        {"position":"DE","name":"Josaiah Stewart","school":"Michigan"},
        {"position":"LDT","name":"Aaron Graves","school":"Iowa"},
        {"position":"NT","name":"Ty Robinson","school":"Nebraska"},
        {"position":"DE","name":"Matayo Uiagalelei","school":"Oregon"},
        {"position":"MLB","name":"Cody Lindenberg","school":"Minnesota"},
        {"position":"MLB","name":"Ernest Hausmann","school":"Michigan"},
        {"position":"WLB","name":"Kain Medrano","school":"UCLA"},
        {"position":"BCB","name":"Nikko Reed","school":"Oregon"},
        {"position":"LCB","name":"Justin Walley","school":"Minnesota"},
        {"position":"LCB","name":"Zeke Berry","school":"Michigan"},
        {"position":"SS","name":"Kobe Savage","school":"Oregon"},
        {"position":"FS","name":"Quinn Schulte","school":"Iowa"},
        {"position":"FS","name":"Miles Scott","school":"Illinois"},
        {"position":"MLB","name":"Cody Simon","school":"Ohio State"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Mateen Bhaghani","school":"UCLA"},
        {"position":"KO","name":"Michael Lantz","school":"USC"},
        {"position":"PT","name":"Atticus Bertrams","school":"Wisconsin"},
        {"position":"KR","name":"Makai Lemon","school":"USC"},
        {"position":"PR","name":"Caleb Downs","school":"Ohio State"},
        {"position":"MLB","name":"Braydon Brus","school":"Northwestern"}
      ]
    },
    "HonorableMention": [
      {"position":"QB","name":"Will Howard","school":"Ohio State"},
      {"position":"QB","name":"Billy Edwards","school":"Maryland"},
      {"position":"QB","name":"Luke Altmyer","school":"Illinois"},
      {"position":"RB","name":"Darius Taylor","school":"Minnesota"},
      {"position":"RB","name":"Dante Dowdell","school":"Nebraska"},
      {"position":"RB","name":"Justice Ellison","school":"Indiana"},
      {"position":"RB","name":"Ty Son Lawton","school":"Indiana"},
      {"position":"RB","name":"Kaytron Allen","school":"Penn State"},
      {"position":"RB","name":"Nicholas Singleton","school":"Penn State"},
      {"position":"WR-X","name":"Giles Jackson","school":"Washington"},
      {"position":"WR-X","name":"Vinny Anthony II","school":"Wisconsin"},
      {"position":"WR-X","name":"Zakhari Franklin","school":"Illinois"},
      {"position":"WR-Z","name":"Carnell Tate","school":"Ohio State"},
      {"position":"WR-Z","name":"Omar Cooper Jr.","school":"Indiana"},
      {"position":"WR-X","name":"Bryce Kirtz","school":"Northwestern"},
      {"position":"WR-Z","name":"Evan Stewart","school":"Oregon"},
      {"position":"WR-Y","name":"Makai Lemon","school":"USC"},
      {"position":"WR-F","name":"Traeshon Holden","school":"Oregon"},
      {"position":"TE","name":"Jameson Geers","school":"Minnesota"},
      {"position":"TE","name":"Zach Horton","school":"Indiana"},
      {"position":"TE","name":"Max Klare","school":"Purdue"},
      {"position":"RB","name":"TreVeyon Henderson","school":"Ohio State"},
      {"position":"RB","name":"Quinshon Judkins","school":"Ohio State"},
      {"position":"RB","name":"Tawee Walker","school":"Wisconsin"},
      {"position":"RT","name":"Ajani Cornelius","school":"Oregon"},
      {"position":"LT","name":"Bryce Benhart","school":"Nebraska"},
      {"position":"LT","name":"Trey Wedig","school":"Indiana"},
      {"position":"OG","name":"Luke Newman","school":"Michigan State"},
      {"position":"RG","name":"Josh Priebe","school":"Michigan"},
      {"position":"RG","name":"Sal Wormley","school":"Penn State"},
      {"position":"C","name":"Gus Hartwig","school":"Purdue"},
      {"position":"C","name":"Seth McLaughlin","school":"Ohio State"},
      {"position":"C","name":"Iapani Laloulu","school":"Oregon"},
      {"position":"RG","name":"Kwabena Asamoah","school":"Rutgers"},
      {"position":"C","name":"Justin Evans","school":"Nebraska"},
      {"position":"LG","name":"Drew Evans","school":"Indiana"},
      {"position":"RT","name":"Quinn Carroll","school":"Minnesota"},
      {"position":"LT","name":"Carter Smith","school":"Indiana"},
      {"position":"RT","name":"Anthony Donkoh","school":"Penn State"},
      {"position":"JACK","name":"Teitum Tuioti","school":"Oregon"},
      {"position":"LDE","name":"Oluwafemi Oladejo","school":"UCLA"},
      {"position":"LDE","name":"Max Llewellyn","school":"Iowa"},
      {"position":"DT","name":"Anthony Smith","school":"Minnesota"},
      {"position":"NT","name":"TeRah Edwards","school":"Illinois"},
      {"position":"NT","name":"Dennis Briggs Jr.","school":"Illinois"},
      {"position":"DT","name":"CJ West","school":"Indiana"},
      {"position":"LDT","name":"Zane Durant","school":"Penn State"},
      {"position":"DT","name":"Kyonte Hamilton","school":"Rutgers"},
      {"position":"LDE","name":"Dani Dennis-Sutton","school":"Penn State"},
      {"position":"RUSH","name":"JT Tuimoloau","school":"Ohio State"},
      {"position":"DT","name":"Jah Joyner","school":"Minnesota"},
      {"position":"MLB","name":"Mac Uihlein","school":"Northwestern"},
      {"position":"WLB","name":"Tony Rojas","school":"Penn State"},
      {"position":"MAC","name":"Bryce Boettcher","school":"Oregon"},
      {"position":"MLB","name":"Kobe King","school":"Penn State"},
      {"position":"WLB","name":"Alphonzo Tuputala","school":"Washington"},
      {"position":"WLB","name":"Jaishawn Barham","school":"Michigan"},
      {"position":"MLB","name":"Rolijah Hardy","school":"Indiana"},
      {"position":"WLB","name":"Mason Cobb","school":"USC"},
      {"position":"MLB","name":"Easton Mascarenas-Arnold","school":"USC"},
      {"position":"RCB","name":"Will Johnson","school":"Michigan"},
      {"position":"LCB","name":"Jermari Harris","school":"Iowa"},
      {"position":"RCB","name":"A.J. Harris","school":"Penn State"},
      {"position":"RCB","name":"Kaylin Moore","school":"UCLA"},
      {"position":"FCB","name":"Jabbar Muhammad","school":"Oregon"},
      {"position":"RCB","name":"Bo Mascoe","school":"Rutgers"},
      {"position":"LCB","name":"Thaddeus Dixon","school":"Washington"},
      {"position":"RCB","name":"Greedy Vance Jr.","school":"USC"},
      {"position":"RCB","name":"Robert Longerbeam","school":"Rutgers"},
      {"position":"SS","name":"Antonio Stevens","school":"Purdue"},
      {"position":"SS","name":"DeShon Singleton","school":"Nebraska"},
      {"position":"SS","name":"Matthew Bailey","school":"Illinois"},
      {"position":"FS","name":"Zakee Wheatley","school":"Penn State"},
      {"position":"SS","name":"Quinten Johnson","school":"Michigan"},
      {"position":"FS","name":"Bryan Addison","school":"UCLA"},
      {"position":"SS","name":"Dante Trader Jr.","school":"Maryland"},
      {"position":"SS","name":"Jalen Huskey","school":"Maryland"},
      {"position":"SS","name":"Hunter Wohler","school":"Wisconsin"},
      {"position":"WLB","name":"Sonny Styles","school":"Ohio State"},
      {"position":"FS","name":"Kamren Fabiculanan","school":"Washington"},
      {"position":"FS","name":"Glendon Miller","school":"Maryland"},
      {"position":"PK","name":"Jonathan Kim","school":"Michigan State"},
      {"position":"KO","name":"Tommy Doman","school":"Michigan"},
      {"position":"PT","name":"Bryce McFerson","school":"Maryland"},
      {"position":"KR","name":"Nicholas Singleton","school":"Penn State"},
      {"position":"PR","name":"Hank Beatty","school":"Illinois"},
      {"position":"NB","name":"Zion Tracy","school":"Penn State"}
    ]
  }
}
