"""2024 CFN All‑ACC Team & Awards"""

{
  "acc": {
    "Awards": {
      "PlayerOfTheYear": {"name":"Cam Ward","position":"QB","school":"Miami"},
      "OffensivePlayerOfTheYear": {"name":"Cam Ward","position":"QB","school":"Miami"},
      "DefensivePlayerOfTheYear": {"name":"Nohl Williams","position":"LCB","school":"California"},
      "SpecialistOfTheYear": {"name":"Collin Rogers","position":"PK","school":"SMU"},
      "NewcomerOfTheYear": {"name":"Desmond Reid","position":"RB","school":"Pittsburgh"},
      "CoachOfTheYear": {"name":"Rhett Lashlee","position":"Coach","school":"SMU"}
    },
    "PositionAwards": {
      "QuarterbackOfTheYear": {"name":"Cam Ward","position":"QB","school":"Miami"},
      "RunningBackOfTheYear": {"name":"Omarion Hampton","position":"RB","school":"North Carolina"},
      "WideReceiverOfTheYear": {"name":"Xavier Restrepo","position":"WR-X","school":"Miami"},
      "TightEndOfTheYear": {"name":"Oronde Gadsden II","position":"TE","school":"Syracuse"},
      "OffensiveTackleOfTheYear": {"name":"PJ Williams","position":"RT","school":"SMU"},
      "OffensiveGuardOfTheYear": {"name":"Willie Lampkin","position":"RG","school":"North Carolina"},
      "CenterOfTheYear": {"name":"Zeke Correll","position":"C","school":"NC State"},
      "OffensiveLinemanOfTheYear": {"name":"PJ Williams","position":"RT","school":"SMU"},
      "OffensiveLineOfTheYear": {"name":"SMU Mustangs","position":"OL Unit","school":"SMU"},
      "OffensiveNewcomerOfTheYear": {"name":"Desmond Reid","position":"RB","school":"Pittsburgh"},
      "EdgeDefenderOfTheYear": {"name":"Donovan Ezeiruaku","position":"RDE","school":"Boston College"},
      "InteriorDefenderOfTheYear": {"name":"Jared Harrison-Hunte","position":"LDT","school":"SMU"},
      "LinebackerOfTheYear": {"name":"Kyle Louis","position":"STAR","school":"Pittsburgh"},
      "CornerbackOfTheYear": {"name":"Nohl Williams","position":"LCB","school":"California"},
      "SafetyOfTheYear": {"name":"Isaiah Nwokobia","position":"S","school":"SMU"},
      "DefensiveLineOfTheYear": {"name":"SMU Mustangs","position":"DL Unit","school":"SMU"},
      "SecondaryOfTheYear": {"name":"Miami secondary","position":"Secondary Unit","school":"Miami"},
      "DefensiveNewcomerOfTheYear": {"name":"Jared Harrison-Hunte","position":"LDT","school":"SMU"},
      "KickerOfTheYear": {"name":"Collin Rogers","position":"PK","school":"SMU"},
      "PunterOfTheYear": {"name":"Alex Mastromanno","position":"P","school":"Florida State"},
      "KickReturnerOfTheYear": {"name":"Chris Johnson Jr.","position":"KR","school":"Wake Forest"},
      "PuntReturnerOfTheYear": {"name":"Taylor Morin","position":"PR","school":"Georgia Tech"},
      "SpecialTeamerOfTheYear": {"name":"Daylon Gordon","position":"RB","school":"North Carolina"},
      "KickoffSpecialistOfTheYear": {"name":"Andres Borregales","position":"KO","school":"Miami"}
    },
    "FirstTeam": {
      "Offense": [
        {"position":"QB","name":"Cam Ward","school":"Miami"},
        {"position":"RB","name":"Omarion Hampton","school":"North Carolina"},
        {"position":"RB","name":"LeQuint Allen","school":"Syracuse"},
        {"position":"WR-X","name":"Xavier Restrepo","school":"Miami"},
        {"position":"WR-X","name":"Ja’Corey Brooks","school":"Louisville"},
        {"position":"WR-X","name":"Jackson Meeks","school":"Syracuse"},
        {"position":"TE","name":"Oronde Gadsden II","school":"Syracuse"},
        {"position":"RB","name":"Desmond Reid","school":"Pittsburgh"},
        {"position":"RT","name":"Brian Parker II","school":"Duke"},
        {"position":"RG","name":"Willie Lampkin","school":"North Carolina"},
        {"position":"C","name":"Zeke Correll","school":"NC State"},
        {"position":"RG","name":"Justin Osborne","school":"SMU"},
        {"position":"RT","name":"PJ Williams","school":"SMU"}
      ],
      "Defense": [
        {"position":"RDE","name":"Donovan Ezeiruaku","school":"Boston College"},
        {"position":"RDE","name":"Ashton Gillotte","school":"Louisville"},
        {"position":"LDT","name":"Jared Harrison-Hunte","school":"SMU"},
        {"position":"DT","name":"Simeon Barrow Jr.","school":"Miami"},
        {"position":"STAR","name":"Kyle Louis","school":"Pittsburgh"},
        {"position":"WLB","name":"Francisco Mauigoa","school":"Miami"},
        {"position":"LILB","name":"Teddye Buchanan","school":"California"},
        {"position":"LCB","name":"Nohl Williams","school":"California"},
        {"position":"LCB","name":"Avieon Terrell","school":"Clemson"},
        {"position":"RCB","name":"Deuce Harmon","school":"SMU"},
        {"position":"SS","name":"Jaylen Jones","school":"Virginia Tech"},
        {"position":"FS","name":"Jonathan McGill","school":"SMU"},
        {"position":"SS","name":"Isaiah Nwokobia","school":"SMU"},
        {"position":"RCB","name":"Chandler Rivers","school":"Duke"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Collin Rogers","school":"SMU"},
        {"position":"KO","name":"Andres Borregales","school":"Miami"},
        {"position":"PT","name":"Alex Mastromanno","school":"Florida State"},
        {"position":"KR","name":"Chris Johnson Jr.","school":"Miami"},
        {"position":"PR","name":"Taylor Morin","school":"wake-forest"},
        {"position":"RB","name":"Daylon Gordon","school":"georgia-tech"}
      ]
    },
    "SecondTeam": {
      "Offense": [
        {"position":"QB","name":"Kyle McCord","school":"Syracuse"},
        {"position":"RB","name":"Bhayshul Tuten","school":"Virginia Tech"},
        {"position":"RB","name":"Isaac Brown","school":"Louisville"},
        {"position":"WR-H","name":"Antonio Williams","school":"Clemson"},
        {"position":"WR-X","name":"Elic Ayomanor","school":"Stanford"},
        {"position":"WR-X","name":"Konata Mumpfield","school":"Pittsburgh"},
        {"position":"TE","name":"Jake Briningstool","school":"Clemson"},
        {"position":"RB","name":"Brashard Smith","school":"SMU"},
        {"position":"RT","name":"Francis Mauigoa","school":"Miami"},
        {"position":"LG","name":"Anthony Carter Jr.","school":"NC State"},
        {"position":"C","name":"Pete Nygra","school":"Louisville"},
        {"position":"RG","name":"Timothy McKay","school":"NC State"},
        {"position":"LT","name":"Monroe Mills","school":"Louisville"}
      ],
      "Defense": [
        {"position":"RDE","name":"Elijah Roberts","school":"smu"},
        {"position":"LDE","name":"Tyler Baron","school":"miami"},
        {"position":"RDT","name":"Aeneas Peebles","school":"virginia-tech"},
        {"position":"NT","name":"Darrell Jackson Jr","school":"florida-state"},
        {"position":"WLB","name":"Cameron Bergeron","school":"duke"},
        {"position":"WLB","name":"Amare Campbell","school":"north-carolina"},
        {"position":"MLB","name":"Alex Howard","school":"duke"},
        {"position":"LCB","name":"Quincy Riley","school":"Louisville"},
        {"position":"LCB","name":"Daryl Porter Jr.","school":"Miami"},
        {"position":"LCB","name":"Kempton Shine","school":"virginia-tech"},
        {"position":"FS","name":"Javon McIntyre","school":"Pittsburgh"},
        {"position":"FS","name":"Nick Andersen","school":"Wake Forest"},
        {"position":"FS","name":"Mishael Powell","school":"Miami"},
        {"position":"LDE","name":"T.J. Parker","school":"Clemson"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Ben Sauls","school":"pittsburgh"},
        {"position":"KO","name":"Aidan Birr","school":"Georgia Tech"},
        {"position":"PT","name":"Daniel Sparks","school":"virginia"},
        {"position":"KR","name":"Samuel Singleton Jr.","school":"Florida State"},
        {"position":"PR","name":"Tiger Bachmeier","school":"Stanford"},
        {"position":"BCB","name":"Shadarian Harrison","school":"Pittsburgh"}
      ]
    },
    "ThirdTeam": {
      "Offense": [
        {"position":"QB","name":"Cade Klubnik","school":"Clemson"},
        {"position":"RB","name":"Demond Claiborne","school":"Wake-Forest"},
        {"position":"RB","name":"Phil Mafah","school":"Clemson"},
        {"position":"WR-X","name":"Jordan Moore","school":"Duke"},
        {"position":"WR-X","name":"Malachi Fields","school":"Virginia"},
        {"position":"WR-Z","name":"Eli Pancol","school":"Duke"},
        {"position":"TE","name":"Elijah Arroyo","school":"miami"},
        {"position":"FLEX","name":"Trebor Pena","school":"syracuse"},
        {"position":"LT","name":"DeVonte Gordon","school":"Wake Forest"},
        {"position":"LG","name":"Matt Gulbin","school":"Wake Forest"},
        {"position":"C","name":"Brian Stevens","school":"Virginia"},
        {"position":"LG","name":"Caleb Krings","school":"Duke"},
        {"position":"LT","name":"Blake Steen","school":"Virginia"}
      ],
      "Defense": [
        {"position":"RDE","name":"Antwaun Powell-Ryland","school":"Virginia Tech"},
        {"position":"DE","name":"Kam Butler","school":"virginia"},
        {"position":"RDT","name":"Kevin Pointer","school":"wake-forest"},
        {"position":"NT","name":"Joshua Farmer","school":"Florida State"},
        {"position":"DE","name":"Kam Butler","school":"Virginia"},
        {"position":"WLB","name":"Rasheem Biles","school":"Pittsburgh"},
        {"position":"STAR","name":"Ozzie Nicholas","school":"Duke"},
        {"position":"MLB","name":"Kobe Wilson","school":"SMU"},
        {"position":"CB","name":"Ahmari Harvey","school":"Georgia Tech"},
        {"position":"RCB","name":"Dorian Strong","school":"Virginia Tech"},
        {"position":"FCB","name":"Alijah Huzzie","school":"north-carolina"},
        {"position":"BS","name":"Donovan McMillon","school":"Pittsburgh"},
        {"position":"SS","name":"Craig Woodson","school":"California"},
        {"position":"FS","name":"Terry Moore","school":"duke"},
        {"position":"FLEX","name":"Justin Barron","school":"Syracuse"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Ryan Fitzgerald","school":"florida-state"},
        {"position":"KO","name":"Ryan Coe","school":"California"},
        {"position":"PT","name":"Peter Moore","school":"Virginia Tech"},
        {"position":"KR","name":"Kenny Johnson","school":"Pittsburgh"},
        {"position":"PR","name":"Jaylin Lane","school":"Virginia Tech"},
        {"position":"SS","name":"Dylan Day","school":"Miami"}
      ]
    },
    "HonorableMention": [
      {"position":"QB","name":"Kevin Jennings","school":"SMU"},
      {"position":"QB","name":"Eli Holstein","school":"Pittsburgh"},
      {"position":"QB","name":"Maalik Murphy","school":"Duke"},
      {"position":"RB","name":"Javian Thomas","school":"California"},
      {"position":"RB","name":"Jaydn Ott","school":"California"},
      {"position":"RB","name":"Mark Fletcher Jr.","school":"Miami"},
      {"position":"RB","name":"Kye Robichaux","school":"Boston College"},
      {"position":"RB","name":"Damien Martinez","school":"Miami"},
      {"position":"RB","name":"Jamal Haynes","school":"Georgia Tech"},
      {"position":"WR-X","name":"Taylor Morin","school":"Wake Forest"},
      {"position":"WR-X","name":"J.J. Jones","school":"North Carolina"},
      {"position":"WR-Z","name":"Jacolby George","school":"Miami"},
      {"position":"WR-X","name":"Chris Bell","school":"Louisville"},
      {"position":"WR-Z","name":"Key’Shawn Smith","school":"SMU"},
      {"position":"WR-Z","name":"Emmett Mosley V","school":"Stanford"},
      {"position":"WR-Z","name":"Bryant Wesco Jr.","school":"Clemson"},
      {"position":"WR-X","name":"Roderick Daniels Jr.","school":"SMU"},
      {"position":"WR-X","name":"Nyziah Hunter","school":"California"},
      {"position":"TE","name":"John Copenhaver","school":"North Carolina"},
      {"position":"TE","name":"Tyler Neville","school":"Virginia"},
      {"position":"TE","name":"Jack Endries","school":"California"},
      {"position":"TE","name":"Justin Joly","school":"NC State"},
      {"position":"LT","name":"Jacarrius Peak","school":"NC State"},
      {"position":"RT","name":"Keagen Trost","school":"Wake Forest"},
      {"position":"LT","name":"Savion Washington","school":"Syracuse"},
      {"position":"LG","name":"Matthew McCoy","school":"Miami"},
      {"position":"LG","name":"Michael Gonzalez","school":"Louisville"},
      {"position":"RG","name":"Marcus Tate","school":"Clemson"},
      {"position":"C","name":"Drew Kendall","school":"Boston College"},
      {"position":"C","name":"Weston Franklin","school":"Georgia Tech"},
      {"position":"OG","name":"Keylan Rutledge","school":"Georgia Tech"},
      {"position":"LG","name":"Kaden Moore","school":"Virginia Tech"},
      {"position":"C","name":"Jakai Clark","school":"SMU"},
      {"position":"RG","name":"BJ Williams","school":"Pittsburgh"},
      {"position":"LT","name":"Xavier Chaplin","school":"Virginia Tech"},
      {"position":"LT","name":"Anthony Belton","school":"NC State"},
      {"position":"LT","name":"Ozzy Trapilo","school":"Boston College"},
      {"position":"DE","name":"David Bailey","school":"Stanford"},
      {"position":"LDE","name":"Jahfari Harvey","school":"SMU"},
      {"position":"RDE","name":"Fadil Diggs","school":"Syracuse"},
      {"position":"RDT","name":"Kendy Charles","school":"Duke"},
      {"position":"RDT","name":"Bryce Ganious","school":"Wake Forest"},
      {"position":"NT","name":"Aidan Keanaaina","school":"California"},
      {"position":"LDT","name":"Wilfried Pene","school":"Virginia Tech"},
      {"position":"RDT","name":"Payton Page","school":"Clemson"},
      {"position":"DT","name":"Dezmond Tell","school":"Louisville"},
      {"position":"RDE","name":"Isaiah Smith","school":"SMU"},
      {"position":"BAN","name":"Jasheen Davis","school":"Wake Forest"},
      {"position":"LDE","name":"Xavier Carlton","school":"California"},
      {"position":"WLB","name":"Caleb Woodson","school":"Virginia Tech"},
      {"position":"WLB","name":"Daveon Crouch","school":"Boston College"},
      {"position":"MLB","name":"Power Echols","school":"North Carolina"},
      {"position":"WLB","name":"Stanquan Clark","school":"Louisville"},
      {"position":"WLB","name":"Branson Combs","school":"Wake Forest"},
      {"position":"WLB","name":"Sammy Brown","school":"Clemson"},
      {"position":"RILB","name":"Cade Uluave","school":"California"},
      {"position":"WLB","name":"Tre Freeman","school":"Duke"},
      {"position":"WLB","name":"Wesley Bissainthe","school":"Miami"},
      {"position":"LCB","name":"Devon Marshall","school":"NC State"},
      {"position":"BCB","name":"Kaleb Cost","school":"North Carolina"},
      {"position":"RCB","name":"Ashton Hampton","school":"Clemson"},
      {"position":"RCB","name":"Azareye’h Thomas","school":"Florida State"},
      {"position":"LCB","name":"Kevin Knowles II","school":"Florida State"},
      {"position":"LCB","name":"Max Tucker","school":"Boston College"},
      {"position":"LCB","name":"Clarence Lewis","school":"Syracuse"},
      {"position":"RCB","name":"Jeadyn Lukus","school":"Clemson"},
      {"position":"RCB","name":"Corey Thornton","school":"Louisville"},
      {"position":"SS","name":"Davaughn Patterson","school":"Wake Forest"},
      {"position":"FS","name":"Shyheim Brown","school":"Florida State"},
      {"position":"SS","name":"Cale Sanders Jr.","school":"SMU"},
      {"position":"SS","name":"Duce Chestnut","school":"Syracuse"},
      {"position":"FS","name":"Jonas Sanker","school":"Virginia"},
      {"position":"FS","name":"Mitch Leigber","school":"Stanford"},
      {"position":"FS","name":"Tamarcus Cooley","school":"NC State"},
      {"position":"FS","name":"Ahmaad Moses","school":"SMU"},
      {"position":"SS","name":"R.J. Mickens","school":"Clemson"},
      {"position":"SS","name":"Jaylen Stinson","school":"Duke"},
      {"position":"MLB","name":"Keonta Jenkins","school":"Virginia Tech"}
    ]
  }
}
