"""CFN's All-Big-12 Conference List for 2024"""

{
  "big12": {
    "Awards": {
      "PlayerOfTheYear": {"name":"Travis Hunter","position":"LCB","school":"Colorado"},
      "OffensivePlayerOfTheYear": {"name":"Cam Skattebo","position":"RB","school":"Arizona State"},
      "DefensivePlayerOfTheYear": {"name":"Travis Hunter","position":"LCB","school":"Colorado"},
      "SpecialistOfTheYear": {"name":"Tyler Loop","position":"PK","school":"Arizona"},
      "NewcomerOfTheYear": {"name":"Jack Kelly","position":"ROVER","school":"Brigham Young"},
      "CoachOfTheYear": {"name":"Kenny Dillingham","position":"Coach","school":"Arizona State"},
      "ImpactFreshmanOfTheYear": {"name":"Jordan Seaton","position":"LT","school":"Colorado"}
    },
    "PositionAwards": {
      "QuarterbackOfTheYear": {"name":"Shedeur Sanders","position":"QB","school":"Colorado"},
      "RunningBackOfTheYear": {"name":"Cam Skattebo","position":"RB","school":"Arizona State"},
      "WideReceiverOfTheYear": {"name":"Tetairoa McMillan","position":"WR-X","school":"Arizona"},
      "TightEndOfTheYear": {"name":"Brant Kuithe","position":"TE","school":"Utah"},
      "OffensiveTackleOfTheYear": {"name":"Wyatt Milum","position":"OT","school":"West Virginia"},
      "OffensiveGuardOfTheYear": {"name":"Luke Kandra","position":"OG","school":"Cincinnati"},
      "CenterOfTheYear": {"name":"James Brockermeyer","position":"C","school":"TCU"},
      "OffensiveLinemanOfTheYear": {"name":"Wyatt Milum","position":"OT","school":"West Virginia"},
      "OffensiveLineOfTheYear": {"name":"West Virginia Mountaineers","position":"OL Unit","school":"West Virginia"},
      "OffensiveNewcomerOfTheYear": {"name":"Josh Kelly","position":"WR-X","school":"Texas Tech"},
      "OffensiveTransferOfTheYear": {"name":"Josh Kelly","position":"WR-X","school":"Texas Tech"},
      "EdgeDefenderOfTheYear": {"name":"B.J. Green II","position":"LDE","school":"Colorado"},
      "InteriorDefenderOfTheYear": {"name":"Dontay Corleone","position":"DT","school":"Cincinnati"},
      "LinebackerOfTheYear": {"name":"Jacob Rodriguez","position":"WLB","school":"Texas Tech"},
      "CornerbackOfTheYear": {"name":"Travis Hunter","position":"LCB","school":"Colorado"},
      "SafetyOfTheYear": {"name":"Xavion Alford","position":"FS","school":"Arizona State"},
      "DefensiveLineOfTheYear": {"name":"Colorado Buffaloes","position":"DL Unit","school":"Colorado"},
      "SecondaryOfTheYear": {"name":"Arizona State Sun Devils","position":"Secondary Unit","school":"Arizona State"},
      "DefensiveNewcomerOfTheYear": {"name":"Jack Kelly","position":"ROVER","school":"Brigham Young"},
      "DefensiveTransferOfTheYear": {"name":"Jack Kelly","position":"ROVER","school":"Brigham Young"},
      "KickerOfTheYear": {"name":"Will Ferrin","position":"PK","school":"Brigham Young"},
      "PunterOfTheYear": {"name":"Palmer Williams","position":"P","school":"Baylor"},
      "KickReturnerOfTheYear": {"name":"Keelan Marion","position":"KR","school":"Brigham Young"},
      "PuntReturnerOfTheYear": {"name":"JP Richardson","position":"PR","school":"TCU"},
      "SpecialTeamerOfTheYear": {"name":"Micah Gifford","position":"ST","school":"Baylor"},
      "KickoffSpecialistOfTheYear": {"name":"Tyler Loop","position":"KO","school":"Arizona"}
    },
    "FirstTeam": {
      "Offense": [
        {"position":"QB","name":"Shedeur Sanders","school":"Colorado"},
        {"position":"RB","name":"RJ Harvey","school":"Central Florida"},
        {"position":"RB","name":"Cam Skattebo","school":"Arizona State"},
        {"position":"WR-X","name":"Tetairoa McMillan","school":"Arizona"},
        {"position":"WR","name":"Travis Hunter","school":"Colorado"},
        {"position":"WR-F","name":"Jordyn Tyson","school":"Arizona State"},
        {"position":"TE","name":"Brant Kuithe","school":"Utah"},
        {"position":"FLEX","name":"DJ Giddens","school":"Kansas State"},
        {"position":"OT","name":"Wyatt Milum","school":"West Virginia"},
        {"position":"OG","name":"Luke Kandra","school":"Cincinnati"},
        {"position":"OC","name":"James Brockermeyer","school":"TCU"},
        {"position":"OG","name":"Tomas Rimac","school":"West Virginia"},
        {"position":"OT","name":"Spencer Fano","school":"Utah"}
      ],
      "Defense": [
        {"position":"LCB","name":"B.J. Green II","school":"Colorado"},
        {"position":"DT","name":"Dontay Corleone","school":"Cincinnati"},
        {"position":"DT","name":"Ricky Barber","school":"Central Florida"},
        {"position":"EDGE","name":"Brendan Mott","school":"Kansas State"},
        {"position":"LB","name":"Jacob Rodriguez","school":"Texas Tech"},
        {"position":"SLB","name":"Isaiah Glasker","school":"Brigham Young"},
        {"position":"ROVER","name":"Jack Kelly","school":"Brigham Young"},
        {"position":"LCB","name":"Travis Hunter","school":"Colorado"},
        {"position":"SS","name":"Shamari Simmons","school":"Arizona State"},
        {"position":"LCB","name":"Mello Dotson","school":"Kansas"},
        {"position":"SS","name":"Dalton Johnson","school":"Arizona"},
        {"position":"FS","name":"Xavion Alford","school":"Arizona State"},
        {"position":"S","name":"Bud Clark","school":"TCU"},
        {"position":"FLEX","name":"Lander Barton","school":"Utah"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Will Ferrin","school":"Brigham Young"},
        {"position":"KO","name":"Tyler Loop","school":"Arizona"},
        {"position":"P","name":"Palmer Williams","school":"Baylor"},
        {"position":"KR","name":"Keelan Marion","school":"Brigham Young"},
        {"position":"PR","name":"JP Richardson","school":"TCU"},
        {"position":"ST","name":"Micah Gifford","school":"Baylor"}
      ]
    },
    "SecondTeam": {
      "Offense": [
        {"position":"QB","name":"Sam Leavitt","school":"Arizona State"},
        {"position":"RB","name":"Tahj Brooks","school":"Texas Tech"},
        {"position":"RB","name":"Devin Neal","school":"Kansas"},
        {"position":"WR","name":"Jack Bech","school":"TCU"},
        {"position":"WR","name":"Jayden Higgins","school":"Iowa State"},
        {"position":"WR-X","name":"Josh Kelly","school":"Texas Tech"},
        {"position":"TE","name":"Joe Royer","school":"Cincinnati"},
        {"position":"FLEX","name":"Jaylin Noel","school":"Iowa State"},
        {"position":"OT","name":"Bryce Cabeldue","school":"Kansas"},
        {"position":"OG","name":"Tanoa Togiai","school":"Utah"},
        {"position":"C","name":"Jaren Kump","school":"Utah"},
        {"position":"RG","name":"Davion Carter","school":"Texas Tech"},
        {"position":"OT","name":"Logan Brown","school":"Kansas"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Keith Cooper Jr.","school":"Houston"},
        {"position":"DT","name":"Treven Ma’ae","school":"Baylor"},
        {"position":"DT","name":"Lee Hunter","school":"Central Florida"},
        {"position":"RDE","name":"Tyler Batty","school":"Brigham Young"},
        {"position":"MLB","name":"Nikhai Hill-Green","school":"Colorado"},
        {"position":"LB","name":"Jonathan Thompson","school":"Cincinnati"},
        {"position":"LILB","name":"Matt Jones","school":"Baylor"},
        {"position":"CB","name":"Jeremiah Wilson","school":"Houston"},
        {"position":"CB","name":"Jontez Williams","school":"Iowa State"},
        {"position":"CB","name":"Cobee Bryant","school":"Kansas"},
        {"position":"SS","name":"Myles Rowser","school":"Arizona State"},
        {"position":"FS","name":"Tao Johnson","school":"Utah"},
        {"position":"S","name":"A.J. Haulcy","school":"Houston"},
        {"position":"FLEX","name":"Desmond Purnell","school":"Kansas State"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Tyler Loop","school":"Arizona"},
        {"position":"KO","name":"Tabor Allen","school":"Kansas"},
        {"position":"P","name":"Jack Bouwmeester","school":"Utah"},
        {"position":"KR","name":"Jamaal Bell","school":"Baylor"},
        {"position":"PR","name":"Josh Cameron","school":"Baylor"},
        {"position":"ST","name":"Taje McCoy","school":"Colorado"}
      ]
    },
    "ThirdTeam": {
      "Offense": [
        {"position":"QB","name":"Josh Hoover","school":"TCU"},
        {"position":"RB","name":"Corey Kiner","school":"Cincinnati"},
        {"position":"RB","name":"Bryson Washington","school":"Baylor"},
        {"position":"WR-X","name":"LaJohntay Wester","school":"Colorado"},
        {"position":"WR-SL","name":"Chase Roberts","school":"Brigham Young"},
        {"position":"WR-Z","name":"Josh Cameron","school":"Baylor"},
        {"position":"TE","name":"Randy Pittman Jr.","school":"Central Florida"},
        {"position":"RB","name":"Ollie Gordon II","school":"Oklahoma State"},
        {"position":"OT","name":"Easton Kilty","school":"Kansas State"},
        {"position":"RG","name":"Omar Aigbedion","school":"Baylor"},
        {"position":"OC","name":"Bryce Foster","school":"Kansas"},
        {"position":"LG","name":"Weylin Lapuaho","school":"Brigham Young"},
        {"position":"OT","name":"Nick Malone","school":"West Virginia"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Tre Smith","school":"Arizona"},
        {"position":"LDT","name":"Blake Mangelson","school":"Brigham Young"},
        {"position":"DT","name":"Anthony Holmes Jr.","school":"Houston"},
        {"position":"EDGE","name":"T.J. Jackson","school":"West Virginia"},
        {"position":"RILB","name":"Keaton Thomas","school":"Baylor"},
        {"position":"LB","name":"Josiah Trotter","school":"West Virginia"},
        {"position":"LB","name":"Austin Romaine","school":"Kansas State"},
        {"position":"NB","name":"Jakob Robinson","school":"Brigham Young"},
        {"position":"CB","name":"Darien Porter","school":"Iowa State"},
        {"position":"LCB","name":"Keith Abney","school":"Arizona State"},
        {"position":"SS","name":"Cam’Ron Silmon-Craig","school":"Colorado"},
        {"position":"FS","name":"Shilo Sanders","school":"Colorado"},
        {"position":"FS","name":"Tanner Wall","school":"Brigham Young"},
        {"position":"FLEX","name":"Jared Bartlett","school":"Cincinnati"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Gino Garcia","school":"Texas Tech"},
        {"position":"KO","name":"Parker Lewis","school":"Arizona State"},
        {"position":"P","name":"Liam Dougherty","school":"Houston"},
        {"position":"KR","name":"Jeremiah Patterson","school":"Arizona"},
        {"position":"PR","name":"Mekhi Mews","school":"Houston"},
        {"position":"ST","name":"Ben Finneseth","school":"Colorado"}
      ]
    },
    "HonorableMention": [
      {"position":"QB","name":"Jake Retzlaff","school":"Brigham Young"},
      {"position":"QB","name":"Sawyer Robertson","school":"Baylor"},
      {"position":"QB","name":"Rocco Becht","school":"Iowa State"},
      {"position":"RB","name":"Quali Conley","school":"Arizona"},
      {"position":"RB","name":"LJ Martin","school":"Brigham Young"},
      {"position":"RB","name":"CJ Donaldson Jr.","school":"West Virginia"},
      {"position":"RB","name":"Carson Hansen","school":"Iowa State"},
      {"position":"RB","name":"Micah Bernard","school":"Utah"},
      {"position":"RB","name":"Jahiem White","school":"West Virginia"},
      {"position":"WR-X","name":"De’Zhaun Stribling","school":"Oklahoma State"},
      {"position":"WR","name":"Kobe Hudson","school":"Central Florida"},
      {"position":"WR","name":"Luke Grimm","school":"Kansas"},
      {"position":"WR-Z","name":"Caleb Douglas","school":"Texas Tech"},
      {"position":"WR","name":"Xzavier Henderson","school":"Cincinnati"},
      {"position":"WR","name":"Dorian Singer","school":"Utah"},
      {"position":"WR-X","name":"Darius Lassiter","school":"Brigham Young"},
      {"position":"WR","name":"Eric McAlister","school":"TCU"},
      {"position":"WR","name":"JP Richardson","school":"TCU"},
      {"position":"TE","name":"Michael Trigg","school":"Baylor"},
      {"position":"TE","name":"Chamon Metayer","school":"Arizona State"},
      {"position":"TE","name":"Jalin Conyers","school":"Texas Tech"},
      {"position":"FLEX","name":"Cam Cook","school":"TCU"},
      {"position":"WR-Z","name":"Brennan Presley","school":"Oklahoma State"},
      {"position":"WR-X","name":"Monaray Baldwin","school":"Baylor"},
      {"position":"RT","name":"Phillip Houston","school":"Colorado"},
      {"position":"LT","name":"Caleb Rogers","school":"Texas Tech"},
      {"position":"RT","name":"Max Iheanachor","school":"Arizona State"},
      {"position":"OG","name":"Kobe Baynes","school":"Kansas"},
      {"position":"OG","name":"Taylor Poitier","school":"Kansas State"},
      {"position":"LG","name":"Ryan Lengyel","school":"Baylor"},
      {"position":"C","name":"Connor Pay","school":"Brigham Young"},
      {"position":"C","name":"Sam Hecht","school":"Kansas State"},
      {"position":"C","name":"Gavin Gerhardt","school":"Cincinnati"},
      {"position":"OG","name":"Michael Ford Jr.","school":"Kansas"},
      {"position":"RG","name":"Kahlil Benson","school":"Colorado"},
      {"position":"OG","name":"Carson Bruno","school":"TCU"},
      {"position":"OT","name":"John Williams","school":"Cincinnati"},
      {"position":"OT","name":"Amari Knight","school":"Central Florida"},
      {"position":"OT","name":"Carver Willis","school":"Kansas State"},
      { "position": "EDGE", "name": "Obi Ezeigbo", "school": "Oklahoma State" },
      { "position": "EDGE", "name": "Sean Martin", "school": "West Virginia" },
        { "position": "EDGE", "name": "Nyjalik Kelly", "school": "Central Florida" },
        { "position": "DT", "name": "Tommy Dunn Jr.", "school": "Kansas" },
        { "position": "DT", "name": "De’Braylon Carroll", "school": "Texas Tech" },
        { "position": "DE", "name": "Jackie Marshall", "school": "Baylor" },
        { "position": "RDT", "name": "Jeff Clark", "school": "Arizona State" },
        { "position": "DT", "name": "Ta’ita’i Uiagalelei", "school": "Arizona" },
        { "position": "RDE", "name": "Amari McNeill", "school": "Colorado" },
        { "position": "EDGE", "name": "Eric Phillips", "school": "Cincinnati" },
        { "position": "EDGE", "name": "Van Fillinger", "school": "Utah" },
        { "position": "EDGE", "name": "Logan Fano", "school": "Utah" },
        { "position": "MLB", "name": "Caleb McCullough", "school": "Arizona State" },
        { "position": "LB", "name": "Deshawn Pace", "school": "Central Florida" },
        { "position": "LB", "name": "Cornell Wheeler", "school": "Kansas" },
        { "position": "LB", "name": "Ze’ree Alexander", "school": "Central Florida" },
        { "position": "LB", "name": "Johnny Hodges", "school": "TCU" },
        { "position": "LB", "name": "Namdi Obiazor", "school": "TCU" },
        { "position": "MLB", "name": "Jacob Manu", "school": "Arizona" },
        { "position": "LB", "name": "Michael Batton", "school": "Houston" },
        { "position": "MLB", "name": "Ben Roberts", "school": "Texas Tech" },
        { "position": "LCB", "name": "Colton Hood", "school": "Colorado" },
        { "position": "RCB", "name": "D.J. McKinney", "school": "Colorado" },
        { "position": "RCB", "name": "Javan Robinson", "school": "Arizona State" },
        { "position": "LCB", "name": "Korie Black", "school": "Oklahoma State" },
        { "position": "RCB", "name": "Lorando Johnson", "school": "Baylor" },
        { "position": "CB", "name": "LaMareon James", "school": "TCU" },
        { "position": "CB", "name": "Jacob Parrish", "school": "Kansas State" },
        { "position": "BCB", "name": "Tacario Davis", "school": "Arizona" },
        { "position": "CB", "name": "MacMcWilliams", "school": "Central Florida" },
        { "position": "SS", "name": "Owen Goss", "school": "Arizona" },
        { "position": "SS", "name": "Kendal Daniels", "school": "Oklahoma State" },
        { "position": "SS", "name": "VJ Payne", "school": "Kansas State" },
        { "position": "FS", "name": "CJ Baskerville", "school": "Texas Tech" },
        { "position": "FS", "name": "Anthony Wilson", "school": "West Virginia" },
        { "position": "FS", "name": "Devyn Bobby", "school": "Baylor" },
        { "position": "FS", "name": "Carter Stoutmire", "school": "Colorado" },
        { "position": "S", "name": "Malik Verdon", "school": "Iowa State" },
        { "position": "S", "name": "Beau Freyler", "school": "Iowa State" },
        { "position": "FS", "name": "Genesis Smith", "school": "Arizona" },
        { "position": "FLEX", "name": "Smith Snowden", "school": "Utah" },
        { "position": "FLEX", "name": "Cameron Calhoun", "school": "Utah" },
        { "position": "PK", "name": "Alejandro Mata", "school": "Colorado" },
        { "position": "KO", "name": "Jack Stone", "school": "Baylor" },
        { "position": "P", "name": "Ethan Craw", "school": "TCU" },
        { "position": "KR", "name": "Drae McCray", "school": "Texas Tech" },
        { "position": "PR", "name": "Dylan Edwards", "school": "Kansas State" },
        { "position": "ST", "name": "Trey Reynolds", "school": "Utah" }
    ]
  }
}
