"""CFN All-CUSA Conference List 2024"""

{
  "cusa": {
    "Awards": {
      "PlayerOfTheYear": {"name":"Tre Stewart","position":"RB","school":"Jacksonville State"},
      "OffensivePlayerOfTheYear": {"name":"Tre Stewart","position":"RB","school":"Jacksonville State"},
      "DefensivePlayerOfTheYear": {"name":"Caleb Weaver","position":"S","school":"Sam Houston"},
      "SpecialistOfTheYear": {"name":"Buck Buchanan","position":"KOS","school":"Louisiana Tech"},
      "NewcomerOfTheYear": {"name":"Malaki Ta’ase","position":"DT","school":"New Mexico State"},
      "CoachOfTheYear": {"name":"Rich Rodriguez","position":"Coach","school":"Jacksonville State"},
      "ImpactFreshmanOfTheYear": {"name":"Malaki Ta’ase","position":"DT","school":"New Mexico State"}
    },
    "PositionAwards": {
      "QuarterbackOfTheYear": {"name":"Tyler Huff","position":"QB","school":"Jacksonville State"},
      "RunningBackOfTheYear": {"name":"Tre Stewart","position":"RB","school":"Jacksonville State"},
      "WideReceiverOfTheYear": {"name":"Eric Rivers","position":"WR","school":"Florida International"},
      "TightEndOfTheYear": {"name":"Holden Willis","position":"TE","school":"Middle Tennessee"},
      "OffensiveTackleOfTheYear": {"name":"Will O’Steen","position":"OT","school":"Jacksonville State"},
      "OffensiveGuardOfTheYear": {"name":"Jordan White","position":"OG","school":"Liberty"},
      "CenterOfTheYear": {"name":"Canaan Yarro","position":"C","school":"New Mexico State"},
      "OffensiveLinemanOfTheYear": {"name":"Will O’Steen","position":"OT","school":"Jacksonville State"},
      "OffensiveLineOfTheYear": {"name":"Liberty Flames","position":"OL Unit","school":"Liberty"},
      "OffensiveNewcomerOfTheYear": {"name":"Kenny Odom","position":"WR","school":"UTEP"},
      "OffensiveTransferOfTheYear": {"name":"Kenny Odom","position":"WR","school":"UTEP"},
      "EdgeDefenderOfTheYear": {"name":"Chris Murray","position":"EDGE","school":"Sam Houston"},
      "InteriorDefenderOfTheYear": {"name":"Tylon Dunlap","position":"DL","school":"Kennesaw State"},
      "LinebackerOfTheYear": {"name":"Travion Barnes","position":"LB","school":"Florida International"},
      "CornerbackOfTheYear": {"name":"Brian Blades","position":"CB","school":"Florida International"},
      "SafetyOfTheYear": {"name":"Caleb Weaver","position":"S","school":"Sam Houston"},
      "DefensiveLineOfTheYear": {"name":"Sam Houston Bearkats","position":"DL Unit","school":"Sam Houston"},
      "SecondaryOfTheYear": {"name":"Jacksonville State Gamecocks","position":"Secondary Unit","school":"Jacksonville State"},
      "DefensiveNewcomerOfTheYear": {"name":"Malaki Ta’ase","position":"DT","school":"New Mexico State"},
      "DefensiveTransferOfTheYear": {"name":"Antonio Carter II","position":"S","school":"Jacksonville State"},
      "KickerOfTheYear": {"name":"Lucas Carneiro","position":"PK","school":"Western Kentucky"},
      "PunterOfTheYear": {"name":"Jacob Ulrich","position":"P","school":"Kennesaw State"},
      "KickReturnerOfTheYear": {"name":"Qua Ashley","position":"KR","school":"Kennesaw State"},
      "PuntReturnerOfTheYear": {"name":"Kam Thomas","position":"PR","school":"UTEP"},
      "SpecialTeamerOfTheYear": {"name":"Kam Thomas","position":"ST","school":"UTEP"},
      "KickoffSpecialistOfTheYear": {"name":"Travis Franklin Jr.","position":"KOS","school":"Jacksonville State"}
    },
    "FirstTeam": {
      "Offense": [
        {"position":"QB","name":"Tyler Huff","school":"Jacksonville State"},
        {"position":"RB","name":"Tre Stewart","school":"Jacksonville State"},
        {"position":"RB","name":"Quinton Cooley","school":"Liberty"},
        {"position":"WR","name":"Eric Rivers","school":"Florida International"},
        {"position":"WR","name":"Kenny Odom","school":"UTEP"},
        {"position":"WR","name":"Tru Edwards","school":"Louisiana Tech"},
        {"position":"TE","name":"Holden Willis","school":"Middle Tennessee"},
        {"position":"FLEX","name":"Dean Patterson","school":"Florida International"},
        {"position":"OT","name":"Will O’Steen","school":"Jacksonville State"},
        {"position":"OG","name":"Jordan White","school":"Liberty"},
        {"position":"OC","name":"Canaan Yarro","school":"New Mexico State"},
        {"position":"OG","name":"Clay Webb","school":"Jacksonville State"},
        {"position":"OT","name":"Jordan Hall","school":"Liberty"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Chris Murray","school":"Sam Houston"},
        {"position":"DT","name":"Tylon Dunlap","school":"Kennesaw State"},
        {"position":"DT","name":"Jamarrion Solomon","school":"Florida International"},
        {"position":"EDGE","name":"Maurice Westmoreland","school":"UTEP"},
        {"position":"LB","name":"Travion Barnes","school":"Florida International"},
        {"position":"LB","name":"Kavian Gaither","school":"Sam Houston"},
        {"position":"LB","name":"Reginald Hughes","school":"Jacksonville State"},
        {"position":"CB","name":"Geimere Latimer","school":"Jacksonville State"},
        {"position":"CB","name":"Anthony Johnson Jr.","school":"Western Kentucky"},
        {"position":"CB","name":"Brian Blades","school":"Florida International"},
        {"position":"SS","name":"Zechariah Poyser","school":"Jacksonville State"},
        {"position":"FS","name":"Caleb Weaver","school":"Sam Houston"},
        {"position":"S","name":"Upton Stout","school":"Western Kentucky"},
        {"position":"FLEX","name":"J-Rock Swain","school":"Jacksonville State"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Lucas Carneiro","school":"Western Kentucky"},
        {"position":"KOS","name":"Buck Buchanan","school":"Louisiana Tech"},
        {"position":"P","name":"Jacob Ulrich","school":"Kennesaw State"},
        {"position":"KR","name":"Qua Ashley","school":"Kennesaw State"},
        {"position":"PR","name":"Kam Thomas","school":"UTEP"},
        {"position":"ST","name":"Travis Franklin Jr.","school":"Jacksonville State"}
      ]
    },
    "SecondTeam": {
      "Offense": [
        {"position":"QB","name":"Caden Veltkamp","school":"Western Kentucky"},
        {"position":"RB","name":"Elijah Young","school":"Western Kentucky"},
        {"position":"RB","name":"Mike Washington","school":"New Mexico State"},
        {"position":"WR","name":"Omari Kelly","school":"Middle Tennessee"},
        {"position":"WR","name":"Eason Messer","school":"Western Kentucky"},
        {"position":"WR","name":"Kisean Johnson","school":"Western Kentucky"},
        {"position":"TE","name":"Carson Kent","school":"Kennesaw State"},
        {"position":"FLEX","name":"Sean Brown","school":"Jacksonville State"},
        {"position":"OT","name":"Xavior Gray","school":"Liberty"},
        {"position":"OG","name":"Rodney Newsom","school":"Western Kentucky"},
        {"position":"OC","name":"Aaron Fenimore","school":"Liberty"},
        {"position":"OG","name":"AJ Vaipulu","school":"New Mexico State"},
        {"position":"OT","name":"Travis Burke","school":"Florida International"}
      ],
      "Defense": [
        {"position":"EDGE","name":"TJ Bush","school":"Liberty"},
        {"position":"DT","name":"Chris Boti","school":"Liberty"},
        {"position":"DT","name":"Malaki Ta’ase","school":"New Mexico State"},
        {"position":"EDGE","name":"Jevon Leon","school":"Sam Houston"},
        {"position":"LB","name":"Laletia Hale","school":"Jacksonville State"},
        {"position":"LB","name":"Darius Thomas","school":"Western Kentucky"},
        {"position":"LB","name":"Ky’won McCray","school":"Jacksonville State"},
        {"position":"CB","name":"Jabari Mack","school":"Jacksonville State"},
        {"position":"CB","name":"JeRico Washington Jr.","school":"Kennesaw State"},
        {"position":"CB","name":"Amarian Williams","school":"Liberty"},
        {"position":"SS","name":"Antonio Carter II","school":"Jacksonville State"},
        {"position":"FS","name":"Devonte’ Mathews","school":"Western Kentucky"},
        {"position":"S","name":"JoJo Evans","school":"Florida International"},
        {"position":"FLEX","name":"Fred Perry","school":"Jacksonville State"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Abraham Montano","school":"New Mexico State"},
        {"position":"KOS","name":"Garrison Rippa","school":"Jacksonville State"},
        {"position":"P","name":"Grant Chadwick","school":"Middle Tennessee"},
        {"position":"KR","name":"C’Quan Jnopierre","school":"Florida International"},
        {"position":"PR","name":"Solo Lewis","school":"Louisiana Tech"},
        {"position":"ST","name":"Elias Escobar","school":"Sam Houston"}
      ]
    },
    "ThirdTeam": {
      "Offense": [
        {"position":"QB","name":"Hunter Watson","school":"Sam Houston"},
        {"position":"RB","name":"Seth McGowan","school":"New Mexico State"},
        {"position":"RB","name":"Jay Ducker","school":"Sam Houston"},
        {"position":"WR","name":"Cam Vaughn","school":"Jacksonville State"},
        {"position":"WR","name":"Treon Sibley","school":"Liberty"},
        {"position":"WR","name":"Simeon Evans","school":"Sam Houston"},
        {"position":"TE","name":"Eli Finley","school":"Louisiana Tech"},
        {"position":"FLEX","name":"Qua’Vez Humphreys","school":"Sam Houston"},
        {"position":"OT","name":"Kolt Dieterich","school":"Sam Houston"},
        {"position":"OG","name":"Harrison Hayes","school":"Liberty"},
        {"position":"OC","name":"Ethan Hagler","school":"Sam Houston"},
        {"position":"OG","name":"Otis Pitts III","school":"UTEP"},
        {"position":"OT","name":"Marshall Jackson","school":"Western Kentucky"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Eddie Walls III","school":"Florida International"},
        {"position":"DT","name":"KD Johnson","school":"UTEP"},
        {"position":"DT","name":"Damonte Smith","school":"Middle Tennessee"},
        {"position":"EDGE","name":"Deante McCray","school":"Western Kentucky"},
        {"position":"LB","name":"Elijah Anderson-Taylor","school":"Florida International"},
        {"position":"LB","name":"Trey Fields","school":"Sam Houston"},
        {"position":"LB","name":"Kolbe Fields","school":"Louisiana Tech"},
        {"position":"CB","name":"David Fisher","school":"Sam Houston"},
        {"position":"CB","name":"Dexter Ricks Jr.","school":"Liberty"},
        {"position":"CB","name":"Amier Boyd-Matthews","school":"UTEP"},
        {"position":"SS","name":"Kory Chapman","school":"UTEP"},
        {"position":"FS","name":"Isaiah Cash","school":"Sam Houston"},
        {"position":"S","name":"Brylan Green","school":"Liberty"},
        {"position":"FLEX","name":"Jaylon Jimmerson","school":"Sam Houston"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Zeke Rankin","school":"Middle Tennessee"},
        {"position":"KOS","name":"Abraham Montano","school":"New Mexico State"},
        {"position":"P","name":"Patrick Rea","school":"Louisiana Tech"},
        {"position":"KR","name":"Corey Wren","school":"UTEP"},
        {"position":"PR","name":"Brylan Green","school":"Liberty"},
        {"position":"ST","name":"Chandler Matthews","school":"Western Kentucky"}
      ]
    },
    "HonorableMention": [
      {"position":"QB","name":"Nicholas Vattiato","school":"Middle Tennessee"},
      {"position":"QB","name":"Keyone Jenkins","school":"Florida International"},
      {"position":"QB","name":"Kaidon Salter","school":"Liberty"},
      {"position":"RB","name":"Omiri Wiggins","school":"Louisiana Tech"},
      {"position":"RB","name":"Kejon Owens","school":"Florida International"},
      {"position":"RB","name":"Billy Lucas","school":"Liberty"},
      {"position":"RB","name":"DJ McKinney","school":"Sam Houston"},
      {"position":"RB","name":"Jevon Jackson","school":"UTEP"},
      {"position":"RB","name":"Michael Benefield","school":"Kennesaw State"},
      {"position":"WR","name":"Kam Thomas","school":"UTEP"},
      {"position":"WR","name":"Jimmy Holiday","school":"Louisiana Tech"},
      {"position":"WR","name":"KD Hutchinson","school":"Western Kentucky"},
      {"position":"WR","name":"Michael Pettway","school":"Jacksonville State"},
      {"position":"WR","name":"TJ Pride","school":"New Mexico State"},
      {"position":"WR","name":"Myles Butler","school":"Middle Tennessee"},
      {"position":"WR","name":"Trey Goodman","school":"UTEP"},
      {"position":"WR","name":"Dalvin Smith","school":"Western Kentucky"},
      {"position":"WR","name":"Elijah Canion","school":"Liberty"},
      {"position":"TE","name":"Elijah Sohn","school":"Sam Houston"},
      {"position":"TE","name":"Marcus Vinson","school":"UTEP"},
      {"position":"TE","name":"River Helms","school":"Western Kentucky"},
      {"position":"FLEX","name":"Bentley Hanshaw","school":"Liberty"},
      {"position":"FLEX","name":"Lexington Joseph","school":"Florida International"},
      {"position":"FLEX","name":"Jaiden Credle","school":"Middle Tennessee"},
      {"position":"OT","name":"Louie Canepa","school":"New Mexico State"},
      {"position":"OT","name":"Jack Tucker","school":"Liberty"},
      {"position":"OT","name":"Mason Bowers","school":"Kennesaw State"},
      {"position":"OG","name":"JT Pennington","school":"Kennesaw State"},
      {"position":"OG","name":"Ellis Adams","school":"Middle Tennessee"},
      {"position":"OG","name":"Quantavious Leslie","school":"Western Kentucky"},
      {"position":"OC","name":"Daveion Harley","school":"Jacksonville State"},
      {"position":"OC","name":"Evan Wibberley","school":"Western Kentucky"},
      {"position":"OC","name":"Simon Wilson","school":"Middle Tennessee"},
      {"position":"OG","name":"John Paul Flores","school":"Liberty"},
      {"position":"OG","name":"Ben Shellenback","school":"Florida International"},
      {"position":"OG","name":"Bert Hale","school":"Louisiana Tech"},
      {"position":"OT","name":"Jacob Kettels","school":"Kennesaw State"},
      {"position":"OT","name":"Cam Jones","school":"Jacksonville State"},
      {"position":"OT","name":"Rhett Larson","school":"Sam Houston"},
      {"position":"EDGE","name":"Jordan Miles","school":"Kennesaw State"},
      {"position":"EDGE","name":"Buddha Peleti","school":"New Mexico State"},
      {"position":"EDGE","name":"J’Dan Burnett","school":"Louisiana Tech"},
      {"position":"DT","name":"Hosea Wheeler","school":"Western Kentucky"},
      {"position":"DT","name":"Naki Fahina","school":"New Mexico State"},
      {"position":"DT","name":"Denver Warren","school":"Sam Houston"},
      {"position":"DT","name":"Dallas Walker IV","school":"Western Kentucky"},
      {"position":"DT","name":"David Blay","school":"Louisiana Tech"},
      {"position":"DT","name":"Jeramy Passmore","school":"Florida International"},
      {"position":"EDGE","name":"Jessie Evans","school":"Louisiana Tech"},
      {"position":"EDGE","name":"CJ Bazile Jr.","school":"Liberty"},
      {"position":"EDGE","name":"Jawaun Campbell","school":"Jacksonville State"},
      {"position":"LB","name":"Chandler Matthews","school":"Western Kentucky"},
      {"position":"LB","name":"Garland Benyard","school":"Kennesaw State"},
      {"position":"LB","name":"Zach Zimos","school":"Louisiana Tech"},
      {"position":"LB","name":"Dorian Hopkins","school":"UTEP"},
      {"position":"LB","name":"Parker Hughes","school":"Middle Tennessee"},
      {"position":"LB","name":"Nate Dyman","school":"UTEP"},
      {"position":"LB","name":"Joseph Carter","school":"Liberty"},
      {"position":"LB","name":"Donelius Johnson","school":"Kennesaw State"},
      {"position":"LB","name":"Tyler Martinez","school":"New Mexico State"},
      {"position":"CB","name":"Hezekiah Masses","school":"Florida International"},
      {"position":"CB","name":"Fred Davis II","school":"Jacksonville State"},
      {"position":"CB","name":"Tyler Hallum","school":"Kennesaw State"},
      {"position":"CB","name":"Dakerric Hobbs","school":"New Mexico State"},
      {"position":"CB","name":"Tyrell Raby","school":"Middle Tennessee"},
      {"position":"CB","name":"Alex Oliver","school":"Liberty"},
      {"position":"CB","name":"Demarcus Griffin-Taylor","school":"Louisiana Tech"},
      {"position":"CB","name":"Cedric Woods","school":"Louisiana Tech"},
      {"position":"CB","name":"Marvae Myers","school":"Middle Tennessee"},
      {"position":"SS","name":"Dylan Early","school":"New Mexico State"},
      {"position":"SS","name":"Blake Thompson","school":"Louisiana Tech"},
      {"position":"SS","name":"Jamal Potts","school":"Florida International"},
      {"position":"FS","name":"CJ Christian","school":"Florida International"},
      {"position":"FS","name":"John Howse IV","school":"Middle Tennessee"},
      {"position":"FS","name":"Demarko Williams","school":"Western Kentucky"},
      {"position":"S","name":"Tayden Barnes","school":"New Mexico State"},
      {"position":"S","name":"Milon Jones","school":"Kennesaw State"},
      {"position":"S","name":"A’Khori Jones","school":"Liberty"},
      {"position":"FLEX","name":"Sebastian Benjamin","school":"Western Kentucky"},
      {"position":"FLEX","name":"Sone Aupiu","school":"New Mexico State"},
      {"position":"FLEX","name":"Kent Robinson","school":"Western Kentucky"},
      {"position":"PK","name":"Buck Buchanan","school":"Louisiana Tech"},
      {"position":"KOS","name":"Alejandro Prado","school":"Florida International"},
      {"position":"P","name":"George Eberle","school":"New Mexico State"},
      {"position":"KR","name":"Demarcus Griffin-Taylor","school":"Louisiana Tech"},
      {"position":"PR","name":"Omari Kelly","school":"Middle Tennessee"},
      {"position":"ST","name":"Chris Johnson","school":"Middle Tennessee"}
    ]
  }
}

