"""2024 CFN All‑AAC Team & Awards"""

{
  "aac": {
    "Awards": {
      "PlayerOfTheYear": {"name":"Bryson Daily","position":"QB","school":"Army"},
      "OffensivePlayerOfTheYear": {"name":"Bryson Daily","position":"QB","school":"Army"},
      "DefensivePlayerOfTheYear": {"name":"Chandler Martin","position":"MLB","school":"Memphis"},
      "SpecialistOfTheYear": {"name":"Rayuan Lane III","position":"FS","school":"Navy"},
      "NewcomerOfTheYear": {"name":"Adin Huntington","position":"DE","school":"Tulane"},
      "CoachOfTheYear": {"name":"Jeff Monken","position":"Coach","school":"Army"},
      "ImpactFreshmanOfTheYear": {"name":"Tyler Mercer","position":"C","school":"North Texas"}
    },
    "PositionAwards": {
      "QuarterbackOfTheYear": {"name":"Bryson Daily","position":"QB","school":"Army"},
      "RunningBackOfTheYear": {"name":"Makhi Hughes","position":"RB","school":"Tulane"},
      "WideReceiverOfTheYear": {"name":"DT Sheffield","position":"WR-SL","school":"North Texas"},
      "TightEndOfTheYear": {"name":"Houston Thomas","position":"TE","school":"UTSA"},
      "OffensiveTackleOfTheYear": {"name":"Lucas Scott","position":"LT","school":"Army"},
      "OffensiveGuardOfTheYear": {"name":"Shadre Hurst","position":"LG","school":"Tulane"},
      "CenterOfTheYear": {"name":"Brady Small","position":"C","school":"Army"},
      "OffensiveLinemanOfTheYear": {"name":"Lucas Scott","position":"LT","school":"Army"},
      "OffensiveLineOfTheYear": {"name":"Army Black Knights","position":"OL Unit","school":"Army"},
      "OffensiveNewcomerOfTheYear": {"name":"Mario Anderson Jr.","position":"RB","school":"Memphis"},
      "OffensiveTransferOfTheYear": {"name":"Mario Anderson Jr.","position":"RB","school":"Memphis"},
      "EdgeDefenderOfTheYear": {"name":"Jimmori Robinson","position":"DE","school":"UTSA"},
      "InteriorDefenderOfTheYear": {"name":"Patrick Jenkins","position":"DT","school":"Tulane"},
      "LinebackerOfTheYear": {"name":"Chandler Martin","position":"MLB","school":"Memphis"},
      "CornerbackOfTheYear": {"name":"Zah Frazier","position":"LCB","school":"UTSA"},
      "SafetyOfTheYear": {"name":"Gabe Taylor","position":"SS","school":"Rice"},
      "DefensiveLineOfTheYear": {"name":"Tulane Green Wave","position":"DL Unit","school":"Tulane"},
      "SecondaryOfTheYear": {"name":"Navy Midshipmen","position":"Secondary Unit","school":"Navy"},
      "DefensiveNewcomerOfTheYear": {"name":"Adin Huntington","position":"DE","school":"Tulane"},
      "DefensiveTransferOfTheYear": {"name":"Adin Huntington","position":"DE","school":"Tulane"},
      "KickerOfTheYear": {"name":"Maddux Trujillo","position":"K","school":"Temple"},
      "PunterOfTheYear": {"name":"Andrew Stokes","position":"P","school":"South Florida"},
      "KickReturnerOfTheYear": {"name":"Rayshawn Pleasant","position":"KR","school":"Tulane"},
      "PuntReturnerOfTheYear": {"name":"Kam Shanks","position":"PR","school":"UAB"},
      "SpecialTeamerOfTheYear": {"name":"Rayuan Lane III","position":"FS","school":"Navy"},
      "KickoffSpecialistOfTheYear": {"name":"Tristian Vandenberg","position":"KO","school":"Memphis"}
    },
    "FirstTeam": {
      "Offense": [
        {"position":"QB","name":"Bryson Daily","school":"Army"},
        {"position":"RB","name":"Makhi Hughes","school":"Tulane"},
        {"position":"RB","name":"Mario Anderson Jr.","school":"Memphis"},
        {"position":"WR-SL","name":"DT Sheffield","school":"North Texas"},
        {"position":"WR-SL","name":"Dante Wright","school":"Temple"},
        {"position":"WR-X","name":"Mario Williams","school":"Tulane"},
        {"position":"TE-Y","name":"Houston Thomas","school":"UTSA"},
        {"position":"SB-Z","name":"Eli Heidenreich","school":"Navy"},
        {"position":"LT","name":"Lucas Scott","school":"Army"},
        {"position":"LG","name":"Shadre Hurst","school":"Tulane"},
        {"position":"C","name":"Brady Small","school":"Army"},
        {"position":"RG","name":"Paolo Gennarelli","school":"Army"},
        {"position":"RT","name":"Connor Finucane","school":"Army"}
      ],
      "Defense": [
        {"position":"DE","name":"Jimmori Robinson","school":"UTSA"},
        {"position":"DT","name":"Patrick Jenkins","school":"Tulane"},
        {"position":"DT","name":"Roderick Brown","school":"North Texas"},
        {"position":"DE","name":"Desmond Little","school":"UAB"},
        {"position":"MLB","name":"Chandler Martin","school":"Memphis"},
        {"position":"MLB","name":"Colin Ramos","school":"Navy"},
        {"position":"WLB","name":"Mac Harris","school":"South Florida"},
        {"position":"LCB","name":"Zah Frazier","school":"UTSA"},
        {"position":"FCB","name":"Dashaun Peele","school":"Navy"},
        {"position":"LCB","name":"Brian Nelson II","school":"North Texas"},
        {"position":"SS","name":"Gabe Taylor","school":"Rice"},
        {"position":"FS","name":"Rayuan Lane III","school":"Navy"},
        {"position":"SS","name":"Casey Larkin","school":"Army"},
        {"position":"WLB","name":"Kyle Jacob","school":"Navy"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Maddux Trujillo","school":"Temple"},
        {"position":"KO","name":"Tristian Vandenberg","school":"Memphis"},
        {"position":"PT","name":"Andrew Stokes","school":"South Florida"},
        {"position":"KR","name":"Rayshawn Pleasant","school":"Tulane"},
        {"position":"PR","name":"Kam Shanks","school":"UAB"},
        {"position":"FS","name":"Rayuan Lane III","school":"Navy"}
      ]
    },
    "SecondTeam": {
      "Offense": [
        {"position":"QB","name":"Darian Mensah","school":"Tulane"},
        {"position":"RB-A","name":"Kenye Udoh","school":"Army"},
        {"position":"RB","name":"Rahjai Harris","school":"East Carolina"},
        {"position":"WR-X","name":"Roc Taylor","school":"Memphis"},
        {"position":"WR-X","name":"Kamdyn Benjamin","school":"Tulsa"},
        {"position":"WR-X","name":"O’Mega Blake","school":"Charlotte"},
        {"position":"TE","name":"Anthony Landphere","school":"Memphis"},
        {"position":"RB","name":"Dean Connors","school":"Rice"},
        {"position":"LT","name":"Connor McMahon","school":"Navy"},
        {"position":"RG","name":"Bill Katsigiannis","school":"Army"},
        {"position":"C","name":"Vincent Murphy","school":"Tulane"},
        {"position":"RG","name":"Xavier Hill","school":"Memphis"},
        {"position":"LT","name":"Rashad Green","school":"Tulane"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Diwun Black","school":"Temple"},
        {"position":"DE","name":"Adin Huntington","school":"Tulane"},
        {"position":"NT","name":"Landon Robinson","school":"Navy"},
        {"position":"RDE","name":"Terrell Dawkins","school":"North Texas"},
        {"position":"WLB","name":"Jamal Ligon","school":"UTSA"},
        {"position":"WLB","name":"TyQuan King","school":"Temple"},
        {"position":"WLB","name":"Ty Morris","school":"Rice"},
        {"position":"LCB","name":"Dontae Balfour","school":"Charlotte"},
        {"position":"RCB","name":"Davion Ross","school":"Memphis"},
        {"position":"RCB","name":"Donavon Platt","school":"Army"},
        {"position":"SS","name":"Caleb Ransaw","school":"Tulane"},
        {"position":"FS","name":"Al‑Ma’Hi Ali","school":"Charlotte"},
        {"position":"FS","name":"Owen Pewee","school":"UTSA"},
        {"position":"MLB","name":"D.J. Woodbury","school":"Temple"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Stephen Rusnak","school":"Charlotte"},
        {"position":"KO","name":"Ethan Head","school":"Tulane"},
        {"position":"P","name":"Joshua Sloan","school":"Memphis"},
        {"position":"KR","name":"Winston Wright Jr.","school":"East Carolina"},
        {"position":"PR","name":"Kamdyn Benjamin","school":"Tulsa"},
        {"position":"ST","name":"Jackson Barker","school":"East Carolina"}
      ]
    },
    "ThirdTeam": {
      "Offense": [
        {"position": "QB", "name": "Chandler Morris", "school": "North Texas"},
        {"position": "RB", "name": "CJ Campbell Jr.", "school": "Florida Atlantic"},
        {"position": "RB", "name": "Kelley Joiner Jr.", "school": "South Florida"},
        {"position": "WR-Z", "name": "Winston Wright Jr.", "school": "East Carolina"},
        {"position": "WR-X", "name": "Anthony Smith", "school": "East Carolina"},
        {"position": "WR-X", "name": "Matt Sykes", "school": "Rice"},
        {"position": "TE", "name": "Colin Weber", "school": "Charlotte"},
        {"position": "SB", "name": "Noah Short", "school": "Army"},
        {"position": "LT", "name": "Derrick Graham", "school": "Tulane"},
        {"position": "LG", "name": "Jordan Church", "school": "Florida Atlantic"},
        {"position": "C", "name": "Trent Holler", "school": "Memphis"},
        {"position": "LG", "name": "Quez Yates", "school": "UAB"},
        {"position": "LT", "name": "Chris Adams", "school": "Memphis"}
      ],
      "Defense": [
        {"position": "DE", "name": "J.D. Lampley", "school": "East Carolina"},
        {"position": "DT", "name": "R.J. Jackson", "school": "Tulsa"},
        {"position": "RDT", "name": "Bernard Gooden", "school": "South Florida"},
        {"position": "JACK", "name": "Elo Modozie", "school": "Army"},
        {"position": "MLB", "name": "Reid Williford", "school": "Charlotte"},
        {"position": "MLB", "name": "Martavius French", "school": "UTSA"},
        {"position": "WLB", "name": "Andon Thomas", "school": "Army"},
        {"position": "RCB", "name": "Jamel Johnson", "school": "Temple"},
        {"position": "LCB", "name": "Brent Austin", "school": "South Florida"},
        {"position": "LCB", "name": "Daedae Hill", "school": "Florida Atlantic"},
        {"position": "SS", "name": "Phillip Dunnam", "school": "Florida Atlantic"},
        {"position": "FS", "name": "Mbiti Williams Jr.", "school": "Navy"},
        {"position": "SS", "name": "Chance Keith", "school": "Army"},
        {"position": "RCB", "name": "Micah Robinson", "school": "Tulane"}
      ],
      "SpecialTeams": [
        {"position": "PK", "name": "Tate Sandell", "school": "UTSA"},
        {"position": "KOS", "name": "Tristian Vandenberg", "school": "Memphis"},
        {"position": "PT", "name": "Dante Atton", "school": "Temple"},
        {"position": "KR", "name": "Rayshawn Pleasant", "school": "Tulane"},
        {"position": "PR", "name": "Kam Shanks", "school": "UAB"},
        {"position": "ST", "name": "Adrian Maddox", "school": "UAB"}
      ]
    },
    "HonorableMention": [
      {"position":"QB","name":"Seth Henigan","school":"Memphis"},
      {"position":"QB","name":"Owen McCown","school":"UTSA"},
      {"position":"QB","name":"Blake Horvath","school":"Navy"},
      {"position":"RB","name":"Ta’ron Keith","school":"South Florida"},
      {"position":"RB","name":"Robert Henry Jr.","school":"UTSA"},
      {"position":"RB","name":"Mackenzie McGill","school":"North Texas"},
      {"position":"RB","name":"Shane Porter","school":"North Texas"},
      {"position":"FB","name":"Alex Tecza","school":"Navy"},
      {"position":"RB","name":"Lee Beebe Jr.","school":"UAB"},
      {"position":"WR-X","name":"DeMeer Blankumsee","school":"Memphis"},
      {"position":"WR-Z","name":"Amare Thomas","school":"UAB"},
      {"position":"WR-X","name":"Sean Atkins","school":"South Florida"},
      {"position":"WR-Z","name":"Chase Sowell","school":"East Carolina"},
      {"position":"WR-X","name":"Dontae Fleming","school":"Tulane"},
      {"position":"WR-X","name":"Blair Conwright","school":"North Texas"},
      {"position":"WR-Z","name":"Joseph Williams","school":"Tulsa"},
      {"position":"WR-X","name":"Omari Hayes","school":"Florida Atlantic"},
      {"position":"WR-X","name":"Willie McCoy","school":"UTSA"},
      {"position":"TE-Y","name":"Graham Walker","school":"Rice"},
      {"position":"TE-Y","name":"Elijah Mojarro","school":"Rice"},
      {"position":"TE-Y","name":"Patrick Overymer","school":"UTSA"},
      {"position":"RB","name":"Greg Desrosiers Jr.","school":"Memphis"},
      {"position":"RB","name":"Antwain Littleton II","school":"Temple"},
      {"position":"SB-A","name":"Brandon Chatman","school":"Navy"},
      {"position":"RT","name":"Javan Bourton","school":"Navy"},
      {"position":"LT","name":"Kamar Missouri","school":"UTSA"},
      {"position":"RT","name":"Parker Moorer","school":"East Carolina"},
      {"position":"RG","name":"Josh Remetich","school":"Tulane"},
      {"position":"LG","name":"Johnny Dickson III","school":"North Texas"},
      {"position":"RG","name":"Weston Kropp","school":"Rice"},
      {"position":"C","name":"Brent Self","school":"Navy"},
      {"position":"C","name":"CJ James Jr.","school":"UTSA"},
      {"position":"C","name":"Dustyn Hall","school":"East Carolina"},
      {"position":"LG","name":"Ben Purvis","school":"Navy"},
      {"position":"RG","name":"Emmanuel Poku","school":"East Carolina"},
      {"position":"RG","name":"Walter Young Bear","school":"Tulsa"},
      {"position":"LT","name":"Malcolm Lamar Sr.","school":"Florida Atlantic"},
      {"position":"LT","name":"RJ Perry","school":"South Florida"},
      {"position":"LT","name":"Kendall Stanley","school":"Charlotte"},
      {"position":"DE","name":"Owen Ostroksi","school":"Tulsa"},
      {"position":"RUSH","name":"Charles Looes","school":"Rice"},
      {"position":"DE","name":"Justin Red","school":"Navy"},
      {"position":"DT","name":"Michael Larbie","school":"Rice"},
      {"position":"DT","name":"D’Anta Johnson","school":"East Carolina"},
      {"position":"NT","name":"Javon Denis","school":"Memphis"},
      {"position":"DT","name":"Kameron Hamilton","school":"Tulane"},
      {"position":"DT","name":"Amieh Williams","school":"Tulsa"},
      {"position":"DT","name":"Sekou Kromah","school":"Temple"},
      {"position":"RDE","name":"William Whitlow Jr.","school":"Memphis"},
      {"position":"LDE","name":"Chisom Ifeanyi","school":"Florida Atlantic"},
      {"position":"EDGE","name":"Matthew Fobbs‑White","school":"Tulane"},
      {"position":"LB","name":"Mike Edwards III","school":"East Carolina"},
      {"position":"LB","name":"Javion White","school":"Tulane"},
      {"position":"RCB","name":"Max Ahoia","school":"Rice"},
      {"position":"LB","name":"Jaylen Smith","school":"North Texas"},
      {"position":"MLB","name":"Kalib Fortner","school":"Army"},
      {"position":"MLB","name":"Everett Roussaw Jr.","school":"UAB"},
      {"position":"MLB","name":"Zakye Barker","school":"East Carolina"},
      {"position":"MLB","name":"Gavin Potter","school":"Tulsa"},
      {"position":"LB","name":"Cam Burden","school":"Charlotte"},
      {"position":"FCB","name":"Shavon Revel","school":"East Carolina"},
      {"position":"LCB","name":"Jaydan Mayes","school":"Army"},
      {"position":"RCB","name":"Elijah Green","school":"Tulsa"},
      {"position":"RCB","name":"De’Shawn Rucker","school":"South Florida"},
      {"position":"LCB","name":"Sean Fresch","school":"Rice"},
      {"position":"RCB","name":"Isaiah Brown‑Murray","school":"East Carolina"},
      {"position":"LCB","name":"Ridge Texada","school":"North Texas"},
      {"position":"RCB","name":"Kahzir Brown","school":"Florida Atlantic"},
      {"position":"RCB","name":"Colby Dempsey","school":"UAB"},
      {"position":"SS","name":"Jaxson Campbell","school":"Navy"},
      {"position":"SS","name":"Wendol Philord","school":"Florida Atlantic"},
      {"position":"FS","name":"Jaehlen Cannady","school":"Tulsa"},
      {"position":"FS","name":"Tavin Ward","school":"South Florida"},
      {"position":"FS","name":"CJ Heard","school":"Florida Atlantic"},
      {"position":"FS","name":"Max DiDomenico","school":"Army"},
      {"position":"SS","name":"Jalen Geiger","school":"Tulane"},
      {"position":"SS","name":"Sirad Bryant","school":"UAB"},
      {"position":"FS","name":"Tyson Flowers","school":"Rice"},
      {"position":"RCB","name":"Justin Weaver","school":"Army"},
      {"position":"WLB","name":"Trevon Booker","school":"Charlotte"},
      {"position":"RCB","name":"Torey Richardson","school":"Temple"},
      {"position":"PK","name":"Trey Gronotte","school":"Army"},
      {"position":"KO","name":"Carter Davis","school":"Florida Atlantic"},
      {"position":"PT","name":"Angus Davies","school":"Tulsa"},
      {"position":"KR","name":"Henry Rutledge","school":"Charlotte"},
      {"position":"PR","name":"Tyson Thompson","school":"Rice"},
      {"position":"PR","name":"Dax Collins","school":"Tulsa"}
    ]
  }
}
