"""CFN All-Mountain West Conference List 2024"""

{
  "mountain_west": {
    "Awards": {
      "PlayerOfTheYear": {"name":"Ashton Jeanty","position":"RB","school":"Boise State"},
      "OffensivePlayerOfTheYear": {"name":"Ashton Jeanty","position":"RB","school":"Boise State"},
      "DefensivePlayerOfTheYear": {"name":"Jalen Catalon","position":"FS","school":"UNLV"},
      "SpecialistOfTheYear": {"name":"Jonah Dalmas","position":"PK","school":"Boise State"},
      "NewcomerOfTheYear": {"name":"Jalen Catalon","position":"FS","school":"UNLV"},
      "CoachOfTheYear": {"name":"Spencer Danielson","position":"Coach","school":"Boise State"},
      "ImpactFreshmanOfTheYear": {"name":"Caden Chittenden","position":"PK","school":"UNLV"}
    },
    "PositionAwards": {
      "QuarterbackOfTheYear": {"name":"Maddux Madsen","position":"QB","school":"Boise State"},
      "RunningBackOfTheYear": {"name":"Ashton Jeanty","position":"RB","school":"Boise State"},
      "WideReceiverOfTheYear": {"name":"Nick Nash","position":"WR-X","school":"San Jose State"},
      "TightEndOfTheYear": {"name":"Matt Lauter","position":"TE","school":"Boise State"},
      "OffensiveTackleOfTheYear": {"name":"Kage Casey","position":"LT","school":"Boise State"},
      "OffensiveGuardOfTheYear": {"name":"Ben Dooley","position":"LG","school":"Boise State"},
      "CenterOfTheYear": {"name":"Jacob Gardner","position":"C","school":"Colorado State"},
      "OffensiveLinemanOfTheYear": {"name":"Jacob Gardner","position":"C","school":"Colorado State"},
      "OffensiveLineOfTheYear": {"name":"Boise State Broncos","position":"OL Unit","school":"Boise State"},
      "OffensiveNewcomerOfTheYear": {"name":"Marquez Cooper","position":"RB","school":"San Diego State"},
      "OffensiveTransferOfTheYear": {"name":"Marquez Cooper","position":"RB","school":"San Diego State"},
      "EdgeDefenderOfTheYear": {"name":"Ahmed Hassanein","position":"EDGE","school":"Boise State"},
      "InteriorDefenderOfTheYear": {"name":"Alex Whitmore","position":"DT","school":"UNLV"},
      "LinebackerOfTheYear": {"name":"Jackson Woodard","position":"MLB","school":"UNLV"},
      "CornerbackOfTheYear": {"name":"Michael Coats Jr.","position":"LCB","school":"Nevada"},
      "SafetyOfTheYear": {"name":"Jalen Catalon","position":"FS","school":"UNLV"},
      "DefensiveLineOfTheYear": {"name":"Boise State Broncos","position":"DL Unit","school":"Boise State"},
      "SecondaryOfTheYear": {"name":"UNLV Rebels","position":"Secondary Unit","school":"UNLV"},
      "DefensiveNewcomerOfTheYear": {"name":"Jalen Catalon","position":"FS","school":"UNLV"},
      "DefensiveTransferOfTheYear": {"name":"Jalen Catalon","position":"FS","school":"UNLV"},
      "KickerOfTheYear": {"name":"Jonah Dalmas","position":"PK","school":"Boise State"},
      "PunterOfTheYear": {"name":"Tyler Pastula","position":"PT","school":"San Diego State"},
      "KickReturnerOfTheYear": {"name":"Tyler King","position":"KR","school":"Wyoming"},
      "PuntReturnerOfTheYear": {"name":"Jalen Moss","position":"PR","school":"Fresno State"},
      "SpecialTeamerOfTheYear": {"name":"Cole Joyce","position":"MLB","school":"Utah State"},
      "KickoffSpecialistOfTheYear": {"name":"Caden Chittenden","position":"KO","school":"UNLV"}
    },
    "FirstTeam": {
      "Offense": [
        {"position":"QB","name":"Maddux Madsen","school":"Boise State"},
        {"position":"RB","name":"Ashton Jeanty","school":"Boise State"},
        {"position":"RB","name":"Marquez Cooper","school":"San Diego State"},
        {"position":"WR-X","name":"Nick Nash","school":"San Jose State"},
        {"position":"WR-X","name":"Ricky White","school":"UNLV"},
        {"position":"WR-X","name":"Jaden Smith","school":"Nevada"},
        {"position":"TE-Y","name":"Matt Lauter","school":"Boise State"},
        {"position":"WR-X","name":"Mac Delana","school":"Fresno State"},
        {"position":"LT","name":"Kage Casey","school":"Boise State"},
        {"position":"LG","name":"Ben Dooley","school":"Boise State"},
        {"position":"C","name":"Jacob Gardner","school":"Colorado State"},
        {"position":"LG","name":"Drew Moss","school":"Colorado State"},
        {"position":"OT","name":"Caden Barnett","school":"Wyoming"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Ahmed Hassanein","school":"Boise State"},
        {"position":"NT","name":"Alex Whitmore","school":"UNLV"},
        {"position":"NT","name":"Soane Toia","school":"San Jose State"},
        {"position":"RDE","name":"Trey White","school":"San Diego State"},
        {"position":"MLB","name":"Jackson Woodard","school":"UNLV"},
        {"position":"LB","name":"Shae Suiaunoa","school":"Wyoming"},
        {"position":"MLB","name":"Jordan Pollard","school":"San Jose State"},
        {"position":"LCB","name":"Michael Coats Jr.","school":"Nevada"},
        {"position":"RCB","name":"Cam Lockridge","school":"Fresno State"},
        {"position":"CB","name":"Cameron Oliver","school":"UNLV"},
        {"position":"SS","name":"Robert Rahimi","school":"San Jose State"},
        {"position":"FS","name":"Jalen Catalon","school":"UNLV"},
        {"position":"SS","name":"Seyi Oladipo","school":"Boise State"},
        {"position":"FCB","name":"A’Marion McCoy","school":"Boise State"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Jonah Dalmas","school":"Boise State"},
        {"position":"KO","name":"Caden Chittenden","school":"UNLV"},
        {"position":"PT","name":"Tyler Pastula","school":"San Diego State"},
        {"position":"KR","name":"Tyler King","school":"Wyoming"},
        {"position":"PR","name":"Jalen Moss","school":"Fresno State"},
        {"position":"ST","name":"Cole Joyce","school":"Utah State"}
      ]
    },
    "SecondTeam": {
      "Offense": [
        {"position":"QB","name":"Devon Dampier","school":"New Mexico"},
        {"position":"RB","name":"Rahsul Faison","school":"Utah State"},
        {"position":"RB","name":"Eli Sanders","school":"New Mexico"},
        {"position":"WR-X","name":"Justin Lockhart","school":"San Jose State"},
        {"position":"WR","name":"Nick Cenacle","school":"Hawaii"},
        {"position":"WR","name":"Jalen Royals","school":"Utah State"},
        {"position":"TE","name":"Kaleo Ballungay","school":"UNLV"},
        {"position":"WR-X","name":"Jalen Moss","school":"Fresno State"},
        {"position":"LT","name":"Braylen Nelson","school":"Fresno State"},
        {"position":"RG","name":"Mathyus Su’a","school":"UNLV"},
        {"position":"C","name":"Coston Cooley","school":"Air Force"},
        {"position":"OG","name":"Baraka Beckett","school":"New Mexico"},
        {"position":"RT","name":"Aaron Karas","school":"Colorado State"}
      ],
      "Defense": [
        {"position":"RDE","name":"Gabe Kirschke","school":"Colorado State"},
        {"position":"DT","name":"Braxton Fely","school":"Boise State"},
        {"position":"DT","name":"Jacob Holmes","school":"Fresno State"},
        {"position":"EDGE","name":"Jayden Virgin-Morgan","school":"Boise State"},
        {"position":"LB","name":"Taniela Latu","school":"San Jose State"},
        {"position":"MLB","name":"Andrew Simpson","school":"Boise State"},
        {"position":"RILB","name":"Phoenix Jackson","school":"Fresno State"},
        {"position":"LCB","name":"DJ Harvey","school":"San Jose State"},
        {"position":"LCB","name":"Johnathan Baldwin","school":"UNLV"},
        {"position":"RCB","name":"Cam Stone","school":"Hawaii"},
        {"position":"SS","name":"Tori Daffin","school":"Nevada"},
        {"position":"FS","name":"Jordan Vincent","school":"Utah State"},
        {"position":"NB","name":"Wrook Brown","school":"Wyoming"},
        {"position":"SS","name":"Dom Jones","school":"Colorado State"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"John Hoyland","school":"Wyoming"},
        {"position":"KOS","name":"John Hoyland","school":"Wyoming"},
        {"position":"P","name":"Jack Culbreath","school":"Wyoming"},
        {"position":"KR","name":"Kobe Johnson","school":"Colorado State"},
        {"position":"PR","name":"Jacob De Jesus","school":"UNLV"},
        {"position":"ST","name":"Justin Sinclair","school":"Hawaii"}
      ]
    },
    "ThirdTeam": {
      "Offense": [
        {"position":"QB","name":"Hajj-Malik Williams","school":"UNLV"},
        {"position":"RB","name":"Jai’Den Thomas","school":"UNLV"},
        {"position":"RB","name":"Floyd Chalk IV","school":"San Jose State"},
        {"position":"WR","name":"Luke Wysong","school":"New Mexico"},
        {"position":"WR-X","name":"Cam Camper","school":"Boise State"},
        {"position":"WR","name":"Pofele Ashlock","school":"Hawaii"},
        {"position":"TE","name":"Josh Sterzer","school":"Utah State"},
        {"position":"RB","name":"Avery Morrow","school":"Colorado State"},
        {"position":"LT","name":"Nate Williams","school":"San Diego State"},
        {"position":"C","name":"Ross Ulugalu-Maseuli","school":"San Diego State"},
        {"position":"C","name":"Zach Holmes","school":"Boise State"},
        {"position":"RG","name":"Josh Grabowski","school":"Nevada"},
        {"position":"LT","name":"Tiger Shanks","school":"UNLV"}
      ],
      "Defense": [
        {"position":"LDE","name":"Devo Bridges","school":"Fresno State"},
        {"position":"NT","name":"Peyton Zdroik","school":"Air Force"},
        {"position":"NT","name":"Herbert Gums","school":"Boise State"},
        {"position":"DE","name":"Antonio Doyle Jr.","school":"UNLV"},
        {"position":"MLB","name":"Malachi Langley","school":"Fresno State"},
        {"position":"LB","name":"Connor Shay","school":"Wyoming"},
        {"position":"NB","name":"Ayden Hector","school":"Colorado State"},
        {"position":"CB","name":"Julian Neal","school":"Fresno State"},
        {"position":"LCB","name":"Alzillion Hamilton","school":"Fresno State"},
        {"position":"CB","name":"D.J. Graham II","school":"Utah State"},
        {"position":"SS","name":"Rodney Robinson","school":"Boise State"},
        {"position":"FS","name":"Kitan Crawford","school":"Nevada"},
        {"position":"FS","name":"Ty Benefield","school":"Boise State"},
        {"position":"FS","name":"Ike Larsen","school":"Utah State"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Caden Chittenden","school":"UNLV"},
        {"position":"KO","name":"Dylan Lynch","school":"Fresno State"},
        {"position":"PT","name":"Lucas Borrow","school":"Hawaii"},
        {"position":"KR","name":"Tylan Hines","school":"Hawaii"},
        {"position":"PR","name":"Kobe Johnson","school":"Colorado State"},
        {"position":"TE","name":"Justin Erb","school":"Wyoming"}
      ]
    },
    "HonorableMention": [
      {"position":"QB","name":"Mikey Keene","school":"Fresno State"},
      {"position":"QB","name":"Brendon Lewis","school":"Nevada"},
      {"position":"QB","name":"Danny O’Neil","school":"San Diego State"},
      {"position":"RB","name":"NaQuari Rogers","school":"New Mexico"},
      {"position":"RB","name":"Kylin James","school":"UNLV"},
      {"position":"RB","name":"Justin Marshall","school":"Colorado State"},
      {"position":"RB","name":"Elijah Gilliam","school":"Fresno State"},
      {"position":"RB","name":"Savion Red","school":"Nevada"},
      {"position":"RB","name":"Cade Harris","school":"Air Force"},
      {"position":"WR-X","name":"Cortez Braham","school":"Nevada"},
      {"position":"WR-A","name":"Marcus Bellon","school":"Nevada"},
      {"position":"WR-X","name":"Louis Brown IV","school":"San Diego State"},
      {"position":"WR-F","name":"Latrell Caples","school":"Boise State"},
      {"position":"WR-Z","name":"Caleb Goodie","school":"Colorado State"},
      {"position":"WR-X","name":"Jonah Panoke","school":"Hawaii"},
      {"position":"WR-SL","name":"Jordan Napier","school":"San Diego State"},
      {"position":"WR-Z","name":"Ja’Shaun Poke","school":"San Diego State"},
      {"position":"WR-Z","name":"Jaylen Sargent","school":"Wyoming"},
      {"position":"TE","name":"Vince Brown II","school":"Colorado State"},
      {"position":"TE","name":"Jacob Stewart","school":"San Jose State"},
      {"position":"TE","name":"John Michael Gyllenborg","school":"Wyoming"},
      {"position":"FLEX","name":"Otto Tia","school":"Utah State"},
      {"position":"WR-W","name":"Raylen Sharpe","school":"Fresno State"},
      {"position":"TE","name":"Jackson Canaan","school":"San Jose State"},
      {"position":"LT","name":"Isaiah World","school":"Nevada"},
      {"position":"OT","name":"Alex Moore","school":"Air Force"},
      {"position":"OT","name":"Ka’ena Decambra","school":"Hawaii"},
      {"position":"OG","name":"Richard Pearce","school":"New Mexico"},
      {"position":"OG","name":"Michael McAninch","school":"Air Force"},
      {"position":"LG","name":"Tyson Ruffins","school":"Nevada"},
      {"position":"C","name":"Brayden Bryant","school":"San Diego State"},
      {"position":"C","name":"Mose Vavao","school":"Fresno State"},
      {"position":"C","name":"Jack Hasz","school":"UNLV"},
      {"position":"RG","name":"Spencer Lovell","school":"Nevada"},
      {"position":"LG","name":"Marist Talavou","school":"San Jose State"},
      {"position":"OG","name":"Wyatt Bowles","school":"Utah State"},
      {"position":"OT","name":"James Milovale","school":"Hawaii"},
      {"position":"LT","name":"Saveyon Henderson","school":"Colorado State"},
      {"position":"LG","name":"Jalen St. John","school":"UNLV"},
      {"position":"EDGE","name":"Elijah Robinson","school":"Hawaii"},
      {"position":"EDGE","name":"Moso’oipala Tuitele","school":"New Mexico"},
      {"position":"EDGE","name":"Tyce Westland","school":"Wyoming"},
      {"position":"DT","name":"Krishna Clay","school":"San Diego State"},
      {"position":"DT","name":"Thomas Witte","school":"Nevada"},
      {"position":"DT","name":"Dion Washington","school":"Hawaii"},
      {"position":"NT","name":"Gafa Faga","school":"San Jose State"},
      {"position":"DT","name":"Cam Bariteau","school":"Colorado State"},
      {"position":"DT","name":"Isaiah Bruce","school":"Utah State"},
      {"position":"BAN","name":"Fisher Camac","school":"UNLV"},
      {"position":"EDGE","name":"Cian Slone","school":"Utah State"},
      {"position":"RDE","name":"Kristopher Ross","school":"Nevada"},
      {"position":"SLB","name":"Drue Watts","school":"Nevada"},
      {"position":"MLB","name":"Kyle Moretti","school":"San Diego State"},
      {"position":"LB","name":"Logan Taylor","school":"Hawaii"},
      {"position":"LB","name":"Randolph Kpai","school":"New Mexico"},
      {"position":"LB","name":"Dimitri Johnson","school":"New Mexico"},
      {"position":"WLB","name":"Chase Wilson","school":"Colorado State"},
      {"position":"MLB","name":"Tuasivi Nomura","school":"Fresno State"},
      {"position":"LB","name":"John Miller","school":"Utah State"},
      {"position":"LILB","name":"Buom Jock","school":"Colorado State"},
      {"position":"CB","name":"Bryson Taylor","school":"New Mexico"},
      {"position":"CB","name":"Noa Pola‑Gates","school":"New Mexico"},
      {"position":"CB","name":"Keany Parks","school":"Wyoming"},
      {"position":"CB","name":"Caleb Brown","school":"Hawaii"},
      {"position":"LCB","name":"Dominic Morris","school":"Colorado State"},
      {"position":"CB","name":"Trey Williams","school":"Air Force"},
      {"position":"CB","name":"Elijah Palmer","school":"Hawaii"},
      {"position":"CB","name":"Jeremiah Earby","school":"Boise State"},
      {"position":"CB","name":"Jamari Bellamy","school":"Air Force"},
      {"position":"FS","name":"Eric Butler","school":"San Diego State"},
      {"position":"SS","name":"Jack Howell","school":"Colorado State"},
      {"position":"SS","name":"Jett Elad","school":"UNLV"},
      {"position":"FS","name":"Isiah Revis","school":"San Jose State"},
      {"position":"FS","name":"Dean Clark","school":"Fresno State"},
      {"position":"FS","name":"Kilinahe Mendiola‑Jansen","school":"Hawaii"},
      {"position":"FCB","name":"Noah Avinger","school":"New Mexico"},
      {"position":"SS","name":"Nigel Williams","school":"New Mexico"},
      {"position":"SS","name":"Camby Goff","school":"Air Force"},
      {"position":"NB","name":"Christian Ellis","school":"New Mexico"},
      {"position":"FS","name":"Houston Hendrix","school":"Air Force"},
      {"position":"FCB","name":"Michael Dansby","school":"San Jose State"},
      {"position":"PK","name":"Jordan Noyes","school":"Colorado State"},
      {"position":"KO","name":"Elliott Nimrod","school":"Utah State"},
      {"position":"PT","name":"Guy Gillespie","school":"Nevada"},
      {"position":"KR","name":"Ja’Shaun Poke","school":"San Diego State"},
      {"position":"PR","name":"Tory Horton","school":"Colorado State"},
      {"position":"ST","name":"Aedan Seiuli","school":"Nevada"}
    ]
  }
}
