"""CFN All-MAC Conference List 2024"""

{
  "mac": {
    "Awards": {
      "PlayerOfTheYear": {"name":"Harold Fannin Jr.","position":"TE","school":"Bowling Green"},
      "OffensivePlayerOfTheYear": {"name":"Harold Fannin Jr.","position":"TE","school":"Bowling Green"},
      "DefensivePlayerOfTheYear": {"name":"Shaun Dolac","position":"LB","school":"Buffalo"},
      "SpecialistOfTheYear": {"name":"Jesus Gomez","position":"K","school":"Eastern Michigan"},
      "NewcomerOfTheYear": {"name":"Ben McNaboe","position":"EDGE","school":"Ohio"},
      "CoachOfTheYear": {"name":"Tim Albin","position":"Coach","school":"Ohio"},
      "ImpactFreshmanOfTheYear": {"name":"Jayden Studio","position":"LB","school":"Kent State"}
    },
    "PositionAwards": {
      "QuarterbackOfTheYear": {"name":"Parker Navarro","position":"QB","school":"Ohio"},
      "RunningBackOfTheYear": {"name":"Anthony Tyus III","position":"RB","school":"Ohio"},
      "WideReceiverOfTheYear": {"name":"Jerjuan Newton","position":"WR","school":"Toledo"},
      "TightEndOfTheYear": {"name":"Harold Fannin Jr.","position":"TE","school":"Bowling Green"},
      "OffensiveTackleOfTheYear": {"name":"Jack Sherwin","position":"OT","school":"Western Michigan"},
      "OffensiveGuardOfTheYear": {"name":"John Champe","position":"OG","school":"Northern Illinois"},
      "CenterOfTheYear": {"name":"Jacob Gideon","position":"C","school":"Western Michigan"},
      "OffensiveLinemanOfTheYear": {"name":"Jacob Gideon","position":"C","school":"Western Michigan"},
      "OffensiveLineOfTheYear": {"name":"Western Michigan Broncos","position":"OL Unit","school":"Western Michigan"},
      "OffensiveNewcomerOfTheYear": {"name":"Coleman Owen","position":"WR","school":"Ohio"},
      "OffensiveTransferOfTheYear": {"name":"Coleman Owen","position":"WR","school":"Ohio"},
      "EdgeDefenderOfTheYear": {"name":"Brian Ugwu","position":"EDGE","school":"Miami"},
      "InteriorDefenderOfTheYear": {"name":"Devonte O’Malley","position":"DL","school":"Northern Illinois"},
      "LinebackerOfTheYear": {"name":"Shaun Dolac","position":"LB","school":"Buffalo"},
      "CornerbackOfTheYear": {"name":"Raion Strader","position":"CB","school":"Miami"},
      "SafetyOfTheYear": {"name":"Tate Hallock","position":"S","school":"Western Michigan"},
      "DefensiveLineOfTheYear": {"name":"Ohio Bobcats","position":"DL Unit","school":"Ohio"},
      "SecondaryOfTheYear": {"name":"Toledo Rockets","position":"Secondary Unit","school":"Toledo"},
      "DefensiveNewcomerOfTheYear": {"name":"Ben McNaboe","position":"EDGE","school":"Ohio"},
      "DefensiveTransferOfTheYear": {"name":"Ben McNaboe","position":"EDGE","school":"Ohio"},
      "KickerOfTheYear": {"name":"Tristan Mattson","position":"K","school":"Central Michigan"},
      "PunterOfTheYear": {"name":"Alex Bevelhimer","position":"P","school":"Miami"},
      "KickReturnerOfTheYear": {"name":"Malcolm Gillie","position":"KR","school":"Ball State"},
      "PuntReturnerOfTheYear": {"name":"Donte Kent","position":"PR","school":"Central Michigan"},
      "SpecialTeamerOfTheYear": {"name":"Avi McGary","position":"ST","school":"Bowling Green"},
      "KickoffSpecialistOfTheYear": {"name":"Jesus Gomez","position":"KOS","school":"Eastern Michigan"}
    },
    "FirstTeam": {
      "Offense": [
        {"position":"QB","name":"Parker Navarro","school":"Ohio"},
        {"position":"RB","name":"Anthony Tyus III","school":"Ohio"},
        {"position":"RB","name":"Keyon Mozee","school":"Miami"},
        {"position":"WR","name":"Jerjuan Newton","school":"Toledo"},
        {"position":"WR","name":"Coleman Owen","school":"Ohio"},
        {"position":"WR","name":"Adrian Norton","school":"Akron"},
        {"position":"TE","name":"Harold Fannin Jr.","school":"Bowling Green"},
        {"position":"FLEX","name":"Tanner Koziol","school":"Ball State"},
        {"position":"OT","name":"Jack Sherwin","school":"Western Michigan"},
        {"position":"OG","name":"John Champe","school":"Northern Illinois"},
        {"position":"OC","name":"Jacob Gideon","school":"Western Michigan"},
        {"position":"OG","name":"Addison West","school":"Western Michigan"},
        {"position":"OT","name":"Reid Holskey","school":"Miami"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Brian Ugwu","school":"Miami"},
        {"position":"DT","name":"Darius Alexander","school":"Toledo"},
        {"position":"DT","name":"Devonte O’Malley","school":"Northern Illinois"},
        {"position":"EDGE","name":"Bradley Weaver","school":"Ohio"},
        {"position":"LB","name":"Shaun Dolac","school":"Buffalo"},
        {"position":"LB","name":"Matt Salopek","school":"Miami"},
        {"position":"LB","name":"Red Murdock","school":"Buffalo"},
        {"position":"CB","name":"Raion Strader","school":"Miami"},
        {"position":"CB","name":"Jordan Oladokun","school":"Bowling Green"},
        {"position":"CB","name":"Tank Pearson","school":"Ohio"},
        {"position":"SS","name":"Tate Hallock","school":"Western Michigan"},
        {"position":"FS","name":"Nate Valcarcel","school":"Northern Illinois"},
        {"position":"S","name":"Maxen Hook","school":"Toledo"},
        {"position":"FLEX","name":"Brock Horne","school":"Bowling Green"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Tristan Mattson","school":"Central Michigan"},
        {"position":"KOS","name":"Jesus Gomez","school":"Eastern Michigan"},
        {"position":"P","name":"Alex Bevelhimer","school":"Miami"},
        {"position":"KR","name":"Malcolm Gillie","school":"Ball State"},
        {"position":"PR","name":"Donte Kent","school":"Central Michigan"},
        {"position":"ST","name":"Avi McGary","school":"Bowling Green"}
      ]
    },
    "SecondTeam": {
      "Offense": [
        {"position":"QB","name":"Kadin Semonza","school":"Ball State"},
        {"position":"RB","name":"Jaden Nixon","school":"Western Michigan"},
        {"position":"RB","name":"Terion Stewart","school":"Bowling Green"},
        {"position":"WR","name":"Javon Tracy","school":"Miami"},
        {"position":"WR","name":"Reggie Virgin","school":"Miami"},
        {"position":"WR","name":"Chrishon McCray","school":"Kent State"},
        {"position":"TE","name":"Anthony Torres","school":"Toledo"},
        {"position":"FLEX","name":"Blake Bosma","school":"Western Michigan"},
        {"position":"OT","name":"Alex Wollschlaeger","school":"Bowling Green"},
        {"position":"OG","name":"Mickey Rewolinski","school":"Eastern Michigan"},
        {"position":"OC","name":"Charlie Nank","school":"Miami"},
        {"position":"OG","name":"J.J. Lippe","school":"Northern Illinois"},
        {"position":"OT","name":"Will Jados","school":"Miami"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Kobe Stewart","school":"Buffalo"},
        {"position":"DT","name":"Skyler Gill-Howard","school":"Northern Illinois"},
        {"position":"DT","name":"Anthony Hawkins","school":"Bowling Green"},
        {"position":"EDGE","name":"Ben McNaboe","school":"Ohio"},
        {"position":"LB","name":"Bryan McCoy","school":"Akron"},
        {"position":"LB","name":"Daniel Bolden","school":"Toledo"},
        {"position":"LB","name":"James Djonkam","school":"Eastern Michigan"},
        {"position":"CB","name":"Braden Awls","school":"Toledo"},
        {"position":"CB","name":"Avery Smith","school":"Toledo"},
        {"position":"CB","name":"Marquis Cooper","school":"Buffalo"},
        {"position":"SS","name":"DD Snyder II","school":"Ball State"},
        {"position":"FS","name":"Dustin Johnson","school":"Ohio"},
        {"position":"S","name":"DJ Walker","school":"Ohio"},
        {"position":"FLEX","name":"Ty Wise","school":"Miami"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Dom Dzioban","school":"Miami"},
        {"position":"KOS","name":"Dante Jackson","school":"Akron"},
        {"position":"P","name":"Josh Smith","school":"Kent State"},
        {"position":"KR","name":"Jaden Nixon","school":"Western Michigan"},
        {"position":"PR","name":"Bryson Hammer","school":"Toledo"},
        {"position":"ST","name":"Joey Rattin","school":"Northern Illinois"}
      ]
    },
    "ThirdTeam": {
      "Offense": [
        {"position":"QB","name":"Brett Gabbert","school":"Miami"},
        {"position":"RB","name":"Delbert Mimms III","school":"Eastern Michigan"},
        {"position":"RB","name":"Jalen Buckley","school":"Western Michigan"},
        {"position":"WR","name":"Junier Vandeross III","school":"Toledo"},
        {"position":"WR","name":"Luke Floriea","school":"Kent State"},
        {"position":"WR","name":"Victor Snow","school":"Buffalo"},
        {"position":"TE","name":"Grayson Barnes","school":"Northern Illinois"},
        {"position":"FLEX","name":"Al-Jay Henderson","school":"Buffalo"},
        {"position":"OT","name":"Tedi Kushi","school":"Western Michigan"},
        {"position":"OG","name":"John Hofer","school":"Western Michigan"},
        {"position":"OC","name":"Logan Zschernitz","school":"Northern Illinois"},
        {"position":"OG","name":"Kolby Borders","school":"Miami"},
        {"position":"OT","name":"Carson Heidecker","school":"Ohio"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Riley Tolsma","school":"Ball State"},
        {"position":"DT","name":"Jason Williams","school":"Central Michigan"},
        {"position":"DT","name":"Peyton Price","school":"Eastern Michigan"},
        {"position":"EDGE","name":"Kameron Olds","school":"Kent State"},
        {"position":"LB","name":"Joseph Sipp Jr.","school":"Bowling Green"},
        {"position":"LB","name":"Jordan Kwiatkowski","school":"Central Michigan"},
        {"position":"LB","name":"Blake Leake","school":"Ohio"},
        {"position":"CB","name":"Myles Norwood","school":"Ball State"},
        {"position":"CB","name":"Nasir Bowers","school":"Toledo"},
        {"position":"CB","name":"Ja’Corey Benjamin","school":"Bowling Green"},
        {"position":"SS","name":"Silas Walters","school":"Miami"},
        {"position":"FS","name":"Josh Baka","school":"Kent State"},
        {"position":"S","name":"Solomon Brown","school":"Buffalo"},
        {"position":"FLEX","name":"Donte Kent","school":"Central Michigan"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Upton Bellenfant","school":"Buffalo"},
        {"position":"KOS","name":"Upton Bellenfant","school":"Buffalo"},
        {"position":"P","name":"John Henderson","school":"Bowling Green"},
        {"position":"KR","name":"Jacquez Stuart","school":"Toledo"},
        {"position":"PR","name":"Coleman Owen","school":"Ohio"},
        {"position":"ST","name":"Jaion Jackson","school":"Central Michigan"}
      ]
    },
    "HonorableMention": [
      {"position":"QB","name":"Connor Bazelak","school":"Bowling Green"},
      {"position":"QB","name":"Tucker Gleason","school":"Toledo"},
      {"position":"QB","name":"Ben Finley","school":"Akron"},
      {"position":"RB","name":"B.J. Harris","school":"Central Michigan"},
      {"position":"RB","name":"Zahir Abdus-Salaam","school":"Western Michigan"},
      {"position":"RB","name":"Braedon Sloan","school":"Ball State"},
      {"position":"RB","name":"Jordon Simmons","school":"Akron"},
      {"position":"RB","name":"Marion Lukes","school":"Central Michigan"},
      {"position":"RB","name":"Gavin Williams","school":"Northern Illinois"},
      {"position":"WR","name":"Terry Lockett Jr.","school":"Eastern Michigan"},
      {"position":"WR","name":"Markus Allen","school":"Eastern Michigan"},
      {"position":"WR","name":"Oran Singleton Jr.","school":"Eastern Michigan"},
      {"position":"WR","name":"JJ Jenkins","school":"Buffalo"},
      {"position":"WR","name":"Malcolm Johnson Jr.","school":"Bowling Green"},
      {"position":"WR","name":"Trayvon Rudolph","school":"Northern Illinois"},
      {"position":"WR","name":"Kenneth Womack","school":"Western Michigan"},
      {"position":"WR","name":"Chris Parker","school":"Central Michigan"},
      {"position":"WR","name":"Anthony Sambucci","school":"Western Michigan"},
      {"position":"TE","name":"Jake Orlando","school":"Buffalo"},
      {"position":"TE","name":"Mason Williams","school":"Ohio"},
      {"position":"TE","name":"Jake Newell","school":"Akron"},
      {"position":"FLEX","name":"Cam Thompson","school":"Ball State"},
      {"position":"FLEX","name":"Cam Pickett","school":"Ball State"},
      {"position":"FLEX","name":"Qian Magwood","school":"Ball State"},
      {"position":"OT","name":"Evan Malcore","school":"Northern Illinois"},
      {"position":"OT","name":"Henry Tabansi","school":"Buffalo"},
      {"position":"OT","name":"Taran Tyo","school":"Ball State"},
      {"position":"OG","name":"Tyler Doty","school":"Buffalo"},
      {"position":"OG","name":"Nate Pabst","school":"Bowling Green"},
      {"position":"OG","name":"Ethan Spoth","school":"Toledo"},
      {"position":"OC","name":"Dom Polizzi","school":"Buffalo"},
      {"position":"OC","name":"Parker Titsworth","school":"Ohio"},
      {"position":"OC","name":"Dominic Serapiglia III","school":"Central Michigan"},
      {"position":"OG","name":"Christophe Atkinson","school":"Ohio"},
      {"position":"OG","name":"Jon Mucciolo","school":"Ball State"},
      {"position":"OG","name":"Jake Burns","school":"Bowling Green"},
      {"position":"OT","name":"Tunde Fatukasi","school":"Bowling Green"},
      {"position":"OT","name":"Chris Hood","school":"Ball State"},
      {"position":"OT","name":"Brayden Swartout","school":"Central Michigan"},
      {"position": "EDGE", "name": "Stephen Daley", "school": "Kent State"},
    {"position": "EDGE", "name": "CJ Nunnally", "school": "Akron"},
    {"position": "EDGE", "name": "Charles Rosser", "school": "Bowling Green"},
    {"position": "DT", "name": "Jonah Pace", "school": "Central Michigan"},
    {"position": "DT", "name": "Nathan Kapongo", "school": "Akron"},
    {"position": "DT", "name": "Cavon Butler", "school": "Toledo"},
    {"position": "DT", "name": "Isaiah Green", "school": "Western Michigan"},
    {"position": "DT", "name": "Darin Conley", "school": "Ball State"},
    {"position": "DT", "name": "Dontrez Brown", "school": "Bowling Green"},
    {"position": "EDGE", "name": "Dion Crawford", "school": "Buffalo"},
    {"position": "EDGE", "name": "D’Andre Ragin", "school": "Toledo"},
    {"position": "EDGE", "name": "Corey Suttle", "school": "Miami"},
    {"position": "LB", "name": "Jackson Barrow", "school": "Toledo"},
    {"position": "LB", "name": "Antavious Fish", "school": "Akron"},
    {"position": "LB", "name": "Dakota Cochran", "school": "Central Michigan"},
    {"position": "LB", "name": "Joey Stemler", "school": "Ball State"},
    {"position": "LB", "name": "Christian Fuhrman", "school": "Northern Illinois"},
    {"position": "LB", "name": "Lance Dixon", "school": "Toledo"},
    {"position": "LB", "name": "Shay Taylor", "school": "Ohio"},
    {"position": "LB", "name": "Donald Willis", "school": "Western Michigan"},
    {"position": "LB", "name": "Corban Hondru", "school": "Miami"},
    {"position": "CB", "name": "Jacob Finley", "school": "Northern Illinois"},
    {"position": "CB", "name": "Da’Raun McKinney", "school": "Central Michigan"},
    {"position": "CB", "name": "Bilhal Kone", "school": "Western Michigan"},
    {"position": "CB", "name": "Nyquan Washington", "school": "Western Michigan"},
    {"position": "CB", "name": "Daiquan White", "school": "Eastern Michigan"},
    {"position": "CB", "name": "Roman Parodie", "school": "Ohio"},
    {"position": "CB", "name": "Dallas Branch", "school": "Kent State"},
    {"position": "CB", "name": "Devonte Golden-Nelson", "school": "Akron"},
    {"position": "CB", "name": "Aman Greenwood", "school": "Akron"},
    {"position": "SS", "name": "Paul Lewis III", "school": "Akron"},
    {"position": "SS", "name": "George Udo", "school": "Ball State"},
    {"position": "SS", "name": "Emmanuel McNeil-Warren", "school": "Toledo"},
    {"position": "FS", "name": "Eli Blakey", "school": "Miami"},
    {"position": "FS", "name": "Marcus Fuqua", "school": "Buffalo"},
    {"position": "FS", "name": "Aaron Wofford", "school": "Western Michigan"},
    {"position": "S", "name": "Jalen McNair", "school": "Buffalo"},
    {"position": "S", "name": "Elijah Rikard", "school": "Central Michigan"},
    {"position": "S", "name": "Darrian Lewis", "school": "Akron"},
    {"position": "FLEX", "name": "Caleb Spann", "school": "Central Michigan"},
    {"position": "FLEX", "name": "Santana Banner", "school": "Northern Illinois"},
    {"position": "FLEX", "name": "CJ Brown", "school": "Bowling Green"},
    {"position": "PK", "name": "Jesus Gomez", "school": "Eastern Michigan"},
    {"position": "KOS", "name": "Kellan McLaughlin", "school": "Miami"},
    {"position": "P", "name": "Ethan Duane", "school": "Buffalo"},
    {"position": "KR", "name": "Justin Pegues", "school": "Bowling Green"},
    {"position": "PR", "name": "Victor Snow", "school": "Buffalo"},
    {"position": "ST", "name": "Jack Fries", "school": "Ohio"}
    ]
  }
}
