"""CFN All-Sun Belt List 2024"""

{
  "sunbelt": {
    "Awards": {
      "PlayerOfTheYear": {"name":"Mike Green","position":"RDE","school":"Marshall"},
      "OffensivePlayerOfTheYear": {"name":"Tellek Lockette","position":"RG","school":"Texas State"},
      "DefensivePlayerOfTheYear": {"name":"Mike Green","position":"RDE","school":"Marshall"},
      "SpecialistOfTheYear": {"name":"Kenneth Almendares","position":"PK","school":"Louisiana"},
      "NewcomerOfTheYear": {"name":"Fluff Bothwell","position":"RB","school":"South Alabama"},
      "CoachOfTheYear": {"name":"Bryant Vincent","position":"Coach","school":"Louisiana Monroe"},
      "ImpactFreshmanOfTheYear": {"name":"Fluff Bothwell","position":"RB","school":"South Alabama"}
    },
    "PositionAwards": {
      "QuarterbackOfTheYear": {"name":"Jordan McCloud","position":"QB","school":"Texas State"},
      "RunningBackOfTheYear": {"name":"Ahmad Hardy","position":"RB","school":"Louisiana Monroe"},
      "WideReceiverOfTheYear": {"name":"Jamaal Pritchett","position":"WR-X","school":"South Alabama"},
      "TightEndOfTheYear": {"name":"Terrance Carter","position":"TE","school":"Louisiana"},
      "OffensiveTackleOfTheYear": {"name":"Alex Harkey","position":"RT","school":"Texas State"},
      "OffensiveGuardOfTheYear": {"name":"Tellek Lockette","position":"RG","school":"Texas State"},
      "CenterOfTheYear": {"name":"Tanner Morris","position":"C","school":"James Madison"},
      "OffensiveLinemanOfTheYear": {"name":"Tellek Lockette","position":"RG","school":"Texas State"},
      "OffensiveLineOfTheYear": {"name":"Texas State Bobcats","position":"OL Unit","school":"Texas State"},
      "OffensiveNewcomerOfTheYear": {"name":"Fluff Bothwell","position":"RB","school":"South Alabama"},
      "OffensiveTransferOfTheYear": {"name":"Jordan McCloud","position":"QB","school":"Texas State"},
      "EdgeDefenderOfTheYear": {"name":"Mike Green","position":"RDE","school":"Marshall"},
      "InteriorDefenderOfTheYear": {"name":"Santana Hopper","position":"LDE","school":"Appalachian State"},
      "LinebackerOfTheYear": {"name":"Jaden Yates","position":"WLB","school":"Marshall"},
      "CornerbackOfTheYear": {"name":"Josh Moten","position":"RCB","school":"Marshall"},
      "SafetyOfTheYear": {"name":"Travor Randle","position":"SS","school":"Louisiana Monroe"},
      "DefensiveLineOfTheYear": {"name":"JMU Dukes","position":"DL Unit","school":"James Madison"},
      "SecondaryOfTheYear": {"name":"Marshall Thundering Herd","position":"Secondary Unit","school":"Marshall"},
      "DefensiveNewcomerOfTheYear": {"name":"Eric O’Neill","position":"LDE","school":"James Madison"},
      "DefensiveTransferOfTheYear": {"name":"Eric O’Neill","position":"LDE","school":"James Madison"},
      "KickerOfTheYear": {"name":"Kenneth Almendares","position":"PK","school":"Louisiana"},
      "PunterOfTheYear": {"name":"Ryan Heicher","position":"PT","school":"Arkansas State"},
      "KickReturnerOfTheYear": {"name":"Robert Williams","position":"KR","school":"Louisiana"},
      "PuntReturnerOfTheYear": {"name":"Courtney Jackson","position":"PR","school":"Arkansas State"},
      "SpecialTeamerOfTheYear": {"name":"Dalen Cambre","position":"WR-Z","school":"Louisiana"},
      "KickoffSpecialistOfTheYear": {"name":"Brendan Franke","position":"KO","school":"Texas State"}
    },
    "FirstTeam": {
      "Offense": [
        {"position":"QB","name":"Jordan McCloud","school":"Texas State"},
        {"position":"RB","name":"Ahmad Hardy","school":"Louisiana Monroe"},
        {"position":"RB","name":"Fluff Bothwell","school":"South Alabama"},
        {"position":"WR-X","name":"Jamaal Pritchett","school":"South Alabama"},
        {"position":"WR-Z","name":"Devonte Ross","school":"Troy"},
        {"position":"WR-X","name":"Ted Hurst","school":"Georgia State"},
        {"position":"TE","name":"Terrance Carter","school":"Louisiana"},
        {"position":"TE","name":"Dorian Fleming","school":"Georgia State"},
        {"position":"RT","name":"Alex Harkey","school":"Texas State"},
        {"position":"RG","name":"Tellek Lockette","school":"Texas State"},
        {"position":"C","name":"Tanner Morris","school":"James Madison"},
        {"position":"LG","name":"AJ Gillie","school":"Louisiana"},
        {"position":"RT","name":"Pat McMurtrie","school":"James Madison"}
      ],
      "Defense": [
        {"position":"RDE","name":"Mike Green","school":"Marshall"},
        {"position":"LDE","name":"Santana Hopper","school":"Appalachian State"},
        {"position":"DT","name":"Mason Narcisse","school":"Louisiana"},
        {"position":"LDE","name":"Eric O’Neill","school":"James Madison"},
        {"position":"WLB","name":"Jaden Yates","school":"Marshall"},
        {"position":"MLB","name":"K.C. Ossai","school":"Louisiana"},
        {"position":"WLB","name":"Mario Thompson","school":"Old Dominion"},
        {"position":"RCB","name":"Josh Moten","school":"Marshall"},
        {"position":"LCB","name":"Angelo Rankin Jr.","school":"Old Dominion"},
        {"position":"RCB","name":"Terrence Spence","school":"James Madison"},
        {"position":"SS","name":"Travor Randle","school":"Louisiana Monroe"},
        {"position":"NB","name":"Jahron Manning","school":"Old Dominion"},
        {"position":"SS","name":"J.J. Roberts","school":"Marshall"},
        {"position":"BCB","name":"Mattew McDoom","school":"Coastal Carolina"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Kenneth Almendares","school":"Louisiana"},
        {"position":"KO","name":"Brendan Franke","school":"Texas State"},
        {"position":"PT","name":"Ryan Heicher","school":"Arkansas State"},
        {"position":"KR","name":"Robert Williams","school":"Louisiana"},
        {"position":"PR","name":"Courtney Jackson","school":"Arkansas State"},
        {"position":"WR-Z","name":"Dalen Cambre","school":"Louisiana"}
      ]
    },
    "SecondTeam": {
      "Offense": [
        {"position":"QB","name":"Alonza Barnett III","school":"James Madison"},
        {"position":"RB","name":"Damien Taylor","school":"Troy"},
        {"position":"RB","name":"Ismail Mahdi","school":"Texas State"},
        {"position":"WR-X","name":"Corey Rucker","school":"Arkansas State"},
        {"position":"WR-X","name":"Lance LeGendre","school":"Louisiana"},
        {"position":"WR-Z","name":"Joey Hobert","school":"Texas State"},
        {"position":"TE","name":"Taylor Thompson","school":"James Madison"},
        {"position":"TE","name":"Pat Conroy","school":"Old Dominion"},
        {"position":"LT","name":"Jeremy Jones","school":"Marshall"},
        {"position":"RG","name":"Jax Harrington","school":"Louisiana"},
        {"position":"C","name":"Jacob Bayer","school":"Arkansas State"},
        {"position":"LG","name":"Nash Jones","school":"Texas State"},
        {"position":"LT","name":"Dorion Strawn","school":"Texas State"}
      ],
      "Defense": [
        {"position":"JACK","name":"Cameron Whitfield","school":"Louisiana"},
        {"position":"RDT","name":"Brodarius Lewis","school":"Southern Miss"},
        {"position":"RDT","name":"Chris Fitzgerald","school":"James Madison"},
        {"position":"EDGE","name":"Clev Lubin","school":"Coastal Carolina"},
        {"position":"WLB","name":"Blayne Myrick","school":"South Alabama"},
        {"position":"MLB","name":"Jordan Stringer","school":"Troy"},
        {"position":"SLB","name":"Jahleel Culbreath","school":"Old Dominion"},
        {"position":"NB","name":"Jacobie Henderson","school":"Marshall"},
        {"position":"RCB","name":"Lardarius Webb Jr.","school":"South Alabama"},
        {"position":"LCB","name":"DJ Barksdale","school":"James Madison"},
        {"position":"SS","name":"Trevian Thomas","school":"Arkansas State"},
        {"position":"SS","name":"Tyrone Lewis Jr.","school":"Louisiana"},
        {"position":"FS","name":"Jaden Voisin","school":"South Alabama"},
        {"position":"MLB","name":"Trent Hendrick","school":"James Madison"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Laith Marjan","school":"South Alabama"},
        {"position":"KO","name":"Paddy McAteer","school":"Troy"},
        {"position":"PT","name":"Ryan Hanson","school":"James Madison"},
        {"position":"KR","name":"Cameron Ross","school":"James Madison"},
        {"position":"PR","name":"Beau Sparks","school":"Texas State"},
        {"position":"FS","name":"Jerome Carter","school":"Old Dominion"}
      ]
    },
    "ThirdTeam": {
      "Offense": [
        {"position":"QB","name":"Ben Wooldridge","school":"Louisiana"},
        {"position":"RB","name":"Braydon Bennett","school":"Coastal Carolina"},
        {"position":"RB","name":"George Pettaway","school":"James Madison"},
        {"position":"WR-X","name":"Kaedin Robinson","school":"Appalachian State"},
        {"position":"WR-SL","name":"Isiah Paige","school":"Old Dominion"},
        {"position":"WR-SL","name":"Makai Jackson","school":"Appalachian State"},
        {"position":"TE","name":"Eli Wilson","school":"Appalachian State"},
        {"position":"WR-X","name":"Omarion Dollison","school":"James Madison"},
        {"position":"RG","name":"Daniel King","school":"Troy"},
        {"position":"LG","name":"Mehki Butler","school":"Arkansas State"},
        {"position":"C","name":"Logan Osburn","school":"Marshall"},
        {"position":"RG","name":"Cole Potts","school":"James Madison"},
        {"position":"RT","name":"George Jackson","school":"Louisiana"}
      ],
      "Defense": [
        {"position":"RDE","name":"Kalil Alexander","school":"Texas State"},
        {"position":"RDT","name":"Terry Webb","school":"Texas State"},
        {"position":"RDT","name":"Tim Hardiman","school":"Arkansas State"},
        {"position":"RDE","name":"Khairi Manns","school":"James Madison"},
        {"position":"MLB","name":"Brendan Jackson","school":"Troy"},
        {"position":"MLB","name":"Marques Watson‑Trent","school":"Georgia Southern"},
        {"position":"MLB","name":"Darius McKenzie","school":"South Alabama"},
        {"position":"LCB","name":"Trez Moore","school":"Texas State"},
        {"position":"RCB","name":"Dontay Joyner","school":"Arkansas State"},
        {"position":"RCB","name":"LJ Green","school":"Troy"},
        {"position":"SS","name":"Wydett Williams Jr.","school":"Louisiana Monroe"},
        {"position":"SS","name":"Jeremiah Johnson","school":"Georgia State"},
        {"position":"FS","name":"Tyree Skipper","school":"Louisiana"},
        {"position":"FS","name":"Tobias Fletcher","school":"Coastal Carolina"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Kade Hensley","school":"Coastal Carolina"},
        {"position":"KO","name":"Cristiano Rosa","school":"James Madison"},
        {"position":"PT","name":"Alex Smith","school":"Georgia Southern"},
        {"position":"KR","name":"DeAndre Buchannon","school":"Georgia Southern"},
        {"position":"PR","name":"Yamir Knight","school":"James Madison"},
        {"position":"SS","name":"Tyler Brown","school":"James Madison"}
      ]
    },
    "HonorableMention": [
      {"position":"QB","name":"Joey Aguilar","school":"Appalachian State"},
      {"position":"QB","name":"Gio Lopez","school":"South Alabama"},
      {"position":"QB","name":"Braylon Braxton","school":"Marshall"},
      {"position":"RB","name":"Zak Wallace","school":"Arkansas State"},
      {"position":"RB","name":"Kentrel Bullock","school":"South Alabama"},
      {"position":"RB","name":"Jalen White","school":"Georgia Southern"},
      {"position":"RB","name":"Freddie Brock","school":"Georgia State"},
      {"position":"RB","name":"Aaron Young","school":"Old Dominion"},
      {"position":"RB","name":"A.J. Turner","school":"Marshall"},
      {"position":"WR-X","name":"Jaden Williams","school":"Texas State"},
      {"position":"WR-X","name":"Christian Fitzpatrick","school":"Marshall"},
      {"position":"WR-Z","name":"Derwin Burgiss Jr.","school":"Georgia Southern"},
      {"position":"WR-X","name":"Kole Wilson","school":"Texas State"},
      {"position":"WR-SL","name":"Yamir Knight","school":"James Madison"},
      {"position":"WR-X","name":"Jameson Tucker","school":"Coastal Carolina"},
      {"position":"WR-X","name":"Chris Dawn Jr.","school":"Texas State"},
      {"position":"WR-Y","name":"Josh Dallas","school":"Georgia Southern"},
      {"position":"WR-W","name":"Chuck Montgomery","school":"Marshall"},
      {"position":"TE","name":"Brody Dalton","school":"Troy"},
      {"position":"TE","name":"DJ Thomas‑Jones","school":"South Alabama"},
      {"position":"TE","name":"Kyirin Heath","school":"Southern Miss"},
      {"position":"TE","name":"Toby Payne","school":"Marshall"},
      {"position":"RB","name":"Michel Dukes","school":"Georgia State"},
      {"position":"RB","name":"Kenyon Clay","school":"Southern Miss"},
      {"position":"RT","name":"Makilan Thomas","school":"Arkansas State"},
      {"position":"RT","name":"Malachi Carney","school":"South Alabama"},
      {"position":"LT","name":"Nick Del Grande","school":"Coastal Carolina"},
      {"position":"LG","name":"Heston Edwards","school":"Coastal Carolina"},
      {"position":"LG","name":"Griffin Scroggs","school":"Appalachian State"},
      {"position":"RG","name":"Jalen Slappy","school":"Marshall"},
      {"position":"C","name":"Carter Miller","school":"Louisiana Monroe"},
      {"position":"C","name":"Jack Hollifield","school":"Appalachian State"},
      {"position":"C","name":"Chayse Todd","school":"Texas State"},
      {"position":"LG","name":"Bryce Ramsey","school":"Marshall"},
      {"position":"LG","name":"Pichon Wimbley","school":"Georgia Southern"},
      {"position":"RG","name":"Donavan Manson","school":"Coastal Carolina"},
      {"position":"LT","name":"Elijah Prather","school":"Troy"},
      {"position":"LT","name":"Bryant Williams","school":"Louisiana"},
      {"position":"LT","name":"Jesse Ramil","school":"James Madison"},
      {"position":"BAN","name":"Billy Pullen","school":"Louisiana Monroe"},
      {"position":"LDE","name":"Ryan Johnson","school":"Southern Miss"},
      {"position":"DE","name":"Raymond Cutts","school":"Troy"},
      {"position":"RDT","name":"Elhadj Fall","school":"Georgia Southern"},
      {"position":"LDT","name":"Ian Jeffries","school":"Arkansas State"},
      {"position":"LDT","name":"Immanuel Bush","school":"James Madison"},
      {"position":"DT","name":"Darold DeNgohe","school":"James Madison"},
      {"position":"RDT","name":"Chris Thomas Jr.","school":"Marshall"},
      {"position":"NT","name":"Dominique Ratcliff","school":"Texas State"},
      {"position":"LDE","name":"Deeve Harris","school":"Marshall"},
      {"position":"LDE","name":"Kris Trinidad","school":"Old Dominion"},
      {"position":"DE","name":"Jordan Lawson","school":"Louisiana"},
      {"position":"MLB","name":"Charles Willekes","school":"Arkansas State"},
      {"position":"WLB","name":"Tre Pinkney","school":"Southern Miss"},
      {"position":"MLB","name":"Landyn Watson","school":"Marshall"},
      {"position":"MLB","name":"Carl Glass Jr.","school":"Louisiana Monroe"},
      {"position":"MLB","name":"Carmycah Glass","school":"Louisiana"},
      {"position":"MLB","name":"Wyatt Gedeon","school":"Coastal Carolina"},
      {"position":"MLB","name":"Koa Naotala","school":"Old Dominion"},
      {"position":"MLB","name":"Jacob Dobbs","school":"James Madison"},
      {"position":"MLB","name":"Davon Gilmore","school":"Georgia Southern"},
      {"position":"RCB","name":"Gavin Pringle","school":"Georgia Southern"},
      {"position":"RCB","name":"Justin Agu","school":"Louisiana"},
      {"position":"LCB","name":"Damaje Yancey","school":"Texas State"},
      {"position":"RCB","name":"Will James","school":"Southern Miss"},
      {"position":"RCB","name":"Amarion Fortenberry","school":"South Alabama"},
      {"position":"RCB","name":"Dontay Joyner","school":"Arkansas State"},
      {"position":"LCB","name":"David Godsey Jr.","school":"Louisiana Monroe"},
      {"position":"NB","name":"Ian Foster","school":"Marshall"},
      {"position":"RCB","name":"Jordan Scruggs","school":"South Alabama"},
      {"position":"NB","name":"Marc Stampley II","school":"Georgia Southern"},
      {"position":"LCB","name":"Jordan Polk","school":"Texas State"},
      {"position":"LCB","name":"Justin Parks","school":"Arkansas State"},
      {"position":"FS","name":"Justin Powe","school":"Troy"},
      {"position":"FS","name":"Wesley Miller","school":"South Alabama"},
      {"position":"FS","name":"Kenyatta Watson II","school":"Georgia State"},
      {"position":"SS","name":"Dylan Lawrence","school":"Southern Miss"},
      {"position":"SS","name":"Kaleb Culp","school":"Texas State"},
      {"position":"SS","name":"Jacob Thomas","school":"James Madison"},
      {"position":"SPEAR","name":"Devin Lafayette","school":"Troy"},
      {"position":"MLB","name":"Brendan Harrington","school":"Appalachian State"},
      {"position":"MLB","name":"Tray Brown","school":"Coastal Carolina"},
      {"position":"PK","name":"Clune Van Andel","school":"Arkansas State"},
      {"position":"KO","name":"Nathan Totten","school":"Marshall"},
      {"position":"PT","name":"Seamus Hall","school":"Old Dominion"},
      {"position":"KR","name":"Ian Foster","school":"Marshall"},
      {"position":"PR","name":"Jamaal Pritchett","school":"South Alabama"},
      {"position":"NB","name":"Brandon Greil","school":"Arkansas State"}
    ]
  }
}
