# Generated by Django 5.2.1 on 2025-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='side_of_ball',
            field=models.CharField(blank=True, help_text='Offense, Defense or Special Teams', max_length=50, null=True),
        ),
    ]
