# Generated by Django 5.2.1 on 2025-07-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_side_of_ball'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_ourlads_link',
            new_name='ourlads_link',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_school_link',
            new_name='school_link',
        ),
    ]
