# Generated by Django 5.2.1 on 2025-07-26 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_player_ourlads_link_player_ourlads_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='schools_attended',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='A list of schools that the player has attended', null=True, size=None),
        ),
    ]
