# Generated by Django 5.2.1 on 2025-07-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_player_schools_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='conference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
