# Generated by Django 5.2.1 on 2025-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_school_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='number_of_active_nfl_players',
            field=models.IntegerField(default=0, help_text='Number of active players at the school'),
        ),
    ]
