# Generated by Django 5.2.1 on 2025-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_school_number_of_active_nfl_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='number_of_active_nfl_players',
            field=models.IntegerField(default=0, help_text='Number of active NFL players'),
        ),
    ]
