# Generated by Django 5.2.1 on 2025-07-30 21:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_school_number_of_active_nfl_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='thug_positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, help_text='A list of thug positions that the school is known for via Algorithm', size=None),
        ),
    ]
