# Generated by Django 5.2.1 on 2025-07-30 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_school_thug_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveNFLPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.TextField(blank=True, help_text='First name of the active NFL player', null=True)),
                ('last_name', models.TextField(blank=True, help_text='Last name of the active NFL player', null=True)),
                ('team', models.TextField(blank=True, help_text='NFL team the player is currently on', null=True)),
                ('name', models.TextField(blank=True, help_text='Name of the active NFL player', null=True)),
                ('position', models.TextField(blank=True, help_text='Position of the active NFL player', null=True)),
                ('ourlads_position', models.CharField(blank=True, help_text='Ourlads Position on NFL Depth Charts', max_length=50, null=True)),
                ('ourlads_second_position', models.CharField(blank=True, help_text='Ourlads Second Position on NFL Depth Charts. Typically for Special Teams with Kickers / Holders', max_length=50, null=True)),
                ('depth_chart_position', models.IntegerField(blank=True, help_text='1=starter, 2=backup, etc', null=True)),
                ('depth_chart_second_position', models.IntegerField(blank=True, help_text='1=starter, 2=backup, etc for Special Teams', null=True)),
                ('roster_status', models.CharField(blank=True, help_text='Roster Status (e.g. Active, RES, etc...)', max_length=50, null=True)),
                ('ourlads_link', models.TextField(blank=True, help_text='Ourlads Link to the player profile', null=True)),
                ('draft_year', models.IntegerField(blank=True, help_text='Draft Year of the player', null=True)),
                ('draft_round', models.IntegerField(blank=True, help_text='Draft Round of the player', null=True)),
                ('overall_draft_pick', models.IntegerField(blank=True, help_text='Draft Pick of the player', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_nfl_players', to='core.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
