# Generated by Django 5.2.1 on 2025-07-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_activenflplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activenflplayers',
            name='overall_draft_pick',
            field=models.CharField(blank=True, help_text='Draft Pick of the player', max_length=24, null=True),
        ),
    ]
