# Generated by Django 5.2.1 on 2025-07-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_activenflplayers_overall_draft_pick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activenflplayers',
            name='name',
        ),
    ]
