# Generated by Django 5.2.1 on 2025-07-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_activenflplayers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='number_of_active_nfl_players',
            field=models.IntegerField(blank=True, help_text='Number of active NFL players', null=True),
        ),
    ]
