# Generated by Django 5.2.1 on 2025-08-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_school_number_of_active_nfl_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hs_position_rank',
        ),
        migrations.RemoveField(
            model_name='player',
            name='overall_hs_rank',
        ),
        migrations.RemoveField(
            model_name='player',
            name='transfer_overall_rank',
        ),
        migrations.RemoveField(
            model_name='player',
            name='transfer_position_rank',
        ),
        migrations.RemoveField(
            model_name='player',
            name='transfer_rating',
        ),
    ]
