# Generated by Django 5.2.1 on 2025-08-03 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_player_hs_position_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='agent',
        ),
        migrations.AddField(
            model_name='agent',
            name='shared_players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='A list of players that the Agent has shared with other agents or firms', size=None),
        ),
        migrations.AlterUniqueTogether(
            name='activenflplayers',
            unique_together={('school', 'first_name', 'last_name')},
        ),
    ]
