# Generated by Django 5.2.1 on 2025-08-10 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_player_agent_agent_shared_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activenflplayers',
            name='age',
            field=models.FloatField(blank=True, help_text='Age of the player in years', null=True),
        ),
        migrations.AddField(
            model_name='activenflplayers',
            name='agents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='List of Agents representing the player', null=True, size=None),
        ),
        migrations.AddField(
            model_name='activenflplayers',
            name='career_earnings',
            field=models.FloatField(blank=True, help_text='Career Earnings of the player', null=True),
        ),
        migrations.AddField(
            model_name='activenflplayers',
            name='current_cap_hit',
            field=models.FloatField(blank=True, help_text='Current Cap Hit for the player', null=True),
        ),
        migrations.AddField(
            model_name='activenflplayers',
            name='current_year_cash_salary',
            field=models.FloatField(blank=True, help_text='Current Year Cash Salary for the player', null=True),
        ),
        migrations.AddField(
            model_name='activenflplayers',
            name='firm',
            field=models.TextField(blank=True, help_text='Agent Firm representing the player', null=True),
        ),
        migrations.AddField(
            model_name='activenflplayers',
            name='spot_trac_id',
            field=models.IntegerField(blank=True, help_text='Spotrac ID for the player', null=True),
        ),
        migrations.AddField(
            model_name='activenflplayers',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years of Experience in the NFL', null=True),
        ),
    ]
