# Generated by Django 5.2.1 on 2025-07-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rbcareerstats',
            old_name='rush_attempts',
            new_name='attempts',
        ),
        migrations.RenameField(
            model_name='rbcareerstats',
            old_name='rush_touchdowns',
            new_name='rushing_touchdowns',
        ),
        migrations.AlterField(
            model_name='rbcareerstats',
            name='avg_per_rush',
            field=models.IntegerField(),
        ),
    ]
