# Generated by Django 5.2.1 on 2025-07-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_rename_rush_attempts_rbcareerstats_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qbcareerstats',
            old_name='attempts',
            new_name='interceptions',
        ),
        migrations.RenameField(
            model_name='qbcareerstats',
            old_name='interceptions_thrown',
            new_name='pass_attempts',
        ),
    ]
