# Generated by Django 5.2.1 on 2025-07-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_rename_attempts_qbcareerstats_interceptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qbcareerstats',
            old_name='rush_attempts',
            new_name='rushing_attempts',
        ),
        migrations.RenameField(
            model_name='qbcareerstats',
            old_name='rush_touchdowns',
            new_name='rushing_touchdowns',
        ),
        migrations.RenameField(
            model_name='qbcareerstats',
            old_name='rush_yards',
            new_name='rushing_yards',
        ),
    ]
