# Generated by Django 5.2.1 on 2025-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0004_rename_rush_attempts_qbcareerstats_rushing_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbcareerstats',
            name='avg_per_rush',
            field=models.FloatField(),
        ),
    ]
