# Generated by Django 5.2.1 on 2025-07-09 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_player_ourlads_link_player_ourlads_link_and_more'),
        ('webscraper', '0005_alter_rbcareerstats_avg_per_rush'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('played_against', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('solo_tackles', models.IntegerField()),
                ('assisted_tackles', models.IntegerField()),
                ('total_tackles', models.FloatField()),
                ('tackles_for_loss', models.FloatField()),
                ('sacks', models.FloatField()),
                ('qb_hits', models.IntegerField()),
                ('forced_fumbles', models.IntegerField()),
                ('fumble_recoveries', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('int_yards', models.IntegerField()),
                ('avg_int_yards', models.FloatField()),
                ('touchdowns', models.IntegerField()),
                ('pass_defended', models.IntegerField(help_text='Includes pass breakups & INTs')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_game_stats', to='core.player')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QBGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('played_against', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('completions', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('completion_percentage', models.FloatField()),
                ('passing_yards', models.IntegerField()),
                ('yards_per_attempt', models.FloatField()),
                ('passing_touchdowns', models.IntegerField()),
                ('interceptions_thrown', models.IntegerField()),
                ('passer_rating', models.FloatField()),
                ('rush_attempts', models.IntegerField()),
                ('rush_yards', models.IntegerField()),
                ('avg_per_rush', models.FloatField()),
                ('rush_touchdowns', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_game_stats', to='core.player')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiverGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('played_against', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('receptions', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('yards_per_catch', models.FloatField()),
                ('touchdowns', models.IntegerField()),
                ('rush_attempts', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('rush_touchdowns', models.IntegerField()),
                ('avg_per_rush', models.FloatField()),
                ('total_fumbles', models.IntegerField()),
                ('lost_fumbles', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_game_stats', to='core.player')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
