# Generated by Django 5.2.1 on 2025-07-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0006_defensegamestats_qbgamestats_receivergamestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensegamestats',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qbgamestats',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receivergamestats',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
