# Generated by Django 5.2.1 on 2025-07-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0007_alter_defensegamestats_date_alter_qbgamestats_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qbgamestats',
            old_name='attempts',
            new_name='pass_attempts',
        ),
    ]
