# Generated by Django 5.2.1 on 2025-07-10 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0008_rename_attempts_qbgamestats_pass_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qbgamestats',
            old_name='interceptions_thrown',
            new_name='interceptions',
        ),
    ]
