# Generated by Django 5.2.1 on 2025-07-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0009_rename_interceptions_thrown_qbgamestats_interceptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qbgamestats',
            old_name='rush_attempts',
            new_name='rushing_attempts',
        ),
        migrations.RenameField(
            model_name='qbgamestats',
            old_name='rush_yards',
            new_name='rushing_yards',
        ),
    ]
