# Generated by Django 5.2.1 on 2025-07-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0010_rename_rush_attempts_qbgamestats_rushing_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qbgamestats',
            old_name='rush_touchdowns',
            new_name='rushing_touchdowns',
        ),
    ]
