# Generated by Django 5.2.1 on 2025-07-10 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_player_ourlads_link_player_ourlads_link_and_more'),
        ('webscraper', '0011_rename_rush_touchdowns_qbgamestats_rushing_touchdowns'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('played_against', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('attempts', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('avg_per_rush', models.FloatField()),
                ('rushing_touchdowns', models.IntegerField()),
                ('receptions', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('yards_per_catch', models.FloatField()),
                ('receiving_touchdowns', models.IntegerField()),
                ('total_fumbles', models.IntegerField()),
                ('lost_fumbles', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_game_stats', to='core.player')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
