# Generated by Django 5.2.1 on 2025-07-10 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_player_ourlads_link_player_ourlads_link_and_more'),
        ('webscraper', '0012_rbgamestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('overall_rank', models.IntegerField(blank=True, null=True)),
                ('transfer_rank', models.IntegerField(blank=True, null=True)),
                ('composite_rank', models.IntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiting_classes', to='core.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
