# Generated by Django 5.2.1 on 2025-07-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0013_recruitingclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('high_school', models.CharField(blank=True, max_length=255, null=True)),
                ('hometown_city', models.CharField(blank=True, max_length=100, null=True)),
                ('hometown_state', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('rating_score', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('national_rank', models.IntegerField(blank=True, null=True)),
                ('position_rank', models.IntegerField(blank=True, null=True)),
                ('state_rank', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('recruiting_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiting_classes', to='webscraper.recruitingclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
