# Generated by Django 5.2.1 on 2025-07-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0014_recruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='school_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='transfer_rating_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='transfer_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
