# Generated by Django 5.2.1 on 2025-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0016_rename_rating_score_recruit_hs_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='current_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='current_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='current_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='current_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='experience_level_at_current_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
