# Generated by Django 5.2.1 on 2025-07-27 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_player_schools_attended'),
        ('webscraper', '0017_recruit_current_height_recruit_current_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.player'),
        ),
    ]
