# Generated by Django 5.2.1 on 2025-07-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_school_conference'),
        ('webscraper', '0018_recruit_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruits', to='core.player'),
        ),
    ]
