# Generated by Django 5.2.1 on 2025-07-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_school_number_of_active_nfl_players'),
        ('webscraper', '0019_alter_recruit_player'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defensecareerstats',
            unique_together={('player', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='defensegamestats',
            unique_together={('player', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='qbcareerstats',
            unique_together={('player', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='qbgamestats',
            unique_together={('player', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='rbcareerstats',
            unique_together={('player', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='rbgamestats',
            unique_together={('player', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='receivercareerstats',
            unique_together={('player', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='receivergamestats',
            unique_together={('player', 'date')},
        ),
    ]
