# Generated by Django 5.2.1 on 2025-07-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_school_number_of_active_nfl_players'),
        ('webscraper', '0020_alter_defensecareerstats_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defensegamestats',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='qbgamestats',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rbgamestats',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='receivergamestats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='defensegamestats',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qbgamestats',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rbgamestats',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivergamestats',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='defensegamestats',
            unique_together={('player', 'season', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='qbgamestats',
            unique_together={('player', 'season', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='rbgamestats',
            unique_together={('player', 'season', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='receivergamestats',
            unique_together={('player', 'season', 'date')},
        ),
    ]
