# Generated by Django 5.2.1 on 2025-07-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0021_alter_defensegamestats_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
