# Generated by Django 5.2.1 on 2025-07-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0022_recruit_jersey_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='transfer_national_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='transfer_position_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='transfer_state_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
