# Generated by Django 5.2.1 on 2025-08-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0023_recruit_transfer_national_rank_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recruit',
            unique_together={('recruiting_class', 'first_name', 'last_name')},
        ),
    ]
