# Generated by Django 5.2.1 on 2025-07-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accolades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accolade',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accolade',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
