# Generated by Django 5.2.1 on 2025-07-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accolades', '0002_accolade_first_name_accolade_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accolade',
            name='individual_award',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accolade',
            name='team',
            field=models.CharField(blank=True, null=True),
        ),
    ]
