"""Direct All-ACC List from ACC Official Website"""

{
  "acc_direct": {
    "first_team": {
      "offense": [
        {"name": "Cam Ward", "position": "QB", "school": "Miami"},
        {"name": "Omarion Hampton", "position": "RB", "school": "North Carolina"},
        {"name": "Brashard Smith", "position": "RB", "school": "SMU"},
        {"name": "Xavier Restrepo", "position": "WR", "school": "Miami"},
        {"name": "Ja’Corey Brooks", "position": "WR", "school": "Louisville"},
        {"name": "Antonio Williams", "position": "WR", "school": "Clemson"},
        {"name": "Oronde Gadsden II", "position": "TE", "school": "Syracuse"},
        {"name": "Desmond Reid", "position": "AP", "school": "Pitt"},
        {"name": "Blake Miller", "position": "OT", "school": "Clemson"},
        {"name": "Ozzy Trapilo", "position": "OT", "school": "Boston College"},
        {"name": "Willie Lampkin", "position": "OG", "school": "North Carolina"},
        {"name": "Keylan Rutledge", "position": "OG", "school": "Georgia Tech"},
        {"name": "Drew Kendall", "position": "C", "school": "Boston College"}
      ],
      "defense": [
        {"name": "Donovan Ezeiruaku", "position": "DE", "school": "Boston College"},
        {"name": "Antwaun Powell-Ryland", "position": "DE", "school": "Virginia Tech"},
        {"name": "Aeneas Peebles", "position": "DT", "school": "Virginia Tech"},
        {"name": "Simeon Barrow, Jr.", "position": "DT", "school": "Miami"},
        {"name": "Jared Harrison-Hunte", "position": "DT", "school": "SMU"},
        {"name": "Kyle Louis", "position": "LB", "school": "Pitt"},
        {"name": "Barrett Carter", "position": "LB", "school": "Clemson"},
        {"name": "Teddye Buchanan", "position": "LB", "school": "California"},
        {"name": "Nohl Williams", "position": "CB", "school": "California"},
        {"name": "Chandler Rivers", "position": "CB", "school": "Duke"},
        {"name": "Jonas Sanker", "position": "S", "school": "Virginia"},
        {"name": "Isaiah Nwokobia", "position": "S", "school": "SMU"}
      ],
      "specialists": [
        {"name": "Andres Borregales", "position": "PK", "school": "Miami"},
        {"name": "Alex Mastromanno", "position": "P", "school": "Florida State"},
        {"name": "Desmond Reid", "position": "SP", "school": "Pitt"}
      ]
    },
    "second_team": {
      "offense": [
        {"name": "Kyle McCord", "position": "QB", "school": "Syracuse"},
        {"name": "Bhayshul Tuten", "position": "RB", "school": "Virginia Tech"},
        {"name": "Isaac Brown", "position": "RB", "school": "Louisville"},
        {"name": "Trebor Pena", "position": "WR", "school": "Syracuse"},
        {"name": "Jackson Meeks", "position": "WR", "school": "Syracuse"},
        {"name": "Elic Ayomanor", "position": "WR", "school": "Stanford"},
        {"name": "Elijah Arroyo", "position": "TE", "school": "Miami"},
        {"name": "Omarion Hampton", "position": "AP", "school": "North Carolina"},
        {"name": "Brian Parker II", "position": "OT", "school": "Duke"},
        {"name": "Francis Mauigoa", "position": "OT", "school": "Miami"},
        {"name": "Caleb Krings", "position": "OG", "school": "Duke"},
        {"name": "Marcus Tate", "position": "OG", "school": "Clemson"},
        {"name": "Jakai Clark", "position": "C", "school": "SMU"}
      ],
      "defense": [
        {"name": "T.J. Parker", "position": "DE", "school": "Clemson"},
        {"name": "Ashton Gillotte", "position": "DE", "school": "Louisville"},
        {"name": "Jordan van den Berg", "position": "DT", "school": "Georgia Tech"},
        {"name": "Kendy Charles", "position": "DT", "school": "Duke"},
        {"name": "Kobe Wilson", "position": "LB", "school": "SMU"},
        {"name": "Francisco Mauigoa", "position": "LB", "school": "Miami"},
        {"name": "Branson Combs", "position": "LB", "school": "Wake Forest"},
        {"name": "Avieon Terrell", "position": "CB", "school": "Clemson"},
        {"name": "Quincy Riley", "position": "CB", "school": "Louisville"},
        {"name": "Terry Moore", "position": "S", "school": "Duke"},
        {"name": "Mishael Powell", "position": "S", "school": "Miami"},
        {"name": "Donovan McMillon", "position": "S", "school": "Pitt"}
      ],
      "specialists": [
        {"name": "Ryan Fitzgerald", "position": "PK", "school": "Florida State"},
        {"name": "Lachlan Wilson", "position": "P", "school": "California"},
        {"name": "Alex Mastromanno", "position": "SP", "school": "Florida State"}
      ]
    },
    "third_team": {
      "offense": [
        {"name": "Kevin Jennings", "position": "QB", "school": "SMU"},
        {"name": "Phil Mafah", "position": "RB", "school": "Clemson"},
        {"name": "Demond Claiborne", "position": "RB", "school": "Wake Forest"},
        {"name": "Malachi Fields", "position": "WR", "school": "Virginia"},
        {"name": "Jordan Moore", "position": "WR", "school": "Duke"},
        {"name": "Eli Pancol", "position": "WR", "school": "Duke"},
        {"name": "Jake Briningstool", "position": "TE", "school": "Clemson"},
        {"name": "Demond Claiborne", "position": "AP", "school": "Wake Forest"},
        {"name": "PJ Williams", "position": "OT", "school": "SMU"},
        {"name": "Jordan Williams", "position": "OT", "school": "Georgia Tech"},
        {"name": "Logan Parr", "position": "OG", "school": "SMU"},
        {"name": "Walker Parks", "position": "OG", "school": "Clemson"},
        {"name": "Zeke Correll", "position": "C", "school": "NC State"}
      ],
      "defense": [
        {"name": "Xavier Carlton", "position": "DE", "school": "California"},
        {"name": "Davin Vann", "position": "DE", "school": "NC State"},
        {"name": "Payton Page", "position": "DT", "school": "Clemson"},
        {"name": "Cam Horsley", "position": "DT", "school": "Boston College"},
        {"name": "Jahvaree Ritzie", "position": "DT", "school": "North Carolina"},
        {"name": "Rasheem Biles", "position": "LB", "school": "Pitt"},
        {"name": "Ozzie Nicholas", "position": "LB", "school": "Duke"},
        {"name": "Kyle Efford", "position": "LB", "school": "Georgia Tech"},
        {"name": "Clarence Lewis", "position": "CB", "school": "Syracuse"},
        {"name": "Mansoor Delane", "position": "CB", "school": "Virginia Tech"},
        {"name": "Nick Andersen", "position": "S", "school": "Wake Forest"},
        {"name": "Craig Woodson", "position": "S", "school": "California"}
      ],
      "specialists": [
        {"name": "Ben Sauls", "position": "PK", "school": "Pitt"},
        {"name": "Peter Moore", "position": "P", "school": "Virginia Tech"},
        {"name": "Jaylin Lane", "position": "SP", "school": "Virginia Tech"}
      ]
    },
  "honorable_mention": {
    "offense": [
      {"name": "Cade Klubnik", "position": "QB", "school": "Clemson"},
      {"name": "Tyler Shough", "position": "QB", "school": "Louisville"},
      {"name": "LeQuint Allen", "position": "RB", "school": "Syracuse"},
      {"name": "Desmond Reid", "position": "RB", "school": "Pitt"},
      {"name": "Jamal Haynes", "position": "RB", "school": "Georgia Tech"},
      {"name": "Damien Martinez", "position": "RB", "school": "Miami"},
      {"name": "Konata Mumpfield", "position": "WR", "school": "Pitt"},
      {"name": "Jacolby George", "position": "WR", "school": "Miami"},
      {"name": "Taylor Morin", "position": "WR", "school": "Wake Forest"},
      {"name": "Malik Rutherford", "position": "WR", "school": "Georgia Tech"},
      {"name": "Eric Singleton, Jr.", "position": "WR", "school": "Georgia Tech"},
      {"name": "Keyshawn Smith", "position": "WR", "school": "SMU"},
      {"name": "Lewis Bond", "position": "WR", "school": "Boston College"},
      {"name": "Jack Endries", "position": "TE", "school": "California"},
      {"name": "Gavin Bartholomew", "position": "TE", "school": "Pitt"},
      {"name": "RJ Maryland", "position": "TE", "school": "SMU"},
      {"name": "LeQuint Allen", "position": "AP", "school": "Syracuse"},
      {"name": "Isaac Brown", "position": "AP", "school": "Louisville"},
      {"name": "Nohl Williams", "position": "AP", "school": "California"},
      {"name": "Roderick Daniels Jr.", "position": "AP", "school": "SMU"},
      {"name": "Corey Robinson II", "position": "OT", "school": "Georgia Tech"},
      {"name": "Monroe Mills", "position": "OT", "school": "Louisville"},
      {"name": "Tristan Leigh", "position": "OT", "school": "Clemson"},
      {"name": "Jalen Rivers", "position": "OT", "school": "Miami"},
      {"name": "Xavier Chaplin", "position": "OT", "school": "Virginia Tech"},
      {"name": "Savion Washington", "position": "OT", "school": "Syracuse"},
      {"name": "Howard Sampson", "position": "OT", "school": "North Carolina"},
      {"name": "Justin Osborne", "position": "OG", "school": "SMU"},
      {"name": "Anez Cooper", "position": "OG", "school": "Miami"},
      {"name": "Michael Gonzalez", "position": "OG", "school": "Louisville"},
      {"name": "Kaden Moore", "position": "OG", "school": "Virginia Tech"},
      {"name": "Matt Gulbin", "position": "OG", "school": "Wake Forest"},
      {"name": "Jack Conley", "position": "OG", "school": "Boston College"},
      {"name": "Jakob Bradford", "position": "OG", "school": "Syracuse"},
      {"name": "Logan Taylor", "position": "OG", "school": "Boston College"},
      {"name": "Timothy McKay", "position": "OG", "school": "NC State"},
      {"name": "Zach Carpenter", "position": "C", "school": "Miami"},
      {"name": "Weston Franklin", "position": "C", "school": "Georgia Tech"},
      {"name": "Pete Nygra", "position": "C", "school": "Louisville"},
      {"name": "Ryan Linthicum", "position": "C", "school": "Clemson"},
      {"name": "Brian Stevens", "position": "C", "school": "Virginia"},
      {"name": "Luke Petitbon", "position": "C", "school": "Wake Forest"}
    ],
    "defense": [
      {"name": "Fadil Diggs", "position": "DE", "school": "Syracuse"},
      {"name": "Wes Williams", "position": "DE", "school": "Duke"},
      {"name": "Peter Woods", "position": "DE", "school": "Clemson"},
      {"name": "Tyler Baron", "position": "DE", "school": "Miami"},
      {"name": "Elijah Roberts", "position": "DE", "school": "SMU"},
      {"name": "Rueben Bain, Jr.", "position": "DE", "school": "Miami"},
      {"name": "Zeek Biggers", "position": "DT", "school": "Georgia Tech"},
      {"name": "Kevin Pointer", "position": "DT", "school": "Wake Forest"},
      {"name": "Joshua Farmer", "position": "DT", "school": "Florida State"},
      {"name": "Ramon Puryear", "position": "DT", "school": "Louisville"},
      {"name": "DeMonte Capehart", "position": "DT", "school": "Clemson"},
      {"name": "Aaron Hall", "position": "DT", "school": "Duke"},
      {"name": "Akheem Mesidor", "position": "DT", "school": "Miami"},
      {"name": "Kori Roberson Jr.", "position": "DT", "school": "SMU"},
      {"name": "Darrell Jackson Jr.", "position": "DT", "school": "Florida State"},
      {"name": "Nick James", "position": "DT", "school": "Pitt"},
      {"name": "Ahmad Walker", "position": "LB", "school": "SMU"},
      {"name": "Wade Woodaz", "position": "LB", "school": "Clemson"},
      {"name": "Xavier Carlton", "position": "LB", "school": "California"},
      {"name": "Justin Barron", "position": "LB", "school": "Syracuse"},
      {"name": "Power Echols", "position": "LB", "school": "North Carolina"},
      {"name": "Stanquan Clark", "position": "LB", "school": "Louisville"},
      {"name": "Marlowe Wax", "position": "LB", "school": "Syracuse"},
      {"name": "Cade Uluave", "position": "LB", "school": "California"},
      {"name": "Sean Brown", "position": "LB", "school": "NC State"},
      {"name": "Alex Howard", "position": "LB", "school": "Duke"},
      {"name": "Tre Freeman", "position": "LB", "school": "Duke"},
      {"name": "Kam Robinson", "position": "LB", "school": "Virginia"},
      {"name": "Dorian Strong", "position": "CB", "school": "Virginia Tech"},
      {"name": "OJ Frederique", "position": "CB", "school": "Miami"},
      {"name": "Alijah Huzzie", "position": "CB", "school": "North Carolina"},
      {"name": "Corey Thornton", "position": "CB", "school": "Louisville"},
      {"name": "Brandon Crossley", "position": "CB", "school": "SMU"},
      {"name": "Azareye’h Thomas", "position": "CB", "school": "Florida State"},
      {"name": "R.J. Mickens", "position": "S", "school": "Clemson"},
      {"name": "Ahmaad Moses", "position": "S", "school": "SMU"},
      {"name": "Jaylen Stinson", "position": "S", "school": "Duke"},
      {"name": "Jonathan McGill", "position": "S", "school": "SMU"},
      {"name": "Bishop Fitzgerald", "position": "S", "school": "NC State"},
      {"name": "Khalil Barnes", "position": "S", "school": "Clemson"}
    ],
    "specialists": [
      {"name": "Collin Rogers", "position": "PK", "school": "SMU"},
      {"name": "John Love", "position": "PK", "school": "Virginia Tech"},
      {"name": "Brock Travelstead", "position": "PK", "school": "Louisville"},
      {"name": "Jack Stonehouse", "position": "P", "school": "Syracuse"},
      {"name": "Kade Reynoldson", "position": "P", "school": "Duke"},
      {"name": "Daniel Sparks", "position": "P", "school": "Virginia"},
      {"name": "Antonio Williams", "position": "SP", "school": "Clemson"},
      {"name": "Alijah Huzzie", "position": "SP", "school": "North Carolina"},
      {"name": "Collin Rogers", "position": "SP", "school": "SMU"},
      {"name": "Que’Sean Brown", "position": "SP", "school": "Duke"}
    ]
  }
}
}
