"""CFN's All-Big-12 Conference List for 2024"""

ALL_BIG_TWELVE = {
  "year": 2024,
  "name_of_award": "all_conference",
  "conference": "big_twelve",
  "source": "cfn",
  "big_twelve" : [
      {"name": "Travis Hunter", "position": "LCB", "school": "Colorado", "award": "PlayerOfTheYear"},
  {"name": "Cam Skattebo", "position": "RB", "school": "Arizona State", "award": "OffensivePlayerOfTheYear"},
  {"name": "Travis Hunter", "position": "LCB", "school": "Colorado", "award": "DefensivePlayerOfTheYear"},
  {"name": "Tyler Loop", "position": "PK", "school": "Arizona", "award": "SpecialistOfTheYear"},
  {"name": "Jack Kelly", "position": "ROVER", "school": "Brigham Young", "award": "NewcomerOfTheYear"},
  {"name": "Kenny Dillingham", "position": "Coach", "school": "Arizona State", "award": "CoachOfTheYear"},
  {"name": "Jordan Seaton", "position": "LT", "school": "Colorado", "award": "ImpactFreshmanOfTheYear"},
{"name": "Shedeur Sanders", "position": "QB", "school": "Colorado", "award": "QuarterbackOfTheYear"},
  {"name": "Cam Skattebo", "position": "RB", "school": "Arizona State", "award": "RunningBackOfTheYear"},
  {"name": "Tetairoa McMillan", "position": "WR-X", "school": "Arizona", "award": "WideReceiverOfTheYear"},
  {"name": "Brant Kuithe", "position": "TE", "school": "Utah", "award": "TightEndOfTheYear"},
  {"name": "Wyatt Milum", "position": "LT", "school": "West Virginia", "award": "OffensiveTackleOfTheYear"},
  {"name": "Luke Kandra", "position": "RG", "school": "Cincinnati", "award": "OffensiveGuardOfTheYear"},
  {"name": "James Brockermeyer", "position": "C", "school": "TCU", "award": "CenterOfTheYear"},
  {"name": "Wyatt Milum", "position": "LT", "school": "West Virginia", "award": "OffensiveLinemanOfTheYear"},
  {"name": "West Virginia Mountaineers", "position": "OL Unit", "school": "West Virginia", "award": "OffensiveLineOfTheYear"},
  {"name": "Josh Kelly", "position": "WR-X", "school": "Texas Tech", "award": "OffensiveNewcomerOfTheYear"},
  {"name": "Josh Kelly", "position": "WR-X", "school": "Texas Tech", "award": "OffensiveTransferOfTheYear"},
  {"name": "B.J. Green II", "position": "LDE", "school": "Colorado", "award": "EdgeDefenderOfTheYear"},
  {"name": "Dontay Corleone", "position": "DT", "school": "Cincinnati", "award": "InteriorDefenderOfTheYear"},
  {"name": "Jacob Rodriguez", "position": "WLB", "school": "Texas Tech", "award": "LinebackerOfTheYear"},
  {"name": "Travis Hunter", "position": "LCB", "school": "Colorado", "award": "CornerbackOfTheYear"},
  {"name": "Xavion Alford", "position": "FS", "school": "Arizona State", "award": "SafetyOfTheYear"},
  {"name": "Colorado Buffaloes", "position": "DL Unit", "school": "Colorado", "award": "DefensiveLineOfTheYear"},
  {"name": "Arizona State Sun Devils", "position": "Secondary Unit", "school": "Arizona State", "award": "SecondaryOfTheYear"},
  {"name": "Jack Kelly", "position": "ROVER", "school": "Brigham Young", "award": "DefensiveNewcomerOfTheYear"},
  {"name": "Jack Kelly", "position": "ROVER", "school": "Brigham Young", "award": "DefensiveTransferOfTheYear"},
  {"name": "Will Ferrin", "position": "PK", "school": "Brigham Young", "award": "KickerOfTheYear"},
  {"name": "Palmer Williams", "position": "PT", "school": "Baylor", "award": "PunterOfTheYear"},
  {"name": "Keelan Marion", "position": "KR", "school": "Brigham Young", "award": "KickReturnerOfTheYear"},
  {"name": "JP Richardson", "position": "PR", "school": "TCU", "award": "PuntReturnerOfTheYear"},
  {"name": "Micah Gifford", "position": "SS", "school": "Baylor", "award": "SpecialTeamerOfTheYear"},
  {"name": "Tyler Loop", "position": "KO", "school": "Arizona", "award": "KickoffSpecialistOfTheYear"},
{"name": "Shedeur Sanders", "position": "QB", "school": "Colorado", "team": "1"},
  {"name": "RJ Harvey", "position": "RB", "school": "Central Florida", "team": "1"},
  {"name": "Cam Skattebo", "position": "RB", "school": "Arizona State", "team": "1"},
  {"name": "Tetairoa McMillan", "position": "WR-X", "school": "Arizona", "team": "1"},
  {"name": "Travis Hunter", "position": "WR-X", "school": "Colorado", "team": "1"},
  {"name": "Jordyn Tyson", "position": "WR-X", "school": "Arizona State", "team": "1"},
  {"name": "Brant Kuithe", "position": "TE", "school": "Utah", "team": "1"},
  {"name": "DJ Giddens", "position": "RB", "school": "Kansas State", "team": "1"},
  {"name": "Wyatt Milum", "position": "LT", "school": "West Virginia", "team": "1"},
  {"name": "Luke Kandra", "position": "RG", "school": "Cincinnati", "team": "1"},
  {"name": "James Brockermeyer", "position": "C", "school": "TCU", "team": "1"},
  {"name": "Tomas Rimac", "position": "RT", "school": "West Virginia", "team": "1"},
  {"name": "Spencer Fano", "position": "RT", "school": "Utah", "team": "1"},
  
  {"name": "B.J. Green II", "position": "LDE", "school": "Colorado", "team": "1"},
  {"name": "Dontay Corleone", "position": "NT", "school": "Cincinnati", "team": "1"},
  {"name": "Ricky Barber", "position": "DT", "school": "Central Florida", "team": "1"},
  {"name": "Brendan Mott", "position": "LDE", "school": "Kansas State", "team": "1"},
  {"name": "Jacob Rodriguez", "position": "WLB", "school": "Texas Tech", "team": "1"},
  {"name": "Isaiah Glasker", "position": "SLB", "school": "Brigham Young", "team": "1"},
  {"name": "Jack Kelly", "position": "ROVER", "school": "Brigham Young", "team": "1"},
  {"name": "Travis Hunter", "position": "LCB", "school": "Colorado", "team": "1"},
  {"name": "Shamari Simmons", "position": "SS", "school": "Arizona State", "team": "1"},
  {"name": "Mello Dotson", "position": "LCB", "school": "Kansas", "team": "1"},
  {"name": "Dalton Johnson", "position": "SS", "school": "Arizona", "team": "1"},
  {"name": "Xavion Alford", "position": "FS", "school": "Arizona State", "team": "1"},
  {"name": "Bud Clark", "position": "FS", "school": "TCU", "team": "1"},
  {"name": "Lander Barton", "position": "STUD", "school": "Utah", "team": "1"},

  {"name": "Will Ferrin", "position": "PK", "school": "Brigham Young", "team": "1"},
  {"name": "Tyler Loop", "position": "KO", "school": "Arizona", "team": "1"},
  {"name": "Palmer Williams", "position": "PT", "school": "Baylor", "team": "1"},
  {"name": "Keelan Marion", "position": "KR", "school": "Brigham Young", "team": "1"},
  {"name": "JP Richardson", "position": "PR", "school": "TCU", "team": "1"},
  {"name": "Micah Gifford", "position": "SS", "school": "Baylor", "team": "1"},
 {"name": "Sam Leavitt", "position": "QB", "school": "Arizona State", "team": "2"},
  {"name": "Tahj Brooks", "position": "RB", "school": "Texas Tech", "team": "2"},
  {"name": "Devin Neal", "position": "RB", "school": "Kansas", "team": "2"},
  {"name": "Jack Bech", "position": "TE", "school": "TCU", "team": "2"},
  {"name": "Jayden Higgins", "position": "WR-X", "school": "Iowa State", "team": "2"},
  {"name": "Josh Kelly", "position": "WR-X", "school": "Texas Tech", "team": "2"},
  {"name": "Joe Royer", "position": "TE", "school": "Cincinnati", "team": "2"},
  {"name": "Jaylin Noel", "position": "WR-Z", "school": "Iowa State", "team": "2"},
  {"name": "Bryce Cabeldue", "position": "RT", "school": "Kansas", "team": "2"},
  {"name": "Tanoa Togiai", "position": "LG", "school": "Utah", "team": "2"},
  {"name": "Jaren Kump", "position": "C", "school": "Utah", "team": "2"},
  {"name": "Davion Carter", "position": "RG", "school": "Texas Tech", "team": "2"},
  {"name": "Logan Brown", "position": "LT", "school": "Kansas", "team": "2"},

  {"name": "Keith Cooper Jr.", "position": "DE", "school": "Houston", "team": "2"},
  {"name": "Treven Ma’ae", "position": "DT", "school": "Baylor", "team": "2"},
  {"name": "Lee Hunter", "position": "DT", "school": "Central Florida", "team": "2"},
  {"name": "Tyler Batty", "position": "LDE", "school": "Brigham Young", "team": "2"},
  {"name": "Nikhai Hill-Green", "position": "MLB", "school": "Colorado", "team": "2"},
  {"name": "Jonathan Thompson", "position": "MLB", "school": "Cincinnati", "team": "2"},
  {"name": "Matt Jones", "position": "RILB", "school": "Baylor", "team": "2"},
  {"name": "Jeremiah Wilson", "position": "RCB", "school": "Houston", "team": "2"},
  {"name": "Jontez Williams", "position": "RCB", "school": "Iowa State", "team": "2"},
  {"name": "Cobee Bryant", "position": "LCB", "school": "Kansas", "team": "2"},
  {"name": "Myles Rowser", "position": "SS", "school": "Arizona State", "team": "2"},
  {"name": "Tao Johnson", "position": "FS", "school": "Utah", "team": "2"},
  {"name": "A.J. Haulcy", "position": "FS", "school": "Houston", "team": "2"},
  {"name": "Desmond Purnell", "position": "SLB", "school": "Kansas State", "team": "2"},

  {"name": "Tyler Loop", "position": "PK", "school": "Arizona", "team": "2"},
  {"name": "Tabor Allen", "position": "KO", "school": "Kansas", "team": "2"},
  {"name": "Jack Bouwmeester", "position": "PT", "school": "Utah", "team": "2"},
  {"name": "Jamaal Bell", "position": "KR", "school": "Baylor", "team": "2"},
  {"name": "Josh Cameron", "position": "PR", "school": "Baylor", "team": "2"},
  {"name": "Taje McCoy", "position": "RUSH", "school": "Colorado", "team": "2"},
{"position": "QB", "name": "Josh Hoover", "school": "TCU", "unit": "Offense", "team": "3"},
  {"position": "RB", "name": "Corey Kiner", "school": "Cincinnati", "unit": "Offense", "team": "3"},
  {"position": "RB", "name": "Bryson Washington", "school": "Baylor", "unit": "Offense", "team": "3"},
  {"position": "WR-Z", "name": "LaJohntay Wester", "school": "Colorado", "unit": "Offense", "team": "3"},
  {"position": "WR-SL", "name": "Chase Roberts", "school": "Brigham Young", "unit": "Offense", "team": "3"},
  {"position": "WR-Z", "name": "Josh Cameron", "school": "Baylor", "unit": "Offense", "team": "3"},
  {"position": "TE", "name": "Randy Pittman Jr.", "school": "Central Florida", "unit": "Offense", "team": "3"},
  {"position": "RB", "name": "Ollie Gordon II", "school": "Oklahoma State", "unit": "Offense", "team": "3"},
  {"position": "LT", "name": "Easton Kilty", "school": "Kansas State", "unit": "Offense", "team": "3"},
  {"position": "RG", "name": "Omar Aigbedion", "school": "Baylor", "unit": "Offense", "team": "3"},
  {"position": "C", "name": "Bryce Foster", "school": "Kansas", "unit": "Offense", "team": "3"},
  {"position": "LG", "name": "Weylin Lapuaho", "school": "Brigham Young", "unit": "Offense", "team": "3"},
  {"position": "RT", "name": "Nick Malone", "school": "West Virginia", "unit": "Offense", "team": "3"},
  
  {"position": "LDE", "name": "Tre Smith", "school": "Arizona", "unit": "Defense", "team": "3"},
  {"position": "LDT", "name": "Blake Mangelson", "school": "Brigham Young", "unit": "Defense", "team": "3"},
  {"position": "DT", "name": "Anthony Holmes Jr.", "school": "Houston", "unit": "Defense", "team": "3"},
  {"position": "DE", "name": "T.J. Jackson", "school": "West Virginia", "unit": "Defense", "team": "3"},
  {"position": "RILB", "name": "Keaton Thomas", "school": "Baylor", "unit": "Defense", "team": "3"},
  {"position": "MLB", "name": "Josiah Trotter", "school": "West Virginia", "unit": "Defense", "team": "3"},
  {"position": "LB", "name": "Austin Romaine", "school": "Kansas State", "unit": "Defense", "team": "3"},
  {"position": "CB", "name": "Jakob Robinson", "school": "Brigham Young", "unit": "Defense", "team": "3"},
  {"position": "CB", "name": "Darien Porter", "school": "Iowa State", "unit": "Defense", "team": "3"},
  {"position": "CB", "name": "Keith Abney", "school": "Arizona State", "unit": "Defense", "team": "3"},
  {"position": "SS", "name": "Cam’Ron Silmon-Craig", "school": "Colorado", "unit": "Defense", "team": "3"},
  {"position": "FS", "name": "Shilo Sanders", "school": "Colorado", "unit": "Defense", "team": "3"},
  {"position": "S", "name": "Tanner Wall", "school": "Brigham Young", "unit": "Defense", "team": "3"},
  {"position": "FLEX", "name": "Jared Bartlett", "school": "Cincinnati", "unit": "Defense", "team": "3"},
  
  {"position": "PK", "name": "Gino Garcia", "school": "Texas Tech", "unit": "SpecialTeams", "team": "3"},
  {"position": "KOS", "name": "Parker Lewis", "school": "Arizona State", "unit": "SpecialTeams", "team": "3"},
  {"position": "P", "name": "Liam Dougherty", "school": "Houston", "unit": "SpecialTeams", "team": "3"},
  {"position": "KR", "name": "Jeremiah Patterson", "school": "Arizona", "unit": "SpecialTeams", "team": "3"},
  {"position": "PR", "name": "Mekhi Mews", "school": "Houston", "unit": "SpecialTeams", "team": "3"},
  {"position": "ST", "name": "Ben Finneseth", "school": "Colorado", "unit": "SpecialTeams", "team": "3"},
 {"position":"QB","name":"Jake Retzlaff","school":"Brigham Young","team":"honorable_mention"},
  {"position":"QB","name":"Sawyer Robertson","school":"Baylor","team":"honorable_mention"},
  {"position":"QB","name":"Rocco Becht","school":"Iowa State","team":"honorable_mention"},
  {"position":"RB","name":"Quali Conley","school":"Arizona","team":"honorable_mention"},
  {"position":"RB","name":"LJ Martin","school":"Brigham Young","team":"honorable_mention"},
  {"position":"RB","name":"CJ Donaldson Jr.","school":"West Virginia","team":"honorable_mention"},
  {"position":"RB","name":"Carson Hansen","school":"Iowa State","team":"honorable_mention"},
  {"position":"RB","name":"Micah Bernard","school":"Utah","team":"honorable_mention"},
  {"position":"RB","name":"Jahiem White","school":"West Virginia","team":"honorable_mention"},
  {"position":"WR","name":"De’Zhaun Stribling","school":"Oklahoma State","team":"honorable_mention"},
  {"position":"WR","name":"Kobe Hudson","school":"Central Florida","team":"honorable_mention"},
  {"position":"WR","name":"Luke Grimm","school":"Kansas","team":"honorable_mention"},
  {"position":"WR","name":"Caleb Douglas","school":"Texas Tech","team":"honorable_mention"},
  {"position":"WR","name":"Xzavier Henderson","school":"Cincinnati","team":"honorable_mention"},
  {"position":"WR","name":"Dorian Singer","school":"Utah","team":"honorable_mention"},
  {"position":"WR","name":"Darius Lassiter","school":"Brigham Young","team":"honorable_mention"},
  {"position":"WR","name":"Eric McAlister","school":"TCU","team":"honorable_mention"},
  {"position":"WR","name":"JP Richardson","school":"TCU","team":"honorable_mention"},
  {"position":"TE","name":"Michael Trigg","school":"Baylor","team":"honorable_mention"},
  {"position":"TE","name":"Chamon Metayer","school":"Arizona State","team":"honorable_mention"},
  {"position":"TE","name":"Jalin Conyers","school":"Texas Tech","team":"honorable_mention"},
  {"position":"FLEX","name":"Cam Cook","school":"TCU","team":"honorable_mention"},
  {"position":"FLEX","name":"Brennan Presley","school":"Oklahoma State","team":"honorable_mention"},
  {"position":"FLEX","name":"Monaray Baldwin","school":"Baylor","team":"honorable_mention"},
  {"position":"OT","name":"Phillip Houston","school":"Colorado","team":"honorable_mention"},
  {"position":"OT","name":"Caleb Rogers","school":"Texas Tech","team":"honorable_mention"},
  {"position":"OT","name":"Max Iheanachor","school":"Arizona State","team":"honorable_mention"},
  {"position":"OG","name":"Kobe Baynes","school":"Kansas","team":"honorable_mention"},
  {"position":"OG","name":"Taylor Poitier","school":"Kansas State","team":"honorable_mention"},
  {"position":"OG","name":"Ryan Lengyel","school":"Baylor","team":"honorable_mention"},
  {"position":"OC","name":"Connor Pay","school":"Brigham Young","team":"honorable_mention"},
  {"position":"OC","name":"Sam Hecht","school":"Kansas State","team":"honorable_mention"},
  {"position":"OC","name":"Gavin Gerhardt","school":"Cincinnati","team":"honorable_mention"},
  {"position":"OG","name":"Michael Ford Jr.","school":"Kansas","team":"honorable_mention"},
  {"position":"OG","name":"Kahlil Benson","school":"Colorado","team":"honorable_mention"},
  {"position":"OG","name":"Carson Bruno","school":"TCU","team":"honorable_mention"},
  {"position":"OT","name":"John Williams","school":"Cincinnati","team":"honorable_mention"},
  {"position":"OT","name":"Amari Knight","school":"Central Florida","team":"honorable_mention"},
  {"position":"OT","name":"Carver Willis","school":"Kansas State","team":"honorable_mention"},
  {"position":"EDGE","name":"Obi Ezeigbo","school":"Oklahoma State","team":"honorable_mention"},
  {"position":"EDGE","name":"Sean Martin","school":"West Virginia","team":"honorable_mention"},
  {"position":"EDGE","name":"Nyjalik Kelly","school":"Central Florida","team":"honorable_mention"},
  {"position":"DT","name":"Tommy Dunn Jr.","school":"Kansas","team":"honorable_mention"},
  {"position":"DT","name":"De’Braylon Carroll","school":"Texas Tech","team":"honorable_mention"},
  {"position":"DT","name":"Jackie Marshall","school":"Baylor","team":"honorable_mention"},
  {"position":"DT","name":"Jeff Clark","school":"Arizona State","team":"honorable_mention"},
  {"position":"DT","name":"Ta’ita’i Uiagalelei","school":"Arizona","team":"honorable_mention"},
  {"position":"DT","name":"Amari McNeill","school":"Colorado","team":"honorable_mention"},
  {"position":"EDGE","name":"Eric Phillips","school":"Cincinnati","team":"honorable_mention"},
  {"position":"EDGE","name":"Van Fillinger","school":"Utah","team":"honorable_mention"},
  {"position":"EDGE","name":"Logan Fano","school":"Utah","team":"honorable_mention"},
  {"position":"LB","name":"Caleb McCullough","school":"Arizona State","team":"honorable_mention"},
  {"position":"LB","name":"Deshawn Pace","school":"Central Florida","team":"honorable_mention"},
  {"position":"LB","name":"Cornell Wheeler","school":"Kansas","team":"honorable_mention"},
  {"position":"LB","name":"Ze’ree Alexander","school":"Central Florida","team":"honorable_mention"},
  {"position":"LB","name":"Johnny Hodges","school":"TCU","team":"honorable_mention"},
  {"position":"LB","name":"Namdi Obiazor","school":"TCU","team":"honorable_mention"},
  {"position":"LB","name":"Jacob Manu","school":"Arizona","team":"honorable_mention"},
  {"position":"LB","name":"Michael Batton","school":"Houston","team":"honorable_mention"},
  {"position":"LB","name":"Ben Roberts","school":"Texas Tech","team":"honorable_mention"},
  {"position":"CB","name":"Colton Hood","school":"Colorado","team":"honorable_mention"},
  {"position":"CB","name":"D.J. McKinney","school":"Colorado","team":"honorable_mention"},
  {"position":"CB","name":"Javan Robinson","school":"Arizona State","team":"honorable_mention"},
  {"position":"CB","name":"Korie Black","school":"Oklahoma State","team":"honorable_mention"},
  {"position":"CB","name":"Lorando Johnson","school":"Baylor","team":"honorable_mention"},
  {"position":"CB","name":"LaMareon James","school":"TCU","team":"honorable_mention"},
  {"position":"CB","name":"Jacob Parrish","school":"Kansas State","team":"honorable_mention"},
  {"position":"CB","name":"Tacario Davis","school":"Arizona","team":"honorable_mention"},
  {"position":"CB","name":"MacMcWilliams","school":"Central Florida","team":"honorable_mention"},
  {"position":"SS","name":"Owen Goss","school":"Arizona","team":"honorable_mention"},
  {"position":"SS","name":"Kendal Daniels","school":"Oklahoma State","team":"honorable_mention"},
  {"position":"SS","name":"VJ Payne","school":"Kansas State","team":"honorable_mention"},
  {"position":"FS","name":"CJ Baskerville","school":"Texas Tech","team":"honorable_mention"},
  {"position":"FS","name":"Anthony Wilson","school":"West Virginia","team":"honorable_mention"},
  {"position":"FS","name":"Devyn Bobby","school":"Baylor","team":"honorable_mention"},
  {"position":"S","name":"Carter Stoutmire","school":"Colorado","team":"honorable_mention"},
  {"position":"S","name":"Malik Verdon","school":"Iowa State","team":"honorable_mention"},
  {"position":"S","name":"Beau Freyler","school":"Iowa State","team":"honorable_mention"},
  {"position":"FLEX","name":"Genesis Smith","school":"Arizona","team":"honorable_mention"},
  {"position":"FLEX","name":"Smith Snowden","school":"Utah","team":"honorable_mention"},
  {"position":"FLEX","name":"Cameron Calhoun","school":"Utah","team":"honorable_mention"},
  {"position":"PK","name":"Alejandro Mata","school":"Colorado","team":"honorable_mention"},
  {"position":"KOS","name":"Jack Stone","school":"Baylor","team":"honorable_mention"},
  {"position":"P","name":"Ethan Craw","school":"TCU","team":"honorable_mention"},
  {"position":"KR","name":"Drae McCray","school":"Texas Tech","team":"honorable_mention"},
  {"position":"PR","name":"Dylan Edwards","school":"Kansas State","team":"honorable_mention"},
  {"position":"ST","name":"Trey Reynolds","school":"Utah","team":"honorable_mention"}
  ]
}

{
  "big12": {
    "HonorableMention": [
      {"position":"QB","name":"Jake Retzlaff","school":"Brigham Young"},
      {"position":"QB","name":"Sawyer Robertson","school":"Baylor"},
      {"position":"QB","name":"Rocco Becht","school":"Iowa State"},
      {"position":"RB","name":"Quali Conley","school":"Arizona"},
      {"position":"RB","name":"LJ Martin","school":"Brigham Young"},
      {"position":"RB","name":"CJ Donaldson Jr.","school":"West Virginia"},
      {"position":"RB","name":"Carson Hansen","school":"Iowa State"},
      {"position":"RB","name":"Micah Bernard","school":"Utah"},
      {"position":"RB","name":"Jahiem White","school":"West Virginia"},
      {"position":"WR","name":"De’Zhaun Stribling","school":"Oklahoma State"},
      {"position":"WR","name":"Kobe Hudson","school":"Central Florida"},
      {"position":"WR","name":"Luke Grimm","school":"Kansas"},
      {"position":"WR","name":"Caleb Douglas","school":"Texas Tech"},
      {"position":"WR","name":"Xzavier Henderson","school":"Cincinnati"},
      {"position":"WR","name":"Dorian Singer","school":"Utah"},
      {"position":"WR","name":"Darius Lassiter","school":"Brigham Young"},
      {"position":"WR","name":"Eric McAlister","school":"TCU"},
      {"position":"WR","name":"JP Richardson","school":"TCU"},
      {"position":"TE","name":"Michael Trigg","school":"Baylor"},
      {"position":"TE","name":"Chamon Metayer","school":"Arizona State"},
      {"position":"TE","name":"Jalin Conyers","school":"Texas Tech"},
      {"position":"FLEX","name":"Cam Cook","school":"TCU"},
      {"position":"FLEX","name":"Brennan Presley","school":"Oklahoma State"},
      {"position":"FLEX","name":"Monaray Baldwin","school":"Baylor"},
      {"position":"OT","name":"Phillip Houston","school":"Colorado"},
      {"position":"OT","name":"Caleb Rogers","school":"Texas Tech"},
      {"position":"OT","name":"Max Iheanachor","school":"Arizona State"},
      {"position":"OG","name":"Kobe Baynes","school":"Kansas"},
      {"position":"OG","name":"Taylor Poitier","school":"Kansas State"},
      {"position":"OG","name":"Ryan Lengyel","school":"Baylor"},
      {"position":"OC","name":"Connor Pay","school":"Brigham Young"},
      {"position":"OC","name":"Sam Hecht","school":"Kansas State"},
      {"position":"OC","name":"Gavin Gerhardt","school":"Cincinnati"},
      {"position":"OG","name":"Michael Ford Jr.","school":"Kansas"},
      {"position":"OG","name":"Kahlil Benson","school":"Colorado"},
      {"position":"OG","name":"Carson Bruno","school":"TCU"},
      {"position":"OT","name":"John Williams","school":"Cincinnati"},
      {"position":"OT","name":"Amari Knight","school":"Central Florida"},
      {"position":"OT","name":"Carver Willis","school":"Kansas State"},
      { "position": "EDGE", "name": "Obi Ezeigbo", "school": "Oklahoma State" },
      { "position": "EDGE", "name": "Sean Martin", "school": "West Virginia" },
        { "position": "EDGE", "name": "Nyjalik Kelly", "school": "Central Florida" },
        { "position": "DT", "name": "Tommy Dunn Jr.", "school": "Kansas" },
        { "position": "DT", "name": "De’Braylon Carroll", "school": "Texas Tech" },
        { "position": "DT", "name": "Jackie Marshall", "school": "Baylor" },
        { "position": "DT", "name": "Jeff Clark", "school": "Arizona State" },
        { "position": "DT", "name": "Ta’ita’i Uiagalelei", "school": "Arizona" },
        { "position": "DT", "name": "Amari McNeill", "school": "Colorado" },
        { "position": "EDGE", "name": "Eric Phillips", "school": "Cincinnati" },
        { "position": "EDGE", "name": "Van Fillinger", "school": "Utah" },
        { "position": "EDGE", "name": "Logan Fano", "school": "Utah" },
        { "position": "LB", "name": "Caleb McCullough", "school": "Arizona State" },
        { "position": "LB", "name": "Deshawn Pace", "school": "Central Florida" },
        { "position": "LB", "name": "Cornell Wheeler", "school": "Kansas" },
        { "position": "LB", "name": "Ze’ree Alexander", "school": "Central Florida" },
        { "position": "LB", "name": "Johnny Hodges", "school": "TCU" },
        { "position": "LB", "name": "Namdi Obiazor", "school": "TCU" },
        { "position": "LB", "name": "Jacob Manu", "school": "Arizona" },
        { "position": "LB", "name": "Michael Batton", "school": "Houston" },
        { "position": "LB", "name": "Ben Roberts", "school": "Texas Tech" },
        { "position": "CB", "name": "Colton Hood", "school": "Colorado" },
        { "position": "CB", "name": "D.J. McKinney", "school": "Colorado" },
        { "position": "CB", "name": "Javan Robinson", "school": "Arizona State" },
        { "position": "CB", "name": "Korie Black", "school": "Oklahoma State" },
        { "position": "CB", "name": "Lorando Johnson", "school": "Baylor" },
        { "position": "CB", "name": "LaMareon James", "school": "TCU" },
        { "position": "CB", "name": "Jacob Parrish", "school": "Kansas State" },
        { "position": "CB", "name": "Tacario Davis", "school": "Arizona" },
        { "position": "CB", "name": "MacMcWilliams", "school": "Central Florida" },
        { "position": "SS", "name": "Owen Goss", "school": "Arizona" },
        { "position": "SS", "name": "Kendal Daniels", "school": "Oklahoma State" },
        { "position": "SS", "name": "VJ Payne", "school": "Kansas State" },
        { "position": "FS", "name": "CJ Baskerville", "school": "Texas Tech" },
        { "position": "FS", "name": "Anthony Wilson", "school": "West Virginia" },
        { "position": "FS", "name": "Devyn Bobby", "school": "Baylor" },
        { "position": "S", "name": "Carter Stoutmire", "school": "Colorado" },
        { "position": "S", "name": "Malik Verdon", "school": "Iowa State" },
        { "position": "S", "name": "Beau Freyler", "school": "Iowa State" },
        { "position": "FLEX", "name": "Genesis Smith", "school": "Arizona" },
        { "position": "FLEX", "name": "Smith Snowden", "school": "Utah" },
        { "position": "FLEX", "name": "Cameron Calhoun", "school": "Utah" },
        { "position": "PK", "name": "Alejandro Mata", "school": "Colorado" },
        { "position": "KOS", "name": "Jack Stone", "school": "Baylor" },
        { "position": "P", "name": "Ethan Craw", "school": "TCU" },
        { "position": "KR", "name": "Drae McCray", "school": "Texas Tech" },
        { "position": "PR", "name": "Dylan Edwards", "school": "Kansas State" },
        { "position": "ST", "name": "Trey Reynolds", "school": "Utah" }
    ]
  }
}
