"""CFN All-Mountain West Conference List 2024"""

ALL_MOUNTAIN_WEST = {
  "year": 2024,
  "name_of_award": "all_conference",
  "conference": "mountain_west",
  "source": "cfn",
  "mountain_west" : [
       {"award": "PlayerOfTheYear", "name": "Ashton Jeanty", "position": "RB", "school": "Boise State"},
  {"award": "OffensivePlayerOfTheYear", "name": "Ashton Jeanty", "position": "RB", "school": "Boise State"},
  {"award": "DefensivePlayerOfTheYear", "name": "Jalen Catalon", "position": "FS", "school": "UNLV"},
  {"award": "SpecialistOfTheYear", "name": "Jonah Dalmas", "position": "PK", "school": "Boise State"},
  {"award": "NewcomerOfTheYear", "name": "Jalen Catalon", "position": "FS", "school": "UNLV"},
  {"award": "CoachOfTheYear", "name": "Spencer Danielson", "position": "Coach", "school": "Boise State"},
  {"award": "ImpactFreshmanOfTheYear", "name": "Caden Chittenden", "position": "PK", "school": "UNLV"},
{"award": "QuarterbackOfTheYear", "name": "Maddux Madsen", "position": "QB", "school": "Boise State"},
  {"award": "RunningBackOfTheYear", "name": "Ashton Jeanty", "position": "RB", "school": "Boise State"},
  {"award": "WideReceiverOfTheYear", "name": "Nick Nash", "position": "WR-X", "school": "San Jose State"},
  {"award": "TightEndOfTheYear", "name": "Matt Lauter", "position": "TE", "school": "Boise State"},
  {"award": "OffensiveTackleOfTheYear", "name": "Kage Casey", "position": "LT", "school": "Boise State"},
  {"award": "OffensiveGuardOfTheYear", "name": "Ben Dooley", "position": "LG", "school": "Boise State"},
  {"award": "CenterOfTheYear", "name": "Jacob Gardner", "position": "C", "school": "Colorado State"},
  {"award": "OffensiveLinemanOfTheYear", "name": "Jacob Gardner", "position": "C", "school": "Colorado State"},
  {"award": "OffensiveLineOfTheYear", "name": "Boise State Broncos", "position": "OL Unit", "school": "Boise State"},
  {"award": "OffensiveNewcomerOfTheYear", "name": "Marquez Cooper", "position": "RB", "school": "San Diego State"},
  {"award": "OffensiveTransferOfTheYear", "name": "Marquez Cooper", "position": "RB", "school": "San Diego State"},
  {"award": "EdgeDefenderOfTheYear", "name": "Ahmed Hassanein", "position": "EDGE", "school": "Boise State"},
  {"award": "InteriorDefenderOfTheYear", "name": "Alex Whitmore", "position": "DT", "school": "UNLV"},
  {"award": "LinebackerOfTheYear", "name": "Jackson Woodard", "position": "MLB", "school": "UNLV"},
  {"award": "CornerbackOfTheYear", "name": "Michael Coats Jr.", "position": "LCB", "school": "Nevada"},
  {"award": "SafetyOfTheYear", "name": "Jalen Catalon", "position": "FS", "school": "UNLV"},
  {"award": "DefensiveLineOfTheYear", "name": "Boise State Broncos", "position": "DL Unit", "school": "Boise State"},
  {"award": "SecondaryOfTheYear", "name": "UNLV Rebels", "position": "Secondary Unit", "school": "UNLV"},
  {"award": "DefensiveNewcomerOfTheYear", "name": "Jalen Catalon", "position": "FS", "school": "UNLV"},
  {"award": "DefensiveTransferOfTheYear", "name": "Jalen Catalon", "position": "FS", "school": "UNLV"},
  {"award": "KickerOfTheYear", "name": "Jonah Dalmas", "position": "PK", "school": "Boise State"},
  {"award": "PunterOfTheYear", "name": "Tyler Pastula", "position": "PT", "school": "San Diego State"},
  {"award": "KickReturnerOfTheYear", "name": "Tyler King", "position": "KR", "school": "Wyoming"},
  {"award": "PuntReturnerOfTheYear", "name": "Jalen Moss", "position": "PR", "school": "Fresno State"},
  {"award": "SpecialTeamerOfTheYear", "name": "Cole Joyce", "position": "MLB", "school": "Utah State"},
  {"award": "KickoffSpecialistOfTheYear", "name": "Caden Chittenden", "position": "KO", "school": "UNLV"},
{"team": "1", "position": "QB", "name": "Maddux Madsen", "school": "Boise State"},
  {"team": "1", "position": "RB", "name": "Ashton Jeanty", "school": "Boise State"},
  {"team": "1", "position": "RB", "name": "Marquez Cooper", "school": "San Diego State"},
  {"team": "1", "position": "WR-X", "name": "Nick Nash", "school": "San Jose State"},
  {"team": "1", "position": "WR-X", "name": "Ricky White", "school": "UNLV"},
  {"team": "1", "position": "WR-X", "name": "Jaden Smith", "school": "Nevada"},
  {"team": "1", "position": "TE", "name": "Matt Lauter", "school": "Boise State"},
  {"team": "1", "position": "WR-X", "name": "Mac Delana", "school": "Fresno State"},
  {"team": "1", "position": "LT", "name": "Kage Casey", "school": "Boise State"},
  {"team": "1", "position": "LG", "name": "Ben Dooley", "school": "Boise State"},
  {"team": "1", "position": "C", "name": "Jacob Gardner", "school": "Colorado State"},
  {"team": "1", "position": "RG", "name": "Drew Moss", "school": "Colorado State"},
  {"team": "1", "position": "RG", "name": "Caden Barnett", "school": "Wyoming"},

  {"team": "1", "position": "EDGE", "name": "Ahmed Hassanein", "school": "Boise State"},
  {"team": "1", "position": "DT", "name": "Alex Whitmore", "school": "UNLV"},
  {"team": "1", "position": "NT", "name": "Soane Toia", "school": "San Jose State"},
  {"team": "1", "position": "RDE", "name": "Trey White", "school": "San Diego State"},
  {"team": "1", "position": "MLB", "name": "Jackson Woodard", "school": "UNLV"},
  {"team": "1", "position": "MLB", "name": "Shae Suiaunoa", "school": "Wyoming"},
  {"team": "1", "position": "MLB", "name": "Jordan Pollard", "school": "San Jose State"},
  {"team": "1", "position": "LCB", "name": "Michael Coats Jr.", "school": "Nevada"},
  {"team": "1", "position": "RCB", "name": "Cam Lockridge", "school": "Fresno State"},
  {"team": "1", "position": "LCB", "name": "Cameron Oliver", "school": "UNLV"},
  {"team": "1", "position": "SS", "name": "Robert Rahimi", "school": "San Jose State"},
  {"team": "1", "position": "FS", "name": "Jalen Catalon", "school": "UNLV"},
  {"team": "1", "position": "SS", "name": "Seyi Oladipo", "school": "Boise State"},
  {"team": "1", "position": "FCB", "name": "A’Marion McCoy", "school": "Boise State"},

  {"team": "1", "position": "PK", "name": "Jonah Dalmas", "school": "Boise State"},
  {"team": "1", "position": "KO", "name": "Caden Chittenden", "school": "UNLV"},
  {"team": "1", "position": "PT", "name": "Tyler Pastula", "school": "San Diego State"},
  {"team": "1", "position": "KR", "name": "Tyler King", "school": "Wyoming"},
  {"team": "1", "position": "PR", "name": "Jalen Moss", "school": "Fresno State"},
  {"team": "1", "position": "SS", "name": "Cole Joyce", "school": "Utah State"},
{"team": "2", "position": "QB", "name": "Devon Dampier", "school": "New Mexico"},
  {"team": "2", "position": "RB", "name": "Rahsul Faison", "school": "Utah State"},
  {"team": "2", "position": "RB", "name": "Eli Sanders", "school": "New Mexico"},
  {"team": "2", "position": "WR-Z", "name": "Justin Lockhart", "school": "San Jose State"},
  {"team": "2", "position": "WR-Z", "name": "Nick Cenacle", "school": "Hawaii"},
  {"team": "2", "position": "WR-X", "name": "Jalen Royals", "school": "Utah State"},
  {"team": "2", "position": "TE", "name": "Kaleo Ballungay", "school": "UNLV"},
  {"team": "2", "position": "WR-Z", "name": "Jalen Moss", "school": "Fresno State"},
  {"team": "2", "position": "OT", "name": "Braylen Nelson", "school": "Fresno State"},
  {"team": "2", "position": "RG", "name": "Mathyus Su’a", "school": "UNLV"},
  {"team": "2", "position": "C", "name": "Coston Cooley", "school": "Air Force"},
  {"team": "2", "position": "OG", "name": "Baraka Beckett", "school": "New Mexico"},
  {"team": "2", "position": "OT", "name": "Aaron Karas", "school": "Colorado State"},

  {"team": "2", "position": "EDGE", "name": "Gabe Kirschke", "school": "Colorado State"},
  {"team": "2", "position": "DT", "name": "Braxton Fely", "school": "Boise State"},
  {"team": "2", "position": "DT", "name": "Jacob Holmes", "school": "Fresno State"},
  {"team": "2", "position": "EDGE", "name": "Jayden Virgin-Morgan", "school": "Boise State"},
  {"team": "2", "position": "LB", "name": "Taniela Latu", "school": "San Jose State"},
  {"team": "2", "position": "LB", "name": "Andrew Simpson", "school": "Boise State"},
  {"team": "2", "position": "LB", "name": "Phoenix Jackson", "school": "Fresno State"},
  {"team": "2", "position": "CB", "name": "DJ Harvey", "school": "San Jose State"},
  {"team": "2", "position": "LCB", "name": "Johnathan Baldwin", "school": "UNLV"},
  {"team": "2", "position": "RCB", "name": "Cam Stone", "school": "Hawaii"},
  {"team": "2", "position": "SS", "name": "Tori Daffin", "school": "Nevada"},
  {"team": "2", "position": "FS", "name": "Jordan Vincent", "school": "Utah State"},
  {"team": "2", "position": "S", "name": "Wrook Brown", "school": "Wyoming"},
  {"team": "2", "position": "FLEX", "name": "Dom Jones", "school": "Colorado State"},

  {"team": "2", "position": "PK", "name": "John Hoyland", "school": "Wyoming"},
  {"team": "2", "position": "KO", "name": "John Hoyland", "school": "Wyoming"},
  {"team": "2", "position": "PT", "name": "Jack Culbreath", "school": "Wyoming"},
  {"team": "2", "position": "KR", "name": "Kobe Johnson", "school": "Colorado State"},
  {"team": "2", "position": "PR", "name": "Jacob De Jesus", "school": "UNLV"},
  {"team": "2", "position": "FS", "name": "Justin Sinclair", "school": "Hawaii"},
{"team": "3", "position": "QB", "name": "Hajj-Malik Williams", "school": "UNLV"},
  {"team": "3", "position": "RB", "name": "Jai’Den Thomas", "school": "UNLV"},
  {"team": "3", "position": "RB", "name": "Floyd Chalk IV", "school": "San Jose State"},
  {"team": "3", "position": "WR", "name": "Luke Wysong", "school": "New Mexico"},
  {"team": "3", "position": "WR", "name": "Cam Camper", "school": "Boise State"},
  {"team": "3", "position": "WR-SL", "name": "Pofele Ashlock", "school": "Hawaii"},
  {"team": "3", "position": "TE", "name": "Josh Sterzer", "school": "Utah State"},
  {"team": "3", "position": "FLEX", "name": "Avery Morrow", "school": "Colorado State"},
  {"team": "3", "position": "OT", "name": "Nate Williams", "school": "San Diego State"},
  {"team": "3", "position": "OG", "name": "Ross Ulugalu-Maseuli", "school": "San Diego State"},
  {"team": "3", "position": "OC", "name": "Zach Holmes", "school": "Boise State"},
  {"team": "3", "position": "OG", "name": "Josh Grabowski", "school": "Nevada"},
  {"team": "3", "position": "LT", "name": "Tiger Shanks", "school": "UNLV"},

  {"team": "3", "position": "EDGE", "name": "Devo Bridges", "school": "Fresno State"},
  {"team": "3", "position": "DT", "name": "Peyton Zdroik", "school": "Air Force"},
  {"team": "3", "position": "DT", "name": "Herbert Gums", "school": "Boise State"},
  {"team": "3", "position": "EDGE", "name": "Antonio Doyle Jr.", "school": "UNLV"},
  {"team": "3", "position": "LB", "name": "Malachi Langley", "school": "Fresno State"},
  {"team": "3", "position": "LB", "name": "Connor Shay", "school": "Wyoming"},
  {"team": "3", "position": "LB", "name": "Ayden Hector", "school": "Colorado State"},
  {"team": "3", "position": "CB", "name": "Julian Neal", "school": "Fresno State"},
  {"team": "3", "position": "CB", "name": "Alzillion Hamilton", "school": "Fresno State"},
  {"team": "3", "position": "CB", "name": "D.J. Graham II", "school": "Utah State"},
  {"team": "3", "position": "SS", "name": "Rodney Robinson", "school": "Boise State"},
  {"team": "3", "position": "FS", "name": "Kitan Crawford", "school": "Nevada"},
  {"team": "3", "position": "S", "name": "Ty Benefield", "school": "Boise State"},
  {"team": "3", "position": "FLEX", "name": "Ike Larsen", "school": "Utah State"},

  {"team": "3", "position": "PK", "name": "Caden Chittenden", "school": "UNLV"},
  {"team": "3", "position": "KO", "name": "Dylan Lynch", "school": "Fresno State"},
  {"team": "3", "position": "PT", "name": "Lucas Borrow", "school": "Hawaii"},
  {"team": "3", "position": "KR", "name": "Tylan Hines", "school": "Hawaii"},
  {"team": "3", "position": "PR", "name": "Kobe Johnson", "school": "Colorado State"},
  {"team": "3", "position": "ST", "name": "Justin Erb", "school": "Wyoming"},
 {"team": "honorable_mention", "position": "QB", "name": "Mikey Keene", "school": "Fresno State"},
  {"team": "honorable_mention", "position": "QB", "name": "Brendon Lewis", "school": "Nevada"},
  {"team": "honorable_mention", "position": "QB", "name": "Danny O’Neil", "school": "San Diego State"},
  {"team": "honorable_mention", "position": "RB", "name": "NaQuari Rogers", "school": "New Mexico"},
  {"team": "honorable_mention", "position": "RB", "name": "Kylin James", "school": "UNLV"},
  {"team": "honorable_mention", "position": "RB", "name": "Justin Marshall", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "RB", "name": "Elijah Gilliam", "school": "Fresno State"},
  {"team": "honorable_mention", "position": "RB", "name": "Savion Red", "school": "Nevada"},
  {"team": "honorable_mention", "position": "RB", "name": "Cade Harris", "school": "Air Force"},
  {"team": "honorable_mention", "position": "WR", "name": "Cortez Braham", "school": "Nevada"},
  {"team": "honorable_mention", "position": "WR", "name": "Marcus Bellon", "school": "Nevada"},
  {"team": "honorable_mention", "position": "WR", "name": "Louis Brown IV", "school": "San Diego State"},
  {"team": "honorable_mention", "position": "WR", "name": "Latrell Caples", "school": "Boise State"},
  {"team": "honorable_mention", "position": "WR", "name": "Caleb Goodie", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "WR-X", "name": "Jonah Panoke", "school": "Hawaii"},
  {"team": "honorable_mention", "position": "WR", "name": "Jordan Napier", "school": "San Diego State"},
  {"team": "honorable_mention", "position": "WR", "name": "Ja’Shaun Poke", "school": "San Diego State"},
  {"team": "honorable_mention", "position": "WR", "name": "Jaylen Sargent", "school": "Wyoming"},
  {"team": "honorable_mention", "position": "TE", "name": "Vince Brown II", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "TE", "name": "Jacob Stewart", "school": "San Jose State"},
  {"team": "honorable_mention", "position": "TE", "name": "John Michael Gyllenborg", "school": "Wyoming"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Otto Tia", "school": "Utah State"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Raylen Sharpe", "school": "Fresno State"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Jackson Canaan", "school": "San Jose State"},
  {"team": "honorable_mention", "position": "OT", "name": "Isaiah World", "school": "Nevada"},
  {"team": "honorable_mention", "position": "OT", "name": "Alex Moore", "school": "Air Force"},
  {"team": "honorable_mention", "position": "RG", "name": "Ka’ena Decambra", "school": "Hawaii"},
  {"team": "honorable_mention", "position": "OG", "name": "Richard Pearce", "school": "New Mexico"},
  {"team": "honorable_mention", "position": "OG", "name": "Michael McAninch", "school": "Air Force"},
  {"team": "honorable_mention", "position": "OG", "name": "Tyson Ruffins", "school": "Nevada"},
  {"team": "honorable_mention", "position": "C", "name": "Brayden Bryant", "school": "San Diego State"},
  {"team": "honorable_mention", "position": "C", "name": "Mose Vavao", "school": "Fresno State"},
  {"team": "honorable_mention", "position": "C", "name": "Jack Hasz", "school": "UNLV"},
  {"team": "honorable_mention", "position": "OG", "name": "Spencer Lovell", "school": "Nevada"},
  {"team": "honorable_mention", "position": "OG", "name": "Marist Talavou", "school": "San Jose State"},
  {"team": "honorable_mention", "position": "OG", "name": "Wyatt Bowles", "school": "Utah State"},
  {"team": "honorable_mention", "position": "RT", "name": "James Milovale", "school": "Hawaii"},
  {"team": "honorable_mention", "position": "OT", "name": "Saveyon Henderson", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "LG", "name": "Jalen St. John", "school": "UNLV"},
  {"team": "honorable_mention", "position": "RDE", "name": "Elijah Robinson", "school": "Hawaii"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Moso’oipala Tuitele", "school": "New Mexico"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Tyce Westland", "school": "Wyoming"},
  {"team": "honorable_mention", "position": "DT", "name": "Krishna Clay", "school": "San Diego State"},
  {"team": "honorable_mention", "position": "DT", "name": "Thomas Witte", "school": "Nevada"},
  {"team": "honorable_mention", "position": "NT", "name": "Dion Washington", "school": "Hawaii"},
  {"team": "honorable_mention", "position": "DT", "name": "Gafa Faga", "school": "San Jose State"},
  {"team": "honorable_mention", "position": "DT", "name": "Cam Bariteau", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "DT", "name": "Isaiah Bruce", "school": "Utah State"},
  {"team": "honorable_mention", "position": "BAN", "name": "Fisher Camac", "school": "UNLV"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Cian Slone", "school": "Utah State"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Kristopher Ross", "school": "Nevada"},
  {"team": "honorable_mention", "position": "LB", "name": "Drue Watts", "school": "Nevada"},
  {"team": "honorable_mention", "position": "LB", "name": "Kyle Moretti", "school": "San Diego State"},
  {"team": "honorable_mention", "position": "MLB", "name": "Logan Taylor", "school": "Hawaii"},
  {"team": "honorable_mention", "position": "LB", "name": "Randolph Kpai", "school": "New Mexico"},
  {"team": "honorable_mention", "position": "LB", "name": "Dimitri Johnson", "school": "New Mexico"},
  {"team": "honorable_mention", "position": "LB", "name": "Chase Wilson", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "LB", "name": "Tuasivi Nomura", "school": "Fresno State"},
  {"team": "honorable_mention", "position": "LB", "name": "John Miller", "school": "Utah State"},
  {"team": "honorable_mention", "position": "LB", "name": "Buom Jock", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "CB", "name": "Bryson Taylor", "school": "New Mexico"},
  {"team": "honorable_mention", "position": "CB", "name": "Noa Pola‑Gates", "school": "New Mexico"},
  {"team": "honorable_mention", "position": "CB", "name": "Keany Parks", "school": "Wyoming"},
  {"team": "honorable_mention", "position": "LCB", "name": "Caleb Brown", "school": "Hawaii"},
  {"team": "honorable_mention", "position": "CB", "name": "Dominic Morris", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "CB", "name": "Trey Williams", "school": "Air Force"},
  {"team": "honorable_mention", "position": "RCB", "name": "Elijah Palmer", "school": "Hawaii"},
  {"team": "honorable_mention", "position": "CB", "name": "Jeremiah Earby", "school": "Boise State"},
  {"team": "honorable_mention", "position": "LCB", "name": "Jamari Bellamy", "school": "Air Force"},
  {"team": "honorable_mention", "position": "FS", "name": "Eric Butler", "school": "San Diego State"},
  {"team": "honorable_mention", "position": "SS", "name": "Jack Howell", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "SS", "name": "Jett Elad", "school": "UNLV"},
  {"team": "honorable_mention", "position": "FS", "name": "Isiah Revis", "school": "San Jose State"},
  {"team": "honorable_mention", "position": "FS", "name": "Dean Clark", "school": "Fresno State"},
  {"team": "honorable_mention", "position": "FS", "name": "Kilinahe Mendiola‑Jansen", "school": "Hawaii"},
  {"team": "honorable_mention", "position": "FCB", "name": "Noah Avinger", "school": "New Mexico"},
  {"team": "honorable_mention", "position": "SS", "name": "Nigel Williams", "school": "New Mexico"},
  {"team": "honorable_mention", "position": "FS", "name": "Camby Goff", "school": "Air Force"},
  {"team": "honorable_mention", "position": "NB", "name": "Christian Ellis", "school": "New Mexico"},
  {"team": "honorable_mention", "position": "FS", "name": "Houston Hendrix", "school": "Air Force"},
  {"team": "honorable_mention", "position": "FCB", "name": "Michael Dansby", "school": "San Jose State"},
  {"team": "honorable_mention", "position": "PK", "name": "Jordan Noyes", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "KO", "name": "Elliott Nimrod", "school": "Utah State"},
  {"team": "honorable_mention", "position": "PT", "name": "Guy Gillespie", "school": "Nevada"},
  {"team": "honorable_mention", "position": "KR", "name": "Ja’Shaun Poke", "school": "San Diego State"},
  {"team": "honorable_mention", "position": "PR", "name": "Tory Horton", "school": "Colorado State"},
  {"team": "honorable_mention", "position": "SS", "name": "Aedan Seiuli", "school": "Nevada"}
  ]
}
