"""CFN All-Big Ten List"""


ALL_BIG_TEN = {
  "year": 2024,
  "name_of_award": "all_conference",
  "conference": "big_ten",
  "source": "cfn",
  "big_ten" : [
      {
    "name": "Derrick Harmon",
    "position": "DT",
    "school": "Oregon",
    "award": "PlayerOfTheYear"
  },
  {
    "name": "Kaleb Johnson",
    "position": "RB",
    "school": "Iowa",
    "award": "OffensivePlayerOfTheYear"
  },
  {
    "name": "Derrick Harmon",
    "position": "DT",
    "school": "Oregon",
    "award": "DefensivePlayerOfTheYear"
  },
  {
    "name": "Dominic Zvada",
    "position": "PK",
    "school": "Michigan",
    "award": "SpecialistOfTheYear"
  },
  {
    "name": "Jeremiah Smith",
    "position": "WR-X",
    "school": "Ohio State",
    "award": "NewcomerOfTheYear"
  },
  {
    "name": "Curt Cignetti",
    "position": "Coach",
    "school": "Indiana",
    "award": "CoachOfTheYear"
  },
  {
    "name": "Jeremiah Smith",
    "position": "WR-X",
    "school": "Ohio State",
    "award": "ImpactFreshmanOfTheYear"
  },
  {"name": "Kurtis Rourke", "position": "QB", "school": "Indiana", "award": "QuarterbackOfTheYear"},
  {"name": "Kaleb Johnson", "position": "RB", "school": "Iowa", "award": "RunningBackOfTheYear"},
  {"name": "Tai Felton", "position": "WR", "school": "Maryland", "award": "WideReceiverOfTheYear"},
  {"name": "Tyler Warren", "position": "TE", "school": "Penn State", "award": "TightEndOfTheYear"},
  {"name": "Hollin Pierce", "position": "LT", "school": "Rutgers", "award": "OffensiveTackleOfTheYear"},
  {"name": "Nishad Strother", "position": "LG", "school": "Oregon", "award": "OffensiveGuardOfTheYear"},
  {"name": "Mike Katic", "position": "C", "school": "Indiana", "award": "CenterOfTheYear"},
  {"name": "Hollin Pierce", "position": "LT", "school": "Rutgers", "award": "OffensiveLinemanOfTheYear"},
  {"name": "Oregon Ducks", "position": "OL Unit", "school": "Oregon", "award": "OffensiveLineOfTheYear"},
  {"name": "Jeremiah Smith", "position": "WR-X", "school": "Ohio State", "award": "OffensiveNewcomerOfTheYear"},
  {"name": "Kurtis Rourke", "position": "QB", "school": "Indiana", "award": "OffensiveTransferOfTheYear"},
  {"name": "Mikail Kamara", "position": "STUD", "school": "Indiana", "award": "EdgeDefenderOfTheYear"},
  {"name": "Derrick Harmon", "position": "DT", "school": "Oregon", "award": "InteriorDefenderOfTheYear"},
  {"name": "Jay Higgins", "position": "MLB", "school": "Iowa", "award": "LinebackerOfTheYear"},
  {"name": "Xavier Scott", "position": "NB", "school": "Illinois", "award": "CornerbackOfTheYear"},
  {"name": "Tysheem Johnson", "position": "SS", "school": "Oregon", "award": "SafetyOfTheYear"},
  {"name": "Indiana Hoosiers", "position": "DL Unit", "school": "Indiana", "award": "DefensiveLineOfTheYear"},
  {"name": "Illinois Fighting Illini", "position": "DL Unit", "school": "Illinois", "award": "DefensiveNewcomerOfTheYear"},
  {"name": "Mikail Kamara", "position": "STUD", "school": "Indiana", "award": "DefensiveTransferOfTheYear"},
  {"name": "Dominic Zvada", "position": "PK", "school": "Michigan", "award": "KickerOfTheYear"},
  {"name": "Rhys Dakin", "position": "PT", "school": "Iowa", "award": "PunterOfTheYear"},
  {"name": "Kaden Wetjen", "position": "KR", "school": "Iowa", "award": "KickReturnerOfTheYear"},
  {"name": "Kaden Wetjen", "position": "PR", "school": "Iowa", "award": "PuntReturnerOfTheYear"},
  {"name": "Bryson Bonds", "position": "SS", "school": "Indiana", "award": "SpecialTeamerOfTheYear"},
  {"name": "Dragan Kesich", "position": "KO", "school": "Minnesota", "award": "KickoffSpecialistOfTheYear"},
   {"name": "Kurtis Rourke", "position": "QB", "school": "Indiana", "team": 1},
  {"name": "Kaleb Johnson", "position": "RB", "school": "Iowa", "team": 1},
  {"name": "Jordan James", "position": "RB", "school": "Oregon", "team": 1},
  {"name": "Tai Felton", "position": "WR-X", "school": "Maryland", "team": 1},
  {"name": "Jeremiah Smith", "position": "WR-X", "school": "Ohio State", "team": 1},
  {"name": "Pat Bryant", "position": "WR-X", "school": "Illinois", "team": 1},
  {"name": "Tyler Warren", "position": "TE", "school": "Penn State", "team": 1},
  {"name": "Tez Johnson", "position": "WR-X", "school": "Oregon", "team": 1},
  {"name": "Hollin Pierce", "position": "LT", "school": "Rutgers", "team": 1},
  {"name": "Nishad Strother", "position": "LG", "school": "Oregon", "team": 1},
  {"name": "Mike Katic", "position": "C", "school": "Indiana", "team": 1},
  {"name": "Emmanuel Pregnon", "position": "LG", "school": "USC", "team": 1},
  {"name": "Josh Conerly Jr.", "position": "LT", "school": "Oregon", "team": 1},

  {"name": "Mikail Kamara", "position": "STUD", "school": "Indiana", "team": 1},
  {"name": "Derrick Harmon", "position": "DT", "school": "Oregon", "team": 1},
  {"name": "Mason Graham", "position": "DT", "school": "Michigan", "team": 1},
  {"name": "Abdul Carter", "position": "RDE", "school": "Penn State", "team": 1},
  {"name": "Carson Schwesinger", "position": "MLB", "school": "UCLA", "team": 1},
  {"name": "Jailin Walker", "position": "MAC", "school": "Indiana", "team": 1},
  {"name": "Jay Higgins", "position": "MLB", "school": "Iowa", "team": 1},
  {"name": "Xavier Scott", "position": "NB", "school": "Illinois", "team": 1},
  {"name": "Torrie Cox Jr.", "position": "LCB", "school": "Illinois", "team": 1},
  {"name": "D’Angelo Ponds", "position": "LCB", "school": "Indiana", "team": 1},
  {"name": "Tysheem Johnson", "position": "SS", "school": "Oregon", "team": 1},
  {"name": "Jaylen Reed", "position": "FS", "school": "Penn State", "team": 1},
  {"name": "Lathan Ransom", "position": "SS", "school": "Ohio State", "team": 1},
  {"name": "Aiden Fisher", "position": "MLB", "school": "Indiana", "team": 1},

  {"name": "Dominic Zvada", "position": "PK", "school": "Michigan", "team": 1},
  {"name": "Dragan Kesich", "position": "KO", "school": "Minnesota", "team": 1},
  {"name": "Rhys Dakin", "position": "PT", "school": "Iowa", "team": 1},
  {"name": "Kaden Wetjen", "position": "KR", "school": "Iowa", "team": 1},
  {"name": "Kaden Wetjen", "position": "PR", "school": "Iowa", "team": 1},
  {"name": "Bryson Bonds", "position": "SS", "school": "Indiana", "team": 1},
 {"name": "Dillon Gabriel", "position": "QB", "school": "Oregon", "team": 2},
  {"name": "Kyle Monangai", "position": "RB", "school": "Rutgers", "team": 2},
  {"name": "Kalel Mullings", "position": "RB", "school": "Michigan", "team": 2},
  {"name": "Elijah Sarratt", "position": "WR-X", "school": "Indiana", "team": 2},
  {"name": "Denzel Boston", "position": "WR-X", "school": "Washington", "team": 2},
  {"name": "Emeka Egbuka", "position": "WR-Z", "school": "Ohio State", "team": 2},
  {"name": "Colston Loveland", "position": "TE", "school": "Michigan", "team": 2},
  {"name": "Harrison Wallace III", "position": "WR-Z", "school": "Penn State", "team": 2},
  {"name": "Aireontae Ersery", "position": "LT", "school": "Minnesota", "team": 2},
  {"name": "Olaivavega Ioane", "position": "LG", "school": "Penn State", "team": 2},
  {"name": "Logan Jones", "position": "C", "school": "Iowa", "team": 2},
  {"name": "Connor Colby", "position": "RG", "school": "Iowa", "team": 2},
  {"name": "Gennings Dunker", "position": "RT", "school": "Iowa", "team": 2},

  {"name": "Gabe Jacas", "position": "LOLB", "school": "Illinois", "team": 2},
  {"name": "James Carpenter", "position": "DT", "school": "Indiana", "team": 2},
  {"name": "Kenneth Grant", "position": "DT", "school": "Michigan", "team": 2},
  {"name": "Jack Sawyer", "position": "DE", "school": "Ohio State", "team": 2},
  {"name": "Kydran Jenkins", "position": "MLB", "school": "Purdue", "team": 2},
  {"name": "Daniel Djabome", "position": "MLB", "school": "Rutgers", "team": 2},
  {"name": "Carson Bruener", "position": "MLB", "school": "Washington", "team": 2},
  {"name": "Malcolm Hartzog", "position": "NB", "school": "Nebraska", "team": 2},
  {"name": "Ethan Robinson", "position": "LCB", "school": "Minnesota", "team": 2},
  {"name": "Charles Brantley", "position": "NB", "school": "Michigan State", "team": 2},
  {"name": "Nikai Martinez", "position": "SS", "school": "Michigan State", "team": 2},
  {"name": "Koi Perich", "position": "FS", "school": "Minnesota", "team": 2},
  {"name": "Dillon Thieneman", "position": "SS", "school": "Purdue", "team": 2},
  {"name": "Caleb Downs", "position": "FS", "school": "Ohio State", "team": 2},

  {"name": "Drew Stevens", "position": "PK", "school": "Iowa", "team": 2},
  {"name": "Atticus Sappington", "position": "KO", "school": "Oregon", "team": 2},
  {"name": "Eddie Czaplicki", "position": "PT", "school": "USC", "team": 2},
  {"name": "Joseph Himon II", "position": "KR", "school": "Northwestern", "team": 2},
  {"name": "Tez Johnson", "position": "PR", "school": "Oregon", "team": 2},
  {"name": "Isaiah Jones", "position": "MLB", "school": "Indiana", "team": 2},
 {"name": "Drew Allar", "position": "QB", "school": "Penn State", "team": 3},
  {"name": "Jonah Coleman", "position": "RB", "school": "Washington", "team": 3},
  {"name": "Woody Marks", "position": "RB", "school": "USC", "team": 3},
  {"name": "Nick Marsh", "position": "WR-X", "school": "Michigan State", "team": 3},
  {"name": "Daniel Jackson", "position": "WR-Z", "school": "Minnesota", "team": 3},
  {"name": "Dymere Miller", "position": "WR-SL", "school": "Rutgers", "team": 3},
  {"name": "Terrance Ferguson", "position": "TE", "school": "Oregon", "team": 3},
  {"name": "Kaden Prather", "position": "WR-X", "school": "Maryland", "team": 3},
  {"name": "Marcus Mbow", "position": "LT", "school": "Purdue", "team": 3},
  {"name": "Josh Thompson", "position": "RT", "school": "Northwestern", "team": 3},
  {"name": "Jonah Monheim", "position": "C", "school": "USC", "team": 3},
  {"name": "Tyler Cooper", "position": "RG", "school": "Minnesota", "team": 3},
  {"name": "Caleb Tiernan", "position": "RT", "school": "Northwestern", "team": 3},

  {"name": "Josaiah Stewart", "position": "DE", "school": "Michigan", "team": 3},
  {"name": "Aaron Graves", "position": "LDT", "school": "Iowa", "team": 3},
  {"name": "Ty Robinson", "position": "NT", "school": "Nebraska", "team": 3},
  {"name": "Matayo Uiagalelei", "position": "DE", "school": "Oregon", "team": 3},
  {"name": "Cody Lindenberg", "position": "MLB", "school": "Minnesota", "team": 3},
  {"name": "Ernest Hausmann", "position": "MLB", "school": "Michigan", "team": 3},
  {"name": "Kain Medrano", "position": "MLB", "school": "UCLA", "team": 3},
  {"name": "Nikko Reed", "position": "BCB", "school": "Oregon", "team": 3},
  {"name": "Justin Walley", "position": "CB", "school": "Minnesota", "team": 3},
  {"name": "Zeke Berry", "position": "CB", "school": "Michigan", "team": 3},
  {"name": "Kobe Savage", "position": "SS", "school": "Oregon", "team": 3},
  {"name": "Quinn Schulte", "position": "FS", "school": "Iowa", "team": 3},
  {"name": "Miles Scott", "position": "S", "school": "Illinois", "team": 3},
  {"name": "Cody Simon", "position": "FLEX", "school": "Ohio State", "team": 3},

  {"name": "Mateen Bhaghani", "position": "PK", "school": "UCLA", "team": 3},
  {"name": "Michael Lantz", "position": "KOS", "school": "USC", "team": 3},
  {"name": "Atticus Bertrams", "position": "P", "school": "Wisconsin", "team": 3},
  {"name": "Makai Lemon", "position": "KR", "school": "USC", "team": 3},
  {"name": "Caleb Downs", "position": "PR", "school": "Ohio State", "team": 3},
  {"name": "Braydon Brus", "position": "ST", "school": "Northwestern", "team": 3},
  {"name": "Will Howard", "position": "QB", "school": "Ohio State", "team": "honorable_mention"},
  {"name": "Billy Edwards", "position": "QB", "school": "Maryland", "team": "honorable_mention"},
  {"name": "Luke Altmyer", "position": "QB", "school": "Illinois", "team": "honorable_mention"},
  {"name": "Darius Taylor", "position": "RB", "school": "Minnesota", "team": "honorable_mention"},
  {"name": "Dante Dowdell", "position": "RB", "school": "Nebraska", "team": "honorable_mention"},
  {"name": "Justice Ellison", "position": "RB", "school": "Indiana", "team": "honorable_mention"},
  {"name": "Ty Son Lawton", "position": "RB", "school": "Indiana", "team": "honorable_mention"},
  {"name": "Kaytron Allen", "position": "RB", "school": "Penn State", "team": "honorable_mention"},
  {"name": "Nicholas Singleton", "position": "RB", "school": "Penn State", "team": "honorable_mention"},
  {"name": "Giles Jackson", "position": "WR", "school": "Washington", "team": "honorable_mention"},
  {"name": "Vinny Anthony II", "position": "WR", "school": "Wisconsin", "team": "honorable_mention"},
  {"name": "Zakhari Franklin", "position": "WR", "school": "Illinois", "team": "honorable_mention"},
  {"name": "Carnell Tate", "position": "WR", "school": "Ohio State", "team": "honorable_mention"},
  {"name": "Omar Cooper Jr.", "position": "WR", "school": "Indiana", "team": "honorable_mention"},
  {"name": "Bryce Kirtz", "position": "WR", "school": "Northwestern", "team": "honorable_mention"},
  {"name": "Evan Stewart", "position": "WR", "school": "Oregon", "team": "honorable_mention"},
  {"name": "Makai Lemon", "position": "WR", "school": "USC", "team": "honorable_mention"},
  {"name": "Traeshon Holden", "position": "WR", "school": "Oregon", "team": "honorable_mention"},
  {"name": "Jameson Geers", "position": "TE", "school": "Minnesota", "team": "honorable_mention"},
  {"name": "Zach Horton", "position": "TE", "school": "Indiana", "team": "honorable_mention"},
  {"name": "Max Klare", "position": "TE", "school": "Purdue", "team": "honorable_mention"},
  {"name": "TreVeyon Henderson", "position": "FLEX", "school": "Ohio State", "team": "honorable_mention"},
  {"name": "Quinshon Judkins", "position": "FLEX", "school": "Ohio State", "team": "honorable_mention"},
  {"name": "Tawee Walker", "position": "FLEX", "school": "Wisconsin", "team": "honorable_mention"},
  {"name": "Ajani Cornelius", "position": "OT", "school": "Oregon", "team": "honorable_mention"},
  {"name": "Bryce Benhart", "position": "OT", "school": "Nebraska", "team": "honorable_mention"},
  {"name": "Trey Wedig", "position": "OT", "school": "Indiana", "team": "honorable_mention"},
  {"name": "Luke Newman", "position": "OG", "school": "Michigan State", "team": "honorable_mention"},
  {"name": "Josh Priebe", "position": "OG", "school": "Michigan", "team": "honorable_mention"},
  {"name": "Sal Wormley", "position": "OG", "school": "Penn State", "team": "honorable_mention"},
  {"name": "Gus Hartwig", "position": "OC", "school": "Purdue", "team": "honorable_mention"},
  {"name": "Seth McLaughlin", "position": "OC", "school": "Ohio State", "team": "honorable_mention"},
  {"name": "Iapani Laloulu", "position": "OC", "school": "Oregon", "team": "honorable_mention"},
  {"name": "Kwabena Asamoah", "position": "OG", "school": "Rutgers", "team": "honorable_mention"},
  {"name": "Justin Evans-Jenkins", "position": "OG", "school": "Nebraska", "team": "honorable_mention"},
  {"name": "Drew Evans", "position": "OG", "school": "Indiana", "team": "honorable_mention"},
  {"name": "Quinn Carroll", "position": "OT", "school": "Minnesota", "team": "honorable_mention"},
  {"name": "Carter Smith", "position": "OT", "school": "Indiana", "team": "honorable_mention"},
  {"name": "Anthony Donkoh", "position": "OT", "school": "Penn State", "team": "honorable_mention"},
  {"name": "Teitum Tuioti", "position": "EDGE", "school": "Oregon", "team": "honorable_mention"},
  {"name": "Oluwafemi Oladejo", "position": "EDGE", "school": "UCLA", "team": "honorable_mention"},
  {"name": "Max Llewellyn", "position": "EDGE", "school": "Iowa", "team": "honorable_mention"},
  {"name": "Anthony Smith", "position": "DT", "school": "Minnesota", "team": "honorable_mention"},
  {"name": "TeRah Edwards", "position": "DT", "school": "Illinois", "team": "honorable_mention"},
  {"name": "Dennis Briggs Jr.", "position": "DT", "school": "Illinois", "team": "honorable_mention"},
  {"name": "CJ West", "position": "DT", "school": "Indiana", "team": "honorable_mention"},
  {"name": "Zane Durant", "position": "DT", "school": "Penn State", "team": "honorable_mention"},
  {"name": "Kyonte Hamilton", "position": "DT", "school": "Rutgers", "team": "honorable_mention"},
  {"name": "Dani Dennis-Sutton", "position": "DT", "school": "Penn State", "team": "honorable_mention"},
  {"name": "JT Tuimoloau", "position": "DT", "school": "Ohio State", "team": "honorable_mention"},
  {"name": "Jah Joyner", "position": "DT", "school": "Minnesota", "team": "honorable_mention"},
  {"name": "Mac Uihlein", "position": "LB", "school": "Northwestern", "team": "honorable_mention"},
  {"name": "Tony Rojas", "position": "LB", "school": "Penn State", "team": "honorable_mention"},
  {"name": "Bryce Boettcher", "position": "LB", "school": "Oregon", "team": "honorable_mention"},
  {"name": "Kobe King", "position": "LB", "school": "Penn State", "team": "honorable_mention"},
  {"name": "Alphonzo Tuputala", "position": "LB", "school": "Washington", "team": "honorable_mention"},
  {"name": "Jaishawn Barham", "position": "LB", "school": "Michigan", "team": "honorable_mention"},
  {"name": "Rolijah Hardy", "position": "LB", "school": "Indiana", "team": "honorable_mention"},
  {"name": "Mason Cobb", "position": "LB", "school": "USC", "team": "honorable_mention"},
  {"name": "Easton Mascarenas-Arnold", "position": "LB", "school": "USC", "team": "honorable_mention"},
  {"name": "Will Johnson", "position": "CB", "school": "Michigan", "team": "honorable_mention"},
  {"name": "Jermari Harris", "position": "CB", "school": "Iowa", "team": "honorable_mention"},
  {"name": "A.J. Harris", "position": "CB", "school": "Penn State", "team": "honorable_mention"},
  {"name": "Kaylin Moore", "position": "CB", "school": "UCLA", "team": "honorable_mention"},
  {"name": "Jabbar Muhammad", "position": "CB", "school": "Oregon", "team": "honorable_mention"},
  {"name": "Bo Mascoe", "position": "CB", "school": "Rutgers", "team": "honorable_mention"},
  {"name": "Thaddeus Dixon", "position": "CB", "school": "Washington", "team": "honorable_mention"},
  {"name": "Greedy Vance Jr.", "position": "CB", "school": "USC", "team": "honorable_mention"},
  {"name": "Robert Longerbeam", "position": "CB", "school": "Rutgers", "team": "honorable_mention"},
  {"name": "Antonio Stevens", "position": "SS", "school": "Purdue", "team": "honorable_mention"},
  {"name": "DeShon Singleton", "position": "SS", "school": "Nebraska", "team": "honorable_mention"},
  {"name": "Matthew Bailey", "position": "SS", "school": "Illinois", "team": "honorable_mention"},
  {"name": "Zakee Wheatley", "position": "FS", "school": "Penn State", "team": "honorable_mention"},
  {"name": "Quinten Johnson", "position": "FS", "school": "Michigan", "team": "honorable_mention"},
  {"name": "Bryan Addison", "position": "FS", "school": "UCLA", "team": "honorable_mention"},
  {"name": "Dante Trader Jr.", "position": "S", "school": "Maryland", "team": "honorable_mention"},
  {"name": "Jalen Huskey", "position": "S", "school": "Maryland", "team": "honorable_mention"},
  {"name": "Hunter Wohler", "position": "S", "school": "Wisconsin", "team": "honorable_mention"},
  {"name": "Sonny Styles", "position": "FLEX", "school": "Ohio State", "team": "honorable_mention"},
  {"name": "Kamren Fabiculanan", "position": "FLEX", "school": "Washington", "team": "honorable_mention"},
  {"name": "Glendon Miller", "position": "FLEX", "school": "Maryland", "team": "honorable_mention"},
  {"name": "Jonathan Kim", "position": "PK", "school": "Michigan State", "team": "honorable_mention"},
  {"name": "Tommy Doman", "position": "KOS", "school": "Michigan", "team": "honorable_mention"},
  {"name": "Bryce McFerson", "position": "P", "school": "Maryland", "team": "honorable_mention"},
  {"name": "Nicholas Singleton", "position": "KR", "school": "Penn State", "team": "honorable_mention"},
  {"name": "Hank Beatty", "position": "PR", "school": "Illinois", "team": "honorable_mention"},
  {"name": "Zion Tracy", "position": "ST", "school": "Penn State", "team": "honorable_mention"}
  ]
}
