"""CFN All-Sun Belt List 2024"""

ALL_SUN_BELT = {
  "year": 2024,
  "name_of_award": "all_conference",
  "conference": "sun_belt",
  "source": "cfn",
  "sun_belt" : [
       {"name":"Mike Green","position":"RDE","school":"Marshall","award":"PlayerOfTheYear"},
      {"name":"Tellek Lockette","position":"RG","school":"Texas State","award":"OffensivePlayerOfTheYear"},
      {"name":"Mike Green","position":"RDE","school":"Marshall","award":"DefensivePlayerOfTheYear"},
      {"name":"Kenneth Almendares","position":"PK","school":"Louisiana","award":"SpecialistOfTheYear"},
      {"name":"Fluff Bothwell","position":"RB","school":"South Alabama","award":"NewcomerOfTheYear"},
      {"name":"Bryant Vincent","position":"Coach","school":"Louisiana Monroe","award":"CoachOfTheYear"},
      {"name":"Fluff Bothwell","position":"RB","school":"South Alabama","award":"ImpactFreshmanOfTheYear"},
{"name":"Jordan McCloud","position":"QB","school":"Texas State","award":"QuarterbackOfTheYear"},
  {"name":"Ahmad Hardy","position":"RB","school":"Louisiana Monroe","award":"RunningBackOfTheYear"},
  {"name":"Jamaal Pritchett","position":"WR-X","school":"South Alabama","award":"WideReceiverOfTheYear"},
  {"name":"Terrance Carter","position":"TE","school":"Louisiana","award":"TightEndOfTheYear"},
  {"name":"Alex Harkey","position":"RT","school":"Texas State","award":"OffensiveTackleOfTheYear"},
  {"name":"Tellek Lockette","position":"RG","school":"Texas State","award":"OffensiveGuardOfTheYear"},
  {"name":"Tanner Morris","position":"C","school":"James Madison","award":"CenterOfTheYear"},
  {"name":"Tellek Lockette","position":"RG","school":"Texas State","award":"OffensiveLinemanOfTheYear"},
  {"name":"Texas State Bobcats","position":"OL Unit","school":"Texas State","award":"OffensiveLineOfTheYear"},
  {"name":"Fluff Bothwell","position":"RB","school":"South Alabama","award":"OffensiveNewcomerOfTheYear"},
  {"name":"Jordan McCloud","position":"QB","school":"Texas State","award":"OffensiveTransferOfTheYear"},
  {"name":"Mike Green","position":"RDE","school":"Marshall","award":"EdgeDefenderOfTheYear"},
  {"name":"Santana Hopper","position":"DE","school":"Appalachian State","award":"InteriorDefenderOfTheYear"},
  {"name":"Jaden Yates","position":"WLB","school":"Marshall","award":"LinebackerOfTheYear"},
  {"name":"Josh Moten","position":"RCB","school":"Marshall","award":"CornerbackOfTheYear"},
  {"name":"Travor Randle","position":"SS","school":"Louisiana Monroe","award":"SafetyOfTheYear"},
  {"name":"JMU Dukes","position":"DL Unit","school":"James Madison","award":"DefensiveLineOfTheYear"},
  {"name":"Marshall Thundering Herd","position":"Secondary Unit","school":"Marshall","award":"SecondaryOfTheYear"},
  {"name":"Eric O’Neill","position":"LDE","school":"James Madison","award":"DefensiveNewcomerOfTheYear"},
  {"name":"Eric O’Neill","position":"LDE","school":"James Madison","award":"DefensiveTransferOfTheYear"},
  {"name":"Kenneth Almendares","position":"PK","school":"Louisiana","award":"KickerOfTheYear"},
  {"name":"Ryan Heicher","position":"PT","school":"Arkansas State","award":"PunterOfTheYear"},
  {"name":"Robert Williams","position":"KR","school":"Louisiana","award":"KickReturnerOfTheYear"},
  {"name":"Courtney Jackson","position":"PR","school":"Arkansas State","award":"PuntReturnerOfTheYear"},
  {"name":"Dalen Cambre","position":"WR-Z","school":"Louisiana","award":"SpecialTeamerOfTheYear"},
  {"name":"Brendan Franke","position":"KO","school":"Texas State","award":"KickoffSpecialistOfTheYear"},
{"team": "1", "unit": "Offense", "position": "QB", "name": "Jordan McCloud", "school": "Texas State"},
  {"team": "1", "unit": "Offense", "position": "RB", "name": "Ahmad Hardy", "school": "Louisiana Monroe"},
  {"team": "1", "unit": "Offense", "position": "RB", "name": "Fluff Bothwell", "school": "South Alabama"},
  {"team": "1", "unit": "Offense", "position": "WR-X", "name": "Jamaal Pritchett", "school": "South Alabama"},
  {"team": "1", "unit": "Offense", "position": "WR-Z", "name": "Devonte Ross", "school": "Troy"},
  {"team": "1", "unit": "Offense", "position": "WR-X", "name": "Ted Hurst", "school": "Georgia State"},
  {"team": "1", "unit": "Offense", "position": "TE", "name": "Terrance Carter", "school": "Louisiana"},
  {"team": "1", "unit": "Offense", "position": "TE", "name": "Dorian Fleming", "school": "Georgia State"},
  {"team": "1", "unit": "Offense", "position": "RT", "name": "Alex Harkey", "school": "Texas State"},
  {"team": "1", "unit": "Offense", "position": "RG", "name": "Tellek Lockette", "school": "Texas State"},
  {"team": "1", "unit": "Offense", "position": "C", "name": "Tanner Morris", "school": "James Madison"},
  {"team": "1", "unit": "Offense", "position": "LG", "name": "AJ Gillie", "school": "Louisiana"},
  {"team": "1", "unit": "Offense", "position": "RT", "name": "Pat McMurtrie", "school": "James Madison"},
  {"team": "1", "unit": "Defense", "position": "RDE", "name": "Mike Green", "school": "Marshall"},
  {"team": "1", "unit": "Defense", "position": "DE", "name": "Santana Hopper", "school": "Appalachian State"},
  {"team": "1", "unit": "Defense", "position": "DT", "name": "Mason Narcisse", "school": "Louisiana"},
  {"team": "1", "unit": "Defense", "position": "LDE", "name": "Eric O’Neill", "school": "James Madison"},
  {"team": "1", "unit": "Defense", "position": "WLB", "name": "Jaden Yates", "school": "Marshall"},
  {"team": "1", "unit": "Defense", "position": "MLB", "name": "K.C. Ossai", "school": "Louisiana"},
  {"team": "1", "unit": "Defense", "position": "WLB", "name": "Mario Thompson", "school": "Old Dominion"},
  {"team": "1", "unit": "Defense", "position": "RCB", "name": "Josh Moten", "school": "Marshall"},
  {"team": "1", "unit": "Defense", "position": "LCB", "name": "Angelo Rankin Jr.", "school": "Old Dominion"},
  {"team": "1", "unit": "Defense", "position": "RCB", "name": "Terrence Spence", "school": "James Madison"},
  {"team": "1", "unit": "Defense", "position": "SS", "name": "Travor Randle", "school": "Louisiana Monroe"},
  {"team": "1", "unit": "Defense", "position": "NB", "name": "Jahron Manning", "school": "Old Dominion"},
  {"team": "1", "unit": "Defense", "position": "FS", "name": "J.J. Roberts", "school": "Marshall"},
  {"team": "1", "unit": "Defense", "position": "BCB", "name": "Mattew McDoom", "school": "Coastal Carolina"},
  {"team": "1", "unit": "SpecialTeams", "position": "PK", "name": "Kenneth Almendares", "school": "Louisiana"},
  {"team": "1", "unit": "SpecialTeams", "position": "KO", "name": "Brendan Franke", "school": "Texas State"},
  {"team": "1", "unit": "SpecialTeams", "position": "PT", "name": "Ryan Heicher", "school": "Arkansas State"},
  {"team": "1", "unit": "SpecialTeams", "position": "KR", "name": "Robert Williams", "school": "Louisiana"},
  {"team": "1", "unit": "SpecialTeams", "position": "PR", "name": "Courtney Jackson", "school": "Arkansas State"},
  {"team": "1", "unit": "SpecialTeams", "position": "WR-Z", "name": "Dalen Cambre", "school": "Louisiana"},
{"team": "2", "unit": "Offense", "position": "QB", "name": "Alonza Barnett III", "school": "James Madison"},
  {"team": "2", "unit": "Offense", "position": "RB", "name": "Damien Taylor", "school": "Troy"},
  {"team": "2", "unit": "Offense", "position": "RB", "name": "Ismail Mahdi", "school": "Texas State"},
  {"team": "2", "unit": "Offense", "position": "WR-X", "name": "Corey Rucker", "school": "Arkansas State"},
  {"team": "2", "unit": "Offense", "position": "WR-X", "name": "Lance LeGendre", "school": "Louisiana"},
  {"team": "2", "unit": "Offense", "position": "WR-X", "name": "Joey Hobert", "school": "Texas State"},
  {"team": "2", "unit": "Offense", "position": "TE", "name": "Taylor Thompson", "school": "James Madison"},
  {"team": "2", "unit": "Offense", "position": "TE", "name": "Pat Conroy", "school": "Old Dominion"},
  {"team": "2", "unit": "Offense", "position": "LT", "name": "Jeremy Jones", "school": "Marshall"},
  {"team": "2", "unit": "Offense", "position": "RG", "name": "Jax Harrington", "school": "Louisiana"},
  {"team": "2", "unit": "Offense", "position": "C", "name": "Jacob Bayer", "school": "Arkansas State"},
  {"team": "2", "unit": "Offense", "position": "LG", "name": "Nash Jones", "school": "Texas State"},
  {"team": "2", "unit": "Offense", "position": "LT", "name": "Dorion Strawn", "school": "Texas State"},

  {"team": "2", "unit": "Defense", "position": "JACK", "name": "Cameron Whitfield", "school": "Louisiana"},
  {"team": "2", "unit": "Defense", "position": "RDT", "name": "Brodarius Lewis", "school": "Southern Miss"},
  {"team": "2", "unit": "Defense", "position": "RDT", "name": "Chris Fitzgerald", "school": "James Madison"},
  {"team": "2", "unit": "Defense", "position": "LEO", "name": "Clev Lubin", "school": "Coastal Carolina"},
  {"team": "2", "unit": "Defense", "position": "WLB", "name": "Blayne Myrick", "school": "South Alabama"},
  {"team": "2", "unit": "Defense", "position": "MLB", "name": "Jordan Stringer", "school": "Troy"},
  {"team": "2", "unit": "Defense", "position": "SLB", "name": "Jahleel Culbreath", "school": "Old Dominion"},
  {"team": "2", "unit": "Defense", "position": "NB", "name": "Jacobie Henderson", "school": "Marshall"},
  {"team": "2", "unit": "Defense", "position": "NB", "name": "Lardarius Webb Jr.", "school": "South Alabama"},
  {"team": "2", "unit": "Defense", "position": "NB", "name": "DJ Barksdale", "school": "James Madison"},
  {"team": "2", "unit": "Defense", "position": "SS", "name": "Trevian Thomas", "school": "Arkansas State"},
  {"team": "2", "unit": "Defense", "position": "SS", "name": "Tyrone Lewis Jr.", "school": "Louisiana"},
  {"team": "2", "unit": "Defense", "position": "FS", "name": "Jaden Voisin", "school": "South Alabama"},
  {"team": "2", "unit": "Defense", "position": "MLB", "name": "Trent Hendrick", "school": "James Madison"},

  {"team": "2", "unit": "SpecialTeams", "position": "PK", "name": "Laith Marjan", "school": "South Alabama"},
  {"team": "2", "unit": "SpecialTeams", "position": "KO", "name": "Paddy McAteer", "school": "Troy"},
  {"team": "2", "unit": "SpecialTeams", "position": "PT", "name": "Ryan Hanson", "school": "James Madison"},
  {"team": "2", "unit": "SpecialTeams", "position": "KR", "name": "Cameron Ross", "school": "James Madison"},
  {"team": "2", "unit": "SpecialTeams", "position": "PR", "name": "Beau Sparks", "school": "Texas State"},
  {"team": "2", "unit": "SpecialTeams", "position": "FS", "name": "Jerome Carter", "school": "Old Dominion"},
{"team": "3", "unit": "Offense", "position": "QB", "name": "Ben Wooldridge", "school": "Louisiana"},
  {"team": "3", "unit": "Offense", "position": "RB", "name": "Braydon Bennett", "school": "Coastal Carolina"},
  {"team": "3", "unit": "Offense", "position": "RB", "name": "George Pettaway", "school": "James Madison"},
  {"team": "3", "unit": "Offense", "position": "WR-X", "name": "Kaedin Robinson", "school": "Appalachian State"},
  {"team": "3", "unit": "Offense", "position": "WR-X", "name": "Isiah Paige", "school": "Old Dominion"},
  {"team": "3", "unit": "Offense", "position": "WR-SL", "name": "Makai Jackson", "school": "Appalachian State"},
  {"team": "3", "unit": "Offense", "position": "TE", "name": "Eli Wilson", "school": "Appalachian State"},
  {"team": "3", "unit": "Offense", "position": "WR-Z", "name": "Omarion Dollison", "school": "James Madison"},
  {"team": "3", "unit": "Offense", "position": "RG", "name": "Daniel King", "school": "Troy"},
  {"team": "3", "unit": "Offense", "position": "C", "name": "Mehki Butler", "school": "Arkansas State"},
  {"team": "3", "unit": "Offense", "position": "C", "name": "Logan Osburn", "school": "Marshall"},
  {"team": "3", "unit": "Offense", "position": "RG", "name": "Cole Potts", "school": "James Madison"},
  {"team": "3", "unit": "Offense", "position": "RT", "name": "George Jackson", "school": "Louisiana"},

  {"team": "3", "unit": "Defense", "position": "RDE", "name": "Kalil Alexander", "school": "Texas State"},
  {"team": "3", "unit": "Defense", "position": "RDT", "name": "Terry Webb", "school": "Texas State"},
  {"team": "3", "unit": "Defense", "position": "NT", "name": "Tim Hardiman", "school": "Arkansas State"},
  {"team": "3", "unit": "Defense", "position": "LDE", "name": "Khairi Manns", "school": "James Madison"},
  {"team": "3", "unit": "Defense", "position": "WLB", "name": "Brendan Jackson", "school": "Troy"},
  {"team": "3", "unit": "Defense", "position": "MLB", "name": "Marques Watson‑Trent", "school": "Georgia Southern"},
  {"team": "3", "unit": "Defense", "position": "MLB", "name": "Darius McKenzie", "school": "South Alabama"},
  {"team": "3", "unit": "Defense", "position": "LCB", "name": "Trez Moore", "school": "Texas State"},
  {"team": "3", "unit": "Defense", "position": "RCB", "name": "Dontay Joyner", "school": "Arkansas State"},
  {"team": "3", "unit": "Defense", "position": "LCB", "name": "LJ Green", "school": "Troy"},
  {"team": "3", "unit": "Defense", "position": "SS", "name": "Wydett Williams Jr.", "school": "Louisiana Monroe"},
  {"team": "3", "unit": "Defense", "position": "SS", "name": "Jeremiah Johnson", "school": "Georgia State"},
  {"team": "3", "unit": "Defense", "position": "FS", "name": "Tyree Skipper", "school": "Louisiana"},
  {"team": "3", "unit": "Defense", "position": "FS", "name": "Tobias Fletcher", "school": "Coastal Carolina"},

  {"team": "3", "unit": "SpecialTeams", "position": "PK", "name": "Kade Hensley", "school": "Coastal Carolina"},
  {"team": "3", "unit": "SpecialTeams", "position": "KO", "name": "Cristiano Rosa", "school": "James Madison"},
  {"team": "3", "unit": "SpecialTeams", "position": "PT", "name": "Alex Smith", "school": "Georgia Southern"},
  {"team": "3", "unit": "SpecialTeams", "position": "KR", "name": "DeAndre Buchannon", "school": "Georgia Southern"},
  {"team": "3", "unit": "SpecialTeams", "position": "PR", "name": "Yamir Knight", "school": "James Madison"},
  {"team": "3", "unit": "SpecialTeams", "position": "FS", "name": "Tyler Brown", "school": "James Madison"},
 {"team": "honorable_mention", "unit": "Offense", "position": "QB", "name": "Joey Aguilar", "school": "Appalachian State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "QB", "name": "Gio Lopez", "school": "South Alabama"},
  {"team": "honorable_mention", "unit": "Offense", "position": "QB", "name": "Braylon Braxton", "school": "Marshall"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RB", "name": "Zak Wallace", "school": "Arkansas State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RB", "name": "Kentrel Bullock", "school": "South Alabama"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RB", "name": "Jalen White", "school": "Georgia Southern"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RB", "name": "Freddie Brock", "school": "Georgia State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RB", "name": "Aaron Young", "school": "Old Dominion"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RB", "name": "A.J. Turner", "school": "Marshall"},
  {"team": "honorable_mention", "unit": "Offense", "position": "WR-Z", "name": "Jaden Williams", "school": "Texas State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "WR-X", "name": "Christian Fitzpatrick", "school": "Marshall"},
  {"team": "honorable_mention", "unit": "Offense", "position": "WR-X", "name": "Derwin Burgiss Jr.", "school": "Georgia Southern"},
  {"team": "honorable_mention", "unit": "Offense", "position": "WR-X", "name": "Kole Wilson", "school": "Texas State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "WR-SL", "name": "Yamir Knight", "school": "James Madison"},
  {"team": "honorable_mention", "unit": "Offense", "position": "WR-X", "name": "Jameson Tucker", "school": "Coastal Carolina"},
  {"team": "honorable_mention", "unit": "Offense", "position": "WR-X", "name": "Chris Dawn Jr.", "school": "Texas State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "WR-Y", "name": "Josh Dallas", "school": "Georgia Southern"},
  {"team": "honorable_mention", "unit": "Offense", "position": "WR-W", "name": "Chuck Montgomery", "school": "Marshall"},
  {"team": "honorable_mention", "unit": "Offense", "position": "TE", "name": "Brody Dalton", "school": "Troy"},
  {"team": "honorable_mention", "unit": "Offense", "position": "TE", "name": "DJ Thomas‑Jones", "school": "South Alabama"},
  {"team": "honorable_mention", "unit": "Offense", "position": "TE", "name": "Kyirin Heath", "school": "Southern Miss"},
  {"team": "honorable_mention", "unit": "Offense", "position": "TE", "name": "Toby Payne", "school": "Marshall"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RB", "name": "Michel Dukes", "school": "Georgia State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RB", "name": "Kenyon Clay", "school": "Southern Miss"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RT", "name": "Makilan Thomas", "school": "Arkansas State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RT", "name": "Malachi Carney", "school": "South Alabama"},
  {"team": "honorable_mention", "unit": "Offense", "position": "LT", "name": "Nick Del Grande", "school": "Coastal Carolina"},
  {"team": "honorable_mention", "unit": "Offense", "position": "LG", "name": "Heston Edwards", "school": "Coastal Carolina"},
  {"team": "honorable_mention", "unit": "Offense", "position": "LG", "name": "Griffin Scroggs", "school": "Appalachian State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RG", "name": "Jalen Slappy", "school": "Marshall"},
  {"team": "honorable_mention", "unit": "Offense", "position": "C", "name": "Carter Miller", "school": "Louisiana Monroe"},
  {"team": "honorable_mention", "unit": "Offense", "position": "C", "name": "Jack Hollifield", "school": "Appalachian State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "C", "name": "Chayse Todd", "school": "Texas State"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RG", "name": "Bryce Ramsey", "school": "Marshall"},
  {"team": "honorable_mention", "unit": "Offense", "position": "LG", "name": "Pichon Wembley", "school": "Georgia Southern"},
  {"team": "honorable_mention", "unit": "Offense", "position": "RG", "name": "Donavan Manson", "school": "Coastal Carolina"},
  {"team": "honorable_mention", "unit": "Offense", "position": "LT", "name": "Elijah Prather", "school": "Troy"},
  {"team": "honorable_mention", "unit": "Offense", "position": "LT", "name": "Bryant Williams", "school": "Louisiana"},
  {"team": "honorable_mention", "unit": "Offense", "position": "LT", "name": "Jesse Ramil", "school": "James Madison"},
  
  {"team": "honorable_mention", "unit": "Defense", "position": "BAN", "name": "Billy Pullen", "school": "Louisiana Monroe"},
  {"team": "honorable_mention", "unit": "Defense", "position": "RDE", "name": "Ryan Johnson", "school": "Southern Miss"},
  {"team": "honorable_mention", "unit": "Defense", "position": "DT", "name": "Raymond Cutts", "school": "Troy"},
  {"team": "honorable_mention", "unit": "Defense", "position": "LDT", "name": "Elhadj Fall", "school": "Georgia Southern"},
  {"team": "honorable_mention", "unit": "Defense", "position": "DT", "name": "Ian Jeffries", "school": "Arkansas State"},
  {"team": "honorable_mention", "unit": "Defense", "position": "LDT", "name": "Immanuel Bush", "school": "James Madison"},
  {"team": "honorable_mention", "unit": "Defense", "position": "DT", "name": "Darold DeNgohe", "school": "James Madison"},
  {"team": "honorable_mention", "unit": "Defense", "position": "DT", "name": "Chris Thomas Jr.", "school": "Marshall"},
  {"team": "honorable_mention", "unit": "Defense", "position": "NT", "name": "Dominique Ratcliff", "school": "Texas State"},
  {"team": "honorable_mention", "unit": "Defense", "position": "LDE", "name": "Deeve Harris", "school": "Marshall"},
  {"team": "honorable_mention", "unit": "Defense", "position": "LDE", "name": "Kris Trinidad", "school": "Old Dominion"},
  {"team": "honorable_mention", "unit": "Defense", "position": "DE", "name": "Jordan Lawson", "school": "Louisiana"},
  {"team": "honorable_mention", "unit": "Defense", "position": "MLB", "name": "Charles Willekes", "school": "Arkansas State"},
  {"position":"MLB","name":"Tre Pinkney","school":"Southern Miss","team":"honorable_mention"},
  {"position":"MLB","name":"Landyn Watson","school":"Marshall","team":"honorable_mention"},
  {"position":"ROVER","name":"Carl Glass Jr.","school":"Louisiana Monroe","team":"honorable_mention"},
  {"position":"MLB","name":"Carmycah Glass","school":"Louisiana","team":"honorable_mention"},
  {"position":"MLB","name":"Wyatt Gedeon","school":"Coastal Carolina","team":"honorable_mention"},
  {"position":"MLB","name":"Koa Naotala","school":"Old Dominion","team":"honorable_mention"},
  {"position":"WLB","name":"Jacob Dobbs","school":"James Madison","team":"honorable_mention"},
  {"position":"MLB","name":"Davon Gilmore","school":"Georgia Southern","team":"honorable_mention"},
  {"position":"LCB","name":"Gavin Pringle","school":"Georgia Southern","team":"honorable_mention"},
  {"position":"RCB","name":"Justin Agu","school":"Louisiana","team":"honorable_mention"},
  {"position":"LCB","name":"Damaje Yancey","school":"Texas State","team":"honorable_mention"},
  {"position":"RCB","name":"Will James","school":"Southern Miss","team":"honorable_mention"},
  {"position":"LCB","name":"Amarion Fortenberry","school":"South Alabama","team":"honorable_mention"},
  {"position":"RCB","name":"Dontay Joyner","school":"Arkansas State","team":"honorable_mention"},
  {"position":"LCB","name":"David Godsey Jr.","school":"Louisiana Monroe","team":"honorable_mention"},
  {"position":"NB","name":"Ian Foster","school":"Marshall","team":"honorable_mention"},
  {"position":"RCB","name":"Jordan Scruggs","school":"South Alabama","team":"honorable_mention"},
  {"position":"NB","name":"Marc Stampley II","school":"Georgia Southern","team":"honorable_mention"},
  {"position":"RCB","name":"Jordan Polk","school":"Texas State","team":"honorable_mention"},
  {"position":"SS","name":"Justin Parks","school":"Arkansas State","team":"honorable_mention"},
  {"position":"SS","name":"Justin Powe","school":"Troy","team":"honorable_mention"},
  {"position":"FS","name":"Wesley Miller","school":"South Alabama","team":"honorable_mention"},
  {"position":"FS","name":"Kenyatta Watson II","school":"Georgia State","team":"honorable_mention"},
  {"position":"SS","name":"Dylan Lawrence","school":"Southern Miss","team":"honorable_mention"},
  {"position":"SS","name":"Kaleb Culp","school":"Texas State","team":"honorable_mention"},
  {"position":"SS","name":"Jacob Thomas","school":"James Madison","team":"honorable_mention"},
  {"position":"SPEAR","name":"Devin Lafayette","school":"Troy","team":"honorable_mention"},
  {"position":"WLB","name":"Brendan Harrington","school":"Appalachian State","team":"honorable_mention"},
  {"position":"MLB","name":"Tray Brown","school":"Coastal Carolina","team":"honorable_mention"},
  {"position":"PK","name":"Clune Van Andel","school":"Arkansas State","team":"honorable_mention"},
  {"position":"KO","name":"Nathan Totten","school":"Marshall","team":"honorable_mention"},
  {"position":"PT","name":"Seamus Hall","school":"Old Dominion","team":"honorable_mention"},
  {"position":"KR","name":"Ian Foster","school":"Marshall","team":"honorable_mention"},
  {"position":"PR","name":"Jamaal Pritchett","school":"South Alabama","team":"honorable_mention"},
  {"position":"NB","name":"Brandon Greil","school":"Arkansas State","team":"honorable_mention"}
  ]
}
