"""CFN All-SEC List 2024"""

ALL_SEC = {
  "year": 2024,
  "name_of_award": "all_conference",
  "conference": "sec",
  "source": "cfn",
  "sec" : [
      {"award": "PlayerOfTheYear", "name": "Nick Emmanwori", "position": "S", "school": "South Carolina"},
      {"award": "OffensivePlayerOfTheYear", "name": "Dylan Sampson", "position": "RB", "school": "Tennessee"},
      {"award": "DefensivePlayerOfTheYear", "name": "Nick Emmanwori", "position": "S", "school": "South Carolina"},
      {"award": "SpecialistOfTheYear", "name": "Brett Thorson", "position": "P", "school": "Georgia"},
      {"award": "NewcomerOfTheYear", "name": "Ryan Williams", "position": "WR", "school": "Alabama"},
      {"award": "CoachOfTheYear", "name": "Shane Beamer", "position": "Coach", "school": "South Carolina"},
      {"award": "ImpactFreshmanOfTheYear", "name": "Ryan Williams", "position": "WR", "school": "Alabama"},
{"award": "QuarterbackOfTheYear", "name": "Jaxson Dart", "position": "QB", "school": "Ole Miss"},
  {"award": "RunningBackOfTheYear", "name": "Dylan Sampson", "position": "RB", "school": "Tennessee"},
  {"award": "WideReceiverOfTheYear", "name": "Tre Harris", "position": "WR", "school": "Ole Miss"},
  {"award": "TightEndOfTheYear", "name": "Gunnar Helm", "position": "TE", "school": "Texas"},
  {"award": "OffensiveTackleOfTheYear", "name": "Kelvin Banks Jr.", "position": "OT", "school": "Texas"},
  {"award": "OffensiveGuardOfTheYear", "name": "Dylan Fairchild", "position": "OG", "school": "Georgia"},
  {"award": "CenterOfTheYear", "name": "Jake Slaughter", "position": "C", "school": "Florida"},
  {"award": "OffensiveLinemanOfTheYear", "name": "Kelvin Banks Jr.", "position": "OT", "school": "Texas"},
  {"award": "OffensiveLineOfTheYear", "name": "Missouri Tigers", "position": "OL Unit", "school": "Missouri"},
  {"award": "OffensiveNewcomerOfTheYear", "name": "Ryan Williams", "position": "WR", "school": "Alabama"},
  {"award": "EdgeDefenderOfTheYear", "name": "James Pearce Jr.", "position": "EDGE", "school": "Tennessee"},
  {"award": "InteriorDefenderOfTheYear", "name": "T.J. Sanders", "position": "DT", "school": "South Carolina"},
  {"award": "LinebackerOfTheYear", "name": "Chris Paul Jr.", "position": "LB", "school": "Ole Miss"},
  {"award": "CornerbackOfTheYear", "name": "Jahdae Barron", "position": "CB", "school": "Texas"},
  {"award": "SafetyOfTheYear", "name": "Nick Emmanwori", "position": "S", "school": "South Carolina"},
  {"award": "DefensiveLineOfTheYear", "name": "South Carolina Gamecocks", "position": "DL Unit", "school": "South Carolina"},
  {"award": "SecondaryOfTheYear", "name": "Texas Longhorns", "position": "Secondary Unit", "school": "Texas"},
  {"award": "DefensiveNewcomerOfTheYear", "name": "Dylan Stewart", "position": "EDGE", "school": "South Carolina"},
  {"award": "DefensiveTransferOfTheYear", "name": "Princely Umanmielen", "position": "EDGE", "school": "Ole Miss"},
  {"award": "KickerOfTheYear", "name": "Peyton Woodring", "position": "PK", "school": "Georgia"},
  {"award": "PunterOfTheYear", "name": "Brett Thorson", "position": "P", "school": "Georgia"},
  {"award": "KickReturnerOfTheYear", "name": "Barion Brown", "position": "KR", "school": "Kentucky"},
  {"award": "PuntReturnerOfTheYear", "name": "Martel Hight", "position": "PR", "school": "Vanderbilt"},
  {"award": "SpecialTeamerOfTheYear", "name": "King Mack", "position": "ST", "school": "Alabama"},
  {"award": "KickoffSpecialistOfTheYear", "name": "Caden Davis", "position": "KOS", "school": "Ole Miss"},
{"team": "1", "unit": "Offense", "position": "QB", "name": "Jaxson Dart", "school": "Ole Miss"},
  {"team": "1", "unit": "Offense", "position": "RB", "name": "Dylan Sampson", "school": "Tennessee"},
  {"team": "1", "unit": "Offense", "position": "RB", "name": "Jarquez Hunter", "school": "Auburn"},
  {"team": "1", "unit": "Offense", "position": "WR", "name": "Andrew Armstrong", "school": "Arkansas"},
  {"team": "1", "unit": "Offense", "position": "WR", "name": "Tre Harris", "school": "Ole Miss"},
  {"team": "1", "unit": "Offense", "position": "WR", "name": "KeAndre Lambert-Smith", "school": "Auburn"},
  {"team": "1", "unit": "Offense", "position": "TE", "name": "Gunnar Helm", "school": "Texas"},
  {"team": "1", "unit": "Offense", "position": "FLEX", "name": "Ryan Williams", "school": "Alabama"},
  {"team": "1", "unit": "Offense", "position": "OT", "name": "Kelvin Banks Jr.", "school": "Texas"},
  {"team": "1", "unit": "Offense", "position": "OG", "name": "Dylan Fairchild", "school": "Georgia"},
  {"team": "1", "unit": "Offense", "position": "OC", "name": "Jake Slaughter", "school": "Florida"},
  {"team": "1", "unit": "Offense", "position": "OG", "name": "Ar’maj Reed-Adams", "school": "Texas AM"},
  {"team": "1", "unit": "Offense", "position": "OT", "name": "Armand Mambou", "school": "Missouri"},

  {"team": "1", "unit": "Defense", "position": "EDGE", "name": "James Pearce Jr.", "school": "Tennessee"},
  {"team": "1", "unit": "Defense", "position": "DT", "name": "T.J. Sanders", "school": "South Carolina"},
  {"team": "1", "unit": "Defense", "position": "DT", "name": "JJ Pegues", "school": "Ole Miss"},
  {"team": "1", "unit": "Defense", "position": "EDGE", "name": "Dylan Stewart", "school": "South Carolina"},
  {"team": "1", "unit": "Defense", "position": "LB", "name": "Chris Paul Jr.", "school": "Ole Miss"},
  {"team": "1", "unit": "Defense", "position": "LB", "name": "Jihaad Campbell", "school": "Alabama"},
  {"team": "1", "unit": "Defense", "position": "LB", "name": "Whit Weeks", "school": "LSU"},
  {"team": "1", "unit": "Defense", "position": "CB", "name": "Jahdae Barron", "school": "Texas"},
  {"team": "1", "unit": "Defense", "position": "CB", "name": "Trey Amos", "school": "Ole Miss"},
  {"team": "1", "unit": "Defense", "position": "CB", "name": "Brian Mayes", "school": "Texas AM"},
  {"team": "1", "unit": "Defense", "position": "SS", "name": "Nick Emmanwori", "school": "South Carolina"},
  {"team": "1", "unit": "Defense", "position": "FS", "name": "Michael Taaffe", "school": "Texas"},
  {"team": "1", "unit": "Defense", "position": "S", "name": "Andrew Mukuba", "school": "Texas"},
  {"team": "1", "unit": "Defense", "position": "FLEX", "name": "Jermod McCoy", "school": "Tennessee"},

  {"team": "1", "unit": "SpecialTeams", "position": "PK", "name": "Peyton Woodring", "school": "Georgia"},
  {"team": "1", "unit": "SpecialTeams", "position": "KOS", "name": "Caden Davis", "school": "Ole Miss"},
  {"team": "1", "unit": "SpecialTeams", "position": "P", "name": "Brett Thorson", "school": "Georgia"},
  {"team": "1", "unit": "SpecialTeams", "position": "KR", "name": "Barion Brown", "school": "Kentucky"},
  {"team": "1", "unit": "SpecialTeams", "position": "PR", "name": "Martel Hight", "school": "Vanderbilt"},
{"team": "2", "unit": "Offense", "position": "QB", "name": "Diego Pavia", "school": "Vanderbilt"},
  {"team": "2", "unit": "Offense", "position": "RB", "name": "Raheim Sanders", "school": "South Carolina"},
  {"team": "2", "unit": "Offense", "position": "RB", "name": "Ja’Quinden Jackson", "school": "Arkansas"},
  {"team": "2", "unit": "Offense", "position": "WR", "name": "Matthew Golden", "school": "Texas"},
  {"team": "2", "unit": "Offense", "position": "WR", "name": "Kyren Lacy", "school": "LSU"},
  {"team": "2", "unit": "Offense", "position": "WR", "name": "Kevin Coleman", "school": "Mississippi State"},
  {"team": "2", "unit": "Offense", "position": "TE", "name": "Eli Stowers", "school": "Vanderbilt"},
  {"team": "2", "unit": "Offense", "position": "FLEX", "name": "Theo Wease Jr.", "school": "Missouri"},
  {"team": "2", "unit": "Offense", "position": "OT", "name": "Marcus Bryant", "school": "Missouri"},
  {"team": "2", "unit": "Offense", "position": "OG", "name": "Cam’Ron Johnson", "school": "Missouri"},
  {"team": "2", "unit": "Offense", "position": "OC", "name": "Jared Wilson", "school": "Florida"},
  {"team": "2", "unit": "Offense", "position": "OG", "name": "Cayden Green", "school": "Missouri"},
  {"team": "2", "unit": "Offense", "position": "OT", "name": "Micah Pettus", "school": "Ole Miss"},

  {"team": "2", "unit": "Defense", "position": "EDGE", "name": "Princely Umanmielen", "school": "Ole Miss"},
  {"team": "2", "unit": "Defense", "position": "DT", "name": "Walter Nolen", "school": "Ole Miss"},
  {"team": "2", "unit": "Defense", "position": "DT", "name": "Caleb Banks", "school": "Florida"},
  {"team": "2", "unit": "Defense", "position": "EDGE", "name": "Bradyn Swinson", "school": "LSU"},
  {"team": "2", "unit": "Defense", "position": "LB", "name": "Jalon Walker", "school": "Georgia"},
  {"team": "2", "unit": "Defense", "position": "LB", "name": "Danny Stutsman", "school": "Oklahoma"},
  {"team": "2", "unit": "Defense", "position": "LB", "name": "Anthony Hill Jr.", "school": "Texas"},
  {"team": "2", "unit": "Defense", "position": "CB", "name": "Judge Collier", "school": "South Carolina"},
  {"team": "2", "unit": "Defense", "position": "CB", "name": "Will Lee III", "school": "Texas AM"},
  {"team": "2", "unit": "Defense", "position": "CB", "name": "Jalen Kilgore", "school": "South Carolina"},
  {"team": "2", "unit": "Defense", "position": "SS", "name": "John Saunders Jr.", "school": "Ole Miss"},
  {"team": "2", "unit": "Defense", "position": "FS", "name": "Dan Jackson", "school": "Georgia"},
  {"team": "2", "unit": "Defense", "position": "S", "name": "Malachi Moore", "school": "Alabama"},
  {"team": "2", "unit": "Defense", "position": "FLEX", "name": "Jadon Canady", "school": "Ole Miss"},

  {"team": "2", "unit": "SpecialTeams", "position": "PK", "name": "Brock Taylor", "school": "Vanderbilt"},
  {"team": "2", "unit": "SpecialTeams", "position": "KOS", "name": "Aeron Burrell", "school": "LSU"},
  {"team": "2", "unit": "SpecialTeams", "position": "P", "name": "Kai Kroeger", "school": "South Carolina"},
  {"team": "2", "unit": "SpecialTeams", "position": "KR", "name": "Junior Sherrill", "school": "Vanderbilt"},
  {"team": "2", "unit": "SpecialTeams", "position": "PR", "name": "Silas Bolden", "school": "Texas"},
  {"team": "2", "unit": "SpecialTeams", "position": "ST", "name": "Colin Bryant", "school": "South Carolina"},
 {"team": "3", "unit": "Offense", "position": "QB", "name": "Taylen Green", "school": "Arkansas"},
  {"team": "3", "unit": "Offense", "position": "RB", "name": "Le’Veon Moss", "school": "Texas AM"},
  {"team": "3", "unit": "Offense", "position": "RB", "name": "Henry Parrish Jr.", "school": "Ole Miss"},
  {"team": "3", "unit": "Offense", "position": "WR", "name": "Cayden Lee", "school": "Ole Miss"},
  {"team": "3", "unit": "Offense", "position": "WR", "name": "Elijhah Badger", "school": "Florida"},
  {"team": "3", "unit": "Offense", "position": "WR", "name": "Aaron Anderson", "school": "LSU"},
  {"team": "3", "unit": "Offense", "position": "TE", "name": "Mason Taylor", "school": "LSU"},
  {"team": "3", "unit": "Offense", "position": "FLEX", "name": "Caden Durham", "school": "LSU"},
  {"team": "3", "unit": "Offense", "position": "OT", "name": "Dillon Wade", "school": "Auburn"},
  {"team": "3", "unit": "Offense", "position": "OG", "name": "Hayden Conner", "school": "Texas"},
  {"team": "3", "unit": "Offense", "position": "OC", "name": "Jake Majors", "school": "Texas"},
  {"team": "3", "unit": "Offense", "position": "OG", "name": "Torricelli Simpkins III", "school": "South Carolina"},
  {"team": "3", "unit": "Offense", "position": "OT", "name": "Kadyn Proctor", "school": "Alabama"},

  {"team": "3", "unit": "Defense", "position": "EDGE", "name": "Kyle Kennard", "school": "South Carolina"},
  {"team": "3", "unit": "Defense", "position": "DT", "name": "Omarr Norman-Lott", "school": "Tennessee"},
  {"team": "3", "unit": "Defense", "position": "DT", "name": "Tonka Hemingway", "school": "South Carolina"},
  {"team": "3", "unit": "Defense", "position": "EDGE", "name": "Suntarine Perkins", "school": "Ole Miss"},
  {"team": "3", "unit": "Defense", "position": "LB", "name": "C.J. Allen", "school": "Georgia"},
  {"team": "3", "unit": "Defense", "position": "LB", "name": "Deontae Lawson", "school": "Alabama"},
  {"team": "3", "unit": "Defense", "position": "LB", "name": "Xavian Sorey Jr.", "school": "Arkansas"},
  {"team": "3", "unit": "Defense", "position": "CB", "name": "Ashton Stamps", "school": "LSU"},
  {"team": "3", "unit": "Defense", "position": "CB", "name": "Domani Jackson", "school": "Alabama"},
  {"team": "3", "unit": "Defense", "position": "CB", "name": "Malik Muhammad", "school": "Texas"},
  {"team": "3", "unit": "Defense", "position": "SS", "name": "Bray Hubbard", "school": "Alabama"},
  {"team": "3", "unit": "Defense", "position": "FS", "name": "Billy Bowman Jr.", "school": "Oklahoma"},
  {"team": "3", "unit": "Defense", "position": "S", "name": "Marcus Ratcliffe", "school": "Texas AM"},
  {"team": "3", "unit": "Defense", "position": "FLEX", "name": "Daylen Everette", "school": "Georgia"},

  {"team": "3", "unit": "SpecialTeams", "position": "PK", "name": "Randy Bond", "school": "Texas AM"},
  {"team": "3", "unit": "SpecialTeams", "position": "KOS", "name": "Jared Zirkel", "school": "Texas AM"},
  {"team": "3", "unit": "SpecialTeams", "position": "P", "name": "Jeremy Crawshaw", "school": "Florida"},
  {"team": "3", "unit": "SpecialTeams", "position": "KR", "name": "Zavion Thomas", "school": "LSU"},
  {"team": "3", "unit": "SpecialTeams", "position": "PR", "name": "Boo Carter", "school": "Tennessee"},
  {"team": "3", "unit": "SpecialTeams", "position": "ST", "name": "Lewis Carter", "school": "Oklahoma"},
{"position":"QB","name":"Carson Beck","school":"Georgia","team":"honorable_mention"},
  {"position":"QB","name":"Nico Iamaleava","school":"Tennessee","team":"honorable_mention"},
  {"position":"QB","name":"Garrett Nussmeier","school":"LSU","team":"honorable_mention"},
  {"position":"RB","name":"Jam Miller","school":"Alabama","team":"honorable_mention"},
  {"position":"RB","name":"Marcus Carroll","school":"Missouri","team":"honorable_mention"},
  {"position":"RB","name":"Davon Booth","school":"Mississippi State","team":"honorable_mention"},
  {"position":"RB","name":"Amari Daniels","school":"Texas AM","team":"honorable_mention"},
  {"position":"RB","name":"Quintrevion Wisner","school":"Texas","team":"honorable_mention"},
  {"position":"RB","name":"Nate Noel","school":"Missouri","team":"honorable_mention"},
  {"position":"WR","name":"Luther Burden III","school":"Missouri","team":"honorable_mention"},
  {"position":"WR","name":"Dont’e Thornton Jr.","school":"Tennessee","team":"honorable_mention"},
  {"position":"WR","name":"Cam Coleman","school":"Auburn","team":"honorable_mention"},
  {"position":"WR","name":"Dominic Lovett","school":"Georgia","team":"honorable_mention"},
  {"position":"WR","name":"Isaiah Bond","school":"Texas","team":"honorable_mention"},
  {"position":"WR","name":"Antwane Wells Jr.","school":"Ole Miss","team":"honorable_mention"},
  {"position":"WR","name":"Jordan Watkins","school":"Ole Miss","team":"honorable_mention"},
  {"position":"WR","name":"Chimere Dike","school":"Florida","team":"honorable_mention"},
  {"position":"WR","name":"Germie Bernard","school":"Alabama","team":"honorable_mention"},
  {"position":"TE","name":"Caden Prieskorn","school":"Ole Miss","team":"honorable_mention"},
  {"position":"TE","name":"Lawson Luckie","school":"Georgia","team":"honorable_mention"},
  {"position":"TE","name":"Joshua Simon","school":"South Carolina","team":"honorable_mention"},
  {"position":"FLEX","name":"Jaydon Blue","school":"Texas","team":"honorable_mention"},
  {"position":"FLEX","name":"Seydou Traore","school":"Mississippi State","team":"honorable_mention"},
  {"position":"FLEX","name":"Luke Hasz","school":"Arkansas","team":"honorable_mention"},
  {"position":"OT","name":"Dametrious Crownover","school":"Texas AM","team":"honorable_mention"},
  {"position":"OT","name":"Monroe Freeling","school":"Georgia","team":"honorable_mention"},
  {"position":"OT","name":"Cameron Williams","school":"Texas","team":"honorable_mention"},
  {"position":"OG","name":"Tyler Booker","school":"Alabama","team":"honorable_mention"},
  {"position":"OG","name":"Andrej Karic","school":"Tennessee","team":"honorable_mention"},
  {"position":"OG","name":"Tate Ratledge","school":"Georgia","team":"honorable_mention"},
  {"position":"OC","name":"Cooper Mays","school":"Tennessee","team":"honorable_mention"},
  {"position":"OC","name":"Connor Tollison","school":"Missouri","team":"honorable_mention"},
  {"position":"OC","name":"Delfin Xavier Castillo","school":"Vanderbilt","team":"honorable_mention"},
  {"position":"OG","name":"Miles Frazier","school":"LSU","team":"honorable_mention"},
  {"position":"OG","name":"Jeremiah Wright","school":"Auburn","team":"honorable_mention"},
  {"position":"OG","name":"DJ Campbell","school":"Texas","team":"honorable_mention"},
  {"position":"OT","name":"Fernando Carmona","school":"Arkansas","team":"honorable_mention"},
  {"position":"OT","name":"Will Campbell","school":"LSU","team":"honorable_mention"},
  {"position":"OT","name":"Brandon Crenshaw‑Dickson","school":"Florida","team":"honorable_mention"},
  {"position":"EDGE","name":"Johnny Walker Jr.","school":"Missouri","team":"honorable_mention"},
  {"position":"EDGE","name":"LT Overton","school":"Alabama","team":"honorable_mention"},
  {"position":"EDGE","name":"Keldric Faulk","school":"Auburn","team":"honorable_mention"},
  {"position":"DT","name":"Cam’Ron Jackson","school":"Florida","team":"honorable_mention"},
  {"position":"DT","name":"Gracen Halton","school":"Oklahoma","team":"honorable_mention"},
  {"position":"DT","name":"Alfred Collins","school":"Texas","team":"honorable_mention"},
  {"position":"DT","name":"Shemar Turner","school":"Texas AM","team":"honorable_mention"},
  {"position":"DT","name":"Eric Gregory","school":"Arkansas","team":"honorable_mention"},
  {"position":"DT","name":"Deone Walker","school":"Kentucky","team":"honorable_mention"},
  {"position":"EDGE","name":"Colin Simmons","school":"Texas","team":"honorable_mention"},
  {"position":"EDGE","name":"Barryn Sorrell","school":"Texas","team":"honorable_mention"},
  {"position":"EDGE","name":"Landon Jackson","school":"Arkansas","team":"honorable_mention"},
  {"position":"LB","name":"Demetrius Knight Jr.","school":"South Carolina","team":"honorable_mention"},
  {"position":"LB","name":"Bryan Longwell","school":"Vanderbilt","team":"honorable_mention"},
  {"position":"LB","name":"Smael Mondon","school":"Georgia","team":"honorable_mention"},
  {"position":"LB","name":"Kip Lewis","school":"Oklahoma","team":"honorable_mention"},
  {"position":"LB","name":"Dorian Mausi","school":"Auburn","team":"honorable_mention"},
  {"position":"LB","name":"Corey Flagg","school":"Missouri","team":"honorable_mention"},
  {"position":"LB","name":"Bam Martin-Scott","school":"South Carolina","team":"honorable_mention"},
  {"position":"LB","name":"Stone Blanton","school":"Mississippi State","team":"honorable_mention"},
  {"position":"LB","name":"Greg Penn III","school":"LSU","team":"honorable_mention"},
  {"position":"CB","name":"O’Donnell Fortune","school":"South Carolina","team":"honorable_mention"},
  {"position":"CB","name":"Martel Hight","school":"Vanderbilt","team":"honorable_mention"},
  {"position":"CB","name":"Zy Alexander","school":"LSU","team":"honorable_mention"},
  {"position":"CB","name":"Boo Carter","school":"Tennessee","team":"honorable_mention"},
  {"position":"CB","name":"Doneiko Slaughter","school":"Arkansas","team":"honorable_mention"},
  {"position":"CB","name":"Kayin Lee","school":"Auburn","team":"honorable_mention"},
  {"position":"CB","name":"Jonquis Hardaway","school":"Kentucky","team":"honorable_mention"},
  {"position":"CB","name":"Dreyden Norwood","school":"Missouri","team":"honorable_mention"},
  {"position":"CB","name":"Jay Crawford","school":"Auburn","team":"honorable_mention"},
  {"position":"SS","name":"Major Burns","school":"LSU","team":"honorable_mention"},
  {"position":"SS","name":"Isaac Smith","school":"Mississippi State","team":"honorable_mention"},
  {"position":"SS","name":"Randon Fontenette","school":"Vanderbilt","team":"honorable_mention"},
  {"position":"FS","name":"TJ Metcalf","school":"Arkansas","team":"honorable_mention"},
  {"position":"FS","name":"Jordan Castell","school":"Florida","team":"honorable_mention"},
  {"position":"FS","name":"Sage Ryan","school":"LSU","team":"honorable_mention"},
  {"position":"S","name":"Malaki Starks","school":"Georgia","team":"honorable_mention"},
  {"position":"S","name":"Zion Childress","school":"Kentucky","team":"honorable_mention"},
  {"position":"S","name":"Daylan Carnell","school":"Missouri","team":"honorable_mention"},
  {"position":"FLEX","name":"Sai’vion Jones","school":"LSU","team":"honorable_mention"},
  {"position":"FLEX","name":"Trikweze Bridges","school":"Florida","team":"honorable_mention"},
  {"position":"FLEX","name":"Keon Sabb","school":"Alabama","team":"honorable_mention"},
  {"position":"PK","name":"Trey Smack","school":"Florida","team":"honorable_mention"},
  {"position":"PK","name":"Alex Raynor","school":"Kentucky","team":"honorable_mention"},
  {"position":"KOS","name":"Josh Turbyville","school":"Tennessee","team":"honorable_mention"},
  {"position":"P","name":"James Burnip","school":"Alabama","team":"honorable_mention"},
  {"position":"KR","name":"Jeremiah Cobb","school":"Auburn","team":"honorable_mention"},
  {"position":"PR","name":"Chimere Dike","school":"Florida","team":"honorable_mention"},
  {"position":"ST","name":"Jailen Ruth","school":"Vanderbilt","team":"honorable_mention"}
  ]
}
