"""CFN All-SEC List 2024"""

ALL_SEC = {
  "year": 2024,
  "name_of_award": "all_conference",
  "conference": "sec",
  "source": "cfn",
  "sec" : [
      {"award": "PlayerOfTheYear", "name": "Nick Emmanwori", "position": "SS", "school": "South Carolina"},
      {"award": "OffensivePlayerOfTheYear", "name": "Dylan Sampson", "position": "RB", "school": "Tennessee"},
      {"award": "DefensivePlayerOfTheYear", "name": "Nick Emmanwori", "position": "SS", "school": "South Carolina"},
      {"award": "SpecialistOfTheYear", "name": "Brett Thorson", "position": "PT", "school": "Georgia"},
      {"award": "NewcomerOfTheYear", "name": "Ryan Williams", "position": "WR-X", "school": "Alabama"},
      {"award": "CoachOfTheYear", "name": "Shane Beamer", "position": "Coach", "school": "South Carolina"},
      {"award": "ImpactFreshmanOfTheYear", "name": "Ryan Williams", "position": "WR-X", "school": "Alabama"},
{"award": "QuarterbackOfTheYear", "name": "Jaxson Dart", "position": "QB", "school": "Ole Miss"},
  {"award": "RunningBackOfTheYear", "name": "Dylan Sampson", "position": "RB", "school": "Tennessee"},
  {"award": "WideReceiverOfTheYear", "name": "Tre Harris", "position": "WR-X", "school": "Ole Miss"},
  {"award": "TightEndOfTheYear", "name": "Gunnar Helm", "position": "TE", "school": "Texas"},
  {"award": "OffensiveTackleOfTheYear", "name": "Kelvin Banks Jr.", "position": "LT", "school": "Texas"},
  {"award": "OffensiveGuardOfTheYear", "name": "Dylan Fairchild", "position": "RG", "school": "Georgia"},
  {"award": "CenterOfTheYear", "name": "Jake Slaughter", "position": "C", "school": "Florida"},
  {"award": "OffensiveLinemanOfTheYear", "name": "Kelvin Banks Jr.", "position": "LT", "school": "Texas"},
  {"award": "OffensiveLineOfTheYear", "name": "Missouri Tigers", "position": "OL Unit", "school": "Missouri"},
  {"award": "OffensiveNewcomerOfTheYear", "name": "Ryan Williams", "position": "WR-X", "school": "Alabama"},
  {"award": "EdgeDefenderOfTheYear", "name": "James Pearce Jr.", "position": "BUCK", "school": "Tennessee"},
  {"award": "InteriorDefenderOfTheYear", "name": "T.J. Sanders", "position": "RDT", "school": "South Carolina"},
  {"award": "LinebackerOfTheYear", "name": "Chris Paul Jr.", "position": "MLB", "school": "Ole Miss"},
  {"award": "CornerbackOfTheYear", "name": "Jahdae Barron", "position": "FCB", "school": "Texas"},
  {"award": "SafetyOfTheYear", "name": "Nick Emmanwori", "position": "SS", "school": "South Carolina"},
  {"award": "DefensiveLineOfTheYear", "name": "South Carolina Gamecocks", "position": "DL Unit", "school": "South Carolina"},
  {"award": "SecondaryOfTheYear", "name": "Texas Longhorns", "position": "Secondary Unit", "school": "Texas"},
  {"award": "DefensiveNewcomerOfTheYear", "name": "Dylan Stewart", "position": "RDE", "school": "South Carolina"},
  {"award": "DefensiveTransferOfTheYear", "name": "Princely Umanmielen", "position": "BUCK", "school": "Ole Miss"},
  {"award": "KickerOfTheYear", "name": "Peyton Woodring", "position": "PK", "school": "Georgia"},
  {"award": "PunterOfTheYear", "name": "Brett Thorson", "position": "PT", "school": "Georgia"},
  {"award": "KickReturnerOfTheYear", "name": "Barion Brown", "position": "KR", "school": "Kentucky"},
  {"award": "PuntReturnerOfTheYear", "name": "Martel Hight", "position": "PR", "school": "Vanderbilt"},
  {"award": "SpecialTeamerOfTheYear", "name": "King Mack", "position": "SS", "school": "Alabama"},
  {"award": "KickoffSpecialistOfTheYear", "name": "Caden Davis", "position": "KO", "school": "Ole Miss"},
{"team": "1", "unit": "Offense", "position": "QB", "name": "Jaxson Dart", "school": "Ole Miss"},
  {"team": "1", "unit": "Offense", "position": "RB", "name": "Dylan Sampson", "school": "Tennessee"},
  {"team": "1", "unit": "Offense", "position": "RB", "name": "Jarquez Hunter", "school": "Auburn"},
  {"team": "1", "unit": "Offense", "position": "WR-X", "name": "Andrew Armstrong", "school": "Arkansas"},
  {"team": "1", "unit": "Offense", "position": "WR-X", "name": "Tre Harris", "school": "Ole Miss"},
  {"team": "1", "unit": "Offense", "position": "WR-X", "name": "KeAndre Lambert-Smith", "school": "Auburn"},
  {"team": "1", "unit": "Offense", "position": "TE", "name": "Gunnar Helm", "school": "Texas"},
  {"team": "1", "unit": "Offense", "position": "WR-X", "name": "Ryan Williams", "school": "Alabama"},
  {"team": "1", "unit": "Offense", "position": "LT", "name": "Kelvin Banks Jr.", "school": "Texas"},
  {"team": "1", "unit": "Offense", "position": "RG", "name": "Dylan Fairchild", "school": "Georgia"},
  {"team": "1", "unit": "Offense", "position": "C", "name": "Jake Slaughter", "school": "Florida"},
  {"team": "1", "unit": "Offense", "position": "RG", "name": "Ar’maj Reed-Adams", "school": "Texas AM"},
  {"team": "1", "unit": "Offense", "position": "LT", "name": "Armand Mambou", "school": "Missouri"},

  {"team": "1", "unit": "Defense", "position": "DE", "name": "James Pearce Jr.", "school": "Tennessee"},
  {"team": "1", "unit": "Defense", "position": "RDT", "name": "T.J. Sanders", "school": "South Carolina"},
  {"team": "1", "unit": "Defense", "position": "NT", "name": "JJ Pegues", "school": "Ole Miss"},
  {"team": "1", "unit": "Defense", "position": "RDE", "name": "Dylan Stewart", "school": "South Carolina"},
  {"team": "1", "unit": "Defense", "position": "MLB", "name": "Chris Paul Jr.", "school": "Ole Miss"},
  {"team": "1", "unit": "Defense", "position": "MLB", "name": "Jihaad Campbell", "school": "Alabama"},
  {"team": "1", "unit": "Defense", "position": "MLB", "name": "Whit Weeks", "school": "LSU"},
  {"team": "1", "unit": "Defense", "position": "FCB", "name": "Jahdae Barron", "school": "Texas"},
  {"team": "1", "unit": "Defense", "position": "RCB", "name": "Trey Amos", "school": "Ole Miss"},
  {"team": "1", "unit": "Defense", "position": "LCB", "name": "Brian Mayes", "school": "Texas AM"},
  {"team": "1", "unit": "Defense", "position": "SS", "name": "Nick Emmanwori", "school": "South Carolina"},
  {"team": "1", "unit": "Defense", "position": "FS", "name": "Michael Taaffe", "school": "Texas"},
  {"team": "1", "unit": "Defense", "position": "FS", "name": "Andrew Mukuba", "school": "Texas"},
  {"team": "1", "unit": "Defense", "position": "LCB", "name": "Jermod McCoy", "school": "Tennessee"},

  {"team": "1", "unit": "SpecialTeams", "position": "PK", "name": "Peyton Woodring", "school": "Georgia"},
  {"team": "1", "unit": "SpecialTeams", "position": "KO", "name": "Caden Davis", "school": "Ole Miss"},
  {"team": "1", "unit": "SpecialTeams", "position": "PT", "name": "Brett Thorson", "school": "Georgia"},
  {"team": "1", "unit": "SpecialTeams", "position": "KR", "name": "Barion Brown", "school": "Kentucky"},
  {"team": "1", "unit": "SpecialTeams", "position": "PR", "name": "Martel Hight", "school": "Vanderbilt"},
{"team": "2", "unit": "Offense", "position": "QB", "name": "Diego Pavia", "school": "Vanderbilt"},
  {"team": "2", "unit": "Offense", "position": "RB", "name": "Raheim Sanders", "school": "South Carolina"},
  {"team": "2", "unit": "Offense", "position": "RB", "name": "Ja’Quinden Jackson", "school": "Arkansas"},
  {"team": "2", "unit": "Offense", "position": "WR-X", "name": "Matthew Golden", "school": "Texas"},
  {"team": "2", "unit": "Offense", "position": "WR-X", "name": "Kyren Lacy", "school": "LSU"},
  {"team": "2", "unit": "Offense", "position": "WR-H", "name": "Kevin Coleman", "school": "Mississippi State"},
  {"team": "2", "unit": "Offense", "position": "TE", "name": "Eli Stowers", "school": "Vanderbilt"},
  {"team": "2", "unit": "Offense", "position": "WR-Z", "name": "Theo Wease Jr.", "school": "Missouri"},
  {"team": "2", "unit": "Offense", "position": "RT", "name": "Marcus Bryant", "school": "Missouri"},
  {"team": "2", "unit": "Offense", "position": "RG", "name": "Cam’Ron Johnson", "school": "Missouri"},
  {"team": "2", "unit": "Offense", "position": "C", "name": "Jared Wilson", "school": "Florida"},
  {"team": "2", "unit": "Offense", "position": "LG", "name": "Cayden Green", "school": "Missouri"},
  {"team": "2", "unit": "Offense", "position": "RT", "name": "Micah Pettus", "school": "Ole Miss"},

  {"team": "2", "unit": "Defense", "position": "BUCK", "name": "Princely Umanmielen", "school": "Ole Miss"},
  {"team": "2", "unit": "Defense", "position": "DT", "name": "Walter Nolen", "school": "Ole Miss"},
  {"team": "2", "unit": "Defense", "position": "DT", "name": "Caleb Banks", "school": "Florida"},
  {"team": "2", "unit": "Defense", "position": "LDE", "name": "Bradyn Swinson", "school": "LSU"},
  {"team": "2", "unit": "Defense", "position": "MLB", "name": "Jalon Walker", "school": "Georgia"},
  {"team": "2", "unit": "Defense", "position": "MLB", "name": "Danny Stutsman", "school": "Oklahoma"},
  {"team": "2", "unit": "Defense", "position": "MLB", "name": "Anthony Hill Jr.", "school": "Texas"},
  {"team": "2", "unit": "Defense", "position": "RCB", "name": "Judge Collier", "school": "South Carolina"},
  {"team": "2", "unit": "Defense", "position": "RCB", "name": "Will Lee III", "school": "Texas AM"},
  {"team": "2", "unit": "Defense", "position": "NB", "name": "Jalen Kilgore", "school": "South Carolina"},
  {"team": "2", "unit": "Defense", "position": "SS", "name": "John Saunders Jr.", "school": "Ole Miss"},
  {"team": "2", "unit": "Defense", "position": "FS", "name": "Dan Jackson", "school": "Georgia"},
  {"team": "2", "unit": "Defense", "position": "SS", "name": "Malachi Moore", "school": "Alabama"},
  {"team": "2", "unit": "Defense", "position": "NB", "name": "Jadon Canady", "school": "Ole Miss"},

  {"team": "2", "unit": "SpecialTeams", "position": "PK", "name": "Brock Taylor", "school": "Vanderbilt"},
  {"team": "2", "unit": "SpecialTeams", "position": "KO", "name": "Aeron Burrell", "school": "LSU"},
  {"team": "2", "unit": "SpecialTeams", "position": "PT", "name": "Kai Kroeger", "school": "South Carolina"},
  {"team": "2", "unit": "SpecialTeams", "position": "KR", "name": "Junior Sherrill", "school": "Vanderbilt"},
  {"team": "2", "unit": "SpecialTeams", "position": "PR", "name": "Silas Bolden", "school": "Texas"},
  {"team": "2", "unit": "SpecialTeams", "position": "MLB", "name": "Colin Bryant", "school": "South Carolina"},
 {"team": "3", "unit": "Offense", "position": "QB", "name": "Taylen Green", "school": "Arkansas"},
  {"team": "3", "unit": "Offense", "position": "RB", "name": "Le’Veon Moss", "school": "Texas AM"},
  {"team": "3", "unit": "Offense", "position": "RB", "name": "Henry Parrish Jr.", "school": "Ole Miss"},
  {"team": "3", "unit": "Offense", "position": "WR-Y", "name": "Cayden Lee", "school": "Ole Miss"},
  {"team": "3", "unit": "Offense", "position": "WR-X", "name": "Elijhah Badger", "school": "Florida"},
  {"team": "3", "unit": "Offense", "position": "WR-SL", "name": "Aaron Anderson", "school": "LSU"},
  {"team": "3", "unit": "Offense", "position": "TE", "name": "Mason Taylor", "school": "LSU"},
  {"team": "3", "unit": "Offense", "position": "RB", "name": "Caden Durham", "school": "LSU"},
  {"team": "3", "unit": "Offense", "position": "LG", "name": "Dillon Wade", "school": "Auburn"},
  {"team": "3", "unit": "Offense", "position": "RG", "name": "Hayden Conner", "school": "Texas"},
  {"team": "3", "unit": "Offense", "position": "C", "name": "Jake Majors", "school": "Texas"},
  {"team": "3", "unit": "Offense", "position": "RG", "name": "Torricelli Simpkins III", "school": "South Carolina"},
  {"team": "3", "unit": "Offense", "position": "LT", "name": "Kadyn Proctor", "school": "Alabama"},

  {"team": "3", "unit": "Defense", "position": "LDE", "name": "Kyle Kennard", "school": "South Carolina"},
  {"team": "3", "unit": "Defense", "position": "DT", "name": "Omarr Norman-Lott", "school": "Tennessee"},
  {"team": "3", "unit": "Defense", "position": "RDT", "name": "Tonka Hemingway", "school": "South Carolina"},
  {"team": "3", "unit": "Defense", "position": "DE", "name": "Suntarine Perkins", "school": "Ole Miss"},
  {"team": "3", "unit": "Defense", "position": "MONEY", "name": "C.J. Allen", "school": "Georgia"},
  {"team": "3", "unit": "Defense", "position": "STING", "name": "Deontae Lawson", "school": "Alabama"},
  {"team": "3", "unit": "Defense", "position": "MONEY", "name": "Xavian Sorey Jr.", "school": "Arkansas"},
  {"team": "3", "unit": "Defense", "position": "LCB", "name": "Ashton Stamps", "school": "LSU"},
  {"team": "3", "unit": "Defense", "position": "LCB", "name": "Domani Jackson", "school": "Alabama"},
  {"team": "3", "unit": "Defense", "position": "BCB", "name": "Malik Muhammad", "school": "Texas"},
  {"team": "3", "unit": "Defense", "position": "SS", "name": "Bray Hubbard", "school": "Alabama"},
  {"team": "3", "unit": "Defense", "position": "FS", "name": "Billy Bowman Jr.", "school": "Oklahoma"},
  {"team": "3", "unit": "Defense", "position": "SS", "name": "Marcus Ratcliffe", "school": "Texas AM"},
  {"team": "3", "unit": "Defense", "position": "RCB", "name": "Daylen Everette", "school": "Georgia"},

  {"team": "3", "unit": "SpecialTeams", "position": "PK", "name": "Randy Bond", "school": "Texas AM"},
  {"team": "3", "unit": "SpecialTeams", "position": "KO", "name": "Jared Zirkel", "school": "Texas AM"},
  {"team": "3", "unit": "SpecialTeams", "position": "PT", "name": "Jeremy Crawshaw", "school": "Florida"},
  {"team": "3", "unit": "SpecialTeams", "position": "KR", "name": "Zavion Thomas", "school": "LSU"},
  {"team": "3", "unit": "SpecialTeams", "position": "PR", "name": "Boo Carter", "school": "Tennessee"},
  {"team": "3", "unit": "SpecialTeams", "position": "ST", "name": "Lewis Carter", "school": "Oklahoma"},
{"position":"QB","name":"Carson Beck","school":"Georgia","team":"honorable_mention"},
  {"position":"QB","name":"Nico Iamaleava","school":"Tennessee","team":"honorable_mention"},
  {"position":"QB","name":"Garrett Nussmeier","school":"LSU","team":"honorable_mention"},
  {"position":"RB","name":"Jam Miller","school":"Alabama","team":"honorable_mention"},
  {"position":"RB","name":"Marcus Carroll","school":"Missouri","team":"honorable_mention"},
  {"position":"RB","name":"Davon Booth","school":"Mississippi State","team":"honorable_mention"},
  {"position":"RB","name":"Amari Daniels","school":"Texas AM","team":"honorable_mention"},
  {"position":"RB","name":"Quintrevion Wisner","school":"Texas","team":"honorable_mention"},
  {"position":"RB","name":"Nate Noel","school":"Missouri","team":"honorable_mention"},
  {"position":"WR-X","name":"Luther Burden III","school":"Missouri","team":"honorable_mention"},
  {"position":"WR-Y","name":"Dont’e Thornton Jr.","school":"Tennessee","team":"honorable_mention"},
  {"position":"WR-X","name":"Cam Coleman","school":"Auburn","team":"honorable_mention"},
  {"position":"WR-X","name":"Dominic Lovett","school":"Georgia","team":"honorable_mention"},
  {"position":"WR-H","name":"Isaiah Bond","school":"Texas","team":"honorable_mention"},
  {"position":"WR-Y","name":"Antwane Wells Jr.","school":"Ole Miss","team":"honorable_mention"},
  {"position":"WR-Z","name":"Jordan Watkins","school":"Ole Miss","team":"honorable_mention"},
  {"position":"WR-Z","name":"Chimere Dike","school":"Florida","team":"honorable_mention"},
  {"position":"WR-Z","name":"Germie Bernard","school":"Alabama","team":"honorable_mention"},
  {"position":"TE","name":"Caden Prieskorn","school":"Ole Miss","team":"honorable_mention"},
  {"position":"TE","name":"Lawson Luckie","school":"Georgia","team":"honorable_mention"},
  {"position":"TE","name":"Joshua Simon","school":"South Carolina","team":"honorable_mention"},
  {"position":"RB","name":"Jaydon Blue","school":"Texas","team":"honorable_mention"},
  {"position":"TE","name":"Seydou Traore","school":"Mississippi State","team":"honorable_mention"},
  {"position":"TE","name":"Luke Hasz","school":"Arkansas","team":"honorable_mention"},
  {"position":"RT","name":"Dametrious Crownover","school":"Texas AM","team":"honorable_mention"},
  {"position":"LT","name":"Monroe Freeling","school":"Georgia","team":"honorable_mention"},
  {"position":"LG","name":"Cameron Williams","school":"Texas","team":"honorable_mention"},
  {"position":"RG","name":"Tyler Booker","school":"Alabama","team":"honorable_mention"},
  {"position":"LG","name":"Andrej Karic","school":"Tennessee","team":"honorable_mention"},
  {"position":"RG","name":"Tate Ratledge","school":"Georgia","team":"honorable_mention"},
  {"position":"C","name":"Cooper Mays","school":"Tennessee","team":"honorable_mention"},
  {"position":"C","name":"Connor Tollison","school":"Missouri","team":"honorable_mention"},
  {"position":"C","name":"Delfin Xavier Castillo","school":"Vanderbilt","team":"honorable_mention"},
  {"position":"LG","name":"Miles Frazier","school":"LSU","team":"honorable_mention"},
  {"position":"RG","name":"Jeremiah Wright","school":"Auburn","team":"honorable_mention"},
  {"position":"RG","name":"DJ Campbell","school":"Texas","team":"honorable_mention"},
  {"position":"LG","name":"Fernando Carmona","school":"Arkansas","team":"honorable_mention"},
  {"position":"LT","name":"Will Campbell","school":"LSU","team":"honorable_mention"},
  {"position":"RT","name":"Brandon Crenshaw‑Dickson","school":"Florida","team":"honorable_mention"},
  {"position":"DE","name":"Johnny Walker Jr.","school":"Missouri","team":"honorable_mention"},
  {"position":"BAN","name":"LT Overton","school":"Alabama","team":"honorable_mention"},
  {"position":"DE","name":"Keldric Faulk","school":"Auburn","team":"honorable_mention"},
  {"position":"NT","name":"Cam’Ron Jackson","school":"Florida","team":"honorable_mention"},
  {"position":"DT","name":"Gracen Halton","school":"Oklahoma","team":"honorable_mention"},
  {"position":"DT","name":"Alfred Collins","school":"Texas","team":"honorable_mention"},
  {"position":"DT","name":"Shemar Turner","school":"Texas AM","team":"honorable_mention"},
  {"position":"RDT","name":"Eric Gregory","school":"Arkansas","team":"honorable_mention"},
  {"position":"DT","name":"Deone Walker","school":"Kentucky","team":"honorable_mention"},
  {"position":"BUCK","name":"Colin Simmons","school":"Texas","team":"honorable_mention"},
  {"position":"JACK","name":"Barryn Sorrell","school":"Texas","team":"honorable_mention"},
  {"position":"LDE","name":"Landon Jackson","school":"Arkansas","team":"honorable_mention"},
  {"position":"MLB","name":"Demetrius Knight Jr.","school":"South Carolina","team":"honorable_mention"},
  {"position":"MLB","name":"Bryan Longwell","school":"Vanderbilt","team":"honorable_mention"},
  {"position":"MAC","name":"Smael Mondon","school":"Georgia","team":"honorable_mention"},
  {"position":"WLB","name":"Kip Lewis","school":"Oklahoma","team":"honorable_mention"},
  {"position":"MLB","name":"Dorian Mausi","school":"Auburn","team":"honorable_mention"},
  {"position":"MLB","name":"Corey Flagg","school":"Missouri","team":"honorable_mention"},
  {"position":"MLB","name":"Bam Martin-Scott","school":"South Carolina","team":"honorable_mention"},
  {"position":"MLB","name":"Stone Blanton","school":"Mississippi State","team":"honorable_mention"},
  {"position":"MLB","name":"Greg Penn III","school":"LSU","team":"honorable_mention"},
  {"position":"LCB","name":"O’Donnell Fortune","school":"South Carolina","team":"honorable_mention"},
  {"position":"FCB","name":"Martel Hight","school":"Vanderbilt","team":"honorable_mention"},
  {"position":"RCB","name":"Zy Alexander","school":"LSU","team":"honorable_mention"},
  {"position":"NB","name":"Boo Carter","school":"Tennessee","team":"honorable_mention"},
  {"position":"LCB","name":"Doneiko Slaughter","school":"Arkansas","team":"honorable_mention"},
  {"position":"LCB","name":"Kayin Lee","school":"Auburn","team":"honorable_mention"},
  {"position":"BCB","name":"Jonquis Hardaway","school":"Kentucky","team":"honorable_mention"},
  {"position":"RCB","name":"Drey Norwood","school":"Missouri","team":"honorable_mention"},
  {"position":"RCB","name":"Jay Crawford","school":"Auburn","team":"honorable_mention"},
  {"position":"SS","name":"Major Burns","school":"LSU","team":"honorable_mention"},
  {"position":"NB","name":"Isaac Smith","school":"Mississippi State","team":"honorable_mention"},
  {"position":"STAR","name":"Randon Fontenette","school":"Vanderbilt","team":"honorable_mention"},
  {"position":"SS","name":"TJ Metcalf","school":"Arkansas","team":"honorable_mention"},
  {"position":"FS","name":"Jordan Castell","school":"Florida","team":"honorable_mention"},
  {"position":"FS","name":"Sage Ryan","school":"LSU","team":"honorable_mention"},
  {"position":"FS","name":"Malaki Starks","school":"Georgia","team":"honorable_mention"},
  {"position":"SS","name":"Zion Childress","school":"Kentucky","team":"honorable_mention"},
  {"position":"NB","name":"Daylan Carnell","school":"Missouri","team":"honorable_mention"},
  {"position":"RDE","name":"Sai’vion Jones","school":"LSU","team":"honorable_mention"},
  {"position":"SS","name":"Trikweze Bridges","school":"Florida","team":"honorable_mention"},
  {"position":"FS","name":"Keon Sabb","school":"Alabama","team":"honorable_mention"},
  {"position":"PK","name":"Trey Smack","school":"Florida","team":"honorable_mention"},
  {"position":"PK","name":"Alex Raynor","school":"Kentucky","team":"honorable_mention"},
  {"position":"KO","name":"Josh Turbyville","school":"Tennessee","team":"honorable_mention"},
  {"position":"PT","name":"James Burnip","school":"Alabama","team":"honorable_mention"},
  {"position":"KR","name":"Jeremiah Cobb","school":"Auburn","team":"honorable_mention"},
  {"position":"PR","name":"Chimere Dike","school":"Florida","team":"honorable_mention"},
  {"position":"RAZOR","name":"Jailen Ruth","school":"Vanderbilt","team":"honorable_mention"}
  ]
}
