"""CFN All-CUSA Conference List 2024"""

ALL_C_USA = {
  "year": 2024,
  "name_of_award": "all_conference",
  "conference": "c_usa",
  "source": "cfn",
  "c_usa" : [
       {"award": "PlayerOfTheYear", "name": "Tre Stewart", "position": "RB", "school": "Jacksonville State"},
      {"award": "OffensivePlayerOfTheYear", "name": "Tre Stewart", "position": "RB", "school": "Jacksonville State"},
      {"award": "DefensivePlayerOfTheYear", "name": "Caleb Weaver", "position": "SS", "school": "Sam Houston"},
      {"award": "SpecialistOfTheYear", "name": "Buck Buchanan", "position": "KO", "school": "Louisiana Tech"},
      {"award": "NewcomerOfTheYear", "name": "Malaki Ta’ase", "position": "LDE", "school": "New Mexico State"},
      {"award": "CoachOfTheYear", "name": "Rich Rodriguez", "position": "Coach", "school": "Jacksonville State"},
      {"award": "ImpactFreshmanOfTheYear", "name": "Malaki Ta’ase", "position": "LDE", "school": "New Mexico State"},
      {"award": "QuarterbackOfTheYear", "name": "Tyler Huff", "position": "QB", "school": "Jacksonville State"},
  {"award": "RunningBackOfTheYear", "name": "Tre Stewart", "position": "RB", "school": "Jacksonville State"},
  {"award": "WideReceiverOfTheYear", "name": "Eric Rivers", "position": "WR-X", "school": "Florida International"},
  {"award": "TightEndOfTheYear", "name": "Holden Willis", "position": "TE", "school": "Middle Tennessee"},
  {"award": "OffensiveTackleOfTheYear", "name": "Will O’Steen", "position": "LT", "school": "Jacksonville State"},
  {"award": "OffensiveGuardOfTheYear", "name": "Jordan White", "position": "C", "school": "Liberty"},
  {"award": "CenterOfTheYear", "name": "Canaan Yarro", "position": "C", "school": "New Mexico State"},
  {"award": "OffensiveLinemanOfTheYear", "name": "Will O’Steen", "position": "LT", "school": "Jacksonville State"},
  {"award": "OffensiveLineOfTheYear", "name": "Liberty Flames", "position": "OL", "school": "Liberty"},
  {"award": "OffensiveNewcomerOfTheYear", "name": "Kenny Odom", "position": "WR-Z", "school": "UTEP"},
  {"award": "OffensiveTransferOfTheYear", "name": "Kenny Odom", "position": "WR-Z", "school": "UTEP"},
  {"award": "EdgeDefenderOfTheYear", "name": "Chris Murray", "position": "BUCK", "school": "Sam Houston"},
  {"award": "InteriorDefenderOfTheYear", "name": "Tylon Dunlap", "position": "RDE", "school": "Kennesaw State"},
  {"award": "LinebackerOfTheYear", "name": "Travion Barnes", "position": "LILB", "school": "Florida International"},
  {"award": "CornerbackOfTheYear", "name": "Brian Blades II", "position": "RCB", "school": "Florida International"},
  {"award": "SafetyOfTheYear", "name": "Caleb Weaver", "position": "SS", "school": "Sam Houston"},
  {"award": "DefensiveLineOfTheYear", "name": "Sam Houston Bearkats", "position": "DL", "school": "Sam Houston"},
  {"award": "SecondaryOfTheYear", "name": "Jacksonville State Gamecocks", "position": "Secondary", "school": "Jacksonville State"},
  {"award": "DefensiveNewcomerOfTheYear", "name": "Malaki Ta’ase", "position": "LDE", "school": "New Mexico State"},
  {"award": "DefensiveTransferOfTheYear", "name": "Antonio Carter II", "position": "SS", "school": "Jacksonville State"},
  {"award": "KickerOfTheYear", "name": "Lucas Carneiro", "position": "PK", "school": "Western Kentucky"},
  {"award": "PunterOfTheYear", "name": "Jacob Ulrich", "position": "PT", "school": "Kennesaw State"},
  {"award": "KickReturnerOfTheYear", "name": "Qua Ashley", "position": "KR", "school": "Kennesaw State"},
  {"award": "PuntReturnerOfTheYear", "name": "Kam Thomas", "position": "PR", "school": "UTEP"},
  {"award": "SpecialTeamerOfTheYear", "name": "Kam Thomas", "position": "WR-SL", "school": "UTEP"},
  {"award": "KickoffSpecialistOfTheYear", "name": "Travis Franklin Jr.", "position": "KOS", "school": "Jacksonville State"},
 {"team": "1", "unit": "Offense", "position": "QB", "name": "Tyler Huff", "school": "Jacksonville State"},
  {"team": "1", "unit": "Offense", "position": "RB", "name": "Tre Stewart", "school": "Jacksonville State"},
  {"team": "1", "unit": "Offense", "position": "RB", "name": "Quinton Cooley", "school": "Liberty"},
  {"team": "1", "unit": "Offense", "position": "WR-X", "name": "Eric Rivers", "school": "Florida International"},
  {"team": "1", "unit": "Offense", "position": "WR-Z", "name": "Kenny Odom", "school": "UTEP"},
  {"team": "1", "unit": "Offense", "position": "WR-Z", "name": "Tru Edwards", "school": "Louisiana Tech"},
  {"team": "1", "unit": "Offense", "position": "TE", "name": "Holden Willis", "school": "Middle Tennessee"},
  {"team": "1", "unit": "Offense", "position": "WR-Z", "name": "Dean Patterson", "school": "Florida International"},
  {"team": "1", "unit": "Offense", "position": "LT", "name": "Will O’Steen", "school": "Jacksonville State"},
  {"team": "1", "unit": "Offense", "position": "C", "name": "Jordan White", "school": "Liberty"},
  {"team": "1", "unit": "Offense", "position": "C", "name": "Canaan Yarro", "school": "New Mexico State"},
  {"team": "1", "unit": "Offense", "position": "LG", "name": "Clay Webb", "school": "Jacksonville State"},
  {"team": "1", "unit": "Offense", "position": "RT", "name": "Jordan Hall", "school": "Liberty"},

  {"team": "1", "unit": "Defense", "position": "BUCK", "name": "Chris Murray", "school": "Sam Houston"},
  {"team": "1", "unit": "Defense", "position": "RDE", "name": "Tylon Dunlap", "school": "Kennesaw State"},
  {"team": "1", "unit": "Defense", "position": "NT", "name": "Jamarrion Solomon", "school": "Florida International"},
  {"team": "1", "unit": "Defense", "position": "BAN", "name": "Maurice Westmoreland", "school": "UTEP"},
  {"team": "1", "unit": "Defense", "position": "LILB", "name": "Travion Barnes", "school": "Florida International"},
  {"team": "1", "unit": "Defense", "position": "MLB", "name": "Kavian Gaither", "school": "Sam Houston"},
  {"team": "1", "unit": "Defense", "position": "MLB", "name": "Reginald Hughes", "school": "Jacksonville State"},
  {"team": "1", "unit": "Defense", "position": "LCB", "name": "Geimere Latimer", "school": "Jacksonville State"},
  {"team": "1", "unit": "Defense", "position": "LCB", "name": "Anthony Johnson Jr.", "school": "Western Kentucky"},
  {"team": "1", "unit": "Defense", "position": "RCB", "name": "Brian Blades II", "school": "Florida International"},
  {"team": "1", "unit": "Defense", "position": "FS", "name": "Zechariah Poyser", "school": "Jacksonville State"},
  {"team": "1", "unit": "Defense", "position": "SS", "name": "Caleb Weaver", "school": "Sam Houston"},
  {"team": "1", "unit": "Defense", "position": "SS", "name": "Upton Stout", "school": "Western Kentucky"},
  {"team": "1", "unit": "Defense", "position": "LDE", "name": "J-Rock Swain", "school": "Jacksonville State"},

  {"team": "1", "unit": "SpecialTeams", "position": "PK", "name": "Lucas Carneiro", "school": "Western Kentucky"},
  {"team": "1", "unit": "SpecialTeams", "position": "KO", "name": "Buck Buchanan", "school": "Louisiana Tech"},
  {"team": "1", "unit": "SpecialTeams", "position": "PT", "name": "Jacob Ulrich", "school": "Kennesaw State"},
  {"team": "1", "unit": "SpecialTeams", "position": "KR", "name": "Qua Ashley", "school": "Kennesaw State"},
  {"team": "1", "unit": "SpecialTeams", "position": "PR", "name": "Kam Thomas", "school": "UTEP"},
  {"team": "1", "unit": "SpecialTeams", "position": "NB", "name": "Travis Franklin Jr.", "school": "Jacksonville State"},
 {"team": "2", "unit": "Offense", "position": "QB", "name": "Caden Veltkamp", "school": "Western Kentucky"},
  {"team": "2", "unit": "Offense", "position": "RB", "name": "Elijah Young", "school": "Western Kentucky"},
  {"team": "2", "unit": "Offense", "position": "RB", "name": "Mike Washington", "school": "New Mexico State"},
  {"team": "2", "unit": "Offense", "position": "WR-Z", "name": "Omari Kelly", "school": "Middle Tennessee"},
  {"team": "2", "unit": "Offense", "position": "WR-SL", "name": "Eason Messer", "school": "Western Kentucky"},
  {"team": "2", "unit": "Offense", "position": "WR-X", "name": "Kisean Johnson", "school": "Western Kentucky"},
  {"team": "2", "unit": "Offense", "position": "TE", "name": "Carson Kent", "school": "Kennesaw State"},
  {"team": "2", "unit": "Offense", "position": "TE", "name": "Sean Brown", "school": "Jacksonville State"},
  {"team": "2", "unit": "Offense", "position": "LT", "name": "Xavior Gray", "school": "Liberty"},
  {"team": "2", "unit": "Offense", "position": "C", "name": "Rodney Newsom", "school": "Western Kentucky"},
  {"team": "2", "unit": "Offense", "position": "C", "name": "Aaron Fenimore", "school": "Liberty"},
  {"team": "2", "unit": "Offense", "position": "RG", "name": "AJ Vaipulu", "school": "New Mexico State"},
  {"team": "2", "unit": "Offense", "position": "LT", "name": "Travis Burke", "school": "Florida International"},

  {"team": "2", "unit": "Defense", "position": "LOLB", "name": "TJ Bush", "school": "Liberty"},
  {"team": "2", "unit": "Defense", "position": "LDT", "name": "Chris Boti", "school": "Liberty"},
  {"team": "2", "unit": "Defense", "position": "LDE", "name": "Malaki Ta’ase", "school": "New Mexico State"},
  {"team": "2", "unit": "Defense", "position": "DT", "name": "Jevon Leon", "school": "Sam Houston"},
  {"team": "2", "unit": "Defense", "position": "MLB", "name": "Laletia Hale", "school": "Jacksonville State"},
  {"team": "2", "unit": "Defense", "position": "WLB", "name": "Darius Thomas", "school": "Western Kentucky"},
  {"team": "2", "unit": "Defense", "position": "WLB", "name": "Ky’won McCray", "school": "Jacksonville State"},
  {"team": "2", "unit": "Defense", "position": "LCB", "name": "Jabari Mack", "school": "Jacksonville State"},
  {"team": "2", "unit": "Defense", "position": "LCB", "name": "JeRico Washington Jr.", "school": "Kennesaw State"},
  {"team": "2", "unit": "Defense", "position": "LCB", "name": "Amarian Williams", "school": "Liberty"},
  {"team": "2", "unit": "Defense", "position": "SS", "name": "Antonio Carter II", "school": "Jacksonville State"},
  {"team": "2", "unit": "Defense", "position": "FS", "name": "Devonte’ Mathews", "school": "Western Kentucky"},
  {"team": "2", "unit": "Defense", "position": "SS", "name": "JoJo Evans", "school": "Florida International"},
  {"team": "2", "unit": "Defense", "position": "NB", "name": "Fred Perry", "school": "Jacksonville State"},

  {"team": "2", "unit": "SpecialTeams", "position": "PK", "name": "Abraham Montano", "school": "New Mexico State"},
  {"team": "2", "unit": "SpecialTeams", "position": "KO", "name": "Garrison Rippa", "school": "Jacksonville State"},
  {"team": "2", "unit": "SpecialTeams", "position": "PT", "name": "Grant Chadwick", "school": "Middle Tennessee"},
  {"team": "2", "unit": "SpecialTeams", "position": "KR", "name": "C’Quan Jnopierre", "school": "Florida International"},
  {"team": "2", "unit": "SpecialTeams", "position": "PR", "name": "Solo Lewis", "school": "Louisiana Tech"},
  {"team": "2", "unit": "SpecialTeams", "position": "SS", "name": "Elias Escobar", "school": "Sam Houston"},
 {"team": "3", "unit": "Offense", "position": "QB", "name": "Hunter Watson", "school": "Sam Houston"},
  {"team": "3", "unit": "Offense", "position": "RB", "name": "Seth McGowan", "school": "New Mexico State"},
  {"team": "3", "unit": "Offense", "position": "RB", "name": "Jay Ducker", "school": "Sam Houston"},
  {"team": "3", "unit": "Offense", "position": "WR", "name": "Cam Vaughn", "school": "Jacksonville State"},
  {"team": "3", "unit": "Offense", "position": "WR", "name": "Treon Sibley", "school": "Liberty"},
  {"team": "3", "unit": "Offense", "position": "WR", "name": "Simeon Evans", "school": "Sam Houston"},
  {"team": "3", "unit": "Offense", "position": "TE", "name": "Eli Finley", "school": "Louisiana Tech"},
  {"team": "3", "unit": "Offense", "position": "WR-X", "name": "Qua’Vez Humphreys", "school": "Sam Houston"},
  {"team": "3", "unit": "Offense", "position": "LT", "name": "Kolt Dieterich", "school": "Sam Houston"},
  {"team": "3", "unit": "Offense", "position": "RG", "name": "Harrison Hayes", "school": "Liberty"},
  {"team": "3", "unit": "Offense", "position": "C", "name": "Ethan Hagler", "school": "Sam Houston"},
  {"team": "3", "unit": "Offense", "position": "RG", "name": "Otis Pitts III", "school": "UTEP"},
  {"team": "3", "unit": "Offense", "position": "LT", "name": "Marshall Jackson", "school": "Western Kentucky"},

  {"team": "3", "unit": "Defense", "position": "DE", "name": "Eddie Walls III", "school": "Florida International"},
  {"team": "3", "unit": "Defense", "position": "DT", "name": "KD Johnson", "school": "UTEP"},
  {"team": "3", "unit": "Defense", "position": "NT", "name": "Damonte Smith", "school": "Middle Tennessee"},
  {"team": "3", "unit": "Defense", "position": "DE", "name": "Deante McCray", "school": "Western Kentucky"},
  {"team": "3", "unit": "Defense", "position": "MLB", "name": "Elijah Anderson-Taylor", "school": "Florida International"},
  {"team": "3", "unit": "Defense", "position": "MLB", "name": "Trey Fields", "school": "Sam Houston"},
  {"team": "3", "unit": "Defense", "position": "WLB", "name": "Kolbe Fields", "school": "Louisiana Tech"},
  {"team": "3", "unit": "Defense", "position": "LCB", "name": "David Fisher", "school": "Sam Houston"},
  {"team": "3", "unit": "Defense", "position": "RCB", "name": "Dexter Ricks Jr.", "school": "Liberty"},
  {"team": "3", "unit": "Defense", "position": "RCB", "name": "Amier Boyd", "school": "UTEP"},
  {"team": "3", "unit": "Defense", "position": "SS", "name": "Kory Chapman", "school": "UTEP"},
  {"team": "3", "unit": "Defense", "position": "SS", "name": "Isaiah Cash", "school": "Sam Houston"},
  {"team": "3", "unit": "Defense", "position": "FS", "name": "Brylan Green", "school": "Liberty"},
  {"team": "3", "unit": "Defense", "position": "RCB", "name": "Jaylon Jimmerson", "school": "Sam Houston"},

  {"team": "3", "unit": "SpecialTeams", "position": "PK", "name": "Zeke Rankin", "school": "Middle Tennessee"},
  {"team": "3", "unit": "SpecialTeams", "position": "KO", "name": "Abraham Montano", "school": "New Mexico State"},
  {"team": "3", "unit": "SpecialTeams", "position": "PT", "name": "Patrick Rea", "school": "Louisiana Tech"},
  {"team": "3", "unit": "SpecialTeams", "position": "KR", "name": "Corey Wren", "school": "UTEP"},
  {"team": "3", "unit": "SpecialTeams", "position": "PR", "name": "Brylan Green", "school": "Liberty"},
  {"team": "3", "unit": "SpecialTeams", "position": "MLB", "name": "Chandler Matthews", "school": "Western Kentucky"},
{"team": "honorable_mention", "position": "QB", "name": "Nicholas Vattiato", "school": "Middle Tennessee"},
  {"team": "honorable_mention", "position": "QB", "name": "Keyone Jenkins", "school": "Florida International"},
  {"team": "honorable_mention", "position": "QB", "name": "Kaidon Salter", "school": "Liberty"},
  {"team": "honorable_mention", "position": "RB", "name": "Omiri Wiggins", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "RB", "name": "Kejon Owens", "school": "Florida International"},
  {"team": "honorable_mention", "position": "RB", "name": "Billy Lucas", "school": "Liberty"},
  {"team": "honorable_mention", "position": "RB", "name": "DJ McKinney", "school": "Sam Houston"},
  {"team": "honorable_mention", "position": "RB", "name": "Jevon Jackson", "school": "UTEP"},
  {"team": "honorable_mention", "position": "RB", "name": "Michael Benefield", "school": "Kennesaw State"},
  {"team": "honorable_mention", "position": "WR-SL", "name": "Kam Thomas", "school": "UTEP"},
  {"team": "honorable_mention", "position": "WR-X", "name": "Jimmy Holiday", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "WR-Z", "name": "KD Hutchinson", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "WR-SL", "name": "Michael Pettway", "school": "Jacksonville State"},
  {"team": "honorable_mention", "position": "WR-H", "name": "TJ Pride", "school": "New Mexico State"},
  {"team": "honorable_mention", "position": "WR-A", "name": "Myles Butler", "school": "Middle Tennessee"},
  {"team": "honorable_mention", "position": "WR-Z", "name": "Trey Goodman", "school": "UTEP"},
  {"team": "honorable_mention", "position": "WR-Z", "name": "Dalvin Smith", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "WR-Z", "name": "Elijah Canion", "school": "Liberty"},
  {"team": "honorable_mention", "position": "TE", "name": "Elijah Sohn", "school": "Sam Houston"},
  {"team": "honorable_mention", "position": "TE", "name": "Marcus Vinson", "school": "UTEP"},
  {"team": "honorable_mention", "position": "TE", "name": "River Helms", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "TE", "name": "Bentley Hanshaw", "school": "Liberty"},
  {"team": "honorable_mention", "position": "RB", "name": "Lexington Joseph", "school": "Florida International"},
  {"team": "honorable_mention", "position": "RB", "name": "Jaiden Credle", "school": "Middle Tennessee"},
  {"team": "honorable_mention", "position": "RT", "name": "Louie Canepa", "school": "New Mexico State"},
  {"team": "honorable_mention", "position": "LT", "name": "Jack Tucker", "school": "Liberty"},
  {"team": "honorable_mention", "position": "RT", "name": "Mason Bowers", "school": "Kennesaw State"},
  {"team": "honorable_mention", "position": "LG", "name": "JT Pennington", "school": "Kennesaw State"},
  {"team": "honorable_mention", "position": "LG", "name": "Ellis Adams", "school": "Middle Tennessee"},
  {"team": "honorable_mention", "position": "RG", "name": "Quantavious Leslie", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "C", "name": "Daveion Harley", "school": "Jacksonville State"},
  {"team": "honorable_mention", "position": "C", "name": "Evan Wibberley", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "C", "name": "Simon Wilson", "school": "Middle Tennessee"},
  {"team": "honorable_mention", "position": "OG", "name": "John Paul Flores", "school": "Liberty"},
  {"team": "honorable_mention", "position": "OG", "name": "Ben Shellenback", "school": "Florida International"},
  {"team": "honorable_mention", "position": "OG", "name": "Bert Hale", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "OT", "name": "Jacob Kettels", "school": "Kennesaw State"},
  {"team": "honorable_mention", "position": "OT", "name": "Cam Jones", "school": "Jacksonville State"},
  {"team": "honorable_mention", "position": "OT", "name": "Rhett Larson", "school": "Sam Houston"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Jordan Miles", "school": "Kennesaw State"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Buddha Peleti", "school": "New Mexico State"},
  {"team": "honorable_mention", "position": "EDGE", "name": "J’Dan Burnett", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "DT", "name": "Hosea Wheeler", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "DT", "name": "Naki Fahina", "school": "New Mexico State"},
  {"team": "honorable_mention", "position": "DT", "name": "Denver Warren", "school": "Sam Houston"},
  {"team": "honorable_mention", "position": "DT", "name": "Dallas Walker IV", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "DT", "name": "David Blay", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "DT", "name": "Jeramy Passmore", "school": "Florida International"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Jessie Evans", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "EDGE", "name": "CJ Bazile Jr.", "school": "Liberty"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Jawaun Campbell", "school": "Jacksonville State"},
  {"team": "honorable_mention", "position": "LB", "name": "Chandler Matthews", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "LB", "name": "Garland Benyard", "school": "Kennesaw State"},
  {"team": "honorable_mention", "position": "LB", "name": "Zach Zimos", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "LB", "name": "Dorian Hopkins", "school": "UTEP"},
  {"team": "honorable_mention", "position": "LB", "name": "Parker Hughes", "school": "Middle Tennessee"},
  {"team": "honorable_mention", "position": "LB", "name": "Nate Dyman", "school": "UTEP"},
  {"team": "honorable_mention", "position": "LB", "name": "Joseph Carter", "school": "Liberty"},
  {"team": "honorable_mention", "position": "LB", "name": "Donelius Johnson", "school": "Kennesaw State"},
  {"team": "honorable_mention", "position": "LB", "name": "Tyler Martinez", "school": "New Mexico State"},
  {"team": "honorable_mention", "position": "CB", "name": "Hezekiah Masses", "school": "Florida International"},
  {"team": "honorable_mention", "position": "CB", "name": "Fred Davis II", "school": "Jacksonville State"},
  {"team": "honorable_mention", "position": "CB", "name": "Tyler Hallum", "school": "Kennesaw State"},
  {"team": "honorable_mention", "position": "CB", "name": "Dakerric Hobbs", "school": "New Mexico State"},
  {"team": "honorable_mention", "position": "CB", "name": "Tyrell Raby", "school": "Middle Tennessee"},
  {"team": "honorable_mention", "position": "CB", "name": "Alex Oliver", "school": "Liberty"},
  {"team": "honorable_mention", "position": "CB", "name": "Demarcus Griffin-Taylor", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "CB", "name": "Cedric Woods", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "CB", "name": "Marvae Myers", "school": "Middle Tennessee"},
  {"team": "honorable_mention", "position": "SS", "name": "Dylan Early", "school": "New Mexico State"},
  {"team": "honorable_mention", "position": "SS", "name": "Blake Thompson", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "SS", "name": "Jamal Potts", "school": "Florida International"},
  {"team": "honorable_mention", "position": "FS", "name": "CJ Christian", "school": "Florida International"},
  {"team": "honorable_mention", "position": "FS", "name": "John Howse IV", "school": "Middle Tennessee"},
  {"team": "honorable_mention", "position": "FS", "name": "Demarko Williams", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "S", "name": "Tayden Barnes", "school": "New Mexico State"},
  {"team": "honorable_mention", "position": "S", "name": "Milon Jones", "school": "Kennesaw State"},
  {"team": "honorable_mention", "position": "S", "name": "A’Khori Jones", "school": "Liberty"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Sebastian Benjamin", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Sone Aupiu", "school": "New Mexico State"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Kent Robinson", "school": "Western Kentucky"},
  {"team": "honorable_mention", "position": "PK", "name": "Buck Buchanan", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "KOS", "name": "Alejandro Prado", "school": "Florida International"},
  {"team": "honorable_mention", "position": "P", "name": "George Eberle", "school": "New Mexico State"},
  {"team": "honorable_mention", "position": "KR", "name": "Demarcus Griffin-Taylor", "school": "Louisiana Tech"},
  {"team": "honorable_mention", "position": "PR", "name": "Omari Kelly", "school": "Middle Tennessee"},
  {"team": "honorable_mention", "position": "ST", "name": "Chris Johnson", "school": "Middle Tennessee"}
  ]
}
