"""CFN All-MAC Conference List 2024"""


ALL_MAC = {
  "year": 2024,
  "name_of_award": "all_conference",
  "conference": "mac",
  "source": "cfn",
  "mac" : [
      {"award": "PlayerOfTheYear", "name": "Harold Fannin Jr.", "position": "TE", "school": "Bowling Green"},
  {"award": "OffensivePlayerOfTheYear", "name": "Harold Fannin Jr.", "position": "TE", "school": "Bowling Green"},
  {"award": "DefensivePlayerOfTheYear", "name": "Shaun Dolac", "position": "LB", "school": "Buffalo"},
  {"award": "SpecialistOfTheYear", "name": "Jesus Gomez", "position": "K", "school": "Eastern Michigan"},
  {"award": "NewcomerOfTheYear", "name": "Ben McNaboe", "position": "EDGE", "school": "Ohio"},
  {"award": "CoachOfTheYear", "name": "Tim Albin", "position": "Coach", "school": "Ohio"},
  {"award": "ImpactFreshmanOfTheYear", "name": "Jayden Studio", "position": "LB", "school": "Kent State"},
{"award": "QuarterbackOfTheYear", "name": "Parker Navarro", "position": "QB", "school": "Ohio"},
  {"award": "RunningBackOfTheYear", "name": "Anthony Tyus III", "position": "RB", "school": "Ohio"},
  {"award": "WideReceiverOfTheYear", "name": "Jerjuan Newton", "position": "WR", "school": "Toledo"},
  {"award": "TightEndOfTheYear", "name": "Harold Fannin Jr.", "position": "TE", "school": "Bowling Green"},
  {"award": "OffensiveTackleOfTheYear", "name": "Jack Sherwin", "position": "OT", "school": "Western Michigan"},
  {"award": "OffensiveGuardOfTheYear", "name": "John Champe", "position": "OG", "school": "Northern Illinois"},
  {"award": "CenterOfTheYear", "name": "Jacob Gideon", "position": "C", "school": "Western Michigan"},
  {"award": "OffensiveLinemanOfTheYear", "name": "Jacob Gideon", "position": "C", "school": "Western Michigan"},
  {"award": "OffensiveLineOfTheYear", "name": "Western Michigan Broncos", "position": "OL Unit", "school": "Western Michigan"},
  {"award": "OffensiveNewcomerOfTheYear", "name": "Coleman Owen", "position": "WR", "school": "Ohio"},
  {"award": "OffensiveTransferOfTheYear", "name": "Coleman Owen", "position": "WR", "school": "Ohio"},
  {"award": "EdgeDefenderOfTheYear", "name": "Brian Ugwu", "position": "EDGE", "school": "Miami University"},
  {"award": "InteriorDefenderOfTheYear", "name": "Devonte O’Malley", "position": "DL", "school": "Northern Illinois"},
  {"award": "LinebackerOfTheYear", "name": "Shaun Dolac", "position": "LB", "school": "Buffalo"},
  {"award": "CornerbackOfTheYear", "name": "Raion Strader", "position": "CB", "school": "Miami University"},
  {"award": "SafetyOfTheYear", "name": "Tate Hallock", "position": "S", "school": "Western Michigan"},
  {"award": "DefensiveLineOfTheYear", "name": "Ohio Bobcats", "position": "DL Unit", "school": "Ohio"},
  {"award": "SecondaryOfTheYear", "name": "Toledo Rockets", "position": "Secondary Unit", "school": "Toledo"},
  {"award": "DefensiveNewcomerOfTheYear", "name": "Ben McNaboe", "position": "EDGE", "school": "Ohio"},
  {"award": "DefensiveTransferOfTheYear", "name": "Ben McNaboe", "position": "EDGE", "school": "Ohio"},
  {"award": "KickerOfTheYear", "name": "Tristan Mattson", "position": "K", "school": "Central Michigan"},
  {"award": "PunterOfTheYear", "name": "Alex Bevelhimer", "position": "P", "school": "Miami University"},
  {"award": "KickReturnerOfTheYear", "name": "Malcolm Gillie", "position": "KR", "school": "Ball State"},
  {"award": "PuntReturnerOfTheYear", "name": "Donte Kent", "position": "PR", "school": "Central Michigan"},
  {"award": "SpecialTeamerOfTheYear", "name": "Avi McGary", "position": "ST", "school": "Bowling Green"},
  {"award": "KickoffSpecialistOfTheYear", "name": "Jesus Gomez", "position": "KOS", "school": "Eastern Michigan"},
  {"team": "1", "position": "QB", "name": "Parker Navarro", "school": "Ohio"},
  {"team": "1", "position": "RB", "name": "Anthony Tyus III", "school": "Ohio"},
  {"team": "1", "position": "RB", "name": "Keyon Mozee", "school": "Miami University"},
  {"team": "1", "position": "WR", "name": "Jerjuan Newton", "school": "Toledo"},
  {"team": "1", "position": "WR", "name": "Coleman Owen", "school": "Ohio"},
  {"team": "1", "position": "WR", "name": "Adrian Norton", "school": "Akron"},
  {"team": "1", "position": "TE", "name": "Harold Fannin Jr.", "school": "Bowling Green"},
  {"team": "1", "position": "FLEX", "name": "Tanner Koziol", "school": "Ball State"},
  {"team": "1", "position": "OT", "name": "Jack Sherwin", "school": "Western Michigan"},
  {"team": "1", "position": "OG", "name": "John Champe", "school": "Northern Illinois"},
  {"team": "1", "position": "OC", "name": "Jacob Gideon", "school": "Western Michigan"},
  {"team": "1", "position": "OG", "name": "Addison West", "school": "Western Michigan"},
  {"team": "1", "position": "OT", "name": "Reid Holskey", "school": "Miami University"},
  {"team": "1", "position": "EDGE", "name": "Brian Ugwu", "school": "Miami University"},
  {"team": "1", "position": "DT", "name": "Darius Alexander", "school": "Toledo"},
  {"team": "1", "position": "DT", "name": "Devonte O’Malley", "school": "Northern Illinois"},
  {"team": "1", "position": "EDGE", "name": "Bradley Weaver", "school": "Ohio"},
  {"team": "1", "position": "LB", "name": "Shaun Dolac", "school": "Buffalo"},
  {"team": "1", "position": "LB", "name": "Matt Salopek", "school": "Miami University"},
  {"team": "1", "position": "LB", "name": "Red Murdock", "school": "Buffalo"},
  {"team": "1", "position": "CB", "name": "Raion Strader", "school": "Miami University"},
  {"team": "1", "position": "CB", "name": "Jordan Oladokun", "school": "Bowling Green"},
  {"team": "1", "position": "CB", "name": "Tank Pearson", "school": "Ohio"},
  {"team": "1", "position": "SS", "name": "Tate Hallock", "school": "Western Michigan"},
  {"team": "1", "position": "FS", "name": "Nate Valcarcel", "school": "Northern Illinois"},
  {"team": "1", "position": "S", "name": "Maxen Hook", "school": "Toledo"},
  {"team": "1", "position": "FLEX", "name": "Brock Horne", "school": "Bowling Green"},
  {"team": "1", "position": "PK", "name": "Tristan Mattson", "school": "Central Michigan"},
  {"team": "1", "position": "KOS", "name": "Jesus Gomez", "school": "Eastern Michigan"},
  {"team": "1", "position": "P", "name": "Alex Bevelhimer", "school": "Miami University"},
  {"team": "1", "position": "KR", "name": "Malcolm Gillie", "school": "Ball State"},
  {"team": "1", "position": "PR", "name": "Donte Kent", "school": "Central Michigan"},
  {"team": "1", "position": "ST", "name": "Avi McGary", "school": "Bowling Green"},
 {"team": "2", "position": "QB", "name": "Kadin Semonza", "school": "Ball State"},
  {"team": "2", "position": "RB", "name": "Jaden Nixon", "school": "Western Michigan"},
  {"team": "2", "position": "RB", "name": "Terion Stewart", "school": "Bowling Green"},
  {"team": "2", "position": "WR", "name": "Javon Tracy", "school": "Miami University"},
  {"team": "2", "position": "WR", "name": "Reggie Virgin", "school": "Miami University"},
  {"team": "2", "position": "WR", "name": "Chrishon McCray", "school": "Kent State"},
  {"team": "2", "position": "TE", "name": "Anthony Torres", "school": "Toledo"},
  {"team": "2", "position": "FLEX", "name": "Blake Bosma", "school": "Western Michigan"},
  {"team": "2", "position": "OT", "name": "Alex Wollschlaeger", "school": "Bowling Green"},
  {"team": "2", "position": "OG", "name": "Mickey Rewolinski", "school": "Eastern Michigan"},
  {"team": "2", "position": "OC", "name": "Charlie Nank", "school": "Miami University"},
  {"team": "2", "position": "OG", "name": "J.J. Lippe", "school": "Northern Illinois"},
  {"team": "2", "position": "OT", "name": "Will Jados", "school": "Miami University"},
  {"team": "2", "position": "EDGE", "name": "Kobe Stewart", "school": "Buffalo"},
  {"team": "2", "position": "DT", "name": "Skyler Gill-Howard", "school": "Northern Illinois"},
  {"team": "2", "position": "DT", "name": "Anthony Hawkins", "school": "Bowling Green"},
  {"team": "2", "position": "EDGE", "name": "Ben McNaboe", "school": "Ohio"},
  {"team": "2", "position": "LB", "name": "Bryan McCoy", "school": "Akron"},
  {"team": "2", "position": "LB", "name": "Daniel Bolden", "school": "Toledo"},
  {"team": "2", "position": "LB", "name": "James Djonkam", "school": "Eastern Michigan"},
  {"team": "2", "position": "CB", "name": "Braden Awls", "school": "Toledo"},
  {"team": "2", "position": "CB", "name": "Avery Smith", "school": "Toledo"},
  {"team": "2", "position": "CB", "name": "Marquis Cooper", "school": "Buffalo"},
  {"team": "2", "position": "SS", "name": "DD Snyder II", "school": "Ball State"},
  {"team": "2", "position": "FS", "name": "Dustin Johnson", "school": "Ohio"},
  {"team": "2", "position": "S", "name": "DJ Walker", "school": "Ohio"},
  {"team": "2", "position": "FLEX", "name": "Ty Wise", "school": "Miami University"},
  {"team": "2", "position": "PK", "name": "Dom Dzioban", "school": "Miami University"},
  {"team": "2", "position": "KOS", "name": "Dante Jackson", "school": "Akron"},
  {"team": "2", "position": "P", "name": "Josh Smith", "school": "Kent State"},
  {"team": "2", "position": "KR", "name": "Jaden Nixon", "school": "Western Michigan"},
  {"team": "2", "position": "PR", "name": "Bryson Hammer", "school": "Toledo"},
  {"team": "2", "position": "ST", "name": "Joey Rattin", "school": "Northern Illinois"},
 {"team": "3", "position": "QB", "name": "Brett Gabbert", "school": "Miami University"},
  {"team": "3", "position": "RB", "name": "Delbert Mimms III", "school": "Eastern Michigan"},
  {"team": "3", "position": "RB", "name": "Jalen Buckley", "school": "Western Michigan"},
  {"team": "3", "position": "WR", "name": "Junier Vandeross III", "school": "Toledo"},
  {"team": "3", "position": "WR", "name": "Luke Floriea", "school": "Kent State"},
  {"team": "3", "position": "WR", "name": "Victor Snow", "school": "Buffalo"},
  {"team": "3", "position": "TE", "name": "Grayson Barnes", "school": "Northern Illinois"},
  {"team": "3", "position": "FLEX", "name": "Al-Jay Henderson", "school": "Buffalo"},
  {"team": "3", "position": "OT", "name": "Tedi Kushi", "school": "Western Michigan"},
  {"team": "3", "position": "OG", "name": "John Hofer", "school": "Western Michigan"},
  {"team": "3", "position": "OC", "name": "Logan Zschernitz", "school": "Northern Illinois"},
  {"team": "3", "position": "OG", "name": "Kolby Borders", "school": "Miami University"},
  {"team": "3", "position": "OT", "name": "Carson Heidecker", "school": "Ohio"},
  {"team": "3", "position": "EDGE", "name": "Riley Tolsma", "school": "Ball State"},
  {"team": "3", "position": "DT", "name": "Jason Williams", "school": "Central Michigan"},
  {"team": "3", "position": "DT", "name": "Peyton Price", "school": "Eastern Michigan"},
  {"team": "3", "position": "EDGE", "name": "Kameron Olds", "school": "Kent State"},
  {"team": "3", "position": "LB", "name": "Joseph Sipp Jr.", "school": "Bowling Green"},
  {"team": "3", "position": "LB", "name": "Jordan Kwiatkowski", "school": "Central Michigan"},
  {"team": "3", "position": "LB", "name": "Blake Leake", "school": "Ohio"},
  {"team": "3", "position": "CB", "name": "Myles Norwood", "school": "Ball State"},
  {"team": "3", "position": "CB", "name": "Nasir Bowers", "school": "Toledo"},
  {"team": "3", "position": "CB", "name": "Ja’Corey Benjamin", "school": "Bowling Green"},
  {"team": "3", "position": "SS", "name": "Silas Walters", "school": "Miami University"},
  {"team": "3", "position": "FS", "name": "Josh Baka", "school": "Kent State"},
  {"team": "3", "position": "S", "name": "Solomon Brown", "school": "Buffalo"},
  {"team": "3", "position": "FLEX", "name": "Donte Kent", "school": "Central Michigan"},
  {"team": "3", "position": "PK", "name": "Upton Bellenfant", "school": "Buffalo"},
  {"team": "3", "position": "KOS", "name": "Upton Bellenfant", "school": "Buffalo"},
  {"team": "3", "position": "P", "name": "John Henderson", "school": "Bowling Green"},
  {"team": "3", "position": "KR", "name": "Jacquez Stuart", "school": "Toledo"},
  {"team": "3", "position": "PR", "name": "Coleman Owen", "school": "Ohio"},
  {"team": "3", "position": "ST", "name": "Jaion Jackson", "school": "Central Michigan"},
{"team": "honorable_mention", "position": "QB", "name": "Connor Bazelak", "school": "Bowling Green"},
  {"team": "honorable_mention", "position": "QB", "name": "Tucker Gleason", "school": "Toledo"},
  {"team": "honorable_mention", "position": "QB", "name": "Ben Finley", "school": "Akron"},
  {"team": "honorable_mention", "position": "RB", "name": "B.J. Harris", "school": "Central Michigan"},
  {"team": "honorable_mention", "position": "RB", "name": "Zahir Abdus-Salaam", "school": "Western Michigan"},
  {"team": "honorable_mention", "position": "RB", "name": "Braedon Sloan", "school": "Ball State"},
  {"team": "honorable_mention", "position": "RB", "name": "Jordon Simmons", "school": "Akron"},
  {"team": "honorable_mention", "position": "RB", "name": "Marion Lukes", "school": "Central Michigan"},
  {"team": "honorable_mention", "position": "RB", "name": "Gavin Williams", "school": "Northern Illinois"},
  {"team": "honorable_mention", "position": "WR", "name": "Terry Lockett Jr.", "school": "Eastern Michigan"},
  {"team": "honorable_mention", "position": "WR", "name": "Markus Allen", "school": "Eastern Michigan"},
  {"team": "honorable_mention", "position": "WR", "name": "Oran Singleton Jr.", "school": "Eastern Michigan"},
  {"team": "honorable_mention", "position": "WR", "name": "JJ Jenkins", "school": "Buffalo"},
  {"team": "honorable_mention", "position": "WR", "name": "Malcolm Johnson Jr.", "school": "Bowling Green"},
  {"team": "honorable_mention", "position": "WR", "name": "Trayvon Rudolph", "school": "Northern Illinois"},
  {"team": "honorable_mention", "position": "WR", "name": "Kenneth Womack", "school": "Western Michigan"},
  {"team": "honorable_mention", "position": "WR", "name": "Chris Parker", "school": "Central Michigan"},
  {"team": "honorable_mention", "position": "WR", "name": "Anthony Sambucci", "school": "Western Michigan"},
  {"team": "honorable_mention", "position": "TE", "name": "Jake Orlando", "school": "Buffalo"},
  {"team": "honorable_mention", "position": "TE", "name": "Mason Williams", "school": "Ohio"},
  {"team": "honorable_mention", "position": "TE", "name": "Jake Newell", "school": "Akron"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Cam Thompson", "school": "Ball State"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Cam Pickett", "school": "Ball State"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Qian Magwood", "school": "Ball State"},
  {"team": "honorable_mention", "position": "OT", "name": "Evan Malcore", "school": "Northern Illinois"},
  {"team": "honorable_mention", "position": "OT", "name": "Henry Tabansi", "school": "Buffalo"},
  {"team": "honorable_mention", "position": "OT", "name": "Taran Tyo", "school": "Ball State"},
  {"team": "honorable_mention", "position": "OG", "name": "Tyler Doty", "school": "Buffalo"},
  {"team": "honorable_mention", "position": "OG", "name": "Nate Pabst", "school": "Bowling Green"},
  {"team": "honorable_mention", "position": "OG", "name": "Ethan Spoth", "school": "Toledo"},
  {"team": "honorable_mention", "position": "OC", "name": "Dom Polizzi", "school": "Buffalo"},
  {"team": "honorable_mention", "position": "OC", "name": "Parker Titsworth", "school": "Ohio"},
  {"team": "honorable_mention", "position": "OC", "name": "Dominic Serapiglia III", "school": "Central Michigan"},
  {"team": "honorable_mention", "position": "OG", "name": "Christophe Atkinson", "school": "Ohio"},
  {"team": "honorable_mention", "position": "OG", "name": "Jon Mucciolo", "school": "Ball State"},
  {"team": "honorable_mention", "position": "OG", "name": "Jake Burns", "school": "Bowling Green"},
  {"team": "honorable_mention", "position": "OT", "name": "Tunde Fatukasi", "school": "Bowling Green"},
  {"team": "honorable_mention", "position": "OT", "name": "Chris Hood", "school": "Ball State"},
  {"team": "honorable_mention", "position": "OT", "name": "Brayden Swartout", "school": "Central Michigan"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Stephen Daley", "school": "Kent State"},
  {"team": "honorable_mention", "position": "EDGE", "name": "CJ Nunnally", "school": "Akron"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Charles Rosser", "school": "Bowling Green"},
  {"team": "honorable_mention", "position": "DT", "name": "Jonah Pace", "school": "Central Michigan"},
  {"team": "honorable_mention", "position": "DT", "name": "Nathan Kapongo", "school": "Akron"},
  {"team": "honorable_mention", "position": "DT", "name": "Cavon Butler", "school": "Toledo"},
  {"team": "honorable_mention", "position": "DT", "name": "Isaiah Green", "school": "Western Michigan"},
  {"team": "honorable_mention", "position": "DT", "name": "Darin Conley", "school": "Ball State"},
  {"team": "honorable_mention", "position": "DT", "name": "Dontrez Brown", "school": "Bowling Green"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Dion Crawford", "school": "Buffalo"},
  {"team": "honorable_mention", "position": "EDGE", "name": "D’Andre Ragin", "school": "Toledo"},
  {"team": "honorable_mention", "position": "EDGE", "name": "Corey Suttle", "school": "Miami University"},
  {"team": "honorable_mention", "position": "LB", "name": "Jackson Barrow", "school": "Toledo"},
  {"team": "honorable_mention", "position": "LB", "name": "Antavious Fish", "school": "Akron"},
  {"team": "honorable_mention", "position": "LB", "name": "Dakota Cochran", "school": "Central Michigan"},
  {"team": "honorable_mention", "position": "LB", "name": "Joey Stemler", "school": "Ball State"},
  {"team": "honorable_mention", "position": "LB", "name": "Christian Fuhrman", "school": "Northern Illinois"},
  {"team": "honorable_mention", "position": "LB", "name": "Lance Dixon", "school": "Toledo"},
  {"team": "honorable_mention", "position": "LB", "name": "Shay Taylor", "school": "Ohio"},
  {"team": "honorable_mention", "position": "LB", "name": "Donald Willis", "school": "Western Michigan"},
  {"team": "honorable_mention", "position": "LB", "name": "Corban Hondru", "school": "Miami University"},
  {"team": "honorable_mention", "position": "CB", "name": "Jacob Finley", "school": "Northern Illinois"},
  {"team": "honorable_mention", "position": "CB", "name": "Da’Raun McKinney", "school": "Central Michigan"},
  {"team": "honorable_mention", "position": "CB", "name": "Bilhal Kone", "school": "Western Michigan"},
  {"team": "honorable_mention", "position": "CB", "name": "Nyquan Washington", "school": "Western Michigan"},
  {"team": "honorable_mention", "position": "CB", "name": "Daiquan White", "school": "Eastern Michigan"},
  {"team": "honorable_mention", "position": "CB", "name": "Roman Parodie", "school": "Ohio"},
  {"team": "honorable_mention", "position": "CB", "name": "Dallas Branch", "school": "Kent State"},
  {"team": "honorable_mention", "position": "CB", "name": "Devonte Golden-Nelson", "school": "Akron"},
  {"team": "honorable_mention", "position": "CB", "name": "Aman Greenwood", "school": "Akron"},
  {"team": "honorable_mention", "position": "SS", "name": "Paul Lewis III", "school": "Akron"},
  {"team": "honorable_mention", "position": "SS", "name": "George Udo", "school": "Ball State"},
  {"team": "honorable_mention", "position": "SS", "name": "Emmanuel McNeil-Warren", "school": "Toledo"},
  {"team": "honorable_mention", "position": "FS", "name": "Eli Blakey", "school": "Miami University"},
  {"team": "honorable_mention", "position": "FS", "name": "Marcus Fuqua", "school": "Buffalo"},
  {"team": "honorable_mention", "position": "FS", "name": "Aaron Wofford", "school": "Western Michigan"},
  {"team": "honorable_mention", "position": "S", "name": "Jalen McNair", "school": "Buffalo"},
  {"team": "honorable_mention", "position": "S", "name": "Elijah Rikard", "school": "Central Michigan"},
  {"team": "honorable_mention", "position": "S", "name": "Darrian Lewis", "school": "Akron"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Caleb Spann", "school": "Central Michigan"},
  {"team": "honorable_mention", "position": "FLEX", "name": "Santana Banner", "school": "Northern Illinois"},
  {"team": "honorable_mention", "position": "FLEX", "name": "CJ Brown", "school": "Bowling Green"},
  {"team": "honorable_mention", "position": "PK", "name": "Jesus Gomez", "school": "Eastern Michigan"},
  {"team": "honorable_mention", "position": "KOS", "name": "Kellan McLaughlin", "school": "Miami University"},
  {"team": "honorable_mention", "position": "P", "name": "Ethan Duane", "school": "Buffalo"},
  {"team": "honorable_mention", "position": "KR", "name": "Justin Pegues", "school": "Bowling Green"},
  {"team": "honorable_mention", "position": "PR", "name": "Victor Snow", "school": "Buffalo"},
  {"team": "honorable_mention", "position": "ST", "name": "Jack Fries", "school": "Ohio"}
  ]
}
