CFN_ALL_AMERICAN = {
  "year": 2024,
  "name_of_award": "all_american",
  "source": "cfn",
  "cfn": [
    {"name": "Ashton Jeanty", "position": "RB", "school": "Boise State", "award": "PlayerOfTheYear"},
    {"name": "Ashton Jeanty", "position": "RB", "school": "Boise State", "award": "OffensivePlayerOfTheYear"},
    {"name": "Shaun Dolac", "position": "MLB", "school": "Buffalo", "award": "DefensivePlayerOfTheYear"},
    {"name": "Dominic Zvada", "position": "PK", "school": "Michigan", "award": "SpecialistOfTheYear"},
    {"name": "Jeremiah Smith", "position": "WR-X", "school": "Ohio State", "award": "NewcomerOfTheYear"},
    {"name": "Curt Cignetti", "position": "Coach", "school": "Indiana", "award": "CoachOfTheYear"},
    {"name": "Jeremiah Smith", "position": "WR-X", "school": "Ohio State", "award": "ImpactFreshmanOfTheYear"},
    {"name": "Shedeur Sanders", "position": "QB", "school": "Colorado", "award": "QuarterbackOfTheYear"},
    {"name": "Ashton Jeanty", "position": "RB", "school": "Boise State", "award": "RunningBackOfTheYear"},
    {"name": "Nick Nash", "position": "WR-X", "school": "San Jose State", "award": "WideReceiverOfTheYear"},
    {"name": "Harold Fannin Jr.", "position": "TE-A", "school": "Bowling Green", "award": "TightEndOfTheYear"},
    {"name": "Lucas Scott", "position": "LT", "school": "Army", "award": "OffensiveTackleOfTheYear"},
    {"name": "Jordan White", "position": "LG", "school": "Liberty", "award": "OffensiveGuardOfTheYear"},
    {"name": "Jacob Gideon", "position": "C", "school": "Western Michigan", "award": "CenterOfTheYear"},
    {"name": "Lucas Scott", "position": "LT", "school": "Army", "award": "OffensiveLinemanOfTheYear"},
    {"name": "Army Black Knights", "position": "OL Unit", "school": "Army", "award": "OffensiveLineOfTheYear"},
    {"name": "Jeremiah Smith", "position": "WR-X", "school": "Ohio State", "award": "OffensiveNewcomerOfTheYear"},
    {"name": "Cam Ward", "position": "QB", "school": "Miami", "award": "OffensiveTransferOfTheYear"},
    {"name": "Mike Green", "position": "EDGE", "school": "Marshall", "award": "EdgeDefenderOfTheYear"},
    {"name": "Derrick Harmon", "position": "DT", "school": "Oregon", "award": "InteriorDefenderOfTheYear"},
    {"name": "Shaun Dolac", "position": "MLB", "school": "Buffalo", "award": "LinebackerOfTheYear"},
    {"name": "Nohl Williams", "position": "LCB", "school": "California", "award": "CornerbackOfTheYear"},
    {"name": "Nick Emmanwori", "position": "SS", "school": "South Carolina", "award": "SafetyOfTheYear"},
    {"name": "Indiana Hoosiers", "position": "DL Unit", "school": "Indiana", "award": "DefensiveLineOfTheYear"},
    {"name": "Texas Longhorns", "position": "Secondary Unit", "school": "Texas", "award": "SecondaryOfTheYear"},
    {"name": "Mikail Kamara", "position": "STUD", "school": "Indiana", "award": "DefensiveNewcomerOfTheYear"},
    {"name": "Mikail Kamara", "position": "STUD", "school": "Indiana", "award": "DefensiveTransferOfTheYear"},
    {"name": "Dominic Zvada", "position": "PK", "school": "Michigan", "award": "KickerOfTheYear"},
    {"name": "Rhys Dakin", "position": "PT", "school": "Iowa", "award": "PunterOfTheYear"},
    {"name": "Qua Ashley", "position": "KR", "school": "Kennesaw State", "award": "KickReturnerOfTheYear"},
    {"name": "Kam Shanks", "position": "PR", "school": "UAB", "award": "PuntReturnerOfTheYear"},
    {"name": "Rayuan Lane III", "position": "SS", "school": "Navy", "award": "SpecialTeamerOfTheYear"},
    {"name": "Caden Davis", "position": "KO", "school": "Ole Miss", "award": "KickoffSpecialistOfTheYear"},
    {"name": "Rhys Dakin", "position": "PT", "school": "Iowa", "award": "SpecialTeamsNewcomerOfTheYear"},
      {"position": "QB", "name": "Shedeur Sanders", "school": "Colorado", "team": "1"},
      {"position": "RB", "name": "Ashton Jeanty", "school": "Boise State", "team": "1"},
      {"position": "RB", "name": "Cam Skattebo", "school": "Arizona State", "team": "1"},
      {"position": "WR", "name": "Nick Nash", "school": "San Jose State", "team": "1"},
      {"position": "WR", "name": "Eric Rivers", "school": "Florida International", "team": "1"},
      {"position": "WR", "name": "Tetairoa McMillan", "school": "Arizona", "team": "1"},
      {"position": "TE", "name": "Harold Fannin Jr.", "school": "Bowling Green", "team": "1"},
      {"position": "FLEX", "name": "RJ Harvey", "school": "Central Florida", "team": "1"},
      {"position": "OT", "name": "Wyatt Milum", "school": "West Virginia", "team": "1"},
      {"position": "OG", "name": "Jordan White", "school": "Liberty", "team": "1"},
      {"position": "OC", "name": "Jacob Gideon", "school": "Western Michigan", "team": "1"},
      {"position": "OG", "name": "Willie Lampkin", "school": "North Carolina", "team": "1"},
      {"position": "OT", "name": "Lucas Scott", "school": "Army", "team": "1"},
      
      {"position": "EDGE", "name": "Mike Green", "school": "Marshall", "team": "1"},
      {"position": "DT", "name": "Derrick Harmon", "school": "Oregon", "team": "1"},
      {"position": "DT", "name": "Mason Graham", "school": "Michigan", "team": "1"},
      {"position": "EDGE", "name": "Mikail Kamara", "school": "Indiana", "team": "1"},
      {"position": "LB", "name": "Shaun Dolac", "school": "Buffalo", "team": "1"},
      {"position": "LB", "name": "Jackson Woodard", "school": "UNLV", "team": "1"},
      {"position": "LB", "name": "Carson Schwesinger", "school": "UCLA", "team": "1"},
      {"position": "CB", "name": "Nohl Williams", "school": "California", "team": "1"},
      {"position": "CB", "name": "Travis Hunter", "school": "Colorado", "team": "1"},
      {"position": "CB", "name": "Raion Strader", "school": "Miami", "team": "1"},
      {"position": "SS", "name": "Nick Emmanwori", "school": "South Carolina", "team": "1"},
      {"position": "FS", "name": "Michael Taaffe", "school": "Texas", "team": "1"},
      {"position": "S", "name": "Xavier Watts", "school": "Notre Dame", "team": "1"},
      {"position": "FLEX", "name": "Chandler Martin", "school": "Memphis", "team": "1"},
      
      {"position": "PK", "name": "Dominic Zvada", "school": "Michigan", "team": "1"},
      {"position": "KOS", "name": "Caden Davis", "school": "Ole Miss", "team": "1"},
      {"position": "P", "name": "Rhys Dakin", "school": "Iowa", "team": "1"},
      {"position": "KR", "name": "Qua Ashley", "school": "Kennesaw State", "team": "1"},
      {"position": "PR", "name": "Kam Shanks", "school": "UAB", "team": "1"},
      {"position": "ST", "name": "Rayuan Lane III", "school": "Navy", "team": "1"},
        {"position": "QB", "name": "Cam Ward", "school": "Miami", "team": "2"},
        {"position": "RB", "name": "Kaleb Johnson", "school": "Iowa", "team": "2"},
        {"position": "RB", "name": "Tre Stewart", "school": "Jacksonville State", "team": "2"},
        {"position": "WR", "name": "Xavier Restrepo", "school": "Miami", "team": "2"},
        {"position": "WR", "name": "Ricky White", "school": "UNLV", "team": "2"},
        {"position": "WR", "name": "Travis Hunter", "school": "Colorado", "team": "2"},
        {"position": "TE", "name": "Tyler Warren", "school": "Penn State", "team": "2"},
        {"position": "FLEX", "name": "Omarion Hampton", "school": "North Carolina", "team": "2"},
        {"position": "OT", "name": "Kelvin Banks Jr.", "school": "Texas", "team": "2"},
        {"position": "OG", "name": "Dylan Fairchild", "school": "Georgia", "team": "2"},
        {"position": "OC", "name": "Jake Slaughter", "school": "Florida", "team": "2"},
        {"position": "OG", "name": "Ar’maj Reed-Adams", "school": "Texas AM", "team": "2"},
        {"position": "OT", "name": "Connor Finucane", "school": "Army", "team": "2"},
      
        {"position": "EDGE", "name": "Eric O’Neill", "school": "James Madison", "team": "2"},
        {"position": "DT", "name": "Rylie Mills", "school": "Notre Dame", "team": "2"},
        {"position": "DT", "name": "James Carpenter", "school": "Indiana", "team": "2"},
        {"position": "EDGE", "name": "Donovan Ezeiruaku", "school": "Boston College", "team": "2"},
        {"position": "LB", "name": "Jihaad Campbell", "school": "Alabama", "team": "2"},
        {"position": "LB", "name": "Chris Paul Jr.", "school": "Ole Miss", "team": "2"},
        {"position": "LB", "name": "Jailin Walker", "school": "Indiana", "team": "2"},
        {"position": "CB", "name": "Trey Amos", "school": "Ole Miss", "team": "2"},
        {"position": "CB", "name": "Zah Frazier", "school": "UTSA", "team": "2"},
        {"position": "CB", "name": "Jahdae Barron", "school": "Texas", "team": "2"},
        {"position": "SS", "name": "Travor Randle", "school": "louisiana-monroe", "team": "2"},
        {"position": "FS", "name": "Jaylen Reed", "school": "Penn State", "team": "2"},
        {"position": "S", "name": "Jalen Catalon", "school": "UNLV", "team": "2"},
        {"position": "FLEX", "name": "Chandler Rivers", "school": "Duke", "team": "2"},
      
        {"position": "PK", "name": "Collin Rogers", "school": "SMU", "team": "2"},
        {"position": "KOS", "name": "Tyler Loop", "school": "Arizona", "team": "2"},
        {"position": "P", "name": "Eddie Czaplicki", "school": "USC", "team": "2"},
        {"position": "KR", "name": "Keelan Marion", "school": "Brigham Young", "team": "2"},
        {"position": "PR", "name": "Kaden Wetjen", "school": "Iowa", "team": "2"},
        {"position": "ST", "name": "Dalen Cambre", "school": "Louisiana", "team": "2"},
          {"position": "QB", "name": "Kurtis Rourke", "school": "Indiana", "team": "3"},
          {"position": "RB", "name": "Dylan Sampson", "school": "Tennessee", "team": "3"},
          {"position": "RB", "name": "Tahj Brooks", "school": "Texas Tech", "team": "3"},
          {"position": "WR", "name": "Tai Felton", "school": "Maryland", "team": "3"},
          {"position": "WR", "name": "Jayden Higgins", "school": "Iowa State", "team": "3"},
          {"position": "WR", "name": "Jeremiah Smith", "school": "Ohio State", "team": "3"},
          {"position": "TE", "name": "Tanner Koziol", "school": "Ball State", "team": "3"},
          {"position": "FLEX", "name": "Eli Heidenreich", "school": "Navy", "team": "3"},
          {"position": "OT", "name": "Kage Casey", "school": "Boise State", "team": "3"},
          {"position": "OG", "name": "Clay Webb", "school": "Jacksonville State", "team": "3"},
          {"position": "OC", "name": "Brady Small", "school": "Army", "team": "3"},
          {"position": "OG", "name": "Ben Dooley", "school": "Boise State", "team": "3"},
          {"position": "OT", "name": "Hollin Pierce", "school": "Rutgers", "team": "3"},
        
          {"position": "EDGE", "name": "James Pearce Jr.", "school": "Tennessee", "team": "3"},
          {"position": "DT", "name": "T.J. Sanders", "school": "South Carolina", "team": "3"},
          {"position": "DT", "name": "Jared Harrison‑Hunte", "school": "SMU", "team": "3"},
          {"position": "EDGE", "name": "Ashton Gillotte", "school": "Louisville", "team": "3"},
          {"position": "LB", "name": "Whit Weeks", "school": "LSU", "team": "3"},
          {"position": "LB", "name": "Kyle Louis", "school": "Pittsburgh", "team": "3"},
          {"position": "LB", "name": "Jay Higgins", "school": "Iowa", "team": "3"},
          {"position": "CB", "name": "Terrence Spence", "school": "James Madison", "team": "3"},
          {"position": "CB", "name": "Shamari Simmons", "school": "Arizona State", "team": "3"},
          {"position": "CB", "name": "Xavier Scott", "school": "Illinois", "team": "3"},
          {"position": "SS", "name": "Robert Rahimi", "school": "San Jose State", "team": "3"},
          {"position": "FS", "name": "Andrew Mukuba", "school": "Texas", "team": "3"},
          {"position": "S", "name": "Bud Clark", "school": "TCU", "team": "3"},
          {"position": "FLEX", "name": "Jordan Oladokun", "school": "Bowling Green", "team": "3"},
        
          {"position": "PK", "name": "Lucas Carneiro", "school": "Western Kentucky", "team": "3"},
          {"position": "KOS", "name": "Tristian Vandenberg", "school": "Memphis", "team": "3"},
          {"position": "P", "name": "Alex Mastromanno", "school": "Florida State", "team": "3"},
          {"position": "KR", "name": "Rayshawn Pleasant", "school": "Tulane", "team": "3"},
          {"position": "PR", "name": "Martel Hight", "school": "Vanderbilt", "team": "3"},
          {"position": "ST", "name": "Avi McGary", "school": "Bowling Green", "team": "3"},
            {"position": "QB", "name": "Kyle McCord", "school": "Syracuse", "team": "honorable_mention"},
            {"position": "QB", "name": "Jaxson Dart", "school": "Ole Miss", "team": "honorable_mention"},
            {"position": "QB", "name": "Dillon Gabriel", "school": "Oregon", "team": "honorable_mention"},
            {"position": "RB", "name": "Ahmad Hardy", "school": "Louisiana Monroe", "team": "honorable_mention"},
            {"position": "RB", "name": "Makhi Hughes", "school": "Tulane", "team": "honorable_mention"},
            {"position": "RB", "name": "DJ Giddens", "school": "Kansas State", "team": "honorable_mention"},
            {"position": "RB", "name": "Mario Anderson Jr.", "school": "Memphis", "team": "honorable_mention"},
            {"position": "RB", "name": "LeQuint Allen", "school": "Syracuse", "team": "honorable_mention"},
            {"position": "RB", "name": "Desmond Reid", "school": "Pittsburgh", "team": "honorable_mention"},
            {"position": "WR", "name": "Andrew Armstrong", "school": "Arkansas", "team": "honorable_mention"},
            {"position": "WR", "name": "Jordyn Tyson", "school": "Arizona State", "team": "honorable_mention"},
            {"position": "WR", "name": "Jack Bech", "school": "TCU", "team": "honorable_mention"},
            {"position": "WR", "name": "Josh Kelly", "school": "Texas Tech", "team": "honorable_mention"},
            {"position": "WR", "name": "Coleman Owen", "school": "Ohio", "team": "honorable_mention"},
            {"position": "WR", "name": "Jaylin Noel", "school": "Iowa State", "team": "honorable_mention"},
            {"position": "WR", "name": "DT Sheffield", "school": "North Texas", "team": "honorable_mention"},
            {"position": "WR", "name": "Jerjuan Newton", "school": "Toledo", "team": "honorable_mention"},
            {"position": "WR", "name": "Tre Harris", "school": "Ole Miss", "team": "honorable_mention"},
            {"position": "TE", "name": "Oronde Gadsden II", "school": "Syracuse", "team": "honorable_mention"},
            {"position": "TE", "name": "Holden Willis", "school": "Middle Tennessee", "team": "honorable_mention"},
            {"position": "TE", "name": "Gunnar Helm", "school": "Texas", "team": "honorable_mention"},
            {"position": "FLEX", "name": "Jamaal Pritchett", "school": "South Alabama", "team": "honorable_mention"},
            {"position": "FLEX", "name": "LaJohntay Wester", "school": "Colorado", "team": "honorable_mention"},
            {"position": "FLEX", "name": "Fluff Bothwell", "school": "South Alabama", "team": "honorable_mention"},
            {"position": "OT", "name": "Chase Lundt", "school": "Connecticut", "team": "honorable_mention"},
            {"position": "OT", "name": "Armand Mambou", "school": "Missouri", "team": "honorable_mention"},
            {"position": "OT", "name": "Xavior Gray", "school": "Liberty", "team": "honorable_mention"},
            {"position": "OG", "name": "AJ Gillie", "school": "Louisiana", "team": "honorable_mention"},
            {"position": "OG", "name": "John Champe", "school": "Northern Illinois", "team": "honorable_mention"},
            {"position": "OG", "name": "Luke Kandra", "school": "Cincinnati", "team": "honorable_mention"},
            {"position": "OC", "name": "Vincent Murphy", "school": "Tulane", "team": "honorable_mention"},
            {"position": "OC", "name": "Trent Holler", "school": "Memphis", "team": "honorable_mention"},
            {"position": "OC", "name": "Zeke Correll", "school": "NC State", "team": "honorable_mention"},        
              {"position": "OG", "name": "Tellek Lockette", "school": "Texas State", "team": "honorable_mention"},
              {"position": "OG", "name": "Drew Moss", "school": "Colorado State", "team": "honorable_mention"},
              {"position": "OG", "name": "Shadre Hurst", "school": "Tulane", "team": "honorable_mention"},
              {"position": "OT", "name": "Will O’Steen", "school": "Jacksonville State", "team": "honorable_mention"},
              {"position": "OT", "name": "Jack Sherwin", "school": "Western Michigan", "team": "honorable_mention"},
              {"position": "OT", "name": "Jordan Hall", "school": "Liberty", "team": "honorable_mention"},
              {"position": "EDGE", "name": "Ahmed Hassanein", "school": "Boise State", "team": "honorable_mention"},
              {"position": "EDGE", "name": "Abdul Carter", "school": "Penn State", "team": "honorable_mention"},
              {"position": "EDGE", "name": "Elijah Roberts", "school": "SMU", "team": "honorable_mention"},
              {"position": "DT", "name": "JJ Pegues", "school": "Ole Miss", "team": "honorable_mention"},
              {"position": "DT", "name": "Darius Alexander", "school": "Toledo", "team": "honorable_mention"},
              {"position": "DT", "name": "Walter Nolen", "school": "Ole Miss", "team": "honorable_mention"},
              {"position": "DT", "name": "Kenneth Grant", "school": "Michigan", "team": "honorable_mention"},
              {"position": "DT", "name": "Simeon Barrow Jr.", "school": "Miami", "team": "honorable_mention"},
              {"position": "DT", "name": "Aeneas Peebles", "school": "Virginia Tech", "team": "honorable_mention"},
              {"position": "EDGE", "name": "Brian Ugwu", "school": "Miami University", "team": "honorable_mention"},
              {"position": "EDGE", "name": "Jack Sawyer", "school": "Ohio State", "team": "honorable_mention"},
              {"position": "EDGE", "name": "Dylan Stewart", "school": "South Carolina", "team": "honorable_mention"},
              {"position": "LB", "name": "Matt Salopek", "school": "Miami University", "team": "honorable_mention"},
              {"position": "LB", "name": "Kydran Jenkins", "school": "Purdue", "team": "honorable_mention"},
              {"position": "LB", "name": "Colin Ramos", "school": "Navy", "team": "honorable_mention"},
              {"position": "LB", "name": "Aiden Fisher", "school": "Indiana", "team": "honorable_mention"},
              {"position": "LB", "name": "Francisco Mauigoa", "school": "Miami", "team": "honorable_mention"},
              {"position": "LB", "name": "Red Murdock", "school": "Buffalo", "team": "honorable_mention"},
              {"position": "LB", "name": "Jalon Walker", "school": "Georgia", "team": "honorable_mention"},
              {"position": "LB", "name": "Teddye Buchanan", "school": "California", "team": "honorable_mention"},
              {"position": "LB", "name": "Alex Howard", "school": "Duke", "team": "honorable_mention"},
              {"position": "CB", "name": "Dashaun Peele", "school": "Navy", "team": "honorable_mention"},
              {"position": "CB", "name": "Matthew McDoom", "school": "Coastal Carolina", "team": "honorable_mention"},
              {"position": "CB", "name": "Cameron Oliver", "school": "UNLV", "team": "honorable_mention"},
              {"position": "CB", "name": "Mello Dotson", "school": "Kansas", "team": "honorable_mention"},
              {"position": "CB", "name": "Michael Coats Jr.", "school": "Nevada", "team": "honorable_mention"},
                {"position": "CB", "name": "Cam Lockridge", "school": "Fresno State", "team": "honorable_mention"},
                {"position": "CB", "name": "Josh Moten", "school": "Marshall", "team": "honorable_mention"},
                {"position": "CB", "name": "DJ Harvey", "school": "San Jose State", "team": "honorable_mention"},
                {"position": "CB", "name": "Brian Mayes", "school": "Texas AM", "team": "honorable_mention"},
                {"position": "SS", "name": "Gabe Taylor", "school": "Rice", "team": "honorable_mention"},
                {"position": "SS", "name": "Seyi Oladipo", "school": "Boise State", "team": "honorable_mention"},
                {"position": "SS", "name": "Jahron Manning", "school": "Old Dominion", "team": "honorable_mention"},
                {"position": "FS", "name": "Koi Perich", "school": "Minnesota", "team": "honorable_mention"},
                {"position": "FS", "name": "Dillon Thieneman", "school": "Purdue", "team": "honorable_mention"},
                {"position": "FS", "name": "Rayuan Lane III", "school": "Navy", "team": "honorable_mention"},
                {"position": "S", "name": "Isaiah Nwokobia", "school": "SMU", "team": "honorable_mention"},
                {"position": "S", "name": "J.J. Roberts", "school": "Marshall", "team": "honorable_mention"},
                {"position": "S", "name": "A.J. Haulcy", "school": "Houston", "team": "honorable_mention"},
                {"position": "FLEX", "name": "A’Marion McCoy", "school": "Boise State", "team": "honorable_mention"},
                {"position": "FLEX", "name": "Torrie Cox Jr.", "school": "Illinois", "team": "honorable_mention"},
                {"position": "FLEX", "name": "Jermod McCoy", "school": "Tennessee", "team": "honorable_mention"},
                {"position": "PK", "name": "Ben Sauls", "school": "Pittsburgh", "team": "honorable_mention"},
                {"position": "PK", "name": "Ryan Fitzgerald", "school": "Florida State", "team": "honorable_mention"},
                {"position": "PK", "name": "Maddux Trujillo", "school": "Temple", "team": "honorable_mention"},
                {"position": "KOS", "name": "Caden Chittenden", "school": "UNLV", "team": "honorable_mention"},
                {"position": "KOS", "name": "Andres Borregales", "school": "Miami", "team": "honorable_mention"},
                {"position": "KOS", "name": "Aeron Burrell", "school": "LSU", "team": "honorable_mention"},
                {"position": "P", "name": "Brett Thorson", "school": "Georgia", "team": "honorable_mention"},
                {"position": "P", "name": "Kai Kroeger", "school": "South Carolina", "team": "honorable_mention"},
                {"position": "P", "name": "Jeremy Crawshaw", "school": "Florida", "team": "honorable_mention"},
                {"position": "KR", "name": "Kaden Wetjen", "school": "Iowa", "team": "honorable_mention"},
                {"position": "KR", "name": "Lloyd Avant", "school": "Tulsa", "team": "honorable_mention"},
                {"position": "KR", "name": "Winston Wright Jr.", "school": "East Carolina", "team": "honorable_mention"},
                {"position": "PR", "name": "Taylor Morin", "school": "Wake Forest", "team": "honorable_mention"},
                {"position": "PR", "name": "Tiger Bachmeier", "school": "Stanford", "team": "honorable_mention"},
                {"position": "PR", "name": "Roderick Daniels Jr.", "school": "SMU", "team": "honorable_mention"},
                {"position": "ST", "name": "Micah Gifford", "school": "Baylor", "team": "honorable_mention"},
                {"position": "ST", "name": "Cole Joyce", "school": "Utah State", "team": "honorable_mention"},
                {"position": "ST", "name": "Jackson Barker", "school": "East Carolina", "team": "honorable_mention"}            
    ]
}
