"""Default 2024 PWAA Freshman All-American List."""

{
  "pwaa": [
    {
      "name": "DJ Lagway",
      "position": "QB",
      "school": "Florida",
      "height": "6-3",
      "weight": "239",
      "class": "Fr.",
      "hometown": "Willis, Texas",
    },
    {
      "name": "LaNorris Sellers",
      "position": "QB",
      "school": "South Carolina",
      "height": "6-3",
      "weight": "242",
      "class": "R‑Fr.",
      "hometown": "Florence, S.C.",
    },
    {
      "name": "Ahmad Hardy",
      "position": "RB",
      "school": "ULM",
      "height": "5-10",
      "weight": "205",
      "class": "Fr.",
      "hometown": "Monticello, Miss.",
    },
    {
      "name": "Bryson Washington",
      "position": "RB",
      "school": "Baylor",
      "height": "6-0",
      "weight": "203",
      "class": "R‑Fr.",
      "hometown": "Franklin, Texas",
    },
    {
      "name": "Jeremiah Smith",
      "position": "WR",
      "school": "Ohio State",
      "height": "6-3",
      "weight": "215",
      "class": "Fr.",
      "hometown": "Miami Gardens, Fla.",
    },
    {
      "name": "Bryant Wesco Jr.",
      "position": "WR",
      "school": "Clemson",
      "height": "6-2",
      "weight": "180",
      "class": "Fr.",
      "hometown": "Midlothian, Texas",
    },
    {
      "name": "Ryan Williams",
      "position": "WR",
      "school": "Alabama",
      "height": "6-0",
      "weight": "175",
      "class": "Fr.",
      "hometown": "Mobile, Ala.",
    },
    {
      "name": "Mason Williams",
      "position": "TE",
      "school": "Ohio",
      "height": "6-5",
      "weight": "257",
      "class": "R‑Fr.",
      "hometown": "Mogadore, Ohio",
    },
    {
      "name": "Aidan Banfield",
      "position": "OL",
      "school": "North Carolina",
      "height": "6-3",
      "weight": "300",
      "class": "Fr.",
      "hometown": "Buford, Ga.",
    },
    {
      "name": "Tyler Mercer",
      "position": "OL",
      "school": "North Texas",
      "height": "6-4",
      "weight": "290",
      "class": "Fr.",
      "hometown": "Prosper, Texas",
    },
    {
      "name": "Elijah Paige",
      "position": "OL",
      "school": "USC",
      "height": "6-7",
      "weight": "320",
      "class": "R‑Fr.",
      "hometown": "Phoenix, Ariz.",
    },
    {
      "name": "Tyson Ruffins",
      "position": "OL",
      "school": "Nevada",
      "height": "6-2",
      "weight": "291",
      "class": "R‑Fr.",
      "hometown": "Carson, Calif.",
    },
    {
      "name": "Jordan Seaton",
      "position": "OL",
      "school": "Colorado",
      "height": "6-5",
      "weight": "285",
      "class": "Fr.",
      "hometown": "Washington, D.C.",
    },
    {
      "name": "Josiah Thompson",
      "position": "OL",
      "school": "South Carolina",
      "height": "6-7",
      "weight": "300",
      "class": "Fr.",
      "hometown": "Dillon, S.C.",
    },
    {
      "name": "Jamarioius Brown",
      "position": "DL",
      "school": "Ole Miss",
      "height": "6-1",
      "weight": "315",
      "class": "R‑Fr.",
      "hometown": "Moss Point, Miss.",
    },
    {
      "name": "Jayden Jackson",
      "position": "DL",
      "school": "Oklahoma",
      "height": "6-2",
      "weight": "312",
      "class": "Fr.",
      "hometown": "Indianapolis, Ind.",
    },
    {
      "name": "Colin Simmons",
      "position": "DL",
      "school": "Texas",
      "height": "6-3",
      "weight": "245",
      "class": "Fr.",
      "hometown": "Duncanville, Texas",
    },
    {
      "name": "Dylan Stewart",
      "position": "DL",
      "school": "South Carolina",
      "height": "6-6",
      "weight": "248",
      "class": "Fr.",
      "hometown": "Washington, D.C.",
    },
    {
      "name": "Sammy Brown",
      "position": "LB",
      "school": "Clemson",
      "height": "6-2",
      "weight": "235",
      "class": "Fr.",
      "hometown": "Commerce, Ga.",
    },
    {
      "name": "Isaiah Chisom",
      "position": "LB",
      "school": "Oregon State",
      "height": "6-0",
      "weight": "218",
      "class": "R‑Fr.",
      "hometown": "Santa Clarita, Calif.",
    },
    {
      "name": "Josiah Trotter",
      "position": "LB",
      "school": "West Virginia",
      "height": "6-2",
      "weight": "242",
      "class": "R‑Fr.",
      "hometown": "Philadelphia, Pa.",
    },
    {
      "name": "OJ Frederique Jr.",
      "position": "CB",
      "school": "Miami",
      "height": "6-0",
      "weight": "180",
      "class": "Fr.",
      "hometown": "Fort Lauderdale, Fla.",
    },
    {
      "name": "Ashton Hampton",
      "position": "CB",
      "school": "Clemson",
      "height": "6-2",
      "weight": "200",
      "class": "Fr.",
      "hometown": "Tallahassee, Fla.",
    },
    {
      "name": "Leonard Moore",
      "position": "CB",
      "school": "Notre Dame",
      "height": "6-2",
      "weight": "191",
      "class": "Fr.",
      "hometown": "Round Rock, Texas",
    },
    {
      "name": "KJ Bolden",
      "position": "S",
      "school": "Georgia",
      "height": "6-0",
      "weight": "185",
      "class": "Fr.",
      "hometown": "Buford, Ga.",
    },
    {
      "name": "Koi Perich",
      "position": "S",
      "school": "Minnesota",
      "height": "6-1",
      "weight": "200",
      "class": "Fr.",
      "hometown": "Esko, Minn.",
    },
    {
      "name": "Zechariah Poyser",
      "position": "S",
      "school": "jaxsonville-state",
      "height": "6-2",
      "weight": "190",
      "class": "R‑Fr.",
      "hometown": "Wildwood, Fla.",
    },
    {
      "name": "Nolan Hauser",
      "position": "K",
      "school": "Clemson",
      "height": "6-1",
      "weight": "190",
      "class": "Fr.",
      "hometown": "Cornelius, N.C.",
    },
    {
      "name": "Rhys Dakin",
      "position": "P",
      "school": "Iowa",
      "height": "6-0",
      "weight": "222",
      "class": "Fr.",
      "hometown": "Melbourne, Australia",
    },
    {
      "name": "Samuel Singleton Jr.",
      "position": "KR",
      "school": "Florida State",
      "height": "5-11",
      "weight": "195",
      "class": "R‑Fr.",
      "hometown": "Charleston, S.C.",
    },
    {
      "name": "Kam Shanks",
      "position": "PR",
      "school": "UAB",
      "height": "5-8",
      "weight": "180",
      "class": "R‑Fr.",
      "hometown": "Prattville, Ala.",
    },
    {
      "name": "Isaac Brown",
      "position": "AP",
      "school": "Louisville",
      "height": "5-9",
      "weight": "190",
      "class": "Fr.",
      "hometown": "Homestead, Fla.",
    }
  ]
}
