"""CFN All-American List 2024"""

{
  "allamerican": {
    "Awards": {
      "PlayerOfTheYear": {"name":"Ashton Jeanty","position":"RB","school":"Boise State"},
      "OffensivePlayerOfTheYear": {"name":"Ashton Jeanty","position":"RB","school":"Boise State"},
      "DefensivePlayerOfTheYear": {"name":"Shaun Dolac","position":"MLB","school":"Buffalo"},
      "SpecialistOfTheYear": {"name":"Dominic Zvada","position":"PK","school":"Michigan"},
      "NewcomerOfTheYear": {"name":"Jeremiah Smith","position":"WR-X","school":"Ohio State"},
      "CoachOfTheYear": {"name":"Curt Cignetti","position":"Coach","school":"Indiana"},
      "ImpactFreshmanOfTheYear": {"name":"Jeremiah Smith","position":"WR-X","school":"Ohio State"}
    },
    "PositionAwards": {
      "QuarterbackOfTheYear": {"name":"Shedeur Sanders","position":"QB","school":"Colorado"},
      "RunningBackOfTheYear": {"name":"Ashton Jeanty","position":"RB","school":"Boise State"},
      "WideReceiverOfTheYear": {"name":"Nick Nash","position":"WR-X","school":"San Jose State"},
      "TightEndOfTheYear": {"name":"Harold Fannin Jr.","position":"TE-A","school":"Bowling Green"},
      "OffensiveTackleOfTheYear": {"name":"Lucas Scott","position":"LT","school":"Army"},
      "OffensiveGuardOfTheYear": {"name":"Jordan White","position":"RG","school":"Liberty"},
      "CenterOfTheYear": {"name":"Jacob Gideon","position":"C","school":"Western Michigan"},
      "OffensiveLinemanOfTheYear": {"name":"Lucas Scott","position":"LT","school":"Army"},
      "OffensiveLineOfTheYear": {"name":"Army Black Knights","position":"OL Unit","school":"Army"},
      "OffensiveNewcomerOfTheYear": {"name":"Jeremiah Smith","position":"WR","school":"Ohio State"},
      "OffensiveTransferOfTheYear": {"name":"Cam Ward","position":"QB","school":"Miami"},
      "EdgeDefenderOfTheYear": {"name":"Mike Green","position":"RDE","school":"Marshall"},
      "InteriorDefenderOfTheYear": {"name":"Derrick Harmon","position":"DT","school":"Oregon"},
      "LinebackerOfTheYear": {"name":"Shaun Dolac","position":"MLB","school":"Buffalo"},
      "CornerbackOfTheYear": {"name":"Nohl Williams","position":"LCB","school":"California"},
      "SafetyOfTheYear": {"name":"Nick Emmanwori","position":"SS","school":"South Carolina"},
      "DefensiveLineOfTheYear": {"name":"Indiana Hoosiers","position":"DL Unit","school":"Indiana"},
      "SecondaryOfTheYear": {"name":"Texas Longhorns","position":"Secondary Unit","school":"Texas"},
      "DefensiveNewcomerOfTheYear": {"name":"Mikail Kamara","position":"STUD","school":"Indiana"},
      "DefensiveTransferOfTheYear": {"name":"Mikail Kamara","position":"STUD","school":"Indiana"},
      "KickerOfTheYear": {"name":"Dominic Zvada","position":"PK","school":"Michigan"},
      "PunterOfTheYear": {"name":"Rhys Dakin","position":"PT","school":"Iowa"},
      "KickReturnerOfTheYear": {"name":"Qua Ashley","position":"KR","school":"Kennesaw State"},
      "PuntReturnerOfTheYear": {"name":"Kam Shanks","position":"PR","school":"UAB"},
      "SpecialTeamerOfTheYear": {"name":"Rayuan Lane III","position":"BAN","school":"Navy"},
      "KickoffSpecialistOfTheYear": {"name":"Caden Davis","position":"KO","school":"Ole Miss"},
      "SpecialTeamsNewcomerOfTheYear": {"name":"Rhys Dakin","position":"PT","school":"Iowa"}
    },
    "FirstTeam": {
      "Offense": [
        {"position":"QB","name":"Shedeur Sanders","school":"Colorado"},
        {"position":"RB","name":"Ashton Jeanty","school":"Boise State"},
        {"position":"RB","name":"Cam Skattebo","school":"Arizona State"},
        {"position":"WR-X","name":"Nick Nash","school":"San Jose State"},
        {"position":"WR-X","name":"Eric Rivers","school":"Florida International"},
        {"position":"WR-X","name":"Tetairoa McMillan","school":"Arizona"},
        {"position":"TE-A","name":"Harold Fannin Jr.","school":"Bowling Green"},
        {"position":"RB","name":"RJ Harvey","school":"Central Florida"},
        {"position":"LT","name":"Wyatt Milum","school":"West Virginia"},
        {"position":"RG","name":"Jordan White","school":"Liberty"},
        {"position":"C","name":"Jacob Gideon","school":"Western Michigan"},
        {"position":"RG","name":"Willie Lampkin","school":"North Carolina"},
        {"position":"LT","name":"Lucas Scott","school":"Army"}
      ],
      "Defense": [
        {"position":"EDGE","name":"Mike Green","school":"Marshall"},
        {"position":"DT","name":"Derrick Harmon","school":"Oregon"},
        {"position":"NT","name":"Mason Graham","school":"Michigan"},
        {"position":"STUD","name":"Mikail Kamara","school":"Indiana"},
        {"position":"MLB","name":"Shaun Dolac","school":"Buffalo"},
        {"position":"MLB","name":"Jackson Woodard","school":"UNLV"},
        {"position":"MLB","name":"Carson Schwesinger","school":"UCLA"},
        {"position":"LCB","name":"Nohl Williams","school":"California"},
        {"position":"LCB","name":"Travis Hunter","school":"Colorado"},
        {"position":"RCB","name":"Raion Strader","school":"Miami"},
        {"position":"SS","name":"Nick Emmanwori","school":"South Carolina"},
        {"position":"FS","name":"Michael Taaffe","school":"Texas"},
        {"position":"SS","name":"Xavier Watts","school":"Notre Dame"},
        {"position":"MLB","name":"Chandler Martin","school":"Memphis"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Dominic Zvada","school":"Michigan"},
        {"position":"KO","name":"Caden Davis","school":"Ole Miss"},
        {"position":"PT","name":"Rhys Dakin","school":"Iowa"},
        {"position":"KR","name":"Qua Ashley","school":"Kennesaw State"},
        {"position":"PR","name":"Kam Shanks","school":"UAB"},
        {"position":"BAN","name":"Rayuan Lane III","school":"Navy"}
      ]
    },
    "SecondTeam": {
      "Offense": [
        {"position":"QB","name":"Cam Ward","school":"Miami"},
        {"position":"RB","name":"Kaleb Johnson","school":"Iowa"},
        {"position":"RB","name":"Tre Stewart","school":"Jacksonville State"},
        {"position":"WR-X","name":"Xavier Restrepo","school":"Miami"},
        {"position":"WR-X","name":"Ricky White","school":"UNLV"},
        {"position":"WR-X","name":"Travis Hunter","school":"Colorado"},
        {"position":"TE","name":"Tyler Warren","school":"Penn State"},
        {"position":"RB","name":"Omarion Hampton","school":"North Carolina"},
        {"position":"LT","name":"Kelvin Banks Jr.","school":"Texas"},
        {"position":"RG","name":"Dylan Fairchild","school":"Georgia"},
        {"position":"C","name":"Jake Slaughter","school":"Florida"},
        {"position":"RG","name":"Ar’maj Reed-Adams","school":"Texas AM"},
        {"position":"RT","name":"Connor Finucane","school":"Army"}
      ],
      "Defense": [
        {"position":"LDE","name":"Eric O’Neill","school":"James Madison"},
        {"position":"DT","name":"Rylie Mills","school":"Notre Dame"},
        {"position":"DT","name":"James Carpenter","school":"Indiana"},
        {"position":"LDE","name":"Donovan Ezeiruaku","school":"Boston College"},
        {"position":"MLB","name":"Jihaad Campbell","school":"Alabama"},
        {"position":"MLB","name":"Chris Paul Jr.","school":"Ole Miss"},
        {"position":"MLB","name":"Jailin Walker","school":"Indiana"},
        {"position":"LCB","name":"Trey Amos","school":"Ole Miss"},
        {"position":"RCB","name":"Zah Frazier","school":"UTSA"},
        {"position":"FCB","name":"Jahdae Barron","school":"Texas"},
        {"position":"SS","name":"Travor Randle","school":"louisiana-monroe"},
        {"position":"FS","name":"Jaylen Reed","school":"Penn State"},
        {"position":"FS","name":"Jalen Catalon","school":"UNLV"},
        {"position":"RCB","name":"Chandler Rivers","school":"Duke"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Collin Rogers","school":"SMU"},
        {"position":"KO","name":"Tyler Loop","school":"Arizona"},
        {"position":"PT","name":"Eddie Czaplicki","school":"USC"},
        {"position":"KR","name":"Keelan Marion","school":"Brigham Young"},
        {"position":"PR","name":"Kaden Wetjen","school":"Iowa"},
        {"position":"WR-Z","name":"Dalen Cambre","school":"Louisiana"}
      ]
    },
    "ThirdTeam": {
      "Offense": [
        {"position":"QB","name":"Kurtis Rourke","school":"Indiana"},
        {"position":"RB","name":"Dylan Sampson","school":"Tennessee"},
        {"position":"RB","name":"Tahj Brooks","school":"Texas Tech"},
        {"position":"WR-X","name":"Tai Felton","school":"Maryland"},
        {"position":"WR-X","name":"Jayden Higgins","school":"Iowa State"},
        {"position":"WR-X","name":"Jeremiah Smith","school":"Ohio State"},
        {"position":"TE","name":"Tanner Koziol","school":"Ball State"},
        {"position":"SB-Z","name":"Eli Heidenreich","school":"Navy"},
        {"position":"LT","name":"Kage Casey","school":"Boise State"},
        {"position":"RG","name":"Clay Webb","school":"Jacksonville State"},
        {"position":"C","name":"Brady Small","school":"Army"},
        {"position":"LG","name":"Ben Dooley","school":"Boise State"},
        {"position":"LT","name":"Hollin Pierce","school":"Rutgers"}
      ],
      "Defense": [
        {"position":"DE","name":"James Pearce Jr.","school":"Tennessee"},
        {"position":"RDT","name":"T.J. Sanders","school":"South Carolina"},
        {"position":"LDT","name":"Jared Harrison‑Hunte","school":"SMU"},
        {"position":"DE","name":"Ashton Gillotte","school":"Louisville"},
        {"position":"MLB","name":"Whit Weeks","school":"LSU"},
        {"position":"STAR","name":"Kyle Louis","school":"Pittsburgh"},
        {"position":"MLB","name":"Jay Higgins","school":"Iowa"},
        {"position":"LCB","name":"Terrence Spence","school":"James Madison"},
        {"position":"SS","name":"Shamari Simmons","school":"Arizona State"},
        {"position":"NB","name":"Xavier Scott","school":"Illinois"},
        {"position":"SS","name":"Robert Rahimi","school":"San Jose State"},
        {"position":"FS","name":"Andrew Mukuba","school":"Texas"},
        {"position":"FS","name":"Bud Clark","school":"TCU"},
        {"position":"FCB","name":"Jordan Oladokun","school":"Bowling Green"}
      ],
      "SpecialTeams": [
        {"position":"PK","name":"Lucas Carneiro","school":"Western Kentucky"},
        {"position":"KO","name":"Tristian Vandenberg","school":"Memphis"},
        {"position":"PT","name":"Alex Mastromanno","school":"Florida State"},
        {"position":"KR","name":"Rayshawn Pleasant","school":"Tulane"},
        {"position":"PR","name":"Martel Hight","school":"Vanderbilt"},
        {"position":"ST","name":"Avi McGary","school":"Bowling Green"}
      ]
    },
    "HonorableMention": [
      {"position":"QB","name":"Kyle McCord","school":"Syracuse"},
      {"position":"QB","name":"Jaxson Dart","school":"Ole Miss"},
      {"position":"QB","name":"Dillon Gabriel","school":"Oregon"},
      {"position":"RB","name":"Ahmad Hardy","school":"Louisiana Monroe"},
      {"position":"RB","name":"Makhi Hughes","school":"Tulane"},
      {"position":"RB","name":"DJ Giddens","school":"Kansas State"},
      {"position":"RB","name":"Mario Anderson Jr.","school":"Memphis"},
      {"position":"RB","name":"LeQuint Allen","school":"Syracuse"},
      {"position":"RB","name":"Desmond Reid","school":"Pittsburgh"},
      {"position":"WR-X","name":"Andrew Armstrong","school":"Arkansas"},
      {"position":"WR-F","name":"Jordyn Tyson","school":"Arizona State"},
      {"position":"TE","name":"Jack Bech","school":"TCU"},
      {"position":"WR-X","name":"Josh Kelly","school":"Texas Tech"},
      {"position":"WR-X","name":"Coleman Owen","school":"Ohio"},
      {"position":"WR-X","name":"Jaylin Noel","school":"Iowa State"},
      {"position":"WR-SL","name":"DT Sheffield","school":"North Texas"},
      {"position":"WR-X","name":"Jerjuan Newton","school":"Toledo"},
      {"position":"WR-X","name":"Tre Harris","school":"Ole Miss"},
      {"position":"TE","name":"Oronde Gadsden II","school":"Syracuse"},
      {"position":"TE","name":"Holden Willis","school":"Middle Tennessee"},
      {"position":"TE","name":"Gunnar Helm","school":"Texas"},
      {"position":"WR-H","name":"Jamaal Pritchett","school":"South Alabama"},
      {"position":"WR-X","name":"LaJohntay Wester","school":"Colorado"},
      {"position":"RB","name":"Fluff Bothwell","school":"South Alabama"},
      {"position":"LT","name":"Chase Lundt","school":"Connecticut"},
      {"position":"LT","name":"Armand Mambou","school":"Missouri"},
      {"position":"LT","name":"Xavior Gray","school":"Liberty"},
      {"position":"RG","name":"AJ Gillie","school":"Louisiana"},
      {"position":"LG","name":"John Champe","school":"Northern Illinois"},
      {"position":"RG","name":"Luke Kandra","school":"Cincinnati"},
      {"position":"C","name":"Vincent Murphy","school":"Tulane"},
      {"position":"C","name":"Trent Holler","school":"Memphis"},
      {"position":"C","name":"Zeke Correll","school":"NC State"},
      {"position":"RG","name":"Tellek Lockette","school":"Texas State"},
      {"position":"RG","name":"Drew Moss","school":"Colorado State"},
      {"position":"LG","name":"Shadre Hurst","school":"Tulane"},
      {"position":"LT","name":"Will O’Steen","school":"Jacksonville State"},
      {"position":"LT","name":"Jack Sherwin","school":"Western Michigan"},
      {"position":"RT","name":"Jordan Hall","school":"Liberty"},
      {"position":"EDGE","name":"Ahmed Hassanein","school":"Boise State"},
      {"position":"LDE","name":"Abdul Carter","school":"Penn State"},
      {"position":"RDE","name":"Elijah Roberts","school":"SMU"},
      {"position":"DT","name":"JJ Pegues","school":"Ole Miss"},
      {"position":"DT","name":"Darius Alexander","school":"Toledo"},
      {"position":"DT","name":"Walter Nolen","school":"Ole Miss"},
      {"position":"DT","name":"Kenneth Grant","school":"Michigan"},
      {"position":"DT","name":"Simeon Barrow Jr.","school":"Miami"},
      {"position":"RDT","name":"Aeneas Peebles","school":"Virginia Tech"},
      {"position":"EDGE","name":"Brian Ugwu","school":"Miami University"},
      {"position":"DE","name":"Jack Sawyer","school":"Ohio State"},
      {"position":"RDE","name":"Dylan Stewart","school":"South Carolina"},
      {"position":"MLB","name":"Matt Salopek","school":"Miami University"},
      {"position":"LB","name":"Kydran Jenkins","school":"Purdue"},
      {"position":"LB","name":"Colin Ramos","school":"Navy"},
      {"position":"LB","name":"Aiden Fisher","school":"Indiana"},
      {"position":"LB","name":"Francisco Mauigoa","school":"Miami"},
      {"position":"LB","name":"Red Murdock","school":"Buffalo"},
      {"position":"LB","name":"Jalon Walker","school":"Georgia"},
      {"position":"LB","name":"Teddye Buchanan","school":"California"},
      {"position":"LB","name":"Alex Howard","school":"Duke"},
      {"position":"CB","name":"Dashaun Peele","school":"Navy"},
      {"position":"CB","name":"Matthew McDoom","school":"Coastal Carolina"},
      {"position":"CB","name":"Cameron Oliver","school":"UNLV"},
      {"position":"CB","name":"Mello Dotson","school":"Kansas"},
      {"position":"LCB","name":"Michael Coats Jr.","school":"Nevada"},
      {"position":"RCB","name":"Cam Lockridge","school":"Fresno State"},
      {"position":"LCB","name":"Josh Moten","school":"Marshall"},
      {"position":"LCB","name":"DJ Harvey","school":"San Jose State"},
      {"position":"LCB","name":"Brian Mayes","school":"Texas AM"},
      {"position":"SS","name":"Gabe Taylor","school":"Rice"},
      {"position":"SS","name":"Seyi Oladipo","school":"Boise State"},
      {"position":"NB","name":"Jahron Manning","school":"Old Dominion"},
      {"position":"FS","name":"Koi Perich","school":"Minnesota"},
      {"position":"SS","name":"Dillon Thieneman","school":"Purdue"},
      {"position":"FS","name":"Rayuan Lane III","school":"Navy"},
      {"position":"SS","name":"Isaiah Nwokobia","school":"SMU"},
      {"position":"SS","name":"J.J. Roberts","school":"Marshall"},
      {"position":"FS","name":"A.J. Haulcy","school":"Houston"},
      {"position":"FLEX","name":"A’Marion McCoy","school":"Boise State"},
      {"position":"FLEX","name":"Torrie Cox Jr.","school":"Illinois"},
      {"position":"FLEX","name":"Jermod McCoy","school":"Tennessee"},
      {"position":"PK","name":"Ben Sauls","school":"Pittsburgh"},
      {"position":"PK","name":"Ryan Fitzgerald","school":"Florida State"},
      {"position":"PK","name":"Maddux Trujillo","school":"Temple"},
      {"position":"KO","name":"Caden Chittenden","school":"UNLV"},
      {"position":"KO","name":"Andres Borregales","school":"Miami"},
      {"position":"KO","name":"Aeron Burrell","school":"LSU"},
      {"position":"PT","name":"Brett Thorson","school":"Georgia"},
      {"position":"PT","name":"Kai Kroeger","school":"South Carolina"},
      {"position":"PT","name":"Jeremy Crawshaw","school":"Florida"},
      {"position":"KR","name":"Kaden Wetjen","school":"Iowa"},
      {"position":"KR","name":"Lloyd Avant","school":"Tulsa"},
      {"position":"KR","name":"Winston Wright Jr.","school":"East Carolina"},
      {"position":"PR","name":"Taylor Morin","school":"Wake Forest"},
      {"position":"PR","name":"Tiger Bachmeier","school":"Stanford"},
      {"position":"PR","name":"Roderick Daniels Jr.","school":"SMU"},
      {"position":"SS","name":"Micah Gifford","school":"Baylor"},
      {"position":"MLB","name":"Cole Joyce","school":"Utah State"},
      {"position":"MLB","name":"Jackson Barker","school":"East Carolina"}
    ]
  }
}
